### PR TITLE
fix(test runner): improve error message for non-stable test titles

### LINKED ISSUE #23779: [BUG] HTML test result is displaying Internal error: unknown test(s) in worker
### System info
- Playwright Version: [v1.35.1]
- Operating System: macOS 13.2.1 (22D68)
- Browser: All
- Other info:

### Source code

```js
import { expect, test } from "@playwright/test";

test.describe("Test", () => {
  [
    {
      textInput: "123".padEnd(10, Math.round(Math.random() * 10000).toString()),
    },
    {
      textInput: "0.123".padEnd(10, Math.round(Math.random() * 10000).toString()),
    },
    {
      textInput: "-123".padEnd(10, Math.round(Math.random() * 10000).toString()),
    },
  ].forEach((testCase) => {
    test(`@haha verify input behavior with value "${testCase.textInput}"`, async () => {
      // assume we make some action with given value
      // locator.fill(testCase.textInput);
      expect(true).toBe(true);
    });
  });
});
```

**Steps**
- Refer to the existing [issue](https://github.com/microsoft/playwright/issues/13892), it has been fixed. However, the default rest result still displays Internal error: unknown test(s) in worker:
- 

**Expected**

It should not display Internal error issue

**Actual**

image

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #23779.

### CODE REVIEW

File: packages/playwright-test/src/runner/dispatcher.ts [hunk 1]
```diff
@@ -379,7 +379,7 @@ export class Dispatcher {
           return test.titlePath().slice(1).join(' > ');
         });
         massSkipTestsFromRemaining(new Set(params.fatalUnknownTestIds), [{
-          message: `Internal error: unknown test(s) in worker:\n${titles.join('\n')}`
+          message: `Test(s) not found in the worker process. Make sure test titles are stable:\n${titles.join('\n')}`
```
Comment (yury-s) [inline packages/playwright-test/src/runner/dispatcher.ts:382]:
```suggestion
          message: `Test(s) not found in the worker process. Make sure test titles don't change within same run:\n${titles.join('\n')}`
```

**Review by yury-s — APPROVED** [review]
