### PR TITLE
fix: step id not found error log

### LINKED ISSUE #37747: [Regression]: Internal error: step id not found: fixture@46
### Last Good Version

1.54.2

### First Bad Version

1.56.0

### Steps to reproduce

1. Clone the repo at `https://github.com/jonasclaes/playwright-bugs.git`
2. Checkout branch `bug/step-id-not-found`
3. Run `npm install`
4. Run `npx playwright test`

### Expected behavior

I expect not to see the error message.

### Actual behavior

It throws the following internal error:
```
Internal error: step id not found: fixture@46
```

### Additional context

I think I've found the root cause of the bug.

It seems to be related to the screenshot setting in the `playwright.config.ts` in combination with the setup test that returns without performing a navigation and closing the context.

This example is a simplified version, but in our testing repository, we make use of fixtures that spin up other contexts, and pages within those contexts, that's why we close it manually.

This was working before, so this seems to be a regression.

### Environment

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 14.95 GB / 31.46 GB
  Binaries:
    Node: 22.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 11.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.14.0 - C:\Program Files\nodejs\pnpm.CMD
  IDEs:
    VSCode: 1.104.3 - C:\Users\claesj5\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.56.0 => 1.56.0
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/37747

This is the second report about this error line, both weren't pointing to underlying bugs. Maybe we should remove the log line instead?

### CODE REVIEW

File: packages/playwright/src/worker/testInfo.ts [hunk 1]
```diff
@@ -466,8 +466,11 @@ export class TestInfoImpl implements TestInfo {
 
   _attach(attachment: TestInfo['attachments'][0], stepId: string | undefined) {
     const index = this._attachmentsPush(attachment) - 1;
+    let internal = false;
     if (stepId) {
-      this._stepMap.get(stepId)!.attachmentIndices.push(index);
+      const step = this._stepMap.get(stepId)!;
+      step.attachmentIndices.push(index);
+      internal = step.group !== undefined;
```
Comment (dgozman) [inline packages/playwright/src/worker/testInfo.ts]: What about assigning `stepId = undefined` here instead of using a separate `internal` variable?

File: packages/playwright/src/worker/testInfo.ts [hunk 2]
```diff
@@ -480,7 +483,7 @@ export class TestInfoImpl implements TestInfo {
       contentType: attachment.contentType,
       path: attachment.path,
       body: attachment.body?.toString('base64'),
-      stepId,
+      stepId: internal ? undefined : stepId,
```
Comment (dgozman) [inline packages/playwright/src/worker/testInfo.ts]: Let's also undo the previous fix at line 462, and always pass `stepId`.

File: tests/playwright-test/reporter-attachment.spec.ts [hunk 3]
```diff
@@ -349,3 +349,36 @@ test('attaching inside boxed fixture should not log error', { annotation: { type
   expect(text).toContain('    ────────────────────────────────────────────────────────────────────────────────────────────────');
   expect(result.exitCode).toBe(1);
 });
+
+test('trace attaching should not log error', { annotation: { type: 'issue', description: 'https://github.com/microsoft/playwright/issues/37747' } }, async ({ runInlineTest }) => {
```
Comment (dgozman) [inline tests/playwright-test/reporter-attachment.spec.ts]: I don't really follow how this test is related to the bugfix :) I thought you just need to call `testInfo.attachments.push()` from inside a boxed fixture.

Comment (Skn0tt) [reply tests/playwright-test/reporter-attachment.spec.ts]: no, we already had that testcase in place. unsure what's different on this one, i should dig deeper.

Comment (Skn0tt) [reply tests/playwright-test/reporter-attachment.spec.ts]: oh you're right it's right there. `attachments.push` and `attach()` always bites me.

**Review by dgozman — APPROVED** [review]

**Comment by rnicholus** [comment]
This is still not fixed as of 1.56.1. Downgrading to 1.54.2 is the only reliable fix at the moment.

**Comment by Nick2bad4u** [comment]
[**@rnicholus**](https://github.com/rnicholus) commented on [Nov 20, 2025, 10:25 AM EST](https://github.com/microsoft/playwright/pull/37748#issuecomment-3558652835 "2025-11-20T15:25:09Z - Replied by Github Reply Comments"):
> This is still not fixed as of 1.56.1. Downgrading to 1.54.2 is the only reliable fix at the moment.
> 
> _Originally posted by @rnicholus in https://github.com/microsoft/playwright/issues/37748#issuecomment-3558652835_

Same here:

Adding another data point from an Electron test suite.

**Environment**

- `@playwright/test`: `1.56.1`
- OS: Windows (PowerShell 7.5, running locally)
- Playwright config: playwright.config.ts at repo root  
  - Single worker (`workers: 1`) for Electron stability


When running the Electron UI tests

I intermittently see:

```text
Internal error: step id not found: fixture@49
```

The tests themselves still appear to pass, but the internal error appears in the output exactly like what’s described in this issue.

It correlates with tests that:

- Use Electron fixtures to launch the app, then
- Open a modal, interact, and close the Electron app in `afterEach`.

**Observation / Workaround**

If I **turn off recording/attachments in the Playwright config**, the internal error goes away:

```ts
// playwright.config.ts
use: {
  // ...
  // Problematic:
  // screenshot: "only-on-failure",
  // trace: "on-first-retry",
  // video: "retain-on-failure",

  // Workaround that stops the error:
  screenshot: "off",
  trace: "off",
  video: "off",
}
```

With `screenshot/trace/video` disabled:

- The same Electron tests + fixtures run without any `step id not found` errors.
- No changes to the tests or Electron fixtures themselves are needed.

Given the upstream discussion here and in #37147, this looks like the same underlying attachment/step bookkeeping issue, just showing up in an Electron context (fixtures spinning up/tearing down ElectronApplication and windows) rather than a pure browser test.

**Repro pointer**

Repository: https://github.com/Nick2bad4u/Uptime-Watcher

The failing tests before the workaround are in:

- playwright/tests/ui-addsitemodal-basic.ui.playwright.test.ts

**Comment by Skn0tt** [comment]
Thanks for the repro @Nick2bad4u. This PR will fix the log line you're seeing, it's released as part of the imminent v1.57 version.

**Comment by Nick2bad4u** [comment]
> Thanks for the repro @Nick2bad4u. This PR will fix the log line you're seeing, it's released as part of the imminent v1.57 version.

Np. Glad to help and thanks for a fix
