### PR TITLE
fix: implement atomic append for compilation cache

### LINKED ISSUE #26769: Play wright tests are failing when running test cases through ado pipeline. Error [EPERM: operation not permitted, rename 'C:<some-path>\xx.map' -> 'C:\xy.map'
### System info
Playwright Version: [1.34.3]
Operating System: [Windows]
Browser: [Chromium]
Other info:

###Issue
When I am running the play wright test through an ado pipeline all test cases inside the test suite are failing. This is happening only for the first time pipeline run trigger. When I'm re triggering the same pipeline run this issue is not showing up.

###Error
Starting playwright: yarn playwright test x.e2e.test.ts --project=Chromium --retries=2

$ D:\data\CHT\134a2915\src\ooui\apps\package\node_modules.bin\playwright test x.e2e.test.ts --project=Chromium --retries=2

Error: EPERM: operation not permitted, rename 'C:<some-path>\xx.map' -> 'C:\xy.map'

at Object.renameSync (node:fs:980:3)
at writeFileSyncAtomic (D:\data\CHT\134a2915\src\ooui\.store\playwright-core@1.37.0-0fb057c8ee5a5ab5f173\node_modules\playwright-core\lib\utils\fileUtils.js:72:15)
at addToCache (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\compilationCache.js:99:47)
at transformHook (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\transform.js:159:13)
at _utilsBundle.pirates.addHook.exts (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\transform.js:196:12)
at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:936)
at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (D:\data\CHT\134a2915\src\ooui\packages\e2e-tests-utils\lib\src\login\index.ts:2:1)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (D:\data\CHT\134a2915\src\ooui\packages\e2e-tests-utils\src\index.ts:2:1)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (D:\data\CHT\134a2915\src\ooui\apps\package\playwright.config.ts:4:1)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at requireOrImport (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\transform.js:172:20)
at requireOrImportDefaultObject (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\common\configLoader.js:121:53)
at ConfigLoader.loadConfigFile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\common\configLoader.js:94:26)
at runTests (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\cli.js:118:55)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at i.<anonymous> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\cli.js:40:7) {
errno: -4048,
syscall: 'rename',
code: 'EPERM',
path: 'C:<some-path>\xx.map-beqweee',
dest: 'C:<some-path>\xy.map'
}

### PR DESCRIPTION
**Pull request by aslushnikov**
Note: this reverts commit ffd6cf60eb0fc3ea567802da7ed0e6de17f2133f.

Fixes #26769

### CODE REVIEW

File: packages/playwright-test/src/transform/compilationCache.ts [hunk 1]
```diff
@@ -85,17 +100,21 @@ export function getFromCompilationCache(filename: string, hash: string, moduleUr
...
   return {
     addToCache: (code: string, map: any) => {
       fs.mkdirSync(path.dirname(cachePath), { recursive: true });
-      if (map)
-        writeFileSyncAtomic(sourceMapPath, JSON.stringify(map), 'utf8');
-      writeFileSyncAtomic(codePath, code, 'utf8');
+      try {
+        if (map)
+          fs.writeFileSync(sourceMapPath, JSON.stringify(map), { encoding: 'utf8', flag: 'wx' });
+        fs.writeFileSync(codePath, code, { encoding: 'utf8', flag: 'wx' });
```
Comment (pavelfeldman) [inline packages/playwright-test/src/transform/compilationCache.ts:115]: If you break half-way here, you will never overwrite it with a healthy version.

**Review by pavelfeldman — APPROVED** [review]
