### PR TITLE
fix: align glob ** pattern matching with docs

### LINKED ISSUE #37068: [Bug]: waitForURL Doesn't Account for Query Parameters
### Version

1.53.2

### Steps to reproduce

1. Select option which triggers URL update with new/changed query parameter.
2. ```await app.page.waitForURL(`**layout=${layout}`);```

### Expected behavior

`waitForURL` resolves once the URL matches the pattern I provided.

### Actual behavior

The URL changes to `https://localhost:3000/?layout=grid` but the runner just sits there and never resolves.

### Additional context

_No response_

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 22.49 GB / 46.93 GB
  Container: Yes
Binaries:
  Node: 22.17.0 - /usr/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.9.2 - /usr/bin/npm
Languages:
  Bash: 5.2.21 - /usr/bin/bash
```

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/37068

### CODE REVIEW

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts [hunk 1]
```diff
@@ -30,22 +30,15 @@ export function globToRegexPattern(glob: string): string {
...
-      const afterDeep = glob[i + 1];
-      const isDeep = starCount > 1 &&
-          (beforeDeep === '/' || beforeDeep === undefined) &&
-          (afterDeep === '/' || afterDeep === undefined);
-      if (isDeep) {
-        tokens.push('((?:[^/]*(?:\/|$))*)');
-        i++;
-      } else {
+      if (starCount > 1)
+        tokens.push('(.*)');
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/isomorphic/urlMatch.ts:39]: :fire:

**Review by pavelfeldman — APPROVED** [review]
