### PR TITLE
fix(focus): make sure strictness is respected

### LINKED ISSUE #10680: [BUG] locator.focus() does not raise error if locator points to multiple elements with 1.17.0.
**Context:**
- Playwright Version: 1.17.0 and 1.16.3
- Operating System: Mac
- Node.js version: v14.16.0
- Browser: Chromium
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('//link');
  await title.focus();
});
```

**Describe the bug**
With version 1.16.3 above code raises error: `locator.focus: Error: strict mode violation: "//link" resolved to 43 elements:`. But with version 1.17.0 above code passes, but I did expect the code to raise an error.

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/10680

### CODE REVIEW

File: packages/playwright-core/src/server/frames.ts [hunk 1]
```diff
@@ -1037,21 +1037,21 @@ export class Frame extends SdkObject {
   async click(metadata: CallMetadata, selector: string, options: types.MouseClickOptions & types.PointerActionWaitOptions & types.NavigatingActionWaitOptions) {
     const controller = new ProgressController(metadata, this);
     return controller.run(async progress => {
-      return dom.assertDone(await this._retryWithProgressIfNotConnected(progress, selector, options.strict, handle => handle._click(progress, options)));
+      return dom.assertDone(await this._retryWithProgressIfNotConnected(progress, selector, options.strict || false, handle => handle._click(progress, options)));
```
Comment (dgozman) [inline packages/playwright-core/src/server/frames.ts:1040]: nit: we usually do `!!options.strict`

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/frames.ts (hunk 1 above)
Comment (pavelfeldman) [reply packages/playwright-core/src/server/frames.ts]: Done!
