### PR TITLE
fix(test runner): make TestTracing responsible for trace management

### LINKED ISSUE #28476: [BUG] Inaccessible Test Data in UI Mode Post-BeforeAll Hook in UI mode during test execution
### System info
- Playwright Version: [v1.39, v1.40]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code
[Repo with code for reproducing](https://github.com/mi4i0/pw-playground)

I recorded a short [explanation video](https://drive.google.com/file/d/1m58UkaAc-6pa-Mpuqv4lxj5ytU3ztr_p/view?usp=sharing), if needed

**Steps**
1. Open UI mode
2. Run example.spec.ts
3. Check Actions and other test information for this test during execution

**Expected**

Test information (Network, actions, etc.) should be accessible during test execution for all hooks (BeforeAll, beforeEach, etc..)

**Actual**

Test information (such as Network, execution trace, Actions section) disappears after execution of the BeforeAll hook and appears again only after the test finishes (failing, passing, or stopping)

### LINKED ISSUE #28733: [BUG] Trace is not being retained on test failure in before/after hooks.
### System info
Playwright Version: [v1.38.x, v1.39.x, v1.40.0, v1.40.1, v1.41.0-alpha-nov-23-2023]
Operating System: Ubuntu
Browser: [Chromium]
Node Version: v18.17.1
Browser Image: `mcr.microsoft.com/playwright:v<playwright-version>-focal`

### Source code

```
// playwright.config.ts

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: require.resolve('./global-teardown'),
  outputDir: 'test-results',
  testDir: 'tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  timeout: process.env.TEST_TIMEOUT,
  expect: { timeout: 15 * 1000 }, // 15 seconds
  retries: process.env.RETRIES,
  workers: process.env.WORKERS,
  repeatEach: process.env.REPEAT_EACH,

  use: {
    baseURL: process.env.BASE_URL,
    headless: true,
    viewport: { width: process.env.BROWSER_WIDTH, height: process.env.BROWSER_HEIGHT },
    ignoreHTTPSErrors: true,
    defaultBrowserType: 'chromium',
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
    permissions: ['clipboard-read', 'clipboard-write'],
    storageState: <customized storage state>,
    actionTimeout: process.env.ACTION_TIMEOUT,
    navigationTimeout: process.env.NAVIGATION_TIMEOUT,
  },

  reporter: [
    ['list'],
    [
      'allure-playwright',
      {
        suiteTitle: true,
        environmentInfo: {
          NODE_VERSION: process.version,
          OS: process.platform,
          IS_HEADLESS: process.env.HEADLESS,
          BROWSER: process.env.BROWSER,
        },
      },
    ],
    ['json', { outputFile: 'test-results.json' }],
    ['junit', { outputFile: 'test-results.xml' }],
    ['html', { open: 'never' }],
    ['./summaryReporter'],
  ],

  projects: [
    {
      name: 'chromium',
      use: '{ browserName: 'chromium' }',
    },
  ],
});
```
**Steps**
- Running test on docker machine with ubuntu image.
- We are also using **autoWorkerFixture** to store session.

**Expected**

Trace should retain on test failures.

**Actual**

- Trace is not being retained on test failure in before/after hooks.

### LINKED ISSUE #29133: [BUG] Playwright sometimes report failed test even when there are no failed assertions or no assertions at all
I have a page that has a selection box where users can check which widgets they want to see. When they check one, the page calls my API for the relevant info and displays a widget on screen. The test passes, but sometimes it would say it failed, even when there are no errors in the errors log.

### System info
- Playwright Version: v1.40.1
- Operating System: WSL2 w/ Ubuntu 22.04
- Browser: Chromium
- Other info:

### Source code

```ts
import { test, expect } from "@playwright/test";

test.beforeEach(async ({ page }) => {
    await page.goto("/rfid");
});

test.setTimeout(5000);

test("Select cell", async ({ page }) => {
    const rfidRequestPromise = page.waitForRequest("/api/rfid/**");
    const selectStationWidget = page
        .locator("div.MuiStack-root")
        .filter({ hasText: "Select stations" });

    await selectStationWidget.click();

    await selectStationWidget
        .getByRole("checkbox", { name: "Select All" })
        .first()
        .check();

    try {
        await rfidRequestPromise;
    } catch (e) {
        console.log("e", e);
    }

    const checkedStatus = await Promise.all(
        (
            await selectStationWidget.getByRole("checkbox").all()
        ).map(async (el) => await el.isChecked())
    );

    expect(checkedStatus.every((status) => status)).toBe(true);

    const selectStationTexts = await selectStationWidget
        .locator("label")
        .filter({ hasNotText: "Select All" })
        .locator("span.MuiTypography-root")
        .allInnerTexts();

    const rfidWidgetEl = page.locator("div.MuiMasonry-root > .MuiBox-root");
    await Promise.allSettled(
        (await rfidWidgetEl.all()).map(async (el) => await el.waitFor())
    );
    const rfidTitles = await rfidWidgetEl.locator("a").allInnerTexts();

    expect(selectStationTexts.sort()).toEqual(rfidTitles.sort());
});
```

Screenshot of Playwright test UI: https://prnt.sc/pcwUwwXrNa6e

**Steps**
- Run the test a bunch of times

**Expected**

It should pass every time

**Actual**

Sometimes it fails

### PR DESCRIPTION
**Pull request by dgozman**
... instead of a fixture.

Fixes #29133, fixes #28733, fixes #28476.

### CODE REVIEW

File: packages/playwright/src/worker/workerMain.ts [hunk 1]
```diff
@@ -313,6 +313,17 @@ export class WorkerMain extends ProcessRunner {
     let shouldRunAfterEachHooks = false;
 
     await testInfo._runWithTimeout(async () => {
+      const traceError = await testInfo._runAndFailOnError(async () => {
+        const traceFixtureRegistration = test._pool!.registrations.get('trace');
```
Comment (pavelfeldman) [inline packages/playwright/src/worker/workerMain.ts:317]: This is the only place we don't like.

File: packages/playwright/src/worker/testTracing.ts [hunk 2]
```diff
@@ -19,31 +19,104 @@ import type * as trace from '@trace/trace';
...
   private _liveTraceFile: string | undefined;
   private _traceEvents: trace.TraceEvent[] = [];
-  private _options: { sources: boolean; attachments: boolean; _live: boolean; } | undefined;
+  private _temporaryTraceFiles: string[] = [];
+  private _artifactsDir: string;
+  private _tracesDir: string;
+
+  constructor(testInfo: TestInfoImpl) {
+    this._testInfo = testInfo;
+    this._artifactsDir = process.env.TEST_ARTIFACTS_DIR!;
```
Comment (pavelfeldman) [inline packages/playwright/src/worker/testTracing.ts:47]: Now that this is a part of the test runner, you can use explicit value.

**Review by pavelfeldman — APPROVED** [review]
