### PR TITLE
fix(ui): Wait with polling if test is still scheduled

### LINKED ISSUE #38359: [Bug]: Source temporarily disappears when starting test
### Version

1.57.0

### Steps to reproduce

1. Open playwright UI mode
2. Click/focus on a test
3. Run this test
4. Open the 'Source' tab

### Expected behavior

To keep seeing the source of the test

### Actual behavior

For a couple of seconds (during the 'pending' phase) the content of the file is not visible anymore
Image

### Additional context

_No response_

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.93 GB / 15.83 GB
  Binaries:
    Node: 24.11.0 
    npm: 11.6.1
  npmPackages:
    @playwright/test: ^1.56.0 => 1.57.0
```

### PR DESCRIPTION
**Pull request by cpAdm**
Don't poll if the selected test is still selected. Wait for a response from the websocket instead that the test has started (that updates `item` prop). This polling fetch would fail (sw errors), causing the model to be set to a new `TraceModel` with an empty `traceURI`, which in case would make the source call fail (the original issue).

Added assertions to existing test. 
> Tried instead adding following assertions in `runUITest` fixture:
>```
> expect.soft((page && !page.isClosed()) ? await page.consoleMessages() : []).toHaveLength(0);
> expect.soft((page && !page.isClosed()) ? await page.pageErrors() : []).toHaveLength(0);
>```
>
>However many would then fail:
>`snapshot action must have a pageId` (10+ ui-mode tests; e.g. `should not duplicate network entries from beforeAll`)
>`Failed to load resource: the server responded with a status of 404 (Not Found)`  (`should run folder` / `should merge trace events` / `should merge web assertion events` / `should show request source context id`)

Closes: #38359

### CODE REVIEW

File: packages/trace-viewer/src/ui/uiModeTraceView.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ export const TraceView: React.FC<{
       clearTimeout(pollTimer.current);
 
     const result = item.testCase?.results[0];
-    if (!result) {
+    if (!result || item.treeItem?.status === 'scheduled') {
```
Comment (pavelfeldman) [inline packages/trace-viewer/src/ui/uiModeTraceView.tsx:49]: How do we have a test result for something that has not run yet?

Comment (cpAdm) [reply packages/trace-viewer/src/ui/uiModeTraceView.tsx:49]: When running tests, an empty/default `TeleTestResult` is created on the `TeleTestCase` (via `_createTestResult`)
https://github.com/microsoft/playwright/blob/4e0eaba6d9b97cf5752b1374d9a58b3cae4d0428/packages/trace-viewer/src/ui/uiModeView.tsx#L276-L286

File: tests/playwright-test/ui-mode-test-run.spec.ts [hunk 2]
```diff
@@ -160,6 +160,11 @@ test('should run on double click', async ({ runUITest }) => {
             - button "Watch"
           - treeitem "[icon-circle-outline] fails"
   `);
+
+  const allMessages = await page.consoleMessages();
+  const messages = allMessages.filter(m => !m.location().url.includes('trace/sha1/src'));
+  expect(messages).toHaveLength(0);
+  expect(await page.pageErrors()).toHaveLength(0);
```
Comment (Skn0tt) [inline tests/playwright-test/ui-mode-test-run.spec.ts]: it feels wrong to assert on console messages, can this same behaviour also be tested through the source tab?

**Review by Skn0tt — COMMENTED** [review]
Sorry for the late review. The change looks good, but I wonder about the test.

File: tests/playwright-test/ui-mode-test-run.spec.ts (hunk 2 above)
Comment (cpAdm) [reply tests/playwright-test/ui-mode-test-run.spec.ts]: Well I think asserting on console messages is a good way to catch otherwise undetected bugs. 

But I agree that we should add a specific test here, done that.

**Review by Skn0tt — APPROVED** [review]
