### PR TITLE
fix(test runner): separate test fixture scope for beforeAll/afterAll hooks

### LINKED ISSUE #22256: [BUG] afterAll block should be executed after test fixture cleanup
### System info
- Playwright Version: [v1.32.2]
- Operating System: [All]
- Browser: [Chromium]
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
// a.spec.ts
import { test as base } from '@playwright/test';

const test = base.extend<{ testFixture: void }>({
	testFixture: async ({}, use) => {
		console.log('setup test fixture')
		await use();
		console.log('cleanup test fixture')
	},
});

test.describe("describeName", () => {
	test.beforeAll(async ({ browser }) => {
		console.log('before all');
	});

	test.afterAll(async () => {
		console.log('after all');
	});

	test.beforeEach(async () => {
		console.log('before each');
	});

	test.afterEach(async () => {
		console.log('after each');
	});

	test('test 1', async ({testFixture}) => {
		console.log('test 1');
	});

	test('test 2', async ({testFixture}) => {
		console.log('test 2');
	});
});
```

**Steps**
- `npx playwright test specs/a.spec.ts`
- Expect `after all` to be output AFTER `cleanup test fixture`, as documented [here](https://playwright.dev/docs/test-fixtures#execution-order). I am using beforeAll/afterAll to setup/teardown needed data for tests. I need to ensure that the browser page is closed before deleting the data, or I will run into issues where the deleted data is affecting tests.

**Expected**
```
Running 2 tests using 1 worker

  ✓  1 [chromium] › specs/a.spec.ts:31:3 › describeName › test 1 (6ms)
before all
before each
setup test fixture
test 1
after each
cleanup test fixture
  ✓  2 [chromium] › specs/a.spec.ts:35:3 › describeName › test 2 (4ms)
before each
setup test fixture
test 2
after each
cleanup test fixture
after all
```
**Actual**
```
Running 2 tests using 1 worker

  ✓  1 [chromium] › specs/a.spec.ts:31:3 › describeName › test 1 (6ms)
before all
before each
setup test fixture
test 1
after each
cleanup test fixture
  ✓  2 [chromium] › specs/a.spec.ts:35:3 › describeName › test 2 (4ms)
before each
setup test fixture
test 2
after each
after all
cleanup test fixture
```

### PR DESCRIPTION
**Pull request by dgozman**
There was a single test fixture scope that covers all hooks, modifiers and test function. Now beforeAll-like modifiers, beforeAll and afterAll hooks get a scope each.

Fixes #22256.

### CODE REVIEW

File: packages/playwright-test/src/worker/workerMain.ts [hunk 1]
```diff
@@ -492,6 +497,11 @@ export class WorkerMain extends ProcessRunner {
       if (result && extraAnnotations)
         extraAnnotations.push({ type: modifier.type, description: modifier.description });
       testInfo[modifier.type](!!result, modifier.description);
+      if (scope === 'worker') {
+        // Teardown test scope for worker-scoped modifiers, because these are considered beforeAll-like.
```
Comment (pavelfeldman) [inline packages/playwright-test/src/worker/workerMain.ts:501]: According to you, we don't need this code.

**Review by pavelfeldman — APPROVED** [review]
