### PR TITLE
fix(html): remove filter clear button

### LINKED ISSUE #33681: [Bug]: Playwright HTML report does not clear project filter from localhost URL, and reuses this previously used project filter when another filter is applied
### Version

1.49.0

### Steps to reproduce

1. Clone my repo at [https://github.com/apatelia/simple-pw-test](https://github.com/apatelia/simple-pw-test)
2. Install dependencies - `npm install`
3. Install browsers - `npx playwright install`
4. Run tests - `npx playwright test`
5. Open test report - `npx playwright show-report`
6. Notice that all four tests are displayed as passed under `example.spec.ts` file.
7. Click on `chromium` project badge from any test where it is displayed.
8. Notice that `p:chromium` is applied as a search filter in search box at the top of the report, and the URL is updated with `?q=p:chromium` querystring. Only two tests are displayed for `chromium` project.
9. Now, clear this `p:chromium` filter using `x` button that becomes available when mouse is hovered on the extreme right side of search box, as show below.
Image

10. Notice that search box is empty now and all four tests (chromium + Firefox) are displayed correctly. However, URL still contains the `?q=p:chromium` querystring.
11. Now, click on `link` badge displayed next to any of the `get started link` test.
12. Notice that `p:chromium` is reused along with `@link` as search filter even though it was not intended. Also, URL is updated with `?q=p:chromium%20@link` querystring. Also, only one `get started link` test is displayed instead of two tests (chromium + Firefox).
Image

### Expected behavior

I expect to see two (chromium + Firefox) `get started link` tests filtered and displayed instead of only one from `chromium` project, as I applied only `@link` filter and not `p:chromium` filter.

Image

### Actual behavior

It seems that `p:chromium` filter is not cleared from the URL and then it is reused along with `@link` filter, when only `@link` filter is applied.

### Additional context

This bug may be present in older versions as well, I noticed it only after upgrading to 1.49.

I am reporting this bug using Linux now, but I can reproduce this on Windows 11 as well.

### Environment

```shell
System:
    OS: Linux 6.11 Arch Linux
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 22.18 GB / 31.06 GB
    Container: Yes
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.13.2 - ~/.local/share/pnpm/pnpm
  IDEs:
    VSCode: 1.95.3 - /usr/bin/code
  Languages:
    Bash: 5.2.37 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/33681. We tried fixing the nav behaviour in https://github.com/microsoft/playwright/pull/33689, but couldn't come up with behaviour that works well with the browser history. See https://stackoverflow.com/questions/2977023/how-do-you-detect-the-clearing-of-a-search-html5-input for why we cannot detect if the `x` was clicked or the text was deleted.

To remove confusion, this PR removes the `clear` button. Users can still clear with <kbd>⌘+a 🔙</kbd>, and it'll do the right thing.

### CODE REVIEW

File: packages/html-reporter/src/headerView.tsx [hunk 1]
```diff
@@ -49,12 +49,12 @@ export const HeaderView: React.FC<React.PropsWithChildren<{
       <form className='subnav-search' onSubmit={
         event => {
           event.preventDefault();
-          navigate(`#?q=${filterText ? encodeURIComponent(filterText) : ''}`);
+          navigate(filterText ? '#?' + new URLSearchParams({ q: filterText }) : '/');
```
Comment (dgozman) [inline packages/html-reporter/src/headerView.tsx:52]: Why `/`? Wouldn't that navigate to the top-level, even when I open/serve the html report from a subpath?

Comment (Skn0tt) [reply packages/html-reporter/src/headerView.tsx:52]: That's a fair point. I tried `''`, but that didn't do anything. Let me try that again.

Comment (Skn0tt) [reply packages/html-reporter/src/headerView.tsx]: there you go: https://github.com/microsoft/playwright/pull/33754/commits/ebf15622e4cf2fb2473543343a7935ad0198a899

**Review by dgozman — APPROVED** [review]
