### PR TITLE
fix(trace viewer): make paths via stdin work

### LINKED ISSUE #39096: fix(trace): StdinServer._loadTrace does not convert file path to URI format
## Bug Description

In Playwright 1.58.0, the `StdinServer._loadTrace()` method in `traceViewer.ts` does not call `validateTraceUrl()` to convert file paths to the `file?path=` URI format. This causes the trace viewer to fail when receiving trace paths via stdin (used by VS Code extension for live trace).

## Steps to Reproduce

1. Install Playwright 1.58.0 or 1.58.1
2. Use VS Code extension (v1.1.17) with "Show trace viewer" enabled
3. Run a test
4. Observe the trace viewer fails to load with error:

```
Not allowed to load local resource: file:///C:/Users/.../test-results/.playwright-artifacts-0/traces/xxx.json
```

## Root Cause

In commit `185bfb7d4` ("fix(trace): operate trace uri, not path #38566"), the `validateTraceUrl()` function was updated to convert file paths to `file?path=` URI format. However, `StdinServer._loadTrace()` was not updated to use this function.

**Current code (buggy):**
```typescript
private _loadTrace(traceUrl: string) {
  this._traceUrl = traceUrl;  // Raw file path sent to frontend
  clearTimeout(this._pollTimer);
  this.sendEvent?.('loadTraceRequested', { traceUrl });
}
```

**Expected behavior:**
The path should be converted using `validateTraceUrl()` before sending to frontend.

## Affected Components

- VS Code extension live trace functionality
- Any client using `--stdin` mode with `show-trace`

## Workaround

Apply this patch to `node_modules/playwright-core/lib/server/trace/viewer/traceViewer.js`:

```diff
   _loadTrace(traceUrl) {
-    this._traceUrl = traceUrl;
+    const validatedUrl = validateTraceUrl(traceUrl);
+    this._traceUrl = validatedUrl;
     clearTimeout(this._pollTimer);
-    this.sendEvent?.("loadTraceRequested", { traceUrl });
+    this.sendEvent?.("loadTraceRequested", { traceUrl: validatedUrl });
   }
```

For pnpm users, save this as `patches/playwright-core@1.58.1.patch` and add to `package.json`:
```json
"pnpm": {
  "patchedDependencies": {
    "playwright-core@1.58.1": "patches/playwright-core@1.58.1.patch"
  }
}
```

## Environment

- Playwright version: 1.58.0, 1.58.1
- VS Code extension version: 1.1.17
- OS: Windows 11
- Node.js: 20.x

## Related

- Introduced in: #38566

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/39096, which is a regression from https://github.com/microsoft/playwright/pull/38566. The fix is exactly what @li-zhixin outlines, thanks!

### CODE REVIEW

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts [hunk 1]
```diff
@@ -30,11 +30,12 @@ import type { Transport } from '../../utils/httpServer';
 import type { BrowserType } from '../../browserType';
 import type { Page } from '../../page';
 import type http from 'http';
+import type { Readable } from 'stream';
 
 export type TraceViewerServerOptions = {
   host?: string;
   port?: number;
-  isServer?: boolean;
+  stdin?: Readable;
```
Comment (Skn0tt) [inline packages/playwright-core/src/server/trace/viewer/traceViewer.ts]: This can be imported via `playwright-core/server`. I suspect we only have it for testing purposes, and it's not part of our public API to anyone.

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts [hunk 2]
```diff
@@ -224,7 +225,7 @@ class StdinServer implements Transport {
       else
         this._loadTrace(url);
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/trace/viewer/traceViewer.ts:225]: - Make sure that when something enters our code it goes via validateTraceUrl immediately. Rename it to validateTraceUrl to validateTraceUrlOrPath

File: tests/library/trace-viewer.spec.ts [hunk 3]
```diff
@@ -2248,3 +2249,14 @@ test('should capture iframe with srcdoc', async ({ page, server, runAndTrace })
   const frame = await traceViewer.snapshotFrame('Evaluate');
   await expect(frame.frameLocator('iframe').getByRole('button')).toHaveText('Hello iframe');
 });
+
+test('take trace paths via stdin', async ({ showTraceViewer }, testInfo) => {
+  const stdin = new PassThrough();
+  const traceViewer = await showTraceViewer(testInfo.outputPath(), { stdin });
```
Comment (pavelfeldman) [inline tests/library/trace-viewer.spec.ts]: - Let's make sure our tests are e2e, do not use stdin.

File: tests/config/traceViewerFixtures.ts [hunk 4]
```diff
@@ -178,4 +183,17 @@ export const traceViewerFixtures: Fixtures<TraceViewerFixtures, {}, BaseTestFixt
       return showTraceViewer(traceFile);
     });
   },
+
+  startTraceViewer: async ({ context, childProcess }, use) => {
```
Comment (dgozman) [inline tests/config/traceViewerFixtures.ts]: Naming is hard! I will not be able to figure whether to `startTraceViewer` or `showTraceViewer` later on. Perhaps inline this fixture into the test for now?

**Review by dgozman — APPROVED** [review]
