### PR TITLE
fix: timeout error when downloading browsers

### LINKED ISSUE #34686: [Bug]: Time out when downloading browsers
### Version

1.50.1

### Steps to reproduce

- Have a bad internet connection
- Run `pnpm exec playwright install`

### Expected behavior

Browsers download slowly in one go

### Actual behavior

```
Downloading Chromium Headless Shell 133.0.6943.16 (playwright build v1155) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1155/chromium-headless-shell-mac-arm64.zip
77.9 MiB [======              ] 28% 75.7sError: Request to https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1155/chromium-headless-shell-mac-arm64.zip timed out after 30000ms
    at ClientRequest.rejectOnTimeout (/Users/arnaud/git/vite-plugin-react-swc/node_modules/.pnpm/playwright-core@1.50.1/node_modules/playwright-core/lib/utils/network.js:76:15)
    at Object.onceWrapper (node:events:621:28)
    at ClientRequest.emit (node:events:507:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:863:9)
    at Object.onceWrapper (node:events:621:28)
    at TLSSocket.emit (node:events:519:35)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:614:17)
    at process.processTimers (node:internal/timers:549:7)
Downloading Chromium Headless Shell 133.0.6943.16 (playwright build v1155) from https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1155/chromium-headless-shell-mac-arm64.zip
77.9 MiB [====================] 100% 0.0s
Chromium Headless Shell 133.0.6943.16 (playwright build v1155) downloaded to /Users/arnaud/Library/Caches/ms-playwright/chromium_headless_shell-1155
```

### Additional context

The download actually went through the second try, but that's 30s waisted on each browser

### Environment

```shell
MacOS 15, node v23.7.0
```

### PR DESCRIPTION
**Pull request by yury-s**
When cdn server returns a redirect, we create a new request to it and continue the download using it. The old request has an open socket that is idling and if the download takes longer than configured timeout, old request will throw a timeout error. The fix is to make sure to close original request when we no longer need it.

Fixes https://github.com/microsoft/playwright/issues/34686

### CODE REVIEW

**Review by dgozman — APPROVED** [review]
Nice finding!

File: packages/playwright-core/src/server/utils/network.ts [hunk 1]
```diff
@@ -70,10 +70,14 @@ export function httpRequest(params: HTTPRequestParams, onResponse: (r: http.Inco
 
   const requestCallback = (res: http.IncomingMessage) => {
     const statusCode = res.statusCode || 0;
-    if (statusCode >= 300 && statusCode < 400 && res.headers.location)
+    if (statusCode >= 300 && statusCode < 400 && res.headers.location) {
+      // Close the original socket before following the redirect. Otherwise
+      // it may stay idle and cause a timeout error.
+      request.destroy();
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/utils/network.ts:76]: This would also [destroy the underlying TCP socket](https://github.com/nodejs/node/blob/9bbbe60f6b0001964cb62182ce17e7f3980ccf06/lib/_http_outgoing.js#L319), which means setting `keepAlive: true` would no longer have any effect. As of today we attempt to use [keepAlive: true](https://github.com/microsoft/playwright/blob/c9a1ad4d8d718300b0ed2828daa7311bb1692d01/packages/playwright-core/src/server/utils/happyEyeballs.ts#L54-L56) but it was not working for browser downloads because:

- We have a child process / fork for each download. This makes it impossible to re-use TCP connections and leverage `keep-alive: true`.
- With your PR we'd destroy the sockets. We should call `res.resume()` instead of un-register the event listeners.

Also your test also passes without the change to `network.ts` for me which is interesting.

I think we should aim to properly use keepAlive. Whether that's part of this PR or a follow-up can be debated.
This would require getting rid of the OOP (out-of-process) downloader, which was already on the agenda.

Comment (mxschmitt) [reply packages/playwright-core/src/server/utils/network.ts:76]: Discussed offline: Let's follow up with keepAlive: true.

**Review by dgozman — APPROVED** [review]
