### PR TITLE
fix(trace): don't replace unknown braces in action title

### LINKED ISSUE #36483: [Regression]: trace viewer mangles collapsible group names that include text such as double curly braces (e.g. `{{ stuff }}`)
### Version

1.53.0

### Steps to reproduce

1. Download this playwright trace: [example-trace.zip](https://github.com/user-attachments/files/20952907/example-trace.zip)
2. Use playwright version `1.52` trace viewer to view the trace, e.g. `playwright show-trace example-trace.zip`
    - Observe that the trace _correctly_ shows `hidden_stuff` in the collapsible group text:
        Correct display with version 1.52
3. Use playwright version `1.53.0` trace viewer to view the trace, e.g. `playwright show-trace example-trace.zip`
    - Observe that the trace _does not_ correctly show `hidden_stuff` in the collapsible group text:
        Incorrect display with version 1.53.0

### Expected behavior

Playwright trace viewer should show the collapsible group name exactly as given in the string passed to [Tracing.group(name)](https://playwright.dev/python/docs/api/class-tracing#tracing-group-option-name), even if it has unusual characters such as curly braces

E.g. as with version `1.52`:
Correct display with version 1.52

### Actual behavior

Collapsible group names are sometimes mangled if the have unusual characters such as curly braces

E.g.:
Incorrect display with version 1.53.0

### Additional context

The following script was used to generate the attached [example trace](https://github.com/user-attachments/files/20952907/example-trace.zip):
```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "playwright~=1.52.0",
# ]
# ///

from pathlib import Path

from playwright.sync_api import sync_playwright


def main():
    with (
        sync_playwright() as pw,
        pw.chromium.launch(headless=False) as browser,
        browser.new_context() as browser_context,
        browser_context.new_page() as page,
    ):
        browser_context.tracing.start(snapshots=True, screenshots=True, sources=True)
        try:
            browser_context.tracing.group("This group has curly braces here --> {{ hidden_stuff }} <--")
            page.evaluate("console.log('hello world')")
            browser_context.tracing.group_end()
        finally:
            browser_context.tracing.stop(path=Path("example-trace.zip"))


if __name__ == "__main__":
    main()
```

NOTE: while the given trace was generated with playwright version `1.52.0`, the issue also occurs for traces generated with `1.53.0`

### Environment

```Text
- Operating System: macOS 15.3.2
- CPU: arm64
- Browser: All
- Python Version: Any
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/36483

### CODE REVIEW

File: packages/trace-viewer/src/ui/actionList.tsx [hunk 1]
```diff
@@ -164,6 +164,13 @@ export function renderTitleForCall(action: ActionTraceEvent): { elements: React.
     title.push(chunk);
 
     const param = formatProtocolParam(action.params, quotedText);
+    if (!param) {
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/actionList.tsx]: Let's make `formatProtocolParam` return `undefined` for failures, so we can differentiate between an empty string and a missing param.

We should also update `renderTitleForCall`.

Comment (Skn0tt) [reply packages/trace-viewer/src/ui/actionList.tsx]: Done. I also had to change the title in protocol.yml to remove our "{a}{b}" syntax of optionality, since it's clashing with this change.

File: packages/protocol/src/protocol.yml [hunk 2]
```diff
@@ -1425,19 +1425,19 @@ BrowserContext:
         enabled: boolean
 
     clockFastForward:
-      title: Fast forward clock "{ticksNumber}{ticksString}"
+      title: Fast forward clock "{ticks}"
```
Comment (dgozman) [inline packages/protocol/src/protocol.yml]: How about `{ticksNumber|ticksString}`?

File: packages/trace-viewer/src/ui/actionList.tsx [hunk 3]
```diff
@@ -164,6 +164,13 @@ export function renderTitleForCall(action: ActionTraceEvent): { elements: React.
     title.push(chunk);
 
     const param = formatProtocolParam(action.params, quotedText);
+    if (param === undefined) {
+      elements.push(fullMatch);
+      title.push(fullMatch);
+      currentIndex = match.index + fullMatch.length;
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/actionList.tsx]: nit: I'd prefer this line to not be repeated, perhaps `if () {} else if () {} else {}` would be better?

File: packages/playwright-core/src/utils/isomorphic/protocolFormatter.ts [hunk 4]
```diff
@@ -16,44 +16,50 @@
...
+    if (name === 'url') {
+      try {
+        const urlObject = new URL(params[name]);
+        if (urlObject.protocol === 'data:')
+          return urlObject.protocol;
+        if (urlObject.protocol === 'about:')
+          return params[name];
+        return urlObject.pathname + urlObject.search;
+      } catch (error) {
         return params[name];
```
Comment (dgozman) [inline packages/playwright-core/src/utils/isomorphic/protocolFormatter.ts]:
```suggestion
        if (params[name] !== undefined)
          return params[name];
```

File: packages/playwright-core/src/utils/isomorphic/protocolFormatter.ts [hunk 5]
```diff
@@ -16,44 +16,50 @@
...
-    } catch (error) {
-      return params[name];
+      }
     }
-  }
-  if (name === 'timeNumber') {
+    if (name === 'timeNumber') {
     // eslint-disable-next-line no-restricted-globals
-    return new Date(params[name]).toString();
+      return new Date(params[name]).toString();
```
Comment (dgozman) [inline packages/playwright-core/src/utils/isomorphic/protocolFormatter.ts:39]:
```suggestion
      if (params[name] !== undefined)
        return new Date(params[name]).toString();
```

**Review by dgozman — APPROVED** [review]
