### PR TITLE
fix: reset SNAP* env variables when launching Firefox

### LINKED ISSUE #20555: [BUG] Firefox problems when running v1.30.0 inside Webstorm snap terminal
**Context:**

## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 11.14 GB / 27.24 GB
 - Container: Yes (reported by `npx envinfo`, even outside of snap)

## Binaries:
 - Node: 18.13.0 - /usr/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.19.3 - /usr/bin/npm

## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Describe the bug**

Slightly odd problem here (and it may be out of Playwright's control). 

When I run Playwright v1.30.0 inside the terminal in the snap version of WebStorm (e.g. version 2022.3.2), it is unable to launch Firefox with varying symptoms (depending on headless vs headed).

### When running headless

Playwright hangs indefinitely. After pressing Ctrl-C, it prints:

```
    Test was interrupted.

    Fixture "browser" timeout of 0ms exceeded.
```

### When running headed

There are a few errors. First, this:

image

Followed by:

```
[WebServer] (node:342129) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
  1) [firefox] › example.spec.ts:4:7 › @setA › test a ==============================================

    browserContext.newPage: Protocol error (Browser.newPage): Unexpected number of tabs in the new window: 2 newPage@chrome://juggler/content/TargetRegistry.js:317:13
```

The extra tab is a Firefox privacy notice (https://www.mozilla.org/en-US/privacy/firefox/). The browser looks like this:

image

It says it is using the profile `/tmp/playwright_firefoxdev_profile-pkwZ9l` (which is presumably correct).

I see various differences in the Firefox configuration that is used in this scenario. For example, with v1.30.0 inside snap:

```
  "processes": {
    "remoteTypes": {
      "extension": 1,
      "web": 1,
      "webIsolated": 1,
      "privilegedabout": 1,
      "prealloc": 3,
      "socket": 1
    },
    "maxWebContentProcesses": 8
  },
```

v1.29.2 inside snap:

```
  "processes": {
    "remoteTypes": {
      "extension": 1,
      "web": 1,
      "socket": 1
    },
    "maxWebContentProcesses": 60000
  },
```

### When there is no problem

There is no problem with Playwright v1.29.2 inside WebStorm snap. There is also no problem when running Playwright v1.30.0 outside of WebStorm snap. And there is also no problem if I run Playwright inside the official container image inside WebStorm.

### Repro

The specific project doesn't seem to matter, but I pushed a simple example here: https://github.com/jpveooys/playwright-repro/tree/firefox-1-30-0 (where `playwright test --project firefox` can be run).

### PR DESCRIPTION
**Pull request by aslushnikov**
Our builds never come from Snap, so Playwright's Firefox should
never consider that it's been installed via SNAP.

Fixes #20555

### CODE REVIEW

File: packages/playwright-core/src/server/firefox/firefox.ts [hunk 1]
```diff
@@ -46,6 +46,12 @@ export class Firefox extends BrowserType {
   _amendEnvironment(env: Env, userDataDir: string, executable: string, browserArguments: string[]): Env {
     if (!path.isAbsolute(os.homedir()))
       throw new Error(`Cannot launch Firefox with relative home directory. Did you set ${os.platform() === 'win32' ? 'USERPROFILE' : 'HOME'} to a relative path?`);
+    if (os.platform() === 'linux') {
+      // Always remove SNAP_NAMe and SNAP_INSTANCE_NAME env variables since they
+      // confuse Firefox: in our case, builds never come from SNAP.
+      // See https://github.com/microsoft/playwright/issues/20555
+      return {...env, SNAP_NAME: undefined, SNAP_INSTANCE_NAME: undefined };
```
Comment (yury-s) [inline packages/playwright-core/src/server/firefox/firefox.ts:53]: nit: can we have a test for this?

**Review by yury-s — APPROVED** [review]

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/firefox/firefox.ts [hunk 2]
```diff
@@ -46,6 +46,12 @@ export class Firefox extends BrowserType {
   _amendEnvironment(env: Env, userDataDir: string, executable: string, browserArguments: string[]): Env {
     if (!path.isAbsolute(os.homedir()))
       throw new Error(`Cannot launch Firefox with relative home directory. Did you set ${os.platform() === 'win32' ? 'USERPROFILE' : 'HOME'} to a relative path?`);
+    if (os.platform() === 'linux') {
+      // Always remove SNAP_NAMe and SNAP_INSTANCE_NAME env variables since they
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/firefox/firefox.ts:50]:
```suggestion
      // Always remove SNAP_NAME and SNAP_INSTANCE_NAME env variables since they
```
