### PR TITLE
fix: sanitize malformed Unicode in MCP responses

### LINKED ISSUE #1447: Fix malformed Unicode in outgoing MCP responses
A browser action can succeed, but the follow-up MCP response fails to serialize with:

	the request body is not valid JSON: invalid high surrogate in string

This appears to happen when tool output includes malformed Unicode from page-derived text.

## Reproduction

- Start `@playwright/mcp` with `--extension`
- Navigate to a page containing problematic text content
- Perform a browser action such as `browser_click`
- Observe that the action succeeds, but the returned MCP response fails

## Observed behavior

The browser action completes, but the client receives an error during response handling:

`invalid high surrogate in string`

## Expected behavior

If page-derived text contains malformed Unicode, MCP should still return a valid JSON-RPC response instead of failing serialization.

## Likely root cause

The outgoing MCP message contains a JavaScript string with a lone surrogate or other non-well-formed Unicode sequence. This is most likely coming from page-derived strings such as accessibility snapshot text, console text, page title, URL, or other extracted content.

## Evidence

A local wrapper that sanitizes outgoing JSON-RPC string values before transport serialization fixes the issue without changing browser behavior. That strongly suggests the bug is in outgoing message serialization, not in the browser action itself.

## Suggested fix

Sanitize outgoing MCP message strings before transport serialization:

- use `String.prototype.toWellFormed()` when available
- otherwise replace lone surrogates with `\uFFFD`

Apply this at the transport boundary so it covers stdio, SSE, and streamable HTTP responses.

### PR DESCRIPTION
**Pull request by furkankoykiran**
## Summary

Fixes "invalid high surrogate in string" JSON serialization errors in MCP responses when page content contains malformed Unicode (lone surrogates).

## Changes

1. **Add `sanitizeUnicode()` function** ([response.ts](packages/playwright-core/src/tools/response.ts))
   - Uses `String.prototype.toWellFormed()` on Node 20+ for native Unicode sanitization
   - Falls back to manual surrogate replacement for Node 18 compatibility
   - Replaces lone surrogates with U+FFFD (replacement character)

2. **Integrate into response serialization**
   - Applied alongside existing `redactText()` function in `serialize()` method
   - Sanitizes all outgoing MCP response text before JSON serialization

3. **Add comprehensive tests** ([unicode-serialization.spec.ts](tests/mcp/unicode-serialization.spec.ts))
   - Lone high/low surrogates
   - Valid surrogate pairs (emoji, CJK)
   - Mixed content with malformed Unicode
   - Console messages with lone surrogates

## Context

Closes microsoft/playwright-mcp#1447

Previous attempt ([PR #1448 in playwright-mcp](https://github.com/microsoft/playwright-mcp/pull/1448)) was closed because it fixed the issue at the transport layer in `cli.js`. The proper fix location is in `response.ts` where text processing already happens via `redactText()`.

## Verification

```bash
npm run ctest-mcp unicode-serialization
# 6 passed (35.3s)
```

All tests pass, confirming that:
- MCP responses don't fail with JSON serialization errors
- Lone surrogates are replaced with U+FFFD
- Valid surrogate pairs (emoji, CJK) are preserved
- Normal text remains unchanged

### CODE REVIEW

File: packages/playwright-core/src/tools/response.ts [hunk 1]
```diff
@@ -265,6 +265,44 @@ function trimMiddle(text: string, maxLength: number) {
...
 
+/**
+ * Sanitizes a string to ensure it only contains well-formed Unicode.
+ * Replaces lone surrogates (high/low surrogates without their pair) with U+FFFD.
+ * Uses String.prototype.toWellFormed() when available (Node 20+), otherwise
+ * falls back to manual surrogate replacement for Node 18 compatibility.
+ */
+function sanitizeUnicode(text: string): string {
+  // Use native toWellFormed() when available (Node 20+)
+  if (typeof text.toWellFormed === 'function') {
```
Comment (pavelfeldman) [inline packages/playwright-core/src/tools/response.ts]: safe to assume Node 20+ for MCP, we are moving to being 20 altogether.

**Comment by pavelfeldman** [comment]
Also looks like agent-generated blob that fails lint. Better place to handle it though. Assume Node 20 and hand-craft the tests please.

**Comment by furkankoykiran** [comment]
Thanks for the feedback. I've simplified the changes based on your suggestions:

**Changes made:**

1. **Removed Node 18 fallback** - The `sanitizeUnicode()` function now only uses `String.prototype.toWellFormed()` as requested.

2. **Rewrote tests by hand** - Reduced from 6 tests to 3 focused tests that match the style of existing MCP tests:
   - Uses `server.setContent()` for simpler setup
   - Cleaner, more idiomatic test structure
   - Removed excessive assertions

3. **All tests pass** - Confirmed with `npm run ctest-mcp unicode-serialization`

   - handles lone surrogates in page content
   - preserves valid emoji and surrogate pairs
   - handles console messages with lone surrogates

The branch has also been rebased onto latest main and the PR is now up to date.

**Review by pavelfeldman — APPROVED** [review]
