### PR TITLE
fix(network): remove races from sizes calculation

### LINKED ISSUE #15017: [internal]: fix CR protocol ordering handling when responseReceivedExtraInfo comes after loadingFinished
repro:

` FORCE_COLOR=0 DEBUG=pw:protocol npm run ctest -- --headed tests/library/har.spec.ts:358 --repeat-each 1 --reporter=list --max-failures 1 --workers 1 &> test.txt `

telegram-cloud-photo-size-2-5300952528143367152-y

`Network.responseReceivedExtraInfo` comes in after `Network.loadingFinished`

### PR DESCRIPTION
**Pull request by dgozman**
- Do not resolve raw headers upon `loadingFinished`, since they may still come later in `responseReceivedExtraInfo`.
- Introduce separate promises for `encodedBodySize`, `transferSize` and `responseHeadersSize`.
- Make sure we resolve each of the above with data available from the browser, or fallback to manual calculation.
- Set raw response headers for redirects on WebKit.
- Do not stall on cached responses in Chromium, they have erroneously set `hasExtraInfo` flag.
- Use `transferSize` that is available in Firefox protocol.

Fixes #15017.

### CODE REVIEW

File: packages/playwright-core/src/server/webkit/wkPage.ts [hunk 1]
```diff
@@ -1080,6 +1073,9 @@ export class WKPage implements PageDelegate {
     if (!request)
       return;
 
+    // Use provisional headers if we didn't have the response with raw headers.
+    request.request.setRawRequestHeaders(null);
```
Comment (yury-s) [inline packages/playwright-core/src/server/webkit/wkPage.ts:1077]: move it to else branch below for clarity

**Review by yury-s — APPROVED** [review]
