### PR TITLE
fix(ui-mode): run teardown handlers with Command + C

### LINKED ISSUE #23907: [Bug] UI Mode via browser does not run worker teardown on CTRL + C
See https://github.com/microsoft/playwright/pull/23876#discussion_r1242443903.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/23907

### CODE REVIEW

File: tests/playwright-test/ui-mode-fixtures.ts [hunk 1]
```diff
@@ -21,17 +21,24 @@ import type { TestChildProcess } from '../config/commonFixtures';
 import { rimraf } from '../../packages/playwright-core/lib/utilsBundle';
 import { cleanEnv, cliEntrypoint, test as base, writeFiles } from './playwright-test-fixtures';
 import type { Files, RunOptions } from './playwright-test-fixtures';
-import type { Browser, Page, TestInfo } from './stable-test-runner';
+import type { Browser, BrowserType, Page, TestInfo } from './stable-test-runner';
 import { createGuid } from '../../packages/playwright-core/src/utils/crypto';
 
+// We want to have ToT playwright-core here, since we install it's browsers and otherwise don't have the right browser revision.
+const chromium: BrowserType = require('../../packages/playwright-core').chromium;
```
Comment (dgozman) [inline tests/playwright-test/ui-mode-fixtures.ts:28]: I'd inline this comment and require to the line 111. I also wonder how do other `ttest` tests that use `page` work? Is there something special in this case?

File: tests/playwright-test/ui-mode-test-setup.spec.ts [hunk 2]
```diff
@@ -193,3 +193,37 @@ test('should run part of the setup only', async ({ runUITest }) => {
...
+        'playwright.config.ts': `
+          import { defineConfig } from '@playwright/test';
+          export default defineConfig({
+            globalTeardown: './globalTeardown.ts',
+          });
+        `,
+        'globalTeardown.ts': `
+          export default async () => {
+            console.log('\\n%%from-global-teardown0000')
+            await new Promise(f => setTimeout(f, 1000));
```
Comment (dgozman) [inline tests/playwright-test/ui-mode-test-setup.spec.ts:211]: To avoid flakiness, I'd bump to 3000.

**Review by dgozman — APPROVED** [review]

File: tests/playwright-test/ui-mode-fixtures.ts (hunk 1 above)
Comment (mxschmitt) [reply tests/playwright-test/ui-mode-fixtures.ts:28]: its the only place where we launch a browser inside playwright-test, all the other launches are inside runInlineTest which use ToT test-runner.
