### PR TITLE
fix(tsconfig): when extending, retain pathsBasePath from the original config

### LINKED ISSUE #29816: [Bug]: compilerOptions.paths does not work when using extends in tsconfig.json
### Version

1.42.1

### Steps to reproduce

1. `git clone git@github.com:alSergey/pw-reproduction.git`
2. `cd 3.10.3`
3. `npm ci`
4. `npx playwright test`

### Expected behavior

All tests passed successfully

### Actual behavior

```
Error: Cannot find module '~/playwright/const'
Require stack:
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/playwright/example.spec.ts
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/playwright/lib/transform/transform.js
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/playwright/lib/common/config.js
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/playwright/lib/reporters/html.js
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/playwright/lib/runner/reporters.js
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/playwright/lib/runner/runner.js
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/playwright/lib/program.js
- /Users/seralekhin/Desktop/pw-reproduction/3.10.3/node_modules/@playwright/test/cli.js

   at example.spec.ts:2

  1 | import { test, expect } from '@playwright/test';
> 2 | import { PW_URL } from '~/playwright/const';
    | ^
  3 |
  4 | test('has title', async ({ page }) => {
  5 |   await page.goto(PW_URL);

    at Object.<anonymous> (/Users/seralekhin/Desktop/pw-reproduction/3.10.3/playwright/example.spec.ts:2:1)
```

### Additional context

It seems to me that the problem is that you are not taking into account the tsconfig location and the baseUrl field. Here is a similar example, where tsconfig is generated differently and everything works.

1. `git clone git@github.com:alSergey/pw-reproduction.git`
2. `cd 3.5.3`
3. `npm ci`
4. `npx playwright test`

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 202.52 MB / 16.00 GB
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  IDEs:
    VSCode: 1.87.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

### PR DESCRIPTION
**Pull request by dgozman**
This fixes a case where we incorrectly used the final config's base path when resolving relative path mappings in the absence of the baseUrl.

Fixes #29816.

### CODE REVIEW

File: packages/playwright/src/transform/transform.ts [hunk 1]
```diff
@@ -58,16 +58,15 @@ export function transformConfig(): TransformConfig {
 }
 
 function validateTsConfig(tsconfig: LoadedTsConfig): ParsedTsConfigData {
-  // Make 'baseUrl' absolute, because it is relative to the tsconfig.json, not to cwd.
   // When no explicit baseUrl is set, resolve paths relative to the tsconfig file.
   // See https://www.typescriptlang.org/tsconfig#paths
-  const absoluteBaseUrl = path.resolve(path.dirname(tsconfig.tsConfigPath), tsconfig.baseUrl ?? '.');
+  const pathsBase = tsconfig.absoluteBaseUrl ?? tsconfig.paths?.pathsBasePath ?? path.dirname(tsconfig.tsConfigPath);
```
Comment (pavelfeldman) [inline packages/playwright/src/transform/transform.ts:63]:
```suggestion
  const pathsBase = tsconfig.absoluteBaseUrl || tsconfig.paths?.pathsBasePath;
```
