### PR TITLE
fix(chromium): emulate navigator.userAgentData along with UA

### LINKED ISSUE #28989: [BUG]The mobile mode setting in Playwright is not taking effect.
### System info
- Playwright Version: [v1.40]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
After switching from Selenium to Playwright, I encountered a scenario where Playwright couldn't handle it. The product includes a canvas drawing board that can only be used for drawing on mobile devices. In Playwright, I switched the browser to mobile mode, but it only changed the page size. However, when I inspected window.navigator, I noticed that userAgentData.mobile remained false. This prevented me from performing operations on the canvas drawing board. In contrast, when I used Selenium and set mobileEmulation, window.navigator.userAgentData.mobile was true, allowing me to interact with the canvas drawing board as expected. I would like to know if this limitation is specific to Playwright's lack of support for this mobile device scenario or if there are other settings that need to be configured.
### Source code
    with sync_playwright() as playwright:
        iphone = playwright.devices["iPhone 12 Pro"]
        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context(**iphone)
        page=context.new_page()
        page.goto("https://twitter.com/playwrightweb")

**Steps**
- [Running the test]
- [Browser appears for one second]
- [Open the developer mode by pressing F12 and check the navigator.userAgentData.mobile property in the console.]

**Expected**
When setting the device to mobile mode, not only the browser window size changes, but also the desired outcome is for the actual userAgentData.mobile property to be changed to true.

**Actual**
Even though you have set the device in Playwright, it seems that only the browser window size is changing to match the mobile mode, while the browser's mobile property (userAgentData.mobile) remains false.

image

### LINKED ISSUE #29139: [BUG] `sec-ch-ua` still not included when headless
### System info

- Playwright Version: 1.41.0
- Operating System: macOS 13.5.2
- Browser: Chromium 121.0.6167.57
- Other info: Python 3.11.7

### Source code

```python
from contextlib import closing

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # 1. Headless
    with closing(p.chromium.launch()) as browser, closing(
        browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
                " (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
            ),
            record_har_path="headless.har",
        )
    ) as context:
        response_headless = context.new_page().goto(url="https://www.malacards.org/")
    # 2. Headed
    with closing(p.chromium.launch(headless=False)) as browser, closing(
        browser.new_context(record_har_path="headed.har")
    ) as context:
        response_headed = context.new_page().goto(url="https://www.malacards.org/")
```

**Steps**

Compare the two HAR files, and we see the headed HAR's first request has the below headers, whereas the headless HAR's first request does not:

```json
            { "name": "sec-ch-ua", "value": "\"Chromium\";v=\"121\", \"Not A(Brand\";v=\"99\"" },
            { "name": "sec-ch-ua-mobile", "value": "?0" },
            { "name": "sec-ch-ua-platform", "value": "\"macOS\"" },
```

https://github.com/microsoft/playwright/issues/6900 linked https://bugs.chromium.org/p/chromium/issues/detail?id=1212793, which was closed recently. I would like to revive this issue with the desired resolution is `sec-ch-ua` showing up in headless mode. Thank you in advance!

Relates to https://github.com/microsoft/playwright/issues/6900

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #28989, fixes #29139.

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crPage.ts [hunk 1]
```diff
@@ -1257,3 +1261,43 @@ async function emulateTimezone(session: CRSession, timezoneId: string) {
...
+    mobile: !!options.isMobile,
+    model: '',
+    architecture: 'x64',
+    platform: 'Windows',
+    platformVersion: '',
+  };
+  const androidMatch = ua.match(/Android (\d+(\.\d+)?(\.\d+)?)/);
+  const iPhoneMatch = ua.match(/iPhone OS (\d+(_\d+)?)/);
+  const iPadMatch = ua.match(/iPad; CPU OS (\d+(_\d+)?)/);
+  const macOSMatch = ua.match(/Intel Mac OS X (\d+(_\d+)?(_\d+)?)/);
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/crPage.ts:1280]: What about arm macos?

**Review by yury-s — APPROVED** [review]

**Review by mxschmitt — APPROVED** [review]
