### PR TITLE
fix(trace-viewer): Copy request body when copying network request

### LINKED ISSUE #38590: [Regression]: Request body is not correct when copying request
### Last Good Version

1.56

### First Bad Version

1.57

### Steps to reproduce

1. Open UI mode
2. Run following test
```ts
import { test, request, expect } from '@playwright/test';


test('fetch call to example site with payload', async ({}) => {
    const ctx = await request.newContext();
    const res = await ctx.post('https://httpbin.org/post', {
        data: {message: 'Hello from Playwright!', number: 123},
        headers: {'Content-Type': 'application/json'},
    });
    await expect(res).toBeOK();
    await ctx.dispose();
});
```
3. Open network tab
4. Select post request
5. Click copy request (e.g. as fetch)

### Expected behavior

Expected body:
` "body": "{\"message\":\"Hello from Playwright!\",\"number\":123}",`

### Actual behavior

Body:
` "body": "{\"error\":\"trace parameter is missing\"}",`

### Additional context

(also tested with changes from #38566, still an issue)

### Environment

```shell
System:
    OS: Linux 6.6 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
    CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
    Memory: 5.41 GB / 19.53 GB
    Container: Yes
  Binaries:
    Node: 22.15.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.2 - /usr/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
```

### PR DESCRIPTION
**Pull request by cpAdm**
Sidenote: The original code from chrome devtools has since been updated

Closes: #38590

### CODE REVIEW

File: packages/trace-viewer/src/third_party/devtools.ts [hunk 1]
```diff
@@ -57,11 +57,12 @@
  * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  */
 
+import { TraceModel } from '@isomorphic/trace/traceModel';
```
Comment (yury-s) [inline packages/trace-viewer/src/third_party/devtools.ts]:
```suggestion
import type { TraceModel } from '@isomorphic/trace/traceModel';
```

File: tests/playwright-test/ui-mode-test-network-tab.spec.ts [hunk 2]
```diff
@@ -281,3 +281,61 @@ test('should toggle sections inside network details', async ({ runUITest, server
...
+      });
+    `,
+  });
+
+  await page.getByRole('treeitem', { name: 'network tab test' }).dblclick();
+  await page.getByRole('tab', { name: 'Network' }).click();
+  await page.getByRole('listitem').filter({ hasText: 'post-data-1' }).click();
+  await page.getByRole('button', { name: 'Copy request' }).hover();
+
+  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
```
Comment (yury-s) [inline tests/playwright-test/ui-mode-test-network-tab.spec.ts:308]: We don't have clipboard isolation between the tests/system, so this might lead to flakiness. In this particular test we could override 'navigator.clipboard.writeText()' in the UI and avoid call to the actual clipboard.

**Review by yury-s — APPROVED** [review]
> Sidenote: The original code from chrome devtools has since been updated

Feel free to roll it to Playwright.
