### PR TITLE
fix(trace-viewer): don't preserve network selections across runs

### LINKED ISSUE #37223: [Bug]: Network request details stays open when test restarts
### Version

v1.55.0

### Steps to reproduce

1. Given UI mode
2. And you start a test
3. And this test has been completed
4. And you now open up a specific request in the request tab:
    Image
6. When re-starting (this) test
7. Then the details pane of the opened request is still shown

### Expected behavior

I expect the details pane to close if test restarts, as it's the shown request details do not belong to the current test run anymore.

### Actual behavior

Details pane of the opened request is still shown (note that the specific request is not selected anymore)

Image

### Additional context

_No response_

### Environment

```shell
System:
  OS: Linux 6.6 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
  CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
  Memory: 10.39 GB / 23.47 GB
  Container: Yes
Binaries:
  Node: 22.15.1 - /usr/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.9.2 - /usr/bin/npm
  pnpm: 10.15.0 - /usr/bin/pnpm
npmPackages:
  @playwright/test: ^1.55.0 => 1.55.0
```

### PR DESCRIPTION
**Pull request by agg23**
Fixes #37223 

Selection in the network tab was duplicating HAR entries, rather than referring to them by ID. This requires special state management to prevent holding onto the reference for too long. To mitigate this, craft a pseudo ID using HAR index (unique per run) and frame ID to track which HAR entry is selected.

### CODE REVIEW

File: packages/trace-viewer/src/ui/networkTab.tsx [hunk 1]
```diff
@@ -70,7 +72,7 @@ export const NetworkTab: React.FunctionComponent<{
   sdkLanguage: Language,
 }> = ({ boundaries, networkModel, onEntryHovered, sdkLanguage }) => {
   const [sorting, setSorting] = React.useState<Sorting | undefined>(undefined);
-  const [selectedEntry, setSelectedEntry] = React.useState<RenderedEntry | undefined>(undefined);
+  const [selectedEntryKey, setSelectedEntryKey] = React.useState<EntryKey | undefined>(undefined);
```
Comment (pavelfeldman) [inline packages/trace-viewer/src/ui/networkTab.tsx]: Let's make it a string to be sticky

**Review by pavelfeldman — APPROVED** [review]
