### PR TITLE
fix: quote trace file path when printing error message

### LINKED ISSUE #29039: [BUG] No quotes around show-trace path when test fails and path has spaces
### System info
- Playwright Version: [v1.41.0]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

**Steps**
- Make sure that you have a test in a folder that contains spaces
- Let the test fail

**Expected**

Being able to copy the message and paste it in a console. It should be: `npx playwright show-trace "test-results\page-01 - appointments-Create-chromium\trace.zip"`

**Actual**
 `npx playwright show-trace test-results\page-01 - appointments-Create-chromium\trace.zip`
The message doesn't have quotes around the path, causing it to give an error when you copy and paste the message

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/29039

### CODE REVIEW

**Review by mxschmitt — APPROVED** [review]

File: packages/playwright/src/reporters/base.ts [hunk 1]
```diff
@@ -331,7 +331,7 @@ export function formatFailure(config: FullConfig, test: TestCase, options: {inde
             const packageManagerCommand = getPackageManagerExecCommand();
             resultLines.push(colors.cyan(`    Usage:`));
             resultLines.push('');
-            resultLines.push(colors.cyan(`        ${packageManagerCommand} playwright show-trace ${relativePath}`));
+            resultLines.push(colors.cyan(`        ${packageManagerCommand} playwright show-trace "${relativePath}"`));
```
Comment (mxschmitt) [inline packages/playwright/src/reporters/base.ts:334]: nit: maybe print without quotes if path is in [\w\/\\]?
