### PR TITLE
fix: ubuntu version detection for linux mint

### LINKED ISSUE #28078: [BUG] Installed dependencies for Linux Mint 21.x are incorrect (Ubuntu 20 vs 22 expected)
### System info
- Playwright Version: v1.39
- Operating System: Linux Mint 21.2
- Browser: All
- Other info:

**Steps**
- Run install-deps

**Expected**

Playwright installs Ubuntu 22 deps

**Actual**

Playwright tries to install Ubuntu 20 deps, but Mint 21 is based on Ubuntu 22

Mint (distro id "linuxmint") should be added to  ``playwright-core/src/utils/hostPlatform.ts`` (like pop and neon)

/etc/os-release
```
NAME="Linux Mint"
VERSION="21.2 (Victoria)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.2"
VERSION_ID="21.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=victoria
UBUNTU_CODENAME=jammy

```

### PR DESCRIPTION
**Pull request by faulpeltz**
Add Linux Mint (Ubuntu based distro) version detection for dependency installation
Uses:
Linux Mint 21.x -> Ubuntu 22.04
Linux Mint 20.x -> Ubuntu 20.04

Fixes #28078

### CODE REVIEW

File: packages/playwright-core/src/utils/hostPlatform.ts [hunk 1]
```diff
@@ -72,6 +72,12 @@ function calculatePlatform(): { hostPlatform: HostPlatform, isOfficiallySupporte
         return { hostPlatform: ('ubuntu20.04' + archSuffix) as HostPlatform, isOfficiallySupportedPlatform };
       return { hostPlatform: ('ubuntu22.04' + archSuffix) as HostPlatform, isOfficiallySupportedPlatform };
     }
+    // Linux Mint is ubuntu-based but does not have the same versions
+    if (distroInfo?.id === 'linuxmint') {
+      if (parseInt(distroInfo.version, 10) < 21)
```
Comment (mxschmitt) [inline packages/playwright-core/src/utils/hostPlatform.ts:77]:
```suggestion
      if (parseInt(distroInfo.version, 10) <= 20)
```

**Review by mxschmitt — APPROVED** [review]
