### PR TITLE
fix(listeners): avoid "too many listeners" problem safely

### LINKED ISSUE #4224: [BUG] Don't disable nodes maxListeners warning on
Assuming #4223 lands, we currently disable the process maxListeners warning, which isn't ideal.

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/4224

### CODE REVIEW

File: src/server/processLauncher.ts [hunk 1]
```diff
@@ -58,6 +58,10 @@ export async function gracefullyCloseAll() {
   await Promise.all(Array.from(gracefullyCloseSet).map(gracefullyClose => gracefullyClose().catch(e => {})));
 }
 
+// We currently spawn a process per page when recording video in Chromium.
+//  This triggers "too many listeners" on the process object once you have more than 10 pages open.
+process.setMaxListeners(100);
```
Comment (JoelEinbinder) [inline src/server/processLauncher.ts:63]:
```suggestion
process.setMaxListeners(0);
```

**Review by JoelEinbinder — APPROVED** [review]
