### PR TITLE
fix: bail early when installing channels on non-ubuntu

### LINKED ISSUE #11615: [BUG] Unable to install chrome on Amazon Linux
**Context:**
- Playwright Version: 1.17.1
- Operating System: Amazon Linux
- Node.js version: 14.18.2
- Browser: Chrome
- Extra: AWS Amplify

**Code Snippet**
amplify.yml
```
npx playwright install chrome
npx playwright test --config=tests/playwright.config.ts
```

**Bug**
When I execute these commands on Amazon Linux, I get the following errors in the console:

```
[WARNING]: 2022-01-25 16:16:25 (253 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [90862320/90862320]
[WARNING]: + apt-get install -y ./google-chrome-stable_current_amd64.deb
[WARNING]: /codebuild/output/src200775475/src/adventure5-liveops/node_modules/playwright-core/bin/reinstall_chrome_stable_linux.sh: line 30: apt-get: command not found
[INFO]: Failed to install browsers
                                 Error: Failed to install chrome
[ERROR]: !!! Test execution failed, one or more tests are not passing
```

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #11615

### CODE REVIEW

File: packages/playwright-core/bin/reinstall_chrome_beta_linux.sh [hunk 1]
```diff
@@ -7,6 +7,17 @@ if [[ $(arch) == "aarch64" ]]; then
   exit 1
 fi
 
+if [[ ! -f "/etc/os-release" ]]; then
+  echo "ERROR: cannot install on unknown linux distribution"
```
Comment (yury-s) [inline packages/playwright-core/bin/reinstall_chrome_beta_linux.sh:11]: maybe: `ERROR: cannot install on unknown linux distribution (/etc/os-release is missing)` ?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/bin/reinstall_chrome_beta_linux.sh (hunk 1 above)
Comment (aslushnikov) [reply packages/playwright-core/bin/reinstall_chrome_beta_linux.sh]: done
