### PR TITLE
fix(cli): install chromium along with ffmpeg

### LINKED ISSUE #557: [BUG] ffmpeg missing when only installing one browser on Linux
I was only interested in chromium so I used `playwright install chromium`
This only created ~/.cache/ms-playwright/chromium-854489/

But then when I tried to get a video trace, it failed with:
```
playwright._impl._api_types.Error: Failed to launch browser: Error: spawn ~/.cache/ms-playwright/ffmpeg-1005/ffmpeg-linux ENOENT
```

`playwright install ffmpeg` does not work:
```
Invalid browser name: 'ffmpeg'. Expecting 'chromium', 'firefox' or 'webkit'.
```

Note that running `playwright install` does download ffmpeg, the issue only exists when you just want 1 browser.
```
Downloading webkit v1438 - 77.2 Mb [====================] 100% 0.0s 
webkit v1438 downloaded to ~/.cache/ms-playwright/webkit-1438
Downloading firefox v1234 - 72.2 Mb [====================] 100% 0.0s 
firefox v1234 downloaded to ~/.cache/ms-playwright/firefox-1234
Downloading ffmpeg v1005 - 2.6 Mb [====================] 100% 0.0s 
ffmpeg v1005 downloaded to ~/.cache/ms-playwright/ffmpeg-1005
```

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright-python/issues/557

### CODE REVIEW

File: src/cli/cli.ts [hunk 1]
```diff
@@ -90,6 +90,8 @@ program
           process.exit(1);
         }
       }
+      if (browserType.length && browserType.includes('chromium'))
```
Comment (dgozman) [inline src/cli/cli.ts:93]: Let's move this logic to installBrowsersWithProgressBar instead? This way we won't miss ffpmeg in some other usecase.

**Review by dgozman — APPROVED** [review]
