### PR TITLE
fix(toHaveScreenshot): nice error when rebasing with bad expectation

### LINKED ISSUE #37222: [Bug]: toHaveScreenshot fails in Github workflow
### Version

1.55.0

### Steps to reproduce

1. Send a PR to https://github.com/nikclayton/niv-screenshot-tests (e.g., https://github.com/nikclayton/niv-screenshot-tests/pull/4, which was supposed to demonstrate how Playwright could be used to catch visual regressions).
2. That will run https://github.com/nikclayton/niv-screenshot-tests/blob/main/.github/workflows/update-screenshots.yml
3. That installs Playwright, and runs "pnpm exec playwright test --update-snapshots"
4. That runs the test at https://github.com/nikclayton/niv-screenshot-tests/blob/main/tests/nivenly.spec.ts

### Expected behavior

Test completes successfully, and updates any changed screenshots.

### Actual behavior

Workflow run fails because of Playwright test failures: https://github.com/nikclayton/niv-screenshot-tests/actions/runs/17295488508/job/49092548400?pr=4

```
Screenshot attempt 1 failed:  The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
...

  1) [chromium] › tests/nivenly.spec.ts:4:5 › homepage ─────────────────────────────────────────────

    TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

      22 |     for (let attempt = 0; attempt <= maxAttempts; attempt++) {
      23 |         try {
    > 24 |             return await expect(element).toHaveScreenshot(name, options)
         |                    ^
      25 |         } catch (error) {
      26 |             lastError = error
      27 |             console.warn(
        at expectScreenshotWithRetries (/home/runner/work/niv-screenshot-tests/niv-screenshot-tests/tests/nivenly.spec.ts:24:20)
        at /home/runner/work/niv-screenshot-tests/niv-screenshot-tests/tests/nivenly.spec.ts:6:5

    Error Context: test-results/nivenly-homepage-chromium/error-context.md
```

I've attached the full log from the workflow run: [workflow.log](https://github.com/user-attachments/files/22024784/workflow.log)

### Additional context

_No response_

### Environment

```shell
Whatever the GH environment is.
```

### PR DESCRIPTION
**Pull request by dgozman**
Before, we swallowed the actual error `Could not decoded expected image as PNG` and instead tried to write `undefined` buffer to a file.

This produced a cryptic error message from Node.js with no clear signal to the user.

References #37222.

### CODE REVIEW

File: packages/playwright-core/src/server/utils/comparators.ts [hunk 1]
```diff
@@ -98,11 +98,11 @@ function validateBuffer(buffer: Buffer, mimeType: string): void {
   if (mimeType === 'image/png') {
     const pngMagicNumber = [137, 80, 78, 71, 13, 10, 26, 10];
     if (buffer.length < pngMagicNumber.length || !pngMagicNumber.every((byte, index) => buffer[index] === byte))
-      throw new Error('could not decode image as PNG.');
+      throw new Error('Could not decode expected image as PNG.');
```
Comment (yury-s) [inline packages/playwright-core/src/server/utils/comparators.ts:101]: Maybe include file name in the error?

File: packages/playwright/src/matchers/toMatchSnapshot.ts [hunk 2]
```diff
@@ -410,13 +410,18 @@ export async function toHaveScreenshot(
...
-      return writeFiles();
+      return writeFiles(actual);
     }
     return helper.handleMatching();
   }
 
-  if (helper.updateSnapshots === 'changed' || helper.updateSnapshots === 'all')
-    return writeFiles();
+  if (helper.updateSnapshots === 'changed' || helper.updateSnapshots === 'all') {
+    if (actual)
```
Comment (yury-s) [inline packages/playwright/src/matchers/toMatchSnapshot.ts:419]: Why is it undefined here even if the expectation is bad?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/server/utils/comparators.ts (hunk 1 above)
Comment (dgozman) [reply packages/playwright-core/src/server/utils/comparators.ts:101]: Unfortunately, this place does not know about the file name, and plumbing it is not worth it.
