### PR TITLE
fix: make fetch api work with connectOverCDP

### LINKED ISSUE #13520: [Question]: Error when `connect_over_cdp` using `context.request`
### Your question

Context:

- Playwright Version: 1.20.1
- Operating System: Windows11
- Python version: 3.9.12
- Browser: chrome

Error info:
```shell
Traceback (most recent call last):
  File "E:\code\python\github\get_data.py", line 18, in <module>
    run(playwright)
  File "E:\code\python\github\get_data.py", line 13, in run
    resp = req.get("https://github.com")
  File "G:\apps\miniconda\envs\v3.9\lib\site-packages\playwright\sync_api\_generated.py", line 13942, in get
    self._sync(
  File "G:\apps\miniconda\envs\v3.9\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "G:\apps\miniconda\envs\v3.9\lib\site-packages\playwright\_impl\_fetch.py", line 147, in get
    return await self.fetch(
  File "G:\apps\miniconda\envs\v3.9\lib\site-packages\playwright\_impl\_fetch.py", line 303, in fetch
    response = await self._channel.send(
  File "G:\apps\miniconda\envs\v3.9\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "G:\apps\miniconda\envs\v3.9\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: connect ENOENT per-context
=========================== logs ===========================
→ GET https://github.com/
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
  accept: */*
  accept-encoding: gzip,deflate,br
============================================================
```

```python
from playwright.sync_api import sync_playwright


def run(playwright):
    # chrome.exe --remote-debugging-port=9222 --user-data-dir=D:\Temp\chrome
    browser = playwright.chromium.connect_over_cdp("http://localhost:9222")
    page = browser.new_page()
    page.goto("https://github.com")

    context = browser.new_context()

    req = context.request
    resp = req.get("https://github.com")
    print(resp.status)


with sync_playwright() as playwright:
    run(playwright)

```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/13520

Maybe there is a better way to fix it, we set it here to make proxies work on Windows:

https://github.com/microsoft/playwright/blob/4b85f924ccbbee2fb647ab21b1af48e94eb1108a/packages/playwright-core/src/server/chromium/chromium.ts#L108-L113

### CODE REVIEW

File: packages/playwright-core/src/server/fetch.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ export abstract class APIRequestContext extends SdkObject {
     const method = params.method?.toUpperCase() || 'GET';
     const proxy = defaults.proxy;
     let agent;
-    if (proxy) {
+    if (proxy && proxy.server !== 'playwright-internal-per-context') {
```
Comment (yury-s) [inline packages/playwright-core/src/server/fetch.ts:144]: let's leave it `per-context`, that is what we recommend in our docs

**Review by yury-s — APPROVED** [review]
