### PR TITLE
fix(locator): improve error message when unchecking radio buttons

### LINKED ISSUE #37178: [Bug]:  uncheck() not working for radio buttons in Playwright
### Version

1.55.0

### Description
The `page.uncheck()` method does not seem to work with radio buttons.  
According to the docs, `uncheck()` is mainly for checkboxes, but in case of radio buttons, it throws unexpected behavior instead of failing gracefully or giving a clear message.

### Steps to Reproduce
```javascript
import { test, expect } from '@playwright/test';

test('uncheck radio button', async ({ page }) => {
  await page.setContent(`
    <form>
      <input type="radio" name="gender" value="male" checked>
      <input type="radio" name="gender" value="female">
    </form>
  `);

  const maleRadio = page.locator('input[value="male"]');
  await expect(maleRadio).toBeChecked();

  // Trying to uncheck radio
  await maleRadio.uncheck();

  // Expect it to be unchecked (but it's not working)
  await expect(maleRadio).not.toBeChecked();
});


### Expected behavior

Either:

uncheck() should unselect the radio button, OR

Playwright should throw a clear error message stating that uncheck() is not supported for radio buttons.

### Actual behavior

uncheck() runs, but the radio button remains checked.

Environment

Playwright version: [your version]

OS: [Windows / macOS / Linux]

Node.js version: [your version]

Browser: [Chromium / Firefox / WebKit]

### Additional context

Radio buttons by nature cannot be "unchecked" unless another radio in the same group is selected. Maybe Playwright can improve error messaging for this.

### Environment

```shell
Playwright version: [your version]

OS: [Windows / macOS / Linux]

Node.js version: [your version]

Browser: [Chromium / Firefox / WebKit]
```

### PR DESCRIPTION
**Pull request by dev-shahed**
fix(locator): improve error message when unchecking radio buttons

This patch improves the error message when attempting to uncheck radio buttons using uncheck(), setChecked(false), or page.uncheck(). Previously, these operations would fail with a confusing error message "Clicking the checkbox did not change its state" that didn't clearly explain why the operation failed.

Radio buttons cannot be unchecked by clicking - they can only be unchecked by selecting another radio button in the same group. The new error message clearly explains this behavior and guides users toward the correct approach.

**Before:** Error: locator.uncheck: Clicking the checkbox did not change its state

**After:** Error: locator.uncheck: Cannot uncheck radio button. Radio buttons can only be unchecked by selecting another radio button in the same group.

**Changes:**
- Added `isRadioButton()` utility method to injected script for radio button detection
- Enhanced `_setChecked()` method in ElementHandle to detect radio buttons and provide clear error messaging
- Added test case to verify the new error behavior

**Testing:**
- All existing check/uncheck tests continue to pass
- New test verifies proper error message for radio button uncheck attempts
- Checkbox functionality remains unaffected

Fixes #37178

### CODE REVIEW

File: packages/playwright-core/src/server/dom.ts [hunk 1]
```diff
@@ -732,9 +732,22 @@ export class ElementHandle<T extends Node = Node> extends js.JSHandle<T> {
         throwElementIsNotAttached();
       return result.matches;
     };
+
+    const isRadio = async () => {
+      const result = await progress.race(this.evaluateInUtility(([injected, node]) => injected.isRadioButton(node), {}));
```
Comment (dgozman) [inline packages/playwright-core/src/server/dom.ts]: Could you please merge this evaluate into `isChecked()`?

**Review by dgozman — COMMENTED** [review]
Thank you for the PR! This looks good overall, but bots are unhappy. Could you please address the linter and my comment?

File: packages/playwright-core/src/server/dom.ts (hunk 1 above)
Comment (dev-shahed) [reply packages/playwright-core/src/server/dom.ts]: @dgozman  Yes, done! I merged the radio button detection into the existing elementState('checked') call instead of making a separate evaluation. Now it returns both the checked state and radio button type in a single browser call, which is more efficient. Thanks..

**Comment by dev-shahed** [comment]
@microsoft-github-policy-service agree

**Review by dgozman — APPROVED** [review]
Looks great, merging in. Thank you for the PR!
