### PR TITLE
fix(types): add better descriptions for event emitter methods

### LINKED ISSUE #3174: [BUG] 1.2.1 Docs: Page event listeners description in documentation
Buenos dias amigos!
I noticed that PW documentation does not contain any information about `page.on(), page.off(), page.once()` event listeners. Can you please add some description? Difference between on() and once() or usage of off() can be not obvious for those who did not work with event listeners before. And hints are not so helpful (at least in VS Code):

image
image

### PR DESCRIPTION
**Pull request by JoelEinbinder**
We currently use the same description for `on`, `off`, `once`, `addListener`, and `removeListener` methods. But describing the event itself is only important for `on` and `addListener`.

Fixes #3174

### CODE REVIEW

File: utils/generate_types/index.js [hunk 1]
```diff
@@ -425,4 +434,4 @@ function renderJSSignature(args) {
   if (hasOptional)
     tokens.push(']');
   return tokens.join('');
-}
```
Comment (mxschmitt) [inline utils/generate_types/index.js:428]: nit: EOF line was removed, would be good to keep it how it was.

File: utils/generate_types/index.js [hunk 2]
```diff
@@ -211,10 +211,19 @@ function createEventDescriptions(classDesc) {
...
+    on: 'Adds an event listener.',
+    addListener: 'Adds an event listener.',
+    off: 'Removes an event listener.',
+    removeListener: 'Removes an event listener.',
+    once: 'Adds an event listener that will be automatically removed after it is triggered once.'
+  }
   for (const method of ['on', 'once', 'addListener', 'removeListener', 'off']) {
     for (const {eventName, params, comment} of eventDescriptions) {
-        if (comment)
+        if ((method === 'on' || method === 'addListener') && comment)
```
Comment (mxschmitt) [inline utils/generate_types/index.js:223]: `once` might make sense there too, or do you think its more rarely used?

**Review by mxschmitt — APPROVED** [review]

File: utils/generate_types/index.js (hunk 2 above)
Comment (JoelEinbinder) [reply utils/generate_types/index.js:223]: I think users are more like to know what the event they are listening to does than know what once does.

File: utils/generate_types/index.js [hunk 3]
```diff
@@ -211,10 +211,19 @@ function createEventDescriptions(classDesc) {
 function classBody(classDesc) {
   const parts = [];
   const eventDescriptions = createEventDescriptions(classDesc);
+  const commentForMethod = {
+    on: 'Adds an event listener.',
```
Comment (dgozman) [inline utils/generate_types/index.js:215]: on and addListener items here are unused.

File: utils/generate_types/index.js [hunk 4]
```diff
@@ -211,10 +211,19 @@ function createEventDescriptions(classDesc) {
...
+    addListener: 'Adds an event listener.',
+    off: 'Removes an event listener.',
```
Comment (dgozman) [inline utils/generate_types/index.js:217]: `Removes and event listener added by "on" or "addListener".`

File: utils/generate_types/index.js [hunk 5]
```diff
@@ -211,10 +211,19 @@ function createEventDescriptions(classDesc) {
...
+    removeListener: 'Removes an event listener.',
```
Comment (dgozman) [inline utils/generate_types/index.js:218]: Same here.

File: utils/generate_types/index.js [hunk 6]
```diff
@@ -211,10 +211,19 @@ function createEventDescriptions(classDesc) {
...
+    once: 'Adds an event listener that will be automatically removed after it is triggered once.'
```
Comment (dgozman) [inline utils/generate_types/index.js:219]: `... See "addListener" for more information about this event.`
