### PR TITLE
fix(trace-viewer): Reset selected network entry on retry

### LINKED ISSUE #37223: [Bug]: Network request details stays open when test restarts
### Version

v1.55.0

### Steps to reproduce

1. Given UI mode
2. And you start a test
3. And this test has been completed
4. And you now open up a specific request in the request tab:
    Image
6. When re-starting (this) test
7. Then the details pane of the opened request is still shown

### Expected behavior

I expect the details pane to close if test restarts, as it's the shown request details do not belong to the current test run anymore.

### Actual behavior

Details pane of the opened request is still shown (note that the specific request is not selected anymore)

Image

### Additional context

_No response_

### Environment

```shell
System:
  OS: Linux 6.6 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
  CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
  Memory: 10.39 GB / 23.47 GB
  Container: Yes
Binaries:
  Node: 22.15.1 - /usr/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.9.2 - /usr/bin/npm
  pnpm: 10.15.0 - /usr/bin/pnpm
npmPackages:
  @playwright/test: ^1.55.0 => 1.55.0
```

### PR DESCRIPTION
**Pull request by cpAdm**
A fix was tried in #37280 (after which the ticket was closed), but this commit has been reverted in #37932.

Closes: #37223

### CODE REVIEW

**Comment by cpAdm** [comment]
> ### [Test results](https://mspwblobreport.z1.web.core.windows.net/run-20759133081-2-5225b7bd763b0d57d20425d66747f198bd6cdb14/index.html) for "tests 1"
> 
> **1 failed** ❌ [playwright-test] › ui-mode-test-network-tab.spec.ts:287 › should copy network request `@macos-latest-node20`
> 3 flaky
> 
> 
> 
> **34417 passed, 696 skipped**
> 
> Merge [workflow run](https://github.com/microsoft/playwright/actions/runs/20778687997).

Seems flaky to me, only fails for macos. But not sure why `navigator.clipboard` is undefined..

File: packages/trace-viewer/src/ui/networkTab.tsx [hunk 1]
```diff
@@ -75,6 +75,11 @@ export const NetworkTab: React.FunctionComponent<{
   const [selectedEntry, setSelectedEntry] = React.useState<RenderedEntry | undefined>(undefined);
   const [filterState, setFilterState] = React.useState(defaultFilterState);
 
+  React.useEffect(() => {
```
Comment (Skn0tt) [inline packages/trace-viewer/src/ui/networkTab.tsx]: My understanding of `useEffect` isn't what it used to be, but I think that this means we'll have on render with an invalid `selectedEntry`. Could we instead do something like this?

```
if (selectedEntry not in networkModel)
  selectedEntry = undefined
```

Either like this, or wrapped in a `useMemo` to save some time on large network models.

File: tests/playwright-test/ui-mode-test-network-tab.spec.ts [hunk 2]
```diff
@@ -348,3 +348,28 @@ test('should copy network request', async ({ runUITest, server }) => {
...
+  await page.getByRole('treeitem', { name: 'network tab test' }).dblclick();
+  await page.getByRole('tab', { name: 'Network' }).click();
+  const networkItem = page.getByRole('listitem').filter({ hasText: 'network.html' });
+  await networkItem.click();
+  const headersPanel = page.getByRole('tabpanel', { name: 'Headers' });
+  await expect(headersPanel).toBeVisible();
+
+  await page.getByRole('treeitem', { name: 'network tab test' }).dblclick();
+  await networkItem.waitFor({ state: 'hidden' });
+  await networkItem.waitFor();
```
Comment (Skn0tt) [inline tests/playwright-test/ui-mode-test-network-tab.spec.ts:373]: this feels like it might flake if the render states align with the stars. do we need it in the test? otherwise let's remove it, asserting that the headersPanel gets hidden should be enough

Comment (cpAdm) [reply tests/playwright-test/ui-mode-test-network-tab.spec.ts:373]: I see you concern. But we need to somehow make sure that the 2nd test run is fully completed before checking that the headerspanel is hidden. Since the `headersPanel` will also be hidden right after the test has started ('No network calls' is shown). So when we remove the 2 `waitFor`s, the test will actually pass without the code fix.

The 'network tab test' takes about a second before the `networkItem` appears again. So I don't think this will cause any flakiness.

File: packages/trace-viewer/src/ui/networkTab.tsx (hunk 1 above)
Comment (cpAdm) [reply packages/trace-viewer/src/ui/networkTab.tsx]: You're right. This indeed triggers two renders. Changed it to use a `useMemo` instead.

Comment (cpAdm) [reply packages/trace-viewer/src/ui/networkTab.tsx]: Sidenote, it might also be interesting to see if Playwright could adopt [React Compiler](https://react.dev/learn/react-compiler) slowly, that way we don't need to manually use `useMemo` everywhere.

**Review by Skn0tt — APPROVED** [review]
