### PR TITLE
fix(test-runner): support ANSII terminals with list reporter

### LINKED ISSUE #7177: [BUG] Powershell/cmd.exe does not display the status mark (✓/x)
**Context:**
- Playwright Version: [1.12.0]
- Operating System: [Windows]
- Browser: [ Chromium]

Description:

This is a minor issue , if you run test cases using Line reporter via Command prompt or Gitbash, when test cases pass, we get a question 
Gitbash
CmdPrompt

mark symbol instead of a tick mark

### PR DESCRIPTION
**Pull request by mxschmitt**
Tested with PowerShell, the Command Prompt, the new Windows Terminal and Visual Studio Code.

Fixes #7177.

### CODE REVIEW

File: src/test/reporters/list.ts [hunk 1]
```diff
@@ -20,6 +20,11 @@ import milliseconds from 'ms';
 import { BaseReporter, formatTestTitle } from './base';
 import { FullConfig, Suite, Test, TestResult } from '../reporter';
 
+// Allow it in the Visual Studio Code Terminal and the new Windows Terminal
+const DOES_NOT_SUPPORT_UTF8_IN_TERMINAL = process.platform === 'win32' && process.env.TERM_PROGRAM !== 'vscode' && !process.env.WT_SESSION
```
Comment (dgozman) [inline src/test/reporters/list.ts:24]: Missing semicolon

**Review by dgozman — APPROVED** [review]
