### PR TITLE
fix(css parser): support nested builtin functions

### LINKED ISSUE #27743: [BUG] locator.count: Error while parsing selector ":nth-last-child(1 of ...) ~ *"
Maybe it's not the bug but not yet supported selector by Playwright so sorry in advance 🙏 
I skimmed through the Stack Overflow and a couple of articles but couldn't find a similar issue.

### System info
- Playwright Version: [v1.XX] - default in playground
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.] - MacOS 14, but ran in the playground
- Browser: [All, Chromium, Firefox, WebKit] - Chrome
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the test file**

https://try.playwright.tech/?l=javascript&s=khc2kb8

**Link to the JSFiddle with CSS selector usage**
https://jsfiddle.net/654t7skb/9/

**Steps**
- Open the JSFiddle, see that selector successfully highlights some elements
- Run the Playwright playground file, see that it throws an error after being unable to parse that selector

**Expected**

`nth-last-child( )` selector is supported

**Actual**

`nth-last-child( )` selector is NOT supported

### PR DESCRIPTION
**Pull request by dgozman**
Things like `:nth-child(1 of :has(span:nth-last-child(3)))`.

Fixes #27743.

### CODE REVIEW

File: packages/playwright-core/src/utils/isomorphic/cssParser.ts [hunk 1]
```diff
@@ -221,14 +225,22 @@ export function parseCSS(selector: string, customNames: Set<string>): { selector
 
   function consumeBuiltinFunctionArguments(): string {
     let s = '';
-    while (!isCloseParen() && !isEOF())
+    let balance = 1;  // First open paren is a part of a function token.
+    while (!isEOF()) {
+      if (isOpenParen() || (tokens[pos] instanceof css.FunctionToken))
```
Comment (yury-s) [inline packages/playwright-core/src/utils/isomorphic/cssParser.ts:230]: nit: introduce `isFunctionToken()` as there is at least one more usage of it

**Review by yury-s — APPROVED** [review]
