### PR TITLE
fix(html): don't display a chip with empty content with no projects

### LINKED ISSUE #37146: [Regression]: HTML reporter displays a broken chip link when there are no projects
### Last Good Version

1.54

### First Bad Version

1.55

### Steps to reproduce

The code is trivial. Config:
```ts 
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: 'html'
});
```
Test:
```ts
import { test } from '@playwright/test';

test('my test', () => {});
```

### Expected behavior

Playwright 1.54:

Image

### Actual behavior

Playwright 1.55:

Image

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 14.7.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 56.06 MB / 16.00 GB
  Binaries:
    Node: 20.18.3 - ~/.nvm/versions/node/v20.18.3/bin/node
    npm: 11.3.0 - ~/.nvm/versions/node/v20.18.3/bin/npm
    pnpm: 10.7.1 - ~/Library/pnpm/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.55 => 1.55.0
```

### PR DESCRIPTION
**Pull request by agg23**
#37146 

For some reason when we have no user specified projects, we insert a project with the empty string as its name. This was getting displayed following #36866.

### CODE REVIEW

File: packages/html-reporter/src/labels.tsx [hunk 1]
```diff
@@ -44,7 +44,10 @@ export const ProjectAndTagLabelsView: React.FC<{
   useLinks?: boolean,
   style?: React.CSSProperties,
 }> = ({ projectNames, activeProjectName, otherLabels, useLinks, style }) => {
-  return (projectNames.length > 0 || otherLabels.length > 0) && <span className='label-row' style={style ?? {}}>
+  // We can have an empty project name if we have no projects specified in the config
```
Comment (dgozman) [inline packages/html-reporter/src/labels.tsx:47]: We can also have multiple empty projects. Will this code work in such a case?

```
projects: [
  { name: 'chromium' },
  { /* some settings */ },
  { /* different settings */ },
  { name: 'webkit' },
]
```

Comment (agg23) [reply packages/html-reporter/src/labels.tsx:47]: Screenshot 2025-08-26 at 5 46 02 AM

It functions with any project without a name.

**Review by dgozman — APPROVED** [review]
