### PR TITLE
fix: dark-mode in UI Mode

### LINKED ISSUE #33660: [Regression]: Unable to open Playwright UI in Dark Mode.
### Last Good Version

1.48.1

### First Bad Version

1.49.0

### Steps to reproduce

Running the following command:
npx playwright test tests --ui

### Expected behavior

I want it to open in Dark mode.

### Actual behavior

In 1.48.1. - opens the UI in Dark Mode
In 1.49.0. - opens the UI in Light Mode

### Additional context

_No response_

### Environment

```shell
npx envinfo --preset playwright
Need to install the following packages:
envinfo@7.14.0
Ok to proceed? (y)


  System:
    OS: Windows 11 10.0.22631
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 7.92 GB / 31.58 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - E:\Project\Project_Tools\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
    playwright: ^1.49.0 => 1.49.0


npx envinfo --preset playwright

  System:
    OS: Windows 11 10.0.22631
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 6.39 GB / 31.58 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - E:\Project\Project_Tools\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.2
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Regressed in https://github.com/microsoft/playwright/pull/33350/files#diff-5e8771fb083ee3a9e97263f0a2c0b71134c58c29f7d208e5fd0341577e00c57dR166 instead of adjusting the call-side we should check inside the function if the passed value is truthy so it doesn't hit us in the future again.

Fixes https://github.com/microsoft/playwright/issues/33660

### CODE REVIEW

File: packages/playwright-core/src/server/launchApp.ts [hunk 1]
```diff
@@ -46,9 +46,9 @@ export async function launchApp(browserType: BrowserType, options: {
     channel: !options.persistentContextOptions?.executablePath ? findChromiumChannel(options.sdkLanguage) : undefined,
     noDefaultViewport: true,
     ignoreDefaultArgs: ['--enable-automation'],
-    colorScheme: 'no-override',
     acceptDownloads: isUnderTest() ? 'accept' : 'internal-browser-default',
     ...options?.persistentContextOptions,
+    colorScheme: options?.persistentContextOptions?.colorScheme ?? 'no-override',
```
Comment (dgozman) [inline packages/playwright-core/src/server/launchApp.ts:51]: Should we do the same for other options present here and in `persistentContextOptions`?

**Review by dgozman — APPROVED** [review]

**Review by dgozman — APPROVED** [review]

**Comment by ScarletMcLearn** [comment]
Hello. 

The issue is showing as fixed.

How do I get the changes in my local?

Please suggest.

Thank you.

**Comment by mxschmitt** [comment]
`npm install -D @playwright/test@beta` until we have the fix released as 1.49.1.

**Comment by ScarletMcLearn** [comment]
Thank you @mxschmitt.
You rock.

**Comment by ScarletMcLearn** [comment]
Hello @mxschmitt, the issue is occuring again.
Please look into it when you get a chance.
Thank you.

**Comment by mxschmitt** [comment]
Let's continue the discussion in https://github.com/microsoft/playwright/issues/33660#issuecomment-2488366083.
