### PR TITLE
fix: download of attachments in UI Mode

### LINKED ISSUE #26326: [BUG] Can't download attachments from UI mode
Related to https://github.com/microsoft/playwright/issues/22736

### System info
- Playwright Version: [v1.36.2]
- Operating System: [Windows 11, macOS 13.5]
- Browser: [Chromium]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('download file', async ({ page }, testInfo) => {
  const payload = "data:application/zip;base64,UEsDBAoAAAAAAJCNB1eCidH3BQAAAAUAAAAJAAAASGVsbG8udHh0SGVsbG9QSwECPwMKAAAAAACQjQdXgonR9wUAAAAFAAAACQAkAAAAAAAAACCApIEAAAAASGVsbG8udHh0CgAgAAAAAAABABgAm6rbDUbJ2QEAAAAAAAAAAAAAAAAAAAAAUEsFBgAAAAABAAEAWwAAACwAAAAAAA==";
  await page.setContent(`<a href="${payload}" download="myFile.zip">My Link</a>`);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('a').click();
  const download = await downloadPromise;
  const path = download.suggestedFilename();
  await download.saveAs(path);
  if (path)
    testInfo.attachments.push({ name: 'myFile.zip', path: path, contentType: 'application/zip' });
  expect(path).toBeTruthy();
});
```

**Steps**
- `npx playwright test --ui`
- Run the test
- See the attached file and try to actually view it / download it / open it

image

**Expected**

Can download the attachment and check what it contains, no matter the mode.
Also expected would be to get the right filename (the one specified in `attachments.push`) which probably means the server needs to set proper Content-Disposition headers (?).

**Actual**

- ❌ can't be downloaded from UI mode
- (✅) can be downloaded from HTML mode but thas a random filename instead of the expected name
- ❌ can't be downloaded from VS Code extension

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/26326.

### CODE REVIEW

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts [hunk 1]
```diff
@@ -146,6 +146,7 @@ export async function openTraceViewerApp(traceUrls: string[], browserName: strin
     ignoreDefaultArgs: ['--enable-automation'],
     colorScheme: 'no-override',
     useWebSocket: isUnderTest(),
+    keepDefaultDownloadBehavior: isUnderTest() ? false : true,
```
Comment (dgozman) [inline packages/playwright-core/src/server/trace/viewer/traceViewer.ts:149]: Perhaps it's time to introduce `launchApp()` internal method that would also replace `installAppIcon()` and unify the usages? Because I assume all other apps we launch would also need this download behavior.

File: packages/playwright-core/src/server/chromium/crBrowser.ts [hunk 2]
```diff
@@ -343,7 +343,7 @@ export class CRBrowserContext extends BrowserContext {
   override async _initialize() {
     assert(!Array.from(this._browser._crPages.values()).some(page => page._browserContext === this));
     const promises: Promise<any>[] = [super._initialize()];
-    if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') {
+    if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank' && !this._options.keepDefaultDownloadBehavior) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/chromium/crBrowser.ts:346]: - What about other browsers? This option should work in all of them.
- Perhaps it makes sense to replace `options.acceptDownloads` with an enum `downloads: 'accept' | 'deny' | 'internal-browser-default'`?

File: packages/trace-viewer/src/sw.ts [hunk 3]
```diff
@@ -145,6 +146,49 @@ async function doFetch(event: FetchEvent): Promise<Response> {
...
+  const nameHasExt = name.includes('.');
+  if (!nameHasExt)
+    name += extensionForContentType(attachment.contentType);
+  headers.set('Content-Disposition', `attachment; filename="${name}"`);
+  if (attachment.contentType)
+    headers.set('Content-Type', attachment.contentType);
+  return headers;
+}
+
+function extensionForContentType(contentType: string): string {
```
Comment (dgozman) [inline packages/trace-viewer/src/sw.ts:164]: Don't we have an utility like this already?

File: packages/trace-viewer/src/sw.ts [hunk 4]
```diff
@@ -122,9 +122,10 @@ async function doFetch(event: FetchEvent): Promise<Response> {
         // We will accept explicit ?trace= value as well as the clientId associated with the trace.
         if (traceUrl !== trace && !traceUrls.includes(trace))
           continue;
-        const blob = await traceModel!.resourceForSha1(relativePath.slice('/sha1/'.length));
+        const sha1 = relativePath.slice('/sha1/'.length);
```
Comment (dgozman) [inline packages/trace-viewer/src/sw.ts:125]: Let's extract this into `serveResource(traceModel, sha1)` method?

File: packages/trace-viewer/src/sw.ts [hunk 5]
```diff
@@ -145,6 +146,49 @@ async function doFetch(event: FetchEvent): Promise<Response> {
...
 
+function headersForResource(traceModel: TraceModel, sha1: string): Headers | undefined {
+  const attachment = traceModel.attachmentForSha1(sha1);
+  if (!attachment)
+    return;
+  const headers = new Headers();
+  let name = attachment.name;
+  const nameHasExt = name.includes('.');
+  if (!nameHasExt)
+    name += extensionForContentType(attachment.contentType);
```
Comment (dgozman) [inline packages/trace-viewer/src/sw.ts:157]: Was this explicitly requested? I'd leave `attachment.name` without adding anything.

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts (hunk 1 above)
Comment (mxschmitt) [reply packages/playwright-core/src/server/trace/viewer/traceViewer.ts]: https://github.com/microsoft/playwright/pull/26499

File: packages/trace-viewer/src/sw.ts (hunk 3 above)
Comment (mxschmitt) [reply packages/trace-viewer/src/sw.ts:168]: did not find any.

Comment (yury-s) [reply packages/trace-viewer/src/sw.ts:168]: mime.getExtension() should do what you need

File: packages/trace-viewer/src/sw.ts (hunk 5 above)
Comment (yury-s) [reply packages/trace-viewer/src/sw.ts:161]: @mxschmitt add a comment explaining why we add it here?

**Review by yury-s — APPROVED** [review]

**Comment by mxschmitt** [comment]
Note: I left the content-type to file extension out for now, since its rare that customers look at the screenshot/video attachments inside UI Mode (these are just named: `screenshot` and `video`). Trace won't be present there, since we use it internally for UI Mode.
