### PR TITLE
fix(esm): dont bail for preflight requests

### LINKED ISSUE #39172: [Bug]: Playwright 1.58.0 collects *.esm.preflight files as tests, causing duplicate test title errors
### Version

1.58.0

### Steps to reproduce

**Minimal Reproduction Repository:** https://github.com/Abhinegi2/playwright-issue

Clone the repository and run:
```bash
git clone https://github.com/Abhinegi2/playwright-issue.git
cd playwright-issue
npm install
npx playwright install chromium
npx playwright test
```
Or reproduce from scratch:

1. Create a TypeScript ESM project with "type": "module" in package.json.
2. Install @playwright/test@1.58.0 and tsx@4.21.0
3. import tsx/esm in [playwright.config.ts]
``` 
import { defineConfig } from "@playwright/test";
import "tsx/esm";
export default defineConfig({
testDir: "./tests",
build: { external: ["*"] },
}); 
```
4. Create any test file (e.g., tests/example.spec.ts)
5. Run npx playwright test

### Expected behavior

Playwright should only collect and execute tests from `*.spec.ts` files (or other configured test file patterns). No `*.esm.preflight` files should be involved in test collection.

### Actual behavior

Playwright reports duplicate test title errors, referencing non-existent `*.esm.preflight` files:
Error: duplicate test title "example test", first declared in example.spec.ts.esm.preflight:3
at example.spec.ts:1
```
1 | import { test, expect } from "@playwright/test";
| ^
2 |
3 | test("example test", async ({ page }) => {
4 | await page.goto("[https://example.com](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)");
```

These `.esm.preflight` files don't exist in the repository but appear to be created by the `tsx/esm` loader and are being incorrectly collected as test files by Playwright.

### Additional context

- **Regression**: This works correctly in Playwright 1.57.0
- **Workaround**: Downgrade to `@playwright/test@1.57.0`
- **Real-world impact**: This is blocking upgrades in production projects, such as [Aam-Digital/ndb-core](https://github.com/Aam-Digital/ndb-core)
- **Related issue**: #39028 (closed, requesting proper repro - this is the proper reproduction)

The `.esm.preflight` files appear to be generated by tsx's ESM loader transformation but should be excluded from Playwright's test file collection pattern.

### Environment

```shell
System:
    OS: macOS 26.2
    CPU: (8) arm64 Apple M3
    Memory: 92.39 MB / 8.00 GB
Binaries:
    Node: 22.19.0
    npm: 11.6.4
IDEs:
    VSCode: 1.108.2
Languages:
    Bash: 3.2.57
npmPackages:
    @playwright/test: 1.58.0
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/39172.

Interestingly, the test without the fix immediately leads to the `Error: duplicate test title "another test", first declared in example.spec.ts.esm.preflight:13` bug, so we have a good repro even without tsx. It seems to affect any loader.

### CODE REVIEW

File: packages/playwright/src/transform/esmLoader.ts [hunk 1]
```diff
@@ -62,19 +62,23 @@ const kSupportedFormats = new Map([
...
+    if (!kSupportedFormats.has(context.format))
+      return defaultLoad(moduleUrl, context, defaultLoad);
+
+    // Bail for node_modules.
+    if (!shouldTransform(filename))
+      return defaultLoad(moduleUrl, context, defaultLoad);
+  }
 
   const code = fs.readFileSync(filename, 'utf-8');
   const transformed = transformHook(code, filename, moduleUrl);
```
Comment (dgozman) [inline packages/playwright/src/transform/esmLoader.ts]: I'd skip this for preflights that we want to bail on, e.g. from node_modules. Since we are not supposed to transform them, we don't need to prepopulate source mapes.

I'd make a custom `defaultLoad` function that would return `void 0` for preflights or call the actual `defaultLoad` for non-preflights.

Comment (Skn0tt) [reply packages/playwright/src/transform/esmLoader.ts]: I didn't like the custom defaultLoad function, but I found a different way of writing it that skips the fs ops and transform for preflights, and looks pretty readable.

File: packages/playwright/src/transform/esmLoader.ts [hunk 2]
```diff
@@ -71,7 +70,13 @@ async function load(originalModuleUrl: string, context: { format?: string }, def
   if (!moduleUrl.startsWith('file://'))
     return defaultLoad(moduleUrl, context, defaultLoad);
 
+  const isPreflight = moduleUrl.endsWith(esmPreflightExtension);
+  moduleUrl = moduleUrl.replace(esmPreflightExtension, '');
   const filename = url.fileURLToPath(moduleUrl);
+  const format = kSupportedFormats.get(context.format) || (fileIsModule(filename) ? 'module' : 'commonjs');
+  if (isPreflight)
```
Comment (dgozman) [inline packages/playwright/src/transform/esmLoader.ts]: This always skips `transformHook` which is the sole purpose of having a preflight.

File: packages/playwright/src/transform/esmLoader.ts [hunk 3]
```diff
@@ -62,34 +62,39 @@ const kSupportedFormats = new Map([
 // Node < 18.6: defaultLoad takes 3 arguments.
 // Node >= 18.6: nextLoad from the chain takes 2 arguments.
 async function load(originalModuleUrl: string, context: { format?: string }, defaultLoad: Function) {
+  const isPreflight = originalModuleUrl.endsWith(esmPreflightExtension);
```
Comment (pavelfeldman) [inline packages/playwright/src/transform/esmLoader.ts]: Let me offer an alternative as I think this change is somewhat missing the point. The like 65 in the old code is offender, it needs to go.

Comment (pavelfeldman) [reply packages/playwright/src/transform/esmLoader.ts]: https://github.com/microsoft/playwright/pull/39338/changes

Comment (Skn0tt) [reply packages/playwright/src/transform/esmLoader.ts]: That patch let's through `.esm.preflight` loads to the next loader, which will fail because it can't find the file. It doesn't pass my reproduction test, and doesn't fix the issue.

Comment (pavelfeldman) [reply packages/playwright/src/transform/esmLoader.ts]: As discussed offline, I don't think we have a choice - 'bad' loader can be before us up in the chain.

Comment (Skn0tt) [reply packages/playwright/src/transform/esmLoader.ts]: i updated the PR to be based on your patch, and i've added the catch for the bad loader and two more tests, take a look.

File: packages/playwright/src/transform/esmLoader.ts [hunk 4]
```diff
@@ -72,12 +71,20 @@ async function load(originalModuleUrl: string, context: { format?: string }, def
     return defaultLoad(moduleUrl, context, defaultLoad);
 
   const filename = url.fileURLToPath(moduleUrl);
+  const isPreflight = moduleUrl.endsWith(esmPreflightExtension);
+
   // Bail for node_modules.
-  if (!shouldTransform(filename))
+  if (!shouldTransform(filename)) {
+    if (isPreflight)
```
Comment (pavelfeldman) [inline packages/playwright/src/transform/esmLoader.ts]: This violates the 'assume any order' consideration.

**Review by pavelfeldman — APPROVED** [review]

**Comment by Skn0tt** [comment]
I verified that it still fixes https://github.com/microsoft/playwright/issues/39172 - the `catch` makes it work.
