### PR TITLE
fix(aria): escape leading dash in property values

### LINKED ISSUE #33874: [Bug]: ariaSnapshot generates invalid yaml when text node has content "-"
### Version

1.49.0

### Steps to reproduce

Having an HTML region of this form

```html
<section aria-labelledby="heading-id">
  <h3 id="heading-id">Title</h3>
  -
</section>
```

generates an invalid yaml output:

```yaml
- region "Title":
  - heading "Title" [level=3]
  - text: -
```

From `js-yaml` with `yaml.load(await locator.ariaSnapshot())`:

```
YAMLException: bad indentation of a mapping entry (10:15)

  8 |     - region "Title":
  9 |       - heading "Title" [level=3]
 10 |       - text: -
--------------------^
```

### Expected behavior

The YAML should be valid.

### Actual behavior

Invalid characters in YAML, due to missing escaping.

### Additional context

_No response_

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 2.96 GB / 7.76 GB
    Container: Yes
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.12.1 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @playwright/test: 1.49.0 => 1.49.0
    js-yaml: 4.1.0 => 4.1.0
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/33874

### CODE REVIEW

File: packages/playwright-core/src/server/injected/yaml.ts [hunk 1]
```diff
@@ -59,7 +59,7 @@ function yamlStringNeedsQuotes(str: string): boolean {
     return true;
 
   // Strings starting with '-' followed by a space need quotes
```
Comment (yury-s) [inline packages/playwright-core/src/server/injected/yaml.ts:61]:
```suggestion
  // Strings starting with '-' need quotes
```

**Review by yury-s — APPROVED** [review]
