### PR TITLE
fix(core): prevent concurrent downloads clobbering by using unique temp dirs

### LINKED ISSUE #32179: [Bug]: Jobs running concurrently on the same machine download browsers to the same directory and clobber each other (Windows)
### Version

1.44

### Steps to reproduce

I'm using Azure DevOps Server with self-hosted agents (Windows). I am running many pipelines throughout the night and part of that is running Playwright tests (.NET and MSTest).

Each agent installs the browsers to an agent-specific directory using the `PLAYWRIGHT_BROWSERS_PATH` environment variable. This way each agent has its own copy of the browsers and everything is nicely isolated.

The issue is that while the browsers are eventually installed to `PLAYWRIGHT_BROWSERS_PATH`, they are downloaded to `C:\Users\username\AppData\Local\Temp`. While I have multiple agents, several of them are running on the same machine as the same user. This means that if agent 1 and agent 2 are running at roughly the same time, they will both try to download the browsers to the same location and will end up clobbering each other.

### Expected behavior

The `PLAYWRIGHT_BROWSERS_PATH` keeps the browsers completely isolated, including the download.

### Actual behavior

The agent will begin to download the browsers but it won't be long before you see this error.
```
[Error: ENOENT: no such file or directory, open 'C:\Users\[REDACTED]\AppData\Local\Temp\playwright-download-firefox-win64-1449.zip'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\[REDACTED]\\AppData\\Local\\Temp\\playwright-download-firefox-win64-1449.zip'
}
```

### Additional context

_No response_

### Environment

```Text
- Operating System: Windows Server 2022 21H2 (OS Build 20348.2655)
- Browser: All
- .NET Version (TFM): net8.0
- Other info: Azure DevOps Server 2022
```

### PR DESCRIPTION
**Pull request by emyjamalian**
- This change ensures concurrent 'npx playwright install' processes do not clobber each other by downloading to a unique temporary directory before finalizing.
- Adds unique temp dir per download in packages/playwright-core/src/server/registry/browserFetcher.ts.
- Adds installation test tests/installation/concurrent-download.spec.ts validating concurrent installs.
- Test assertions avoid depending on stdout formatting.
- Fixes https://github.com/microsoft/playwright/issues/32179

### CODE REVIEW

**Comment by emyjamalian** [comment]
@microsoft-github-policy-service agree

**Comment by emyjamalian** [comment]
> @emyjamalian please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

File: packages/playwright-core/src/server/registry/browserFetcher.ts [hunk 1]
```diff
@@ -133,7 +143,7 @@ function getDownloadProgress(): OnProgressCallback {
 }
 
 function getAnimatedDownloadProgress(): OnProgressCallback {
-  let progressBar: ProgressBar;
+  let progressBar: any;
```
Comment (yury-s) [inline packages/playwright-core/src/server/registry/browserFetcher.ts]: Revert this change.

File: packages/playwright-core/src/server/registry/browserFetcher.ts [hunk 2]
```diff
@@ -63,8 +66,15 @@ export async function downloadBrowserWithProgressBar(title: string, browserDirec
     process.exitCode = 1;
     throw e;
   } finally {
-    if (await existsAsync(zipPath))
-      await fs.promises.unlink(zipPath);
+    // Clean up the temporary directory and its contents
+    if (await existsAsync(uniqueTempDir)) {
+      try {
+        await fs.promises.rm(uniqueTempDir, { recursive: true, force: true });
```
Comment (yury-s) [inline packages/playwright-core/src/server/registry/browserFetcher.ts]: Call `removeFolders()` from `packages/playwright-core/src/server/utils/fileUtils.ts` instead.

File: tests/installation/concurrent-download.spec.ts [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+test('concurrent browser downloads should not clobber each other', async ({ exec, checkInstalledSoftwareOnDisk, _browsersPath, tmpWorkspace }) => {
+  // Set up a workspace with playwright installed
+  await exec('npm init -y');
+  await exec('npm install playwright');
+  // Start multiple concurrent install processes
+  const processes = [];
+  const numProcesses = 3;
+
+  for (let i = 0; i < numProcesses; i++) {
+    const child = spawn('npx', ['playwright', 'install', 'chromium'], {
```
Comment (yury-s) [inline tests/installation/concurrent-download.spec.ts]: Use `exec` fixture instead, it already collects the output.

**Review by yury-s — CHANGES_REQUESTED** [review]

File: tests/installation/concurrent-download.spec.ts (hunk 3 above)
Comment (emyjamalian) [reply tests/installation/concurrent-download.spec.ts]: @yury-s Thanks for your review.
resolved your comments in [5b0e045](https://github.com/microsoft/playwright/pull/37335/commits/5b0e045f7bcf2c3b6e94b96dbfde10c4097d7683)

File: tests/installation/concurrent-download.spec.ts [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+ */
+
+import { test } from './npmTest';
+test.use({ isolateBrowsers: true });
+
+test('concurrent browser downloads should not clobber each other', async ({ exec, checkInstalledSoftwareOnDisk }) => {
+  await exec('npm init -y');
+  await exec('npm install playwright');
+  const numProcesses = 3;
+  await Promise.all(Array.from({ length: numProcesses }, () => exec('npx playwright install chromium')));
```
Comment (yury-s) [inline tests/installation/concurrent-download.spec.ts]: All 3 commands will try to install browsers into the same directory, which may lead to the test flakiness. Please make sure the the commands run with different `PLAYWRIGHT_BROWSERS_PATH` values, something like:

```js
    await Promise.all(Array.from({ length: numProcesses }, (_, index) =>
      exec('npx playwright install chromium', {
        env: {
          PLAYWRIGHT_BROWSERS_PATH: test.info().outputPath(`browsers-${index}`),
        }
      })
    ));
```

**Review by yury-s — COMMENTED** [review]
The new test is failing on Windows.

File: tests/installation/concurrent-download.spec.ts [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+  await exec('npm install playwright');
+  const numProcesses = 3;
+  await Promise.all(Array.from({ length: numProcesses }, (_, index) =>
+    exec('npx playwright install chromium', {
+      env: {
+        PLAYWRIGHT_BROWSERS_PATH: testInfo.outputPath(`browsers-${index}`),
+      }
+    })
+  ));
+  // Aggregate installed software across individual browser paths and verify expected components exist
```
Comment (yury-s) [inline tests/installation/concurrent-download.spec.ts]: Why aggregate if you can simply check it in each directory? Just move the `installed` set and all 3 checks inside the loop - each installation should have all 3 binaries present.

**Review by yury-s — APPROVED** [review]

**Review by yury-s — APPROVED** [review]
