### PR TITLE
fix(chromium): fix crash if connecting to a browser with a serviceworker

### LINKED ISSUE #5648: [BUG] Error: Duplicate target when trying to connectOverCDP next time
Great work on `connectOverCDP` 👍 I am loving the ability to connect to an existing instance rather than launch a new chrome every time.

**Context:**
- Playwright Version: 1.9.1
- Operating System: Mac
- Node.js version: 12.x
- Browser: Chromium

**Code Snippet**

```javascript

const { chromium } = require("playwright");

(async () => {
	const browser = await chromium.connectOverCDP({
                // NOTE: change this with ws URL by launching chrome with CDP
		wsEndpoint: `ws://127.0.0.1: 56685/devtools/browser/a5d5af82-e168-4ebb-8b87-199c3e5dc260`,
	});
	const contexts = browser.contexts();
	const browserContext = contexts[0];
	const page = await browserContext.newPage();
	await page.goto("https://playwright.dev");
})();
```

**Describe the bug**
Error log:

```
[1] app: 2021-02-28T03:57:53.593Z app:debug 1614484673593 -> Chrome Endpoint: ws://127.0.0.1:56685/devtools/browser/a5d5af82-e168-4ebb-8b87-199c3e5dc260
[1] app: 2021-02-28T03:57:53.643Z app:warn 1614484673641 -> Error: Duplicate target 3E6BA14AC5D3C8825FC23623D1B55050
[1] app:     at Object.assert (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/utils/utils.js:80:15)
[1] app:     at CRBrowser._onAttachedToTarget (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crBrowser.js:152:17)
[1] app:     at CRSession.emit (events.js:315:20)
[1] app:     at CRSession.EventEmitter.emit (domain.js:483:12)
[1] app:     at /Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crConnection.js:157:22
[1] app:     at runNextTicks (internal/process/task_queues.js:62:5)
[1] app:     at processImmediate (internal/timers.js:429:9) Promise { <rejected> Error: Duplicate target 3E6BA14AC5D3C8825FC23623D1B55050 at Object.assert (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/utils/utils.js:80:15) at CRBrowser._onAttachedToTarget (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crBrowser.js:152:17) at CRSession.emit (events.js:315:20) at CRSession.EventEmitter.emit (domain.js:483:12) at /Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crConnection.js:157:22 at runNextTicks (internal/process/task_queues.js:62:5) at processImmediate (internal/timers.js:429:9) }
```

First time connection works properly but next time I try to connect to same WS URL, I see this error.

### PR DESCRIPTION
**Pull request by JoelEinbinder**
`Target.setAutoAttach` appears to connect to service workers again, which causes us to crash with duplicate target errors. Also service workers that were created before connecting to the browser were incorrectly dispatched to the client layer.

Fixes #5648

### CODE REVIEW

File: src/server/chromium/crBrowser.ts [hunk 1]
```diff
@@ -60,10 +60,11 @@ export class CRBrowser extends Browser {
     browser._defaultContext = new CRBrowserContext(browser, undefined, options.persistent);
 
     const existingTargetAttachPromises: Promise<any>[] = [];
-    // First page, background pages and their service workers in the persistent context
+    // First page and background pages in the persistent context
     // are created automatically and may be initialized before we enable auto-attach.
+    // Their service workers are also automatically created, but setAutoAttach attaches to them.
```
Comment (yury-s) [inline src/server/chromium/crBrowser.ts:65]: huh

**Review by yury-s — APPROVED** [review]

**Comment by JoelEinbinder** [comment]
@dgozman you suggested just deleting all the Target.setDiscoverTargets code. It appears to work! ptal

File: src/server/chromium/crBrowser.ts [hunk 2]
```diff
@@ -50,6 +50,9 @@ export class CRBrowser extends Browser {
     const browser = new CRBrowser(connection, options);
     browser._devtools = devtools;
     const session = connection.rootSession;
+    if ((options as any).__testHookOnConnectToBrowser)
```
Comment (dgozman) [inline src/server/chromium/crBrowser.ts:53]: Doesn't existing `__testHookBeforeCreateBrowser` work?

**Review by dgozman — APPROVED** [review]

File: src/server/chromium/crBrowser.ts [hunk 3]
```diff
@@ -59,32 +62,11 @@ export class CRBrowser extends Browser {
     }
     browser._defaultContext = new CRBrowserContext(browser, undefined, options.persistent);
 
-    const existingTargetAttachPromises: Promise<any>[] = [];
-    // First page, background pages and their service workers in the persistent context
-    // are created automatically and may be initialized before we enable auto-attach.
```
Comment (yury-s) [inline src/server/chromium/crBrowser.ts:64]: How can we be sure that scenario mentioned in the comment is still handled correctly?

Comment (JoelEinbinder) [reply src/server/chromium/crBrowser.ts:64]: There are new tests for what's described in this comment.

File: src/server/chromium/crBrowser.ts (hunk 2 above)
Comment (JoelEinbinder) [reply src/server/chromium/crBrowser.ts:53]: I wanted to wait after the websocket connection is established. What if the DevTools initialization does something async before reporting the first target?

Comment (dgozman) [reply src/server/chromium/crBrowser.ts:53]: Sure.
