### PR TITLE
chrome: cache tsconfig for folder

### LINKED ISSUE #32459: [Bug]: Memory Consumption Issue with Playwright 1.44.1- Assistance Required
### Version

1.44.1

### Steps to reproduce

We have created a minimal repository to demonstrate the issue, with the following branches:

```memory-uses-for-playwright-1.41``` (Playwright 1.41)

```memory-uses-for-playwright-1.42``` (Playwright 1.42)

**Repository Link:** [GitHub - Pooj123-A/playwright-memory-issue](https://github.com/Pooj123-A/playwright-memory-issue/tree/main)

**Reproduction Steps:**

1. Clone the repository.

2. Install dependencies: ```npm install```.

3. Run tests: ```npm run profile-test src/test.spec.tsx (for profiling)``` or  ```npm run test src/test.spec.tsx(for normal execution).```

### Analysis Instructions:

The npm run profile-test script is designed for profiling with pprof. After running the tests, you can visualize memory profiles using pprof:

### Install Go and pprof if not already installed:

```brew install go```
 
### Use pprof to start a local web server for profile visualization:

```go tool pprof -http=:8080 pprof-heap-<timestamp>.pb.gz```
 ***By comparing the profiles for Playwright 1.41.1 and 1.42+, you will observe differences in memory usage that underscore the impact of the changes introduced in the newer version.***
### version 1.41.1:
[pprof-heap-27164.pb.gz](https://github.com/user-attachments/files/16884093/pprof-heap-27164.pb.gz)

image

### Version 1.42.0: 
[pprof-heap-21911.pb.gz](https://github.com/user-attachments/files/16884096/pprof-heap-21911.pb.gz)

image

### Expected behavior

**Error:** JavaScript heap out-of-memory error
- **Memory Usage**: When running a large number of tests (~1000) with Playwright 1.41.1, memory consumption remains stable and within the allocated limits (e.g., 8 GB). The tests complete successfully without encountering out-of-memory errors.
- **Performance**: Playwright should handle large test suites efficiently, with memory usage being proportional to the number of tests executed.
- **Stability**: Playwright should not exhibit significant changes in memory consumption or performance issues after minor version upgrades.

### Actual behavior

1. **Memory Consumption:** After upgrading to Playwright 1.44.1, there is a substantial increase in memory consumption when running a large number of tests, leading to JavaScript heap out-of-memory (OOM) errors. Memory usage significantly exceeds what was observed in Playwright 1.41.1.

2. **Performance:** Due to increased memory consumption, Playwright fails to complete test executions within the available memory limits, resulting in test failures and performance degradation.

### Overview

After upgrading Playwright from version 1.41.1 to 1.44.1 within our large monorepo, we have encountered a substantial increase in memory consumption. This issue has manifested during our test runs.

### Problem Details

When running approximately 1000 tests in a single shard with 8 GB of memory, Playwright fails with a JavaScript heap out-of-memory (OOM) error.

### Error Message

We are receiving the following error message:

Screenshot 2024-09-03 at 10 37 58

**pprof-profiling with playwright 1.41**

   
[pprof-heap-40490.pb.gz](https://github.com/user-attachments/files/16883832/pprof-heap-40490.pb.gz)

**pprof-profiling with playwright 1.42** 

[pprof-heap-17561.pb.gz](https://github.com/user-attachments/files/16883836/pprof-heap-17561.pb.gz)

#### Problem: 
After upgrading to Playwright 1.44.1, we observed a significant increase in memory usage and experienced heap out-of-memory issues during large-scale test executions.

#### Root Cause Identification: 
Through memory profiling we isolated the issue to ```loadTsConfig``` located in ```playwright/lib/third_party/tsconfig-loader.js```
Increase in memory consumption appears to be associated with changes introduced in **Playwright 1.42**. Updated code significantly altered how configurations are loaded and managed, including handling arrays of configurations and recursively loading references.

These changes have led to a noticeable increase in memory consumption, which is impacting performance.
### Relevant PR:
For more details, you can refer to the changes introduced in this **PR:** [feat(tsconfig): respect tsconfig references by pavelfeldman · Pull Request #29330 · microsoft/playwright](https://github.com/microsoft/playwright/pull/29330/files)
This PR outlines the modifications that are contributing to the memory increase issue.

### Profiling with pprof: 
We utilized pprof to profile memory usage and identify hotspots.
Through profiling we identified that  loadAndValidateTsconfigsForFile() method as a major contributor to high memory usage.  

### Comparison with Previous Version: 
We compared memory usage between Playwright 1.41.1 and 1.42+ by profiling both versions. This comparison highlighted noticeable increase in memory consumption.

### Patch Implementation: 
To validate our findings, we applied a temporary workaround by reverting to the logic used in Playwright 1.41.1. This adjustment successfully mitigated the memory issues and allowed our tests to pass.
 You can refer to the changes in the patch file: 
[playwright+1.44.1.patch](https://github.com/user-attachments/files/16883941/playwright%2B1.44.1.patch)

### Request for Assistance:

We seek your guidance or a potential fix to address the increased memory consumption observed with Playwright 1.42. Your review of the provided repository and profiling data should help in understanding and resolving the issue.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 117.05 MB / 32.00 GB
  Binaries:
    Node: 18.20.1 - ~/.nvm/versions/node/v18.20.1/bin/node
    Yarn: 3.6.1-git.20240213.hash-589266c04 - ~/.local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/experimental-ct-core: 1.44.1 => 1.44.1 
    @playwright/experimental-ct-react: 1.44.1 => 1.44.1 
    @playwright/experimental-ct-react17: 1.44.1 => 1.44.1 
    @playwright/test: 1.44.1 => 1.44.1 
    playwright: 1.44.1 => 1.44.1 
    playwright-core: 1.44.1 => 1.44.1
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/32459

### CODE REVIEW

File: packages/playwright/src/transform/transform.ts [hunk 1]
```diff
@@ -81,12 +83,44 @@ function validateTsConfig(tsconfig: LoadedTsConfig): ParsedTsConfigData {
...
+  if (_singleTSConfigPath && !_singleTSConfig)
+    _singleTSConfig = loadTsConfig(_singleTSConfigPath).map(validateTsConfig);
+  if (_singleTSConfig)
+    return _singleTSConfig;
+  return loadAndValidateTsconfigsForFolder(path.dirname(file));
+}
+
+function loadAndValidateTsconfigsForFolder(folder: string): ParsedTsConfigData[] {
+  const foldersWithConfig: string[] = [];
+  let currentFolder = folder;
```
Comment (yury-s) [inline packages/playwright/src/transform/transform.ts:95]: You may need to call path.resolve(folder) here.

File: packages/playwright/src/transform/transform.ts [hunk 2]
```diff
@@ -81,12 +83,44 @@ function validateTsConfig(tsconfig: LoadedTsConfig): ParsedTsConfigData {
...
+
+    const parentFolder = path.resolve(currentFolder, '../');
+    if (currentFolder === parentFolder)
+      break;
+    currentFolder = parentFolder;
   }
-  return cachedTSConfigs.get(tsconfigPathOrDirecotry)!;
+
+  for (const folder of foldersWithConfig)
+    cachedTSConfigs.set(folder, result);
```
Comment (yury-s) [inline packages/playwright/src/transform/transform.ts:122]: Maybe store only actual folder with the config since we anyway check the cache for each parent folder now?

**Review by yury-s — APPROVED** [review]

File: packages/playwright/src/transform/transform.ts (hunk 2 above)
Comment (pavelfeldman) [reply packages/playwright/src/transform/transform.ts:122]: that would save us the walk up the folder tree

**Review by yury-s — APPROVED** [review]
