### PR TITLE
fix(aria): process children of hidden elements

### LINKED ISSUE #36296: [Bug]: ariaSnapshot hides `visibility: visible` inside `visibility: hidden`
### Version

tot

### Steps to reproduce

```ts
it('repro', async ({ page }) => {
  await page.setContent(`
    <div style="visibility: hidden;">
      <div style="visibility: visible;">
        <button>Button</button>
      </div>
    </div>
  `);

  await checkAndMatchSnapshot(page.locator('body'), `
    - button "Button"
  `);
});
```

### Expected behavior

I expect the inner button to be in the snapshot.

### Actual behavior

The snapshot is empty.

### Additional context

Chromium considers it visible:

Image

Maybe it's this case that we don't implement:

https://github.com/microsoft/playwright/blob/3c248ed163ff760eb064777130cfe9eb244a8323/packages/injected/src/roleUtils.ts#L263-L265

### Environment

```shell
System:
    OS: macOS 15.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 145.89 MB / 18.00 GB
  Binaries:
    Node: 23.11.0 - ~/.local/state/fnm_multishells/12301_1749718398620/bin/node
    npm: 11.4.1 - ~/.local/state/fnm_multishells/12301_1749718398620/bin/npm
    pnpm: 10.6.5 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.100.3 - /opt/homebrew/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/36296

### CODE REVIEW

File: packages/injected/src/ariaSnapshot.ts [hunk 1]
```diff
@@ -72,11 +83,11 @@ export function generateAriaTree(rootElement: Element, options?: { forAI?: boole
       return;
 
     const element = node as Element;
-    let isVisible = !roleUtils.isElementHiddenForAria(element);
-    if (options?.forAI)
-      isVisible = isVisible || isElementVisible(element);
-    if (!isVisible)
+    if (!isVisible(element, options)) {
+      // skip this element, but still process its children: https://github.com/w3c/aria/issues/1055
+      processElement(ariaNode, element, []);
```
Comment (pavelfeldman) [inline packages/injected/src/ariaSnapshot.ts]: I am not sure how this makes sense. Also, you can't process children as if they are visible. And we probably only want this for non-aria visibility.

Comment (Skn0tt) [reply packages/injected/src/ariaSnapshot.ts]: > I am not sure how this makes sense

How so? As in, you're surprised how Chromium and this issue interpret the ARIA spec, or as in this code is weird?

> Also, you can't process children as if they are visible.

I think we can, because the `isVisible` method takes parent elements into account when determining visibility.

> we probably only want this for non-aria visibility.

It already does so, based on my reading of `isElementHiddenForAria`. I added a test in https://github.com/microsoft/playwright/pull/36316/commits/9775c4a4425eb060a90cd5a3acb53c1d33b3cddc to ensure that.

**Comment by Skn0tt** [comment]
As discussed yesterday, I scoped down the change to the AI snapshot.

File: tests/page/page-aria-snapshot-ai.spec.ts [hunk 2]
```diff
@@ -252,3 +252,16 @@ it('should auto-wait for blocking CSS', async ({ page, server }) => {
   `, { waitUntil: 'commit' });
   expect(await snapshotForAI(page)).toContainYaml('Hello World');
 });
+
+it('should show visible children of hidden elements', { annotation: { type: 'issue', description: 'https://github.com/microsoft/playwright/issues/36296' }  }, async ({ page }) => {
+  await page.setContent(`
```
Comment (dgozman) [inline tests/page/page-aria-snapshot-ai.spec.ts:261]: Let's make this test a bit more involved:

```
- hidden
  - visible
    - neutral
  - hidden
    - visible
  - neutral (no visibility change)
    - visible
      - hidden
    - neutral
```

Comment (Skn0tt) [reply tests/page/page-aria-snapshot-ai.spec.ts:261]: done in https://github.com/microsoft/playwright/pull/36316/commits/9584dc65a7c18b2f578c84cd2c7ebbe686171d69

File: packages/injected/src/ariaSnapshot.ts [hunk 3]
```diff
@@ -61,6 +69,9 @@ export function generateAriaTree(rootElement: Element, options?: { forAI?: boole
     visited.add(node);
 
     if (node.nodeType === Node.TEXT_NODE && node.nodeValue) {
+      if (node.parentElement && !isVisible(node.parentElement, options))
```
Comment (pavelfeldman) [inline packages/injected/src/ariaSnapshot.ts]: Would be nice to solve it via a parameter boolean, that way you don't need to check parent visibility for every text child.

File: packages/injected/src/ariaSnapshot.ts [hunk 4]
```diff
@@ -72,11 +83,12 @@ export function generateAriaTree(rootElement: Element, options?: { forAI?: boole
...
 
     const element = node as Element;
-    let isVisible = !roleUtils.isElementHiddenForAria(element);
-    if (options?.forAI)
-      isVisible = isVisible || isElementVisible(element);
-    if (!isVisible)
+    if (!isVisible(element, options)) {
+      if (options?.forAI)
+        // skip this element, but still process its children https://github.com/microsoft/playwright/issues/36296
+        processElement(ariaNode, element, []);
```
Comment (pavelfeldman) [inline packages/injected/src/ariaSnapshot.ts]: We should be consistent with the aria-owns children. We either respect them in forAI or we don't. Your change makes it inconsistent.

Comment (pavelfeldman) [reply packages/injected/src/ariaSnapshot.ts]: I'd say all we care about is that toAriaNode considers element as role === 'presentation' || role === 'none', then the right things will happen below.

Comment (Skn0tt) [reply packages/injected/src/ariaSnapshot.ts]: Good point, didn't think about aria-owns. Moving this new logic into `toAriaNode` made this a lot better.

File: packages/injected/src/ariaSnapshot.ts (hunk 3 above)
Comment (Skn0tt) [reply packages/injected/src/ariaSnapshot.ts]: Done. The behaviour around `ariaChildren` isn't super obvious to me, so I added a comment.

**Review by Skn0tt — COMMENTED** [review]
Thanks for the good review! Addressed.

File: packages/injected/src/ariaSnapshot.ts [hunk 5]
```diff
@@ -176,8 +179,14 @@ function toAriaNode(element: Element, options?: { forAI?: boolean, refPrefix?: s
     };
   }
 
-  const defaultRole = options?.forAI ? 'generic' : null;
-  const role = roleUtils.getAriaRole(element) ?? defaultRole;
+  let role: AriaRole | null = null;
+  if (options?.forAI) {
+    const isVisible = !roleUtils.isElementHiddenForAria(element) || isElementVisible(element);
```
Comment (pavelfeldman) [inline packages/injected/src/ariaSnapshot.ts]: Are we making these checks twice for each node? Looking at `parentVisible = isElementVisible(element);` and `if (!options?.forAI && roleUtils.isElementHiddenForAria(element))` above.

Comment (Skn0tt) [reply packages/injected/src/ariaSnapshot.ts]: The `isElementHiddenForAria` check is only made once, since one of the checks is behind `forAI` and the other is behind `!forAI`.

`isElementVisible` is indeed called twice for the same element. Even worse, it is called `parentVisible = isElementVisible(element)` is called for each tree node, but only used for a subset of leaf nodes. That's what the parameter argument did, I suppose. Let me see to it.

Comment (Skn0tt) [reply packages/injected/src/ariaSnapshot.ts]: Alright, after molding this change around, I arrived at something good.

**Review by dgozman — APPROVED** [review]

**Review by pavelfeldman — APPROVED** [review]
