### PR TITLE
fix(mcp): lax file path sanitization

### LINKED ISSUE #1063: browser_screenshot tool saves to the incorrect file name
### The issue

We've gotten bug reports in Copilot coding agent of browser_screenshot failing to work properly in some cases. Digging into it I found that the issue is that Playwright does some sort of path sanitization on the file path submitted which causes file paths that contain `-` to be saved with `_` instead.

This breaks logic in CCA which expects the image to be saved with the exact file path given, so the calling code can do some preprocessing of the image before its sent to the model.

GitHub internal issue: https://github.com/github/sweagentd/issues/6136

### Meta comment on tool behavior

This is one of a few different issues that have come out of unexpected behaviors or breaking changes to the browser_screenshot tool. The prior one was the change from returning base64 encoded image data, to defaulting to saving images on disk instead.

Going forward would it be possible to version the tool behavior via a cmd line parameter and/or otherwise document breaking changes?

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright-mcp/issues/1063

### CODE REVIEW

File: packages/playwright/src/mcp/browser/config.ts [hunk 1]
```diff
@@ -372,10 +371,19 @@ function envToString(value: string | undefined): string | undefined {
   return value ? value.trim() : undefined;
 }
 
-function sanitizeForFilePath(s: string) {
+
+export function sanitizeForFilePath(outputDir: string, name: string) {
+  const base = path.resolve(outputDir);
+  // Fast path, permissive
+  const lax = name.split(path.sep).map(s => s.replace(/[\x00-\x1F\x22\x2A\x2F\x3A\x3C\x3E\x3F\x5C\x7C\x7F]/g, '-').trim()).join(path.sep);
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/config.ts]: if it is a file name why does it have path.sep?

File: packages/playwright/src/mcp/browser/config.ts [hunk 2]
```diff
@@ -271,15 +271,26 @@ async function loadConfig(configFile: string | undefined): Promise<Config> {
...
-  return path.join(outputDir, fileName);
+  // Trust code.
+  if (options.origin === 'code')
+    return path.resolve(outputDir, fileName);
+
+  // Trust llm to use valid characters in file names.
+  if (options.origin === 'llm') {
+    const resolvedFile = path.resolve(outputDir, fileName);
+    if (!resolvedFile.startsWith(path.resolve(outputDir) + path.sep))
+      throw new Error(`Resolved file path for ${fileName} is outside of the output directory`);
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/config.ts:289]: Include the directory name in the error message.

**Review by yury-s — APPROVED** [review]
