### PR TITLE
fix(cli): store trace/storage/har on SIGINT

### LINKED ISSUE #16198: [BUG] using terminal to close browser doesn't save storage
**Context:**
- Playwright Version:  latest
- Operating System: Mac
- Node.js version:14.17
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

````npx playwright codegen --save-storage=auth.json github.com````

Login int Github then close codegen using the terminal

````npx playwright codegen --load-storage=auth.json github.com````

Not logged in 

**Describe the bug**

After signing into GitHub when you close codegen using the terminal instead of directly closing the browser then the storage is not saved.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/16198

### CODE REVIEW

File: packages/playwright-core/src/cli/cli.ts [hunk 1]
```diff
@@ -522,6 +523,10 @@ async function launchContext(options: Options, headless: boolean, executablePath
       closeBrowser().catch(e => null);
     });
   });
+  process.on('SIGINT', async () => {
+    await closeBrowser();
+  });
```
Comment (dgozman) [inline packages/playwright-core/src/cli/cli.ts:528]: `process.exit(130);` ?

File: packages/playwright-core/src/protocol/protocol.yml [hunk 2]
```diff
@@ -948,6 +948,7 @@ BrowserContext:
         device: string?
         saveStorage: string?
         outputFile: string?
+        doNotHandleSIGINT: boolean?
```
Comment (dgozman) [inline packages/playwright-core/src/protocol/protocol.yml:951]: `handleSIGINT`

File: packages/playwright-core/src/server/recorder.ts [hunk 3]
```diff
@@ -56,6 +56,7 @@ export class Recorder implements InstrumentationListener {
   private _allMetadatas = new Map<string, CallMetadata>();
   private _debugger: Debugger;
   private _contextRecorder: ContextRecorder;
+  private _doNotHandleSignals: boolean;
```
Comment (dgozman) [inline packages/playwright-core/src/server/recorder.ts:59]: `_handleSIGINT: boolean | undefined`

File: packages/playwright-core/src/server/recorder/recorderApp.ts [hunk 4]
```diff
@@ -165,7 +168,7 @@ export class RecorderApp extends EventEmitter implements IRecorderApp {
 
     // Testing harness for runCLI mode.
     {
-      if (process.env.PWTEST_CLI_EXIT && sources.length) {
+      if ((process.env.PWTEST || process.env.PWTEST_CLI_EXIT) && sources.length) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/recorder/recorderApp.ts:171]: `isUnderTest()`?

File: tests/library/inspector/cli-codegen-2.spec.ts [hunk 5]
```diff
@@ -544,6 +544,20 @@ test.describe('cli codegen', () => {
     expect(fs.existsSync(traceFileName)).toBeTruthy();
   });
 
+  test('should save assets via SIGINT', async ({ runCLI }, testInfo) => {
```
Comment (dgozman) [inline tests/library/inspector/cli-codegen-2.spec.ts:547]: Skip it on Windows right away.

File: tests/library/inspector/cli-codegen-2.spec.ts [hunk 6]
```diff
@@ -544,6 +544,20 @@ test.describe('cli codegen', () => {
...
+    const [traceFileName, storageFileName, harFileName] = [testInfo.outputPath('trace.zip'), testInfo.outputPath('auth.json'), testInfo.outputPath('har.zip')];
```
Comment (dgozman) [inline tests/library/inspector/cli-codegen-2.spec.ts:548]: Too much python in your past.

**Review by dgozman — APPROVED** [review]
