### PR TITLE
fix(reporters): output relative to config

### LINKED ISSUE #17412: [BUG] HTML reporter otuput dir always resolves from the playwright config location
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Node.js version: 16.16
- Browser: All

**Bug Description**

Given the following report configuration

```javascript

const config: PlaywrightTestConfig = {
   //...
reporter: [
    [
      'html',
      {
        outputFolder: '../../dist/apps/playwright-project/playwright-report',
      },
    ],
    [
      'json',
      {
        outputFile:
          'dist/apps/playwright-project/playwright-report/test-results.json',
      },
    ],
  ],
// ....
}
```

and running `npx playwright --config apps/playwright-project/playwright.config.ts` one would expect to get an output like this

```
.
├── apps
│   └── playwright-project
│       ├── playwright.config.ts
│       └── src
│           └── e2e
│               └── my-test.spec.ts
└── dist
    └── apps
        └── playwright-project
            └── playwright-results
                ├── index.html
                └── test-results.json
```

but the html report location is always resolving relative to the playwright.config.ts file location, so the current result is:

```
.
├── apps
│   └── playwright-project
│       ├── dist
│       │   └── apps
│       │       └── playwright-project
│       │           └── playwright-report
│       │               └── index.html
│       ├── playwright.config.ts
│       └── src
│           └── e2e
│               └── my-test.spec.ts
└── dist
    └── apps
        └── playwright-project
            └── playwright-results
                └── test-results.json
```

The HTML reporter should resolve the output dir according to what it received in the `outputFolder` config, just like the JSON reporter does.

### PR DESCRIPTION
**Pull request by rwoll**
Fixes #17412.
Supercedes #17413.

- if configured via playwright.config.ts, relative paths should be relative to the config.
- if configured via env var, should be relative to `cwd`

### CODE REVIEW

File: packages/playwright-test/src/reporters/json.ts [hunk 1]
```diff
@@ -19,13 +19,14 @@ import path from 'path';
...
 import { MultiMap } from 'playwright-core/lib/utils/multimap';
+import type { FullConfigInternal } from '../types';
 
 export function toPosixPath(aPath: string): string {
   return aPath.split(path.sep).join(path.posix.sep);
 }
 
 class JSONReporter implements Reporter {
-  config!: FullConfig;
+  config!: FullConfigInternal;
```
Comment (pavelfeldman) [inline packages/playwright-test/src/reporters/json.ts:29]: This suggests that reporters need internal APIs, which does not sound right.

Comment (pavelfeldman) [reply packages/playwright-test/src/reporters/json.ts:29]: If config is used, you have configFile. If config is not used, I don't think you can even configure these reporters.

**Review by dgozman — APPROVED** [review]

File: packages/playwright-test/src/reporters/json.ts [hunk 2]
```diff
@@ -19,6 +19,7 @@ import path from 'path';
 import type { FullConfig, TestCase, Suite, TestResult, TestError, TestStep, FullResult, Location, Reporter, JSONReport, JSONReportSuite, JSONReportSpec, JSONReportTest, JSONReportTestResult, JSONReportTestStep } from '../../types/testReporter';
 import { prepareErrorStack } from './base';
 import { MultiMap } from 'playwright-core/lib/utils/multimap';
+import assert from 'assert';
```
Comment (mxschmitt) [inline packages/playwright-test/src/reporters/json.ts:22]: this assert seems wrong, its not our custom assert.

**Review by mxschmitt — CHANGES_REQUESTED** [review]
