### PR TITLE
fix(cli): throw an error if invalid choice is specified for --update-snapshots option

### LINKED ISSUE #36297: [Bug]: `--update-snapshots` parse from CLI seems broken
### Version

1.52.0

### Steps to reproduce

run

```
playwright test --project=chromium --workers=8 --retries=2 --update-snapshots tests/test.e2e.ts:23
```

### Expected behavior

Only selected tests running

### Actual behavior

All tests started

### Additional context

If i move flag `--update-snapshots` between two other, like

```diff
- playwright test --project=chromium --workers=8 --retries=2 --update-snapshots tests/test.e2e.ts:23
+ playwright test --project=chromium --workers=8 --update-snapshots --retries=2 tests/test.e2e.ts:23
```

or add explicitly set some value to it, like

```diff
- playwright test --project=chromium --workers=8 --retries=2 --update-snapshots tests/test.e2e.ts:23
+ playwright test --project=chromium --workers=8 --retries=2 --update-snapshots=all tests/test.e2e.ts:23
```

Then only selected tests running.

Looks like that in problematic case tests list is interpreted like value for `--update-snapshots`, so there is also flag value validation missing.

### Environment

```shell
System:
    OS: macOS 15.3.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 662.17 MB / 36.00 GB
  Binaries:
    Node: 20.18.2 - ~/.nvm/versions/node/v20.18.2/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.2/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

### PR DESCRIPTION
**Pull request by yury-s**
This avoids unexpected behavior when file name is treated as a value of `--update-snapshots` parameter. Previously it'd be silently swallowed and now we'll throw an error. If the option is passed without a value it must be either followed by another option or be the last in the command line.

See also: https://github.com/tj/commander.js/pull/2382
Fixes: https://github.com/microsoft/playwright/issues/36297

### CODE REVIEW

File: packages/playwright/src/program.ts [hunk 1]
```diff
@@ -373,41 +373,41 @@ const kTraceModes: TraceMode[] = ['on', 'off', 'on-first-retry', 'on-all-retries
...
-  ['--ui', `Run tests in interactive UI mode`],
-  ['--ui-host <host>', 'Host to serve UI on; specifying this option opens UI in a browser tab'],
-  ['--ui-port <port>', 'Port to serve UI on, 0 for any free port; specifying this option opens UI in a browser tab'],
-  ['-u, --update-snapshots [mode]', `Update snapshots with actual results. Possible values are "all", "changed", "missing", and "none". Running tests without the flag defaults to "missing"; running tests with the flag but without a value defaults to "changed".`],
-  ['--update-source-method <method>', `Chooses the way source is updated. Possible values are 'overwrite', '3way' and 'patch'. Defaults to 'patch'`],
-  ['-j, --workers <workers>', `Number of concurrent workers or percentage of logical CPU cores, use 1 to run in a single worker (default: 50%)`],
-  ['-x', `Stop after the first failure`],
+const testOptions: [string, { description: string, choices?: string[], preset?: string }][] = [
+  /* deprecated */ ['--browser <browser>', { description: `Browser to use for tests, one of "all", "chromium", "firefox" or "webkit" (default: "chromium")` }],
```
Comment (pavelfeldman) [inline packages/playwright/src/program.ts:379]: Take care of default() too

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright/src/program.ts (hunk 1 above)
Comment (yury-s) [reply packages/playwright/src/program.ts:379]: I'd love to, but we need to use user config values as the defaults and it's not parsed yet at this point. Added a comment about it in the code.
