### PR TITLE
fix: allow to show uncompressed trace dir

### LINKED ISSUE #1160: Can't view traces using playwright trace viewer or https://trace.playwright.dev/
Hello,

I have configured playwright mcp to use traces --caps=tracing. LLM starts and stops tracing and as an output I can see it generated files for traces as per the image below.

Image

Unfortunately I can't seem to open them. I tried compressing them as zip but neither playwright trace viewer nor web version is able to open the file. Screenshot below from the web version of trace viewer.

Image

Could you help me with this issue?
Any diagnosing I could do on my side?

Thanks in advance.

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright-mcp/issues/1160

### CODE REVIEW

File: packages/trace-viewer/src/sw/main.ts [hunk 1]
```diff
@@ -102,14 +102,33 @@ function loadTrace(clientId: string, url: URL, isContextRequest: boolean, progre
...
+}
+
+function isZipUrl(traceUrl: string): boolean {
+  if (traceUrl.endsWith('.zip'))
+    return true;
+  const url = parseURL(traceUrl);
+  // If it cannot be parsed, assume it is a file path.
+  if (!url)
+    return false;
+  // blob urls do not have .zip extension
```
Comment (pavelfeldman) [inline packages/trace-viewer/src/sw/main.ts]: What does the protocol have to do with zip?

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts [hunk 2]
```diff
@@ -72,15 +72,24 @@ export async function startTraceViewerServer(options?: TraceViewerServerOptions)
     if (relativePath.startsWith('/file')) {
       try {
         const filePath = url.searchParams.get('path')!;
-        if (fs.existsSync(filePath))
-          return server.serveFile(request, response, url.searchParams.get('path')!);
+        let traceFile;
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/trace/viewer/traceViewer.ts]: Why are we getting into the file:// branch?

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts [hunk 3]
```diff
@@ -52,16 +53,32 @@ export type TraceViewerAppOptions = {
...
-  if (traceUrl.endsWith('.json'))
-    traceFile = traceUrl.substring(0, traceUrl.length - '.json'.length);
+    return traceUrl;
+
+  if (traceUrl.startsWith('http://') || traceUrl.startsWith('https://'))
+    return traceUrl;
+
+  if (traceUrl.endsWith('.json')) {
+    const traceFile = traceUrl.substring(0, traceUrl.length - '.json'.length) + '.trace';
+    if (!fs.existsSync(traceFile))
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/trace/viewer/traceViewer.ts]: I don't think we need this, technically existence of -recording-1.trace would suffice.

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts (hunk 3 above)
Comment (yury-s) [reply packages/playwright-core/src/server/trace/viewer/traceViewer.ts]: Agreed. Removed.
