### PR TITLE
fix: allow relative userDataDir

### LINKED ISSUE #34700: [Bug]: user_data_dir in launch_persistent_context() resolves relative paths relative to browser executable instead of current working directory
### Version

1.50.0

### Steps to reproduce

1. Create a script with:
```python
browser = await playwright.chromium.launch_persistent_context(
    user_data_dir='./user_data',
    # user_data_dir='user_data', # same result
    executable_path='./chromium/chrome.exe'
)
```
2. Run the script from a working directory different from the browser's executable location
3. Observe where the user_data directory is actually created

### Expected behavior

The user_data_dir should be created relative to the current working directory. (./user_data/)

### Actual behavior

The user_data_dir is created relative to the directory containing the browser executable. (./chromuim/user_data/)

### Additional context

_No response_

### Environment

```Text
- Operating System: [Windows 10]
- CPU: [x86]
- Browser: [Chromium]
- Python Version: [3.13]
- Other info:
```

### PR DESCRIPTION
**Pull request by mxschmitt**
A relative directory in Chromium's user-data-dir argument ends up getting resolved against the directory of `chrome.exe` rather than the `CWD` on Windows.

Relates https://chromium-review.googlesource.com/c/chromium/src/+/2717314

Fixes https://github.com/microsoft/playwright/issues/34700

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/chromium.ts [hunk 1]
```diff
@@ -275,7 +275,7 @@ export class Chromium extends BrowserType {
 
   override defaultArgs(options: types.LaunchOptions, isPersistent: boolean, userDataDir: string): string[] {
     const chromeArguments = this._innerDefaultArgs(options);
-    chromeArguments.push(`--user-data-dir=${userDataDir}`);
+    chromeArguments.push(`--user-data-dir=${path.resolve(userDataDir)}`);
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/chromium.ts:278]: This is going to be relative to the driver's location in language ports, isn't it? I believe we want it to be relative to the client executable, which means computing it on the client.

**Review by yury-s — COMMENTED** [review]
Why don't we need to resolve it in the other two browsers?

File: packages/playwright-core/src/server/chromium/chromium.ts (hunk 1 above)
Comment (mxschmitt) [reply packages/playwright-core/src/server/chromium/chromium.ts]: Its relative to the CWD of where the driver was started. In all of the ports, we don't specify the CWD, so it inherits the CWD of the parent process:

- [Python](https://github.com/microsoft/playwright-python/blob/d3aacbb7dccbd39b37965013070d95a043ed0f3e/playwright/_impl/_transport.py#L120)
- [.NET](https://github.com/microsoft/playwright-dotnet/blob/390f50e53259065c86db8111403590a26512e735/src/Playwright/Transport/StdIOTransport.cs#L117C29-L117C45)
- [Java](https://github.com/microsoft/playwright-java/blob/995cf902fb09fd54ea512eab06101cc8d62d5009/driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java#L74)

Sounds reasonable to me?

**Comment by mxschmitt** [comment]
> Why don't we need to resolve it in the other two browsers?

Only Chromium on Windows behaved weirdly - moved it a layer up to normalise it everywhere!

File: packages/playwright-core/src/server/browserType.ts [hunk 2]
```diff
@@ -188,6 +188,8 @@ export abstract class BrowserType extends SdkObject {
     tempDirectories.push(artifactsDir);
 
     if (userDataDir) {
+      if (!path.isAbsolute(userDataDir))
```
Comment (dgozman) [inline packages/playwright-core/src/server/browserType.ts:191]: This should be done on the client!

File: tests/library/defaultbrowsercontext-2.spec.ts [hunk 3]
```diff
@@ -101,6 +101,20 @@ it('should accept userDataDir', async ({ createUserDataDir, browserType }) => {
   expect(fs.readdirSync(userDataDir).length).toBeGreaterThan(0);
 });
 
+it('should accept relative userDataDir', async ({ createUserDataDir, browserType }) => {
+  const userDataDir = await createUserDataDir();
+  const cwd = process.cwd();
+  try {
+    console.log(userDataDir);
```
Comment (dgozman) [inline tests/library/defaultbrowsercontext-2.spec.ts:108]: Don't want to spam console in the test.

File: tests/library/defaultbrowsercontext-2.spec.ts [hunk 4]
```diff
@@ -101,6 +101,20 @@ it('should accept userDataDir', async ({ createUserDataDir, browserType }) => {
...
+    process.chdir(userDataDir);
```
Comment (dgozman) [inline tests/library/defaultbrowsercontext-2.spec.ts:109]: Instead of this, perhaps pass `path.relative(process.cwd(), path.join(userDataDir, 'foobar'))`?

File: tests/library/defaultbrowsercontext-2.spec.ts (hunk 3 above)
Comment (dgozman) [reply tests/library/defaultbrowsercontext-2.spec.ts:108]: I would still like this console.log to be removed.

File: packages/playwright-core/src/client/browserType.ts [hunk 5]
```diff
@@ -14,6 +14,7 @@
  * limitations under the License.
  */
 
+import path from 'path';
```
Comment (dgozman) [inline packages/playwright-core/src/client/browserType.ts:17]: Welcome to the happy linting days!

**Review by dgozman — APPROVED** [review]

File: tests/library/defaultbrowsercontext-2.spec.ts (hunk 4 above)
Comment (mxschmitt) [reply tests/library/defaultbrowsercontext-2.spec.ts:109]: Not a huge of polluting the actual cwd during the test run hence doing it this way.
