### PR TITLE
fix(chromium): insert oopifs into the frame hierarchy when connecting over CDP

### LINKED ISSUE #17656: [BUG]when using connect_over_cdp, the browser_context.pages returned pages missing child_frames
**Context:**
- Playwright Version: 1.25.2
- Operating System: Windows
- Python version: 3.8.2
- Browser: Chromium

**Code Snippet**

```python
    async def connect_to_browser(self):
        if not self._playwright:
            self._playwright = await async_playwright().start()
        self._browser = await self._playwright.chromium.connect_over_cdp(f"http://localhost:9222")
        self._browser_context = self._browser.contexts[0]
        pages = self._browser_context.pages 
```

**Describe the bug**
when using connect_over_cdp, the browser_context.pages returned pages missing child_frames
image

but when i using browser_context.new_page() and page.goto(url), (same url) the returned page contain child_frames
image

### PR DESCRIPTION
**Pull request by dgozman**
Previously, the information of the parent frame for an OOPIF target was not available over CDP. With the latest Chromium, we can finally determine where does the OOPIF fit in the frame hierarchy.

Fixes #17656.

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crPage.ts [hunk 1]
```diff
@@ -432,13 +432,13 @@ class FrameSession {
...
       eventsHelper.addEventListener(this._client, 'Runtime.executionContextDestroyed', event => this._onExecutionContextDestroyed(event.executionContextId)),
       eventsHelper.addEventListener(this._client, 'Runtime.executionContextsCleared', event => this._onExecutionContextsCleared()),
-      eventsHelper.addEventListener(this._client, 'Target.attachedToTarget', event => this._onAttachedToTarget(event)),
-      eventsHelper.addEventListener(this._client, 'Target.detachedFromTarget', event => this._onDetachedFromTarget(event)),
     ]);
   }
 
   private _addBrowserListeners() {
     this._eventListeners.push(...[
+      eventsHelper.addEventListener(this._client, 'Target.attachedToTarget', event => this._onAttachedToTarget(event)),
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/crPage.ts:440]: Is this compatible with chromium <141 ?

File: packages/playwright-core/src/server/chromium/crPage.ts [hunk 2]
```diff
@@ -713,7 +713,12 @@ class FrameSession {
     if (event.targetInfo.type === 'iframe') {
       // Frame id equals target id.
       const targetId = event.targetInfo.targetId;
-      const frame = this._page.frameManager.frame(targetId);
+      let frame = this._page.frameManager.frame(targetId);
+      if (!frame && event.targetInfo.parentFrameId) {
+        // When connecting to an existing page with an iframe, there is an "iframe" target,
+        // but no local frame is reported in getFrameTree. We can create a remote frame here.
+        frame = this._page.frameManager.frameAttached(targetId, event.targetInfo.parentFrameId);
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/crPage.ts:720]: Could it be that the parent frame has not been reported yet/has been removed already at this point?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/server/chromium/crPage.ts (hunk 2 above)
Comment (dgozman) [reply packages/playwright-core/src/server/chromium/crPage.ts:720]: Targets come from the browser target and the source of truth. If the frame is removed, we'll get `Target.detachedFromTarget` shortly after.

File: packages/playwright-core/src/server/chromium/crPage.ts (hunk 1 above)
Comment (dgozman) [reply packages/playwright-core/src/server/chromium/crPage.ts:440]: Yes, these events were always coming from the browser.
