### PR TITLE
fix(html): truncate step titles

### LINKED ISSUE #38538: [Bug]: Long step names prevent clicking on step attachment link
### Version

1.57.0

### Steps to reproduce

Clone repo at https://github.com/bdcarr/playwright-attachment-link-bug and follow the instructions in the readme to generate a HTML report demonstrating the issue.

### Expected behavior

You can click on the attachment icon and have it take you to the relevant attachment, regardless of how long the step name is.

### Actual behavior

If the step name + location is long enough to reach the attachment icon, something blocks your click, so you can't jump to the attachment from the test step.

https://github.com/user-attachments/assets/afffc626-2f2a-4c90-af60-5dfde3b57739

The example I've given only shows the step name being long, but I also tested with a name that is just long enough to push the step location (e.g. "example.spec.js:5") into the attachment link. You can fiddle around with this just by editing the DOM while viewing the report.

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 15.7.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 132.64 MB / 32.00 GB
  Binaries:
    Node: 20.19.4 - /Users/brycecarr/.local/state/fnm_multishells/26667_1764804574151/bin/node
    npm: 10.8.2 - /Users/brycecarr/.local/state/fnm_multishells/26667_1764804574151/bin/npm
    pnpm: 10.8.1 - /Users/brycecarr/Library/pnpm/pnpm
    Deno: 2.5.6 - /opt/homebrew/bin/deno
  IDEs:
    VSCode: 1.107.0 - /usr/local/bin/code
    Cursor: 2.0.77 - /usr/local/bin/cursor
  Languages:
    Bash: 5.3.8 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.57.0 => 1.57.0
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/38538

https://github.com/user-attachments/assets/c6dc5a5b-721b-4dd9-ae2d-2353dcde126c

### CODE REVIEW

File: packages/html-reporter/src/testResultView.tsx [hunk 1]
```diff
@@ -194,19 +194,20 @@ const StepTreeItem: React.FC<{
   depth: number,
 }> = ({ test, step, result, depth }) => {
   const searchParams = useSearchParams();
-  return <TreeItem title={<span aria-label={step.title}>
-    <span style={{ float: 'right' }}>{msToString(step.duration)}</span>
+  return <TreeItem title={<span aria-label={step.title} className='step-title-container'>
```
Comment (dgozman) [inline packages/html-reporter/src/testResultView.tsx]: Since this is now a flex, make it a div instead.

File: packages/html-reporter/src/testResultView.tsx [hunk 2]
```diff
@@ -194,19 +194,20 @@ const StepTreeItem: React.FC<{
...
+    {statusIcon(step.error || step.duration === -1 ? 'failed' : (step.skipped ? 'skipped' : 'passed'))}
+    <span className='step-title-text'>{step.title}</span>
+    {step.count > 1 && <><span className='step-multiplier'>✕</span><span className='test-result-counter'>{step.count}</span></>}
```
Comment (dgozman) [inline packages/html-reporter/src/testResultView.tsx]: Why turn ` x ` into a separate span?

File: packages/html-reporter/src/testResultView.css [hunk 3]
```diff
@@ -37,12 +37,62 @@
 .test-result-path {
   padding: 0 0 0 5px;
   color: var(--color-fg-muted);
+  flex-shrink: 0;
```
Comment (dgozman) [inline packages/html-reporter/src/testResultView.css]: I think that test title is more important than a location. I'd put them together in a single flex-grow/shrink container, and leave them as pure inline spans.

File: packages/html-reporter/src/testResultView.css [hunk 4]
```diff
@@ -37,12 +37,62 @@
...
+
+.step-attachment-link:hover {
+  background-color: var(--color-neutral-muted);
+}
+
+.step-attachment-link .octicon {
+  margin-right: 0;
+}
+
+.step-duration {
```
Comment (dgozman) [inline packages/html-reporter/src/testResultView.css:87]: Shouldn't this be `flex: none`?

File: packages/html-reporter/src/testResultView.tsx (hunk 2 above)
Comment (Skn0tt) [reply packages/html-reporter/src/testResultView.tsx]: so that we can add spacing around it - without the spacing, everything is too cramped

Comment (Skn0tt) [reply packages/html-reporter/src/testResultView.tsx]: hmm, it also works without it now.

File: packages/html-reporter/src/testResultView.css [hunk 5]
```diff
@@ -43,6 +43,51 @@
...
+
+.step-title-container {
+  display: flex;
+  align-items: center;
+  flex: auto;
+  min-width: 0;
+}
+
+.step-title-container > * {
+  flex-shrink: 0;
```
Comment (dgozman) [inline packages/html-reporter/src/testResultView.css:57]: nit: I think you can achieve the same by making `.step-title-container` be a block rather than flex. Up to you though.

**Review by dgozman — APPROVED** [review]

**Comment by bdcarr** [comment]
Hell yeah, thank you!
