### PR TITLE
fix(test runner): keep track of remaining tests on the runner side

### LINKED ISSUE #7444: [BUG] when maxFailures is reached it does not terminate the other workers
**Context:**
- Playwright Version: @playwright/test@^1.12.3
- Operating System: mac big sur
- Node.js version:  v14.16.1
- Browser: all
- Extra: N/a

I'm running 3 sample tests with the following configuration 

``` typescript
const config: PlaywrightTestConfig = {
  maxFailures: 1,
  workers: 2,
  use: {
    headless: true,
  },
  reporter: [["list"], ["json", { outputFile: "report.json" }]],
  timeout:40000,
  outputDir:`${process.cwd()}/output`
}
```

I'm noticing that the "maxFailures" option have a strange behaviour running on multiple workers, the runner seems to wait for every worker to complete tests, even after the max failure count is reached, but then all subsequent tests are marked as "skipped".

Here's my console output for an ad hoc test run aimed to reproduce the issue. 

```
Running 3 tests using 2 workers

    long.test.ts:5:5 › [chromium] long tests long test: 
  x 1) short.test.ts:3:1 › [chromium] short test (10ms)
**long test finished**
    long.test.ts:12:5 › [chromium] long tests another long test: 
another long test finished


  1) short.test.ts:3:1 › [chromium] short test =====================================================

    Error: expect(received).toBeFalsy()

    Received: true

      2 |
      3 | test("short test",()=>{
    > 4 |     expect(true).toBeFalsy()
        |                  ^
      5 |     console.log('short test finished')
      6 | })

        at /Users/agiangrande/Documents/repo/issue-playwright/short.test.ts:4:18
        at FixtureRunner.resolveParametersAndRunHookOrTest (/Users/agiangrande/Documents/repo/issue-playwright/node_modules/@playwright/test/lib/test/fixtures.js:241:16)
        at WorkerRunner._runTestWithBeforeHooks (/Users/agiangrande/Documents/repo/issue-playwright/node_modules/@playwright/test/lib/test/workerRunner.js:290:39)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)


  1 failed
    short.test.ts:3:1 › [chromium] short test ======================================================
  2 skipped
```

[here's](https://github.com/Daemos87/issue-playwright.git) a repo to reproduce the issue, just clone, yarn install, yarn test  

**Expectation**

I think the runner should stop all workers immediately after the max failure count is reached, or at least it shouldn't mark a test as skipped if it was effectively executed.

### PR DESCRIPTION
**Pull request by dgozman**
This fixes two issues:
- Sudden worker process exit is properly accounted for.
- We can `stop()` workers willy-nilly, e.g. after reaching maxFailures.

Details:
- DonePayload does not send `remaining` anymore, and worker does not track it.
- Instead, `Dispatcher._runJob` track remaining tests and acts accordingly.
- Upon worker exit, we emulate a fatal error for all remaining tests.

Drive-by:
- Do not report `onTestBegin` after reaching `maxFailures` to avoid confusion. Before, we did report `onTestBegin`, but not `onTestEnd`.
- List reporter aligned between "running" and "finished" state - it was one character misplaced.
- Do not show the first 3 lines of test file when we cannot locate the error location in it - that's just noise.
- Added a SIGINT test.

Fixes #7444.

### CODE REVIEW

File: src/test/reporters/list.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ class ListReporter extends BaseReporter {
         process.stdout.write('\n');
         this._lastRow++;
       }
-      process.stdout.write('    ' + colors.gray(formatTestTitle(this.config, test) + ': ') + '\n');
+      process.stdout.write('     ' + colors.gray(formatTestTitle(this.config, test) + ': ') + '\n');
```
Comment (JoelEinbinder) [inline src/test/reporters/list.ts:48]: I feel like every one of your patches changes the spaces in at least one of these reporters.

File: src/test/dispatcher.ts [hunk 2]
```diff
@@ -199,8 +224,17 @@ export class Dispatcher {
...
 
       // This job is over, we just scheduled another one.
-      doneCallback();
-    });
+      doneWithJob();
+    };
+    worker.on('done', onDone);
+
+    const onExit = () => {
+      const error = new Error('Worker process did exit unexpectedly');
```
Comment (JoelEinbinder) [inline src/test/dispatcher.ts:232]: nit
```suggestion
      const error = new Error('Worker process exited unexpectedly');
```

File: src/test/dispatcher.ts [hunk 3]
```diff
@@ -199,8 +224,17 @@ export class Dispatcher {
...
+      error.stack = error.message + '    at <unknown>';
```
Comment (JoelEinbinder) [inline src/test/dispatcher.ts:233]: Why make a stack at all here? Seems strange to invent own `<unknown>`.
```

File: tests/playwright-test/runner.spec.ts [hunk 4]
```diff
@@ -59,3 +59,19 @@ test('it should not allow a focused test when forbid-only is used', async ({ run
...
+      test('passed1', () => {});
+      test('passed2', () => {});
+      test('failed1', () => { process.exit(0); });
+      test('failed2', () => {});
+    `
+  });
+  expect(result.exitCode).toBe(1);
+  expect(result.passed).toBe(2);
+  expect(result.failed).toBe(2);
+  expect(result.output).toContain('Worker process did exit unexpectedly');
```
Comment (JoelEinbinder) [inline tests/playwright-test/runner.spec.ts:76]:
```suggestion
  expect(result.output).toContain('Worker process exited unexpectedly');
```

File: tests/playwright-test/runner.spec.ts [hunk 5]
```diff
@@ -59,3 +59,19 @@ test('it should not allow a focused test when forbid-only is used', async ({ run
...
 });
+
+test('it should not hang and report results when worker process suddenly exits', async ({ runInlineTest }) => {
+  const result = await runInlineTest({
+    'a.spec.js': `
+      const { test } = pwt;
+      test('passed1', () => {});
+      test('passed2', () => {});
+      test('failed1', () => { process.exit(0); });
+      test('failed2', () => {});
```
Comment (JoelEinbinder) [inline tests/playwright-test/runner.spec.ts:70]: I'm surprised this one is reported as failed. I feel like that would mess with my flakiness dashboard if one test can cause everything after it to be marked as failed.

File: tests/playwright-test/max-failures.spec.ts [hunk 6]
```diff
@@ -79,3 +79,37 @@ test('max-failures should work with retries', async ({ runInlineTest }) => {
...
+      });
+    `,
+    'b.spec.js': `
+      const { test } = pwt;
+      test('passed short', async () => {
+        await new Promise(f => setTimeout(f, 100));
+      });
+      test('interrupted counts as skipped', async () => {
+        console.log('\\n%%interrupted');
+        await new Promise(f => setTimeout(f, 10000));
```
Comment (JoelEinbinder) [inline tests/playwright-test/max-failures.spec.ts:101]: can we make these a bit smaller numbers. I'd really like to avoid a 10 second wait here

**Review by JoelEinbinder — APPROVED** [review]

File: src/test/dispatcher.ts [hunk 7]
```diff
@@ -299,7 +339,7 @@ export class Dispatcher {
     if (!maxFailures || this._failureCount <= maxFailures)
       this._reporter.onTestEnd(test, result);
     if (maxFailures && this._failureCount === maxFailures)
-      this._isStopped = true;
+      this.stop().catch(e => {});
```
Comment (JoelEinbinder) [inline src/test/dispatcher.ts:342]: Can we make sure `stop` is idempotent. It looks like we can send multiple `stop` messages to a worker with this patch.

**Review by JoelEinbinder — APPROVED** [review]

File: tests/playwright-test/runner.spec.ts (hunk 5 above)
Comment (dgozman) [reply tests/playwright-test/runner.spec.ts:70]: Yeah, we should think about this and maybe figure out a better strategy.
