### PR TITLE
fix(pause): ignore `page.pause` on the server

### LINKED ISSUE #23051: [Feature] Disable pause() when running playwright tests on remote browsers
Let us know what functionality you'd like to see in Playwright and what your use case is.

Sometimes 'pause()' is left unintentionally in the code. When the tests are run on remote browser, they don't get executed. 
If tests  are run on remote browser, automatically disable pause()

Do you think others might benefit from this as well?
Yes

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #23051.

### CODE REVIEW

File: packages/playwright-core/src/client/page.ts [hunk 1]
```diff
@@ -681,6 +681,8 @@ export class Page extends ChannelOwner<channels.PageChannel> implements api.Page
   async pause() {
     if (require('inspector').url())
       return;
+    if (this._connection.isRemote())
+      return;
```
Comment (gskierk) [inline packages/playwright-core/src/client/page.ts:685]: Wouldn't any console.log about skipped execution be helpful in this case? Then the user will know that there are some unexpected pauses in the code.

**Review by yury-s — APPROVED** [review]

**Review by pavelfeldman — APPROVED** [review]
