### PR TITLE
fix(electron): allow launching with spaces in path

### LINKED ISSUE #30755: [Regression]: Playwright 1.44 cannot start Electron application with path contains spaces (Windows)
### Version

1.44.0

### Steps to reproduce

1. Clone this repository https://github.com/c3er/electron-playwright-issue
2. Install dependencies: `npm install`
3. Run test: `npm run test`

### Expected behavior

Test passes. If the test is executed on the desktop, the application window flickers.

### Actual behavior

Test fails with this error message:

```
  Sample integration test
    1) "before all" hook for "opens a window"
    2) "after all" hook for "opens a window"


  0 passing (22ms)
  2 failing

  1) Sample integration test
       "before all" hook for "opens a window":
     electron.launch: Process failed to launch!
      at async startApp (test\integration.spec.js:10:17)
      at async Context.<anonymous> (test\integration.spec.js:26:39)

  2) Sample integration test
       "after all" hook for "opens a window":
     TypeError: Cannot read properties of null (reading 'close')
      at Context.<anonymous> (test\integration.spec.js:28:33)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

### Additional context

The same test works fine with Playwright 1.43.1. If you change the version in the `package.json` and reinstall the dependencies, the test passes.

The bug seems only to occur on Windows. On macOS, it works fine. I didn't try Linux.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 47.42 GB / 63.90 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\Christian\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
  npmPackages:
    playwright: 1.44.0 => 1.44.0
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/30755

### CODE REVIEW

File: packages/playwright-core/src/server/electron/electron.ts [hunk 1]
```diff
@@ -195,6 +195,20 @@ export class Electron extends SdkObject {
...
+      let shell = false;
+      if (process.platform === 'win32') {
+        // On Windows in order to run .cmd files, shell: true is required.
+        // https://github.com/nodejs/node/issues/52554
+        shell = true;
+        // On Windows, we need to quote the executable path if it has spaces.
+        if (command.includes(' '))
+          command = `"${command}"`;
+        // On Windows, we need to quote the arguments if they have spaces.
+        electronArguments.forEach((arg, index) => {
```
Comment (dgozman) [inline packages/playwright-core/src/server/electron/electron.ts:207]: nit: I'd use a `map()` function here

File: packages/playwright-core/src/server/electron/electron.ts [hunk 2]
```diff
@@ -195,6 +195,20 @@ export class Electron extends SdkObject {
         // Packaged apps might have their own command line handling.
         electronArguments.unshift('-r', require.resolve('./loader'));
       }
+      let shell = false;
+      if (process.platform === 'win32') {
+        // On Windows in order to run .cmd files, shell: true is required.
+        // https://github.com/nodejs/node/issues/52554
+        shell = true;
+        // On Windows, we need to quote the executable path if it has spaces.
+        if (command.includes(' '))
```
Comment (dgozman) [inline packages/playwright-core/src/server/electron/electron.ts:204]: Let's quote all of them all the time, seems to be safer.

**Review by dgozman — APPROVED** [review]
