### PR TITLE
fix(oopif): get response body from adopting frame

### LINKED ISSUE #20809: [BUG] Intercepting response body from oopif throws error
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux
- Node.js version: 18.4.0
- Browser: Chromium
- Extra: n/a

**Code Snippet**
```javascript
import { test } from '@playwright/test';

test('route can access response body of oopif requests', async ({ page }) => {
  await page.on('response', async response => console.log(await response.body()));
  await page.goto(server.PREFIX + '/dynamic-oopif.html');
});
```
In this case dynamic-oopif.html is the standard playwright test file. This also reproduces for a simple static page with an oopif like:
`<html><body><iframe src="https://example.com/" width="400" height="400"></body></html>`

**Describe the bug**

Intercepting the response body of the out-of-process iframe results in this error:
`response.body: Protocol error (Network.getResponseBody): No resource with given identifier found`

For some reason this seems to work in _headless_, but running this test headed throws.

I've seen a few similar issues that mention there's sometimes a race condition where the Network stack will dispose of response body on a redirect, but there is no redirect here. Am I missing something obvious?

Thanks!

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/20809

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crNetworkManager.ts [hunk 1]
```diff
@@ -474,6 +476,7 @@ class InterceptableRequest {
   readonly _wallTime: number;
   private _route: RouteImpl | null;
   private _redirectedFrom: InterceptableRequest | null;
+  _adoptingOopifSession: CRSession | undefined;
```
Comment (dgozman) [inline packages/playwright-core/src/server/chromium/crNetworkManager.ts:479]: nit: I'd rather make this `owningNetworkManager: CRNetworkManager`.

File: tests/library/chromium/oopif.spec.ts [hunk 2]
```diff
@@ -336,6 +336,16 @@ it('should not throw on exposeFunction when oopif detaches', async ({ page, brow
   expect(await page.evaluate(() => (window as any).myFunc())).toBe(2022);
 });
 
+it.only('should intercept response body from oopif', async function({ page, browser, server }) {
```
Comment (dgozman) [inline tests/library/chromium/oopif.spec.ts:339]:
```suggestion
it('should intercept response body from oopif', async function({ page, browser, server }) {
```

File: tests/library/chromium/oopif.spec.ts [hunk 3]
```diff
@@ -336,6 +336,16 @@ it('should not throw on exposeFunction when oopif detaches', async ({ page, brow
...
+  const [response] = await Promise.all([
+    page.waitForResponse('**/grid.html'),
+    page.goto(server.PREFIX + '/dynamic-oopif.html')
+  ]);
+  console.log('XXX');
```
Comment (dgozman) [inline tests/library/chromium/oopif.spec.ts:344]:
```suggestion
```

**Review by dgozman — APPROVED** [review]
