### PR TITLE
fix(navigation): do not count random failures as navigation cancel

### LINKED ISSUE #1044: [REGRESSION]: Webkit multiple page navigations
**Context:**
- GOOD Playwright Version: [0.10.0]
- BAD Playwright Version: [0.11.0]
- Operating System: [Mac]

**Code Snippet**
Using this code to navigate multiple pages:
```javascript
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('https://whatismybrowser.com/')
    const text = await page.$eval('.guides a', el => el.text)
    await page.goto('http://google.com/')
    const title = await page.title()
    await page.goto('http://github.com/')
    const github = await page.title()
    console.log(text, title, github)
    await browser.close();
})();
```

**Describe the bug**
It just ok for other browsers: **chromium** and **firefox**
It was ok for **0.10.0**, but for **0.11.0** I got: 
```
(node:4808) UnhandledPromiseRejectionWarning: Error: While navigating to http://google.com/: Navigation interrupted by another one
```

### PR DESCRIPTION
**Pull request by dgozman**
In WebKit, we sometimes get the following:
- page starts a navigation in some frame;
- we issue page.goto();
- new navigation commits;
- old page is still alive and cancels the frame navigation;
- while waiting for 'Page.frameNavigated' on the frontend from the new target, we receive 'Browser.provisionalLoadFailed' for the frame navigation from the old target;
- this counts as cancel for the new navigation, although it was clearly a cancellation of some other navigation.

Wasn't able to write a reliable test. Any ideas are welcome! Fixes #1044.

### CODE REVIEW

File: src/frames.ts [hunk 1]
```diff
@@ -428,8 +428,11 @@ export class Frame {
     let resolve: (error: Error|void) => void;
     const promise = new Promise<Error|void>(x => resolve = x);
     const watch = (documentId: string, error?: Error) => {
-      if (documentId !== expectedDocumentId)
-        return resolve(new Error('Navigation interrupted by another one'));
+      if (documentId !== expectedDocumentId) {
+        if (!error)
```
Comment (yury-s) [inline src/frames.ts]: if (documentId !== expectedDocumentId && !error)
  error = ...

Would be slightly easier to understand I believe.

**Review by yury-s — APPROVED** [review]

**Comment by yury-s** [comment]
As for testing this, what if we have two consecutive .goto and check that first is cancelled by the second while the second succeedes? The first request could be deferred on the server for better reliability

**Review by JoelEinbinder — APPROVED** [review]
code looks good. Idk about the test.

**Comment by dgozman** [comment]
> As for testing this, what if we have two consecutive .goto and check that first is cancelled by the second while the second succeedes? The first request could be deferred on the server for better reliability

We have 'should fail when canceled by another navigation' which does exactly that. Unfortunately, the issue is slightly different here: first navigation is canceled and that mistakenly "cancels" the second one.

File: src/frames.ts (hunk 1 above)
Comment (dgozman) [reply src/frames.ts]: Reworked a bit, thanks.
