### PR TITLE
fix(library): indexedDB shouldn't stumble over `null` in Firefox

### LINKED ISSUE #35302: [Bug]:   Using IndexedDB (firebase) for shared auth use cases issue
### Version

1.51.1

### Steps to reproduce

1. Clone https://github.com/rimma-elevat/sandbox/tree/master
2. npm i
3. npx http-server -p 8000
4. npx playwright test

My app uses firebase login, which uses IndexedDB.

Observe error:
```
[firefox] › tests/auth.spec.ts:6:5 › should display logged in screen ──────────────────────────

    Error: browserContext.storageState: Unable to serialize IndexedDB: constructorImpl is undefined
    collect/<.indexedDB<@debugger eval code line 234 > eval:88:13
    promise callback*collect@debugger eval code line 234 > eval:87:98
    async*@debugger eval code line 234 > eval:91:3
    evaluate@debugger eval code:234:30
    @debugger eval code:1:44

        at collect/<.indexedDB<@debugger eval code line 234 > eval:88:13
        at promise callback*collect@debugger eval code line 234 > eval:87:98
        at async*@debugger eval code line 234 > eval:91:3
        at evaluate@debugger eval code:234:30
        at @debugger eval code:1:44
        at Object.exports.test._test.test.extend.workerStorageState.scope (/Users/rimma/playwright-sandbox/tests/fixtures.ts:37:28)


```

### Expected behavior

Expect to see no error and ability to reuse auth stored in fixtures across the unit tests.

### Actual behavior

Error: browserContext.storageState: Unable to serialize IndexedDB: constructorImpl is undefined

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 1.21 GB / 18.00 GB
  Binaries:
    Node: 20.18.2 - ~/.nvm/versions/node/v20.18.2/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.2/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.51.1 => 1.51.1
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Resolves https://github.com/microsoft/playwright/issues/35302. We were missing a nullability check, and TypeScript didn't catch it because the type was "any".

### CODE REVIEW

File: packages/playwright-core/src/server/storageScript.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export async function collect(serializers: ReturnType<typeof source>, isFirefox:
       const ctor = v?.constructor;
       if (isFirefox) {
         const constructorImpl = ctor?.toString();
-        if (constructorImpl.startsWith('function Object() {') && constructorImpl.includes('[native code]'))
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/storageScript.ts:40]: Maybe:

    const constructorImpl = ctor?.toString() as string | undefined.
    if (constructorImpl?.star…
instead?

Comment (Skn0tt) [reply packages/playwright-core/src/server/storageScript.ts:40]: sounds good!

**Review by mxschmitt — APPROVED** [review]
