### PR TITLE
fix(test-runner): resolve global hooks relative to the config dir

### LINKED ISSUE #7004: [test runner] Error: Error while reading global-setup.ts: Cannot find module 'global-setup.ts'
This does not work:

```ts
const config: PlaywrightTestConfig = {
  globalSetup: 'global-setup.ts',
};
```

This works
```ts
const config: PlaywrightTestConfig = {
  globalSetup: path.join(__dirname, 'global-setup.ts'),
};
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/7004

### CODE REVIEW

**Review by aslushnikov — APPROVED** [review]

File: src/test/loader.ts [hunk 1]
```diff
@@ -77,6 +77,12 @@ export class Loader {
   private _processConfigObject(rootDir: string) {
     validateConfig(this._config);
 
+    // Resolve script hooks relative to the root dir.
+    if (this._config.globalSetup)
+      this._config.globalSetup = path.resolve(rootDir, this._config.globalSetup);
```
Comment (JoelEinbinder) [inline src/test/loader.ts:82]: I believe this should be resolved to the config file dir not to the root dir.

Comment (pavelfeldman) [reply src/test/loader.ts:82]: Root dir is the file dir (in this method :))
