### PR TITLE
fix(trace viewer): fix memory leak

### LINKED ISSUE #32336: [Bug]: Playwright UI crashes with "Out of Memory"
### Version

1.46.1

### Steps to reproduce

* have a complex website to test 
* have a testcase with 100+ test.step(...) inside and 100+ of expect and actions inside of these - in my current case, the metadata tab says: Counts - pages: 1, actions: 387, events: 223
* run the test
* after completion click and/or hover through the actions tree - it will switch through the numberous snapshots of the website on the right side
* eventually the whole Plawright UI window crashes with an "Out of Memory" Error Message.

With any test of this size it is 100% reproducible within 10 seconds of browsing through the snapshots.
image
Anmerkung 2024-08-27 121156

### Expected behavior

no crash

### Actual behavior

crash!

### Additional context

Is there a way to reduce the memory footprint of playwright? We want to use it on non-dev notebooks with only 16 GB RAM, but that seems to be impossible with our scenario. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    Memory: 5.09 GB / 31.69 GB
  Binaries:
    Node: 20.11.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 4.3.1 - ~\scoop\apps\nodejs-lts\current\bin\yarn.CMD
    npm: 10.2.4 - ~\scoop\apps\nodejs-lts\current\npm.CMD
```

### PR DESCRIPTION
**Pull request by Skn0tt**
In the `visit` method, we currently cache the rendered HTML for every walked node. This re-use works well for traces that consist mostly of references to earlier snapshots.
But for traces that don't share much, this is a large memory overhead and leads to the memory crash documented in https://github.com/microsoft/playwright/issues/32336. For the algocracks amongst you, the current memory usage for an html tree $h$ is $\mathcal{O}(|h| * \text{height}(h))$.

This PR removes that cache from the nodes and replaces it with a snapshot-level cache, fixing the memory crash.
Traces *without* reference should not see a performance impact from this.
Traces *with* references will have slower initial rendering, but re-rendering maintains speed because of the snapshot-level cache.

Closes https://github.com/microsoft/playwright/issues/32336

### CODE REVIEW

File: packages/trace-viewer/src/snapshotRenderer.ts [hunk 1]
```diff
@@ -25,6 +25,34 @@ function isSubtreeReferenceSnapshot(n: NodeSnapshot): n is SubtreeReferenceSnaps
...
+    // reinserting makes this the least recently used entry
+    cache.delete(key);
+    cache.set(key, value);
+    return value;
+  }
+
+
+  const result = compute();
+
+  while (cacheSize + result.length > CACHE_SIZE) {
```
Comment (dgozman) [inline packages/trace-viewer/src/snapshotRenderer.ts:44]: To avoid npe when `result.length > CACHE_SIZE`.

```suggestion
  while (cache.size && cacheSize + result.length > CACHE_SIZE) {
```

File: packages/trace-viewer/src/snapshotRenderer.ts [hunk 2]
```diff
@@ -25,6 +25,34 @@ function isSubtreeReferenceSnapshot(n: NodeSnapshot): n is SubtreeReferenceSnaps
   return Array.isArray(n) && Array.isArray(n[0]);
 }
 
+let cacheSize = 0;
+const cache = new Map<SnapshotRenderer, string>();
+const CACHE_SIZE = 300000000; // 300mb
+
+function cacheAndReturn(key: SnapshotRenderer, compute: () => string): string {
```
Comment (dgozman) [inline packages/trace-viewer/src/snapshotRenderer.ts:32]: nit: now that it's LRU, I'd call this something like `lruCache(...)`.

File: packages/trace-viewer/src/snapshotRenderer.ts [hunk 3]
```diff
@@ -25,6 +25,34 @@ function isSubtreeReferenceSnapshot(n: NodeSnapshot): n is SubtreeReferenceSnaps
...
+    return value;
+  }
+
+
+  const result = compute();
+
+  while (cacheSize + result.length > CACHE_SIZE) {
+    const first = cache.keys().next().value;
+    cacheSize -= cache.get(first)!.length;
+    cache.delete(first);
```
Comment (dgozman) [inline packages/trace-viewer/src/snapshotRenderer.ts:47]:
```suggestion
    const [firstKey, firstValue] = cache.entries().next().value;
    cacheSize -= firstValue.length;
    cache.delete(firstKey);
```

**Review by dgozman — APPROVED** [review]

File: packages/trace-viewer/src/snapshotRenderer.ts [hunk 4]
```diff
@@ -25,6 +25,34 @@ function isSubtreeReferenceSnapshot(n: NodeSnapshot): n is SubtreeReferenceSnaps
   return Array.isArray(n) && Array.isArray(n[0]);
 }
 
+let cacheSize = 0;
+const cache = new Map<SnapshotRenderer, string>();
+const CACHE_SIZE = 300000000; // 300mb
```
Comment (mxschmitt) [inline packages/trace-viewer/src/snapshotRenderer.ts:30]:
```suggestion
const CACHE_SIZE = 300_000_000; // 300mb
```
nit
