### PR TITLE
fix(ui-mode/tv): do not open new tab on macOS

### LINKED ISSUE #9434: [BUG] clicking the Playwright icon in the dock launches a blank Chromium window on macOS
**Context:**
- Playwright Version: 1.15.1
- Operating System: macOS
- Node.js version: 14.17.1

**Describe the bug**

When clicking the macOS dock icon for the Playwright trace viewer or inspector, it launches a blank Chromium page.

https://user-images.githubusercontent.com/25914066/136846916-8e47a888-1e6f-49a8-a152-35e9d5570d92.mov

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/9434

### CODE REVIEW

File: packages/playwright-core/src/server/browserType.ts [hunk 1]
```diff
@@ -112,6 +113,16 @@ export abstract class BrowserType extends SdkObject {
       args,
     });
     const [page] = context.pages();
+    // Chromium on macOS opens a new tab when clicking on the dock icon.
+    // See https://github.com/microsoft/playwright/issues/9434
+    if (this._name === 'chromium' && process.platform === 'darwin') {
```
Comment (dgozman) [inline packages/playwright-core/src/server/browserType.ts:118]: Can we move this whole `launchApp` method to a separate file? We can also merge things from `crApp` into it. This way this new code wouldn't seem out of place.

**Review by dgozman — APPROVED** [review]
