### PR TITLE
fix(video): map video time to frames to reduce skew

### LINKED ISSUE #38219: [Bug]: Video recording length differs from real duration of the test run
### Version

1.56.1

### Steps to reproduce

Code do reproduce:
```python
import sys
import os

from playwright.sync_api import sync_playwright

def run(p, interval):
    browser = p.chromium.launch(headless=True)
    context = browser.new_context(
        record_video_dir=os.getcwd(),
        record_video_size={'width': 1280, 'height': 720}
    )
    page = context.new_page()
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <body>
      <div id="counter">Wait...</div>
      <script>
        const interval = {interval};
        const counter = document.getElementById('counter');
        setInterval(() => {{counter.textContent = new Date().toISOString()}}, interval);
      </script>
    </body>
    </html>
    """
    page.set_content(html_content)
    page.wait_for_timeout(5000)
    video_path = page.video.path()
    context.close()
    browser.close()

    return video_path

interval = 100
if len(sys.argv) > 1:
    interval = int(sys.argv[1])

with sync_playwright() as p:
    print(run(p, interval))
```

Run it with different refresh interval values (in milliseconds) passed by command line argument, examine video duration (I used exiftool).

### Expected behavior

The video duration should be (very close to) 5 seconds, despite the change in the website refresh interval.

### Actual behavior

Different refresh intervals yields different video durations. In my environment I get extreme values for intervals ~31ms and ~57ms:
```shell
$ python3 test.py 31
XXXXXXXX.webm
$ exiftool -Duration XXXXXXXX.webm
Duration                        : 00:00:06.440000000
$ python3 test.py 57
YYYYYYYY.webm
$ exiftool -Duration YYYYYYYY.webm
Duration                        : 00:00:03.480000000
```

### Additional context

This is another approach to report (and hopefully address) this problem. The previous issues (#9611 and #35776) have unfortunately been closed. I am dereminetd to make it happend and will help as much I can in the process. I am running patched version of pw in production (~120k playwright test runs per day) without an issue for last 4 years. I will (re)submit PR with fix shortly.

### Environment

```shell
System:
    OS: macOS 15.7.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.64 GB / 64.00 GB
  Binaries:
    Node: 25.1.0 - /opt/homebrew/bin/node
    npm: 11.6.2 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/38219

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/videoRecorder.ts [hunk 1]
```diff
@@ -122,17 +122,20 @@ export class VideoRecorder {
     if (this._isStopped)
       return;
 
-    if (this._lastFrameBuffer) {
-      const durationSec = timestamp - this._lastFrameTimestamp;
-      const repeatCount = Math.max(1, Math.round(fps * durationSec));
+    if (!this._firstFrameTimestamp)
+      this._firstFrameTimestamp = timestamp;
+
+    const frameNumber = Math.floor((timestamp - this._firstFrameTimestamp) * fps);
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/videoRecorder.ts:128]: You may end up losing frames if you always round down.

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/server/chromium/videoRecorder.ts [hunk 2]
```diff
@@ -148,9 +151,12 @@ export class VideoRecorder {
...
 
   async stop() {
-    if (this._isStopped)
+    if (this._isStopped || !this._lastFrame)
       return;
-    this.writeFrame(Buffer.from([]), this._lastFrameTimestamp + (monotonicTime() - this._lastWriteTimestamp) / 1000);
+    // Pad with at least 1s of the last frame in the end for convenience.
+    // This also ensures non-empty videos with 1 frame.
+    const addTime = Math.max((monotonicTime() - this._lastWriteNodeTime) / 1000, 1);
+    this.writeFrame(Buffer.from([]), this._lastFrame.timestamp + addTime);
```
Comment (gpiszczek) [inline packages/playwright-core/src/server/chromium/videoRecorder.ts:159]: Can you provide a reasoning behind this, please? I do not see benefits but on the other hand it breaks synchronization of video with test run.

I am a little bit surprised by this change, I was trying to push change to add delay at the beginning of recording, which would result in better synchronization (https://github.com/microsoft/playwright/pull/38220/commits/62bae71ac0fe07898b6ce43241432428b8e47361). In first try @yury-s (https://github.com/microsoft/playwright/pull/10145#discussion_r747680654) argued against it as making video longer (we are talking about hunderds of millis at most). In the second try it was silently ignored.

Now you added 1s of padding at the end of EVERY recording just like that.

Can you rethink this change, please?
