### PR TITLE
fix(trace-viewer): prevent browser snapshot from moving out of bounds on host resize

### LINKED ISSUE #38024: [Bug]: Snapshot container not fully visible when made smaller
### Version

1.56.1

### Steps to reproduce

1. Go to https://trace.playwright.dev/?trace=https://demo.playwright.dev/reports/todomvc/data/fa874b0d59cdedec675521c21124e93161d66533.zip
2. Resize the bottom pane such that the snapshot gets smaller

### Expected behavior

To see the full snapshot

### Actual behavior

Bottom of snapshot gets partially hidden behind the bottom pane

Image

### Additional context

_No response_

### Environment

```shell
System:
  OS: Linux 6.6 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
  CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
  Memory: 10.39 GB / 23.47 GB
  Container: Yes
Binaries:
  Node: 22.15.1 - /usr/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.9.2 - /usr/bin/npm
  pnpm: 10.15.0 - /usr/bin/pnpm
npmPackages:
  @playwright/test: ^1.56.0 => 1.56.0
```

### PR DESCRIPTION
**Pull request by agg23**
Fixes #38024

Ensure browser snapshots never move out of bounds in the negative X and Y directions. Additionally prevents the browser from collapsing into an infinitely small box; at the absolute min size, it will overflow offscreen to the positive X, Y.

Screenshot 2025-10-29 at 7 46 46 AM

### CODE REVIEW

File: packages/trace-viewer/src/ui/snapshotTab.tsx [hunk 1]
```diff
@@ -187,33 +187,45 @@ export const SnapshotView: React.FunctionComponent<{
   </div>;
 };
 
+const SNAPSHOT_WRAPPER_PADDING = 10 * 2;
```
Comment (pavelfeldman) [inline packages/trace-viewer/src/ui/snapshotTab.tsx]: we use `const kCamelCase`

File: packages/trace-viewer/src/ui/snapshotTab.tsx [hunk 2]
```diff
@@ -187,33 +187,45 @@ export const SnapshotView: React.FunctionComponent<{
...
 
-  const renderedBrowserFrameSize = {
+  const renderedBrowserExpectedFrameSize = {
     width: Math.max(snapshotContainerSize.width, 480),
-    height: Math.max(snapshotContainerSize.height + windowHeaderHeight, 320),
+    height: Math.max(snapshotContainerSize.height + WINDOW_HEADER_HEIGHT, 320),
   };
 
-  const scale = Math.min(measure.width / renderedBrowserFrameSize.width, measure.height / renderedBrowserFrameSize.height, 1);
+  const actualMeasuredHeight = Math.max(measure.height - SNAPSHOT_WRAPPER_PADDING, 0);
```
Comment (pavelfeldman) [inline packages/trace-viewer/src/ui/snapshotTab.tsx]: Should we measure the right element instead?

Comment (agg23) [reply packages/trace-viewer/src/ui/snapshotTab.tsx]: We can do that. This is specifically to incorporate the inner padding that the wrapping element has. At the moment there's nothing to measure that represents that full area with the padding under consideration. We could add an element for this; it would remove the need for this line and the hardcoded padding constant, but it's also extra DOM just for this use case. I am fine with it either way.

**Review by pavelfeldman — APPROVED** [review]
