### PR TITLE
fix(trace): respect dark mode in blank snapshot

### LINKED ISSUE #39201: [Bug]: [Accessability]: playwright UI displays a big white box on startup even in high constrast black
### Version

latest 2026-02-09

### Steps to reproduce

1. Have high constrast black
2. Install blank template
3. npx playwright test --ui

Image

I down scaled this image so it doesn't mess with my own ability to view the bug report. The offender is the big white box; due to the nature of my eye problem I cannot see anything around it.

### Expected behavior

sorry; first time trying to use playwright I have no idea what it should do

### Actual behavior

big white box appeared despite system being set to high constrast black

### Additional context

https://en.wikipedia.org/wiki/Photophobia

### Environment

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 11.72 GB / 31.95 GB
  Binaries:
    Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @playwright/test: ^1.58.2 => 1.58.2

-- High Contrast Black enabled
```

### PR DESCRIPTION
**Pull request by Skn0tt**
closes https://github.com/microsoft/playwright/issues/39201

before: Screenshot 2026-02-10 at 10 34 47
after: Screenshot 2026-02-10 at 10 34 18

### CODE REVIEW

File: packages/playwright-core/src/utils/isomorphic/trace/snapshotRenderer.ts [hunk 1]
```diff
@@ -639,3 +639,5 @@ function escapeURLsInStyleSheet(text: string): string {
   };
   return text.replace(urlToEscapeRegex1, replacer).replace(urlToEscapeRegex2, replacer);
 }
+
+export const blankSnapshotUrl = 'data:text/html;base64,' + btoa(`<body></body><style>body { color-scheme: light dark; background: light-dark(white, #333) }</style>`);
```
Comment (dgozman) [inline packages/playwright-core/src/utils/isomorphic/trace/snapshotRenderer.ts:643]: I wonder why base64 is needed here? Seems like a nice html snippet.

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/utils/isomorphic/trace/snapshotRenderer.ts (hunk 1 above)
Comment (Skn0tt) [reply packages/playwright-core/src/utils/isomorphic/trace/snapshotRenderer.ts:643]: because of the `,` in `light-dark()` - it truncated behind that. i was a little surprised.
