### PR TITLE
fix(html): falsy description shouldnt crash

### LINKED ISSUE #35469: [Bug]: Page crash observed on HTML report when 0 is parsed into an annotation description
### Version

1.47.1

### Steps to reproduce

Image

Image

Conditions:
Have a test with annotation
Have description dynamically generate as to output 0 as a number (other numbers are fine)
Attempt to open the HTML report
Observe page crash

NOTE: I get that invalid data is being parsed into the annotation, but it'd be great if this case was handled. 

I have attached a barebones HTML report with the outlined state (i had to upload it as a txt)

[index.txt](https://github.com/user-attachments/files/19580991/index.txt)

### Expected behavior

It would be sick if a toString was performed, so if in the case where a number is parsed in, a string will be made anyway. Alternatively failing gracefully by throwing a warning or something would be good too. Other numbers already get handled (maybe by accident?) 

### Actual behavior

The report will not render, only a blank page will be shown when attempting to open the report

### Additional context

_No response_

### Environment

```shell
na
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/35469.

### CODE REVIEW

**Comment by Skn0tt** [comment]
They're either ignoring the red line, or their editor isn't set up properly to incorporate types. Either way, we already have a guard against this, it just doesn't work for `0` because it's falsy.

File: packages/playwright/src/reporters/html.ts [hunk 1]
```diff
@@ -503,7 +503,7 @@ class HtmlBuilder {
 
   private _serializeAnnotations(annotations: api.TestCase['annotations']): TestAnnotation[] {
     // Annotations can be pushed directly, with a wrong type.
-    return annotations.map(a => ({ type: a.type, description: a.description ? String(a.description) : a.description, location: a.location }));
+    return annotations.map(a => ({ type: a.type, description: typeof a.description === 'undefined' ? undefined : String(a.description), location: a.location }));
```
Comment (dgozman) [inline packages/playwright/src/reporters/html.ts:506]: Modern js allows to compare directly: `a.description === undefined`.

File: tests/playwright-test/reporter-html.spec.ts [hunk 2]
```diff
@@ -825,10 +825,30 @@ for (const useIntermediateMergeReport of [true, false] as const) {
       expect(result.passed).toBe(1);
 
       await showReport();
-      await page.click('text=annotated test');
+      await page.getByRole('link', { name: 'annotated test' }).click();
       await expect(page.locator('.test-case-annotation')).toHaveText('issue: I am not interested in this test');
     });
 
+    test('should not crash on falsy non-string annotation', async ({ runInlineTest, page, showReport }) => {
```
Comment (dgozman) [inline tests/playwright-test/reporter-html.spec.ts:832]: When adding a new test, please add an "issue" annotation whenever available.

Comment (Skn0tt) [reply tests/playwright-test/reporter-html.spec.ts]: How ironic that I forget the annotation on a PR about annotations

**Review by dgozman — APPROVED** [review]
