### PR TITLE
fix(ct): ct ID clash on similar imports

### LINKED ISSUE #30085: [Regression]: Component IDs clash with relative imports
### Last Good Version

1.41

### First Bad Version

1.42

### Steps to reproduce

```diff
diff --git a/tests/components/ct-react-vite/tests/repro/one/Component.tsx b/tests/components/ct-react-vite/tests/repro/one/Component.tsx
new file mode 100644
index 000000000..5b0e60d4b
--- /dev/null
+++ b/tests/components/ct-react-vite/tests/repro/one/Component.tsx
@@ -0,0 +1,3 @@
+export default () => {
+    return "one"
+}
diff --git a/tests/components/ct-react-vite/tests/repro/one/test.spec.tsx b/tests/components/ct-react-vite/tests/repro/one/test.spec.tsx
new file mode 100644
index 000000000..d5f3bb735
--- /dev/null
+++ b/tests/components/ct-react-vite/tests/repro/one/test.spec.tsx
@@ -0,0 +1,7 @@
+import { test, expect } from '@playwright/experimental-ct-react';
+import Component from './Component';
+
+test('foo', async ({ mount }) => {
+  const component = await mount(<Component/>);
+  await expect(component).toHaveText('one');
+});
diff --git a/tests/components/ct-react-vite/tests/repro/two/Component.tsx b/tests/components/ct-react-vite/tests/repro/two/Component.tsx
new file mode 100644
index 000000000..3bf222eb4
--- /dev/null
+++ b/tests/components/ct-react-vite/tests/repro/two/Component.tsx
@@ -0,0 +1,3 @@
+export default () => {
+    return "two"
+}
diff --git a/tests/components/ct-react-vite/tests/repro/two/test.spec.tsx b/tests/components/ct-react-vite/tests/repro/two/test.spec.tsx
new file mode 100644
index 000000000..061f34ea1
--- /dev/null
+++ b/tests/components/ct-react-vite/tests/repro/two/test.spec.tsx
@@ -0,0 +1,7 @@
+import { test, expect } from '@playwright/experimental-ct-react';
+import Component from './Component';
+
+test('foo', async ({ mount }) => {
+  const component = await mount(<Component/>);
+  await expect(component).toHaveText('two');
+});
```

### Expected behavior

Works

### Actual behavior

Component `two` gets rendered in `one`.

### Additional context

Regressed in https://github.com/microsoft/playwright/pull/29407.

Around here: https://github.com/microsoft/playwright/pull/29407/files#diff-8dd3534dc5013c3779edeaded71324b0dd1c1807668f3c6d9e9a1aab1c20ae91

1.42.0-alpha-2024-02-09 bad
1.42.0-alpha-2024-02-08 good
range: https://github.com/microsoft/playwright/compare/58f580dbde4d62b7001ff84b1cd5746a53eaf3c8...7a86bf4af62fe3e44a41f94c7a4ab7f645c205e1

### Environment

```shell
N/A
```

### PR DESCRIPTION
**Pull request by mxschmitt**
This restores the [best effort](https://github.com/microsoft/playwright/pull/29407/files#diff-8dd3534dc5013c3779edeaded71324b0dd1c1807668f3c6d9e9a1aab1c20ae91L152) logic if its a relativ path. 

Fixes https://github.com/microsoft/playwright/issues/30085

### CODE REVIEW

File: packages/playwright-ct-core/src/tsxTransform.ts [hunk 1]
```diff
@@ -150,7 +150,7 @@ export type ImportInfo = {
 
 export function importInfo(importNode: T.ImportDeclaration, specifier: T.ImportSpecifier | T.ImportDefaultSpecifier, filename: string): { localName: string, info: ImportInfo } {
   const importSource = importNode.source.value;
-  const idPrefix = importSource.replace(/[^\w_\d]/g, '_');
+  const idPrefix = (importSource.startsWith('.') ? path.join(path.dirname(filename), importSource) : importSource).replace(/[^\w_\d]/g, '_');
```
Comment (pavelfeldman) [inline packages/playwright-ct-core/src/tsxTransform.ts:153]:
```suggestion
  const idPrefix = path.join(filename, '..', importSource).replace(/[^\w_\d]/g, '_');
```

Comment (pavelfeldman) [reply packages/playwright-ct-core/src/tsxTransform.ts:153]: This way you'll close the MUI bug I think.

**Review by pavelfeldman — APPROVED** [review]
