### PR TITLE
fix(expect): throw better received error when no element was found

### LINKED ISSUE #29873: [Bug]:  toHaveText() fails with irrelevant error if applied to non-existing/non-visible elements
### Version

1.41.2

### Steps to reproduce

Create assertion expecting non-existing field to to have text. Ex:

```ts
test('field should be empty', async ({ page }) => {
            //case1
            await expect(page.locator('.i-do-not-exist'), 'field should be empty').toHaveText('');
            //case2
            await expect(page.locator('i-do-not-exist') , 'field should have 'abc' text').toHaveText('abc');
});     
```

### Expected behavior

the assertion should fail but signal the element do not exist instead of saying that element has '' text

### Actual behavior

case1: 

```
Locator: locator('.non-exising-element')
Expected string: ""
Received string: serializes to the same string
```

case2:

```
Error: field should have 'abc' text

    Timed out 15000ms waiting for expect(locator).toHaveText(expected)

    Locator: locator('.non-exising-element')
    Expected string: "abc"
    Received string: ""
```

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 109.13 MB / 16.00 GB
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/29873

### CODE REVIEW

File: packages/playwright-core/src/server/frames.ts [hunk 1]
```diff
@@ -1444,16 +1445,18 @@ export class Frame extends SdkObject {
...
       // Q: Why not throw upon isSessionClosedError(e) as in other places?
       // A: We want user to receive a friendly message containing the last intermediate result.
       if (js.isJavaScriptErrorInEvaluate(e) || isInvalidSelectorError(e))
         throw e;
-      const result: { matches: boolean, received?: any, log?: string[], timedOut?: boolean } = { matches: options.isNot, log: metadata.log };
-      if (lastIntermediateResult.isSet)
+      const result: { matches: boolean, received?: any, log?: string[], timedOut?: boolean, resolvedtoAnElement: boolean } = { matches: options.isNot, log: metadata.log, resolvedtoAnElement: false };
+      if (lastIntermediateResult.isSet) {
         result.received = lastIntermediateResult.received;
+        result.resolvedtoAnElement = lastIntermediateResult.resolvedtoAnElement;
```
Comment (dgozman) [inline packages/playwright-core/src/server/frames.ts:1458]: We can just update `received` here to `<element(s) not found>`.

File: packages/playwright/src/matchers/matcherHint.ts [hunk 2]
```diff
@@ -20,6 +20,14 @@ import type { Locator } from 'playwright-core';
 import type { StackFrame } from '@protocol/channels';
 import { stringifyStackFrames } from 'playwright-core/lib/utils';
 
+const kNoElementsFoundMessage = '<element(s) not found>';
+
+export function rewriteIfNoElementFound(received: any, log: string[] | undefined): any {
+  if (log?.[log.length - 1].startsWith('waiting for '))
```
Comment (dgozman) [inline packages/playwright/src/matchers/matcherHint.ts:26]: I thought you'd still set `<element(s) not found>` on the server, and check the "received" here to avoid rewriting it into something on the client-side. This way, all language ports will also get it for free.

File: packages/playwright/src/matchers/matcherHint.ts [hunk 3]
```diff
@@ -20,6 +20,7 @@ import type { Locator } from 'playwright-core';
 import type { StackFrame } from '@protocol/channels';
 import { stringifyStackFrames } from 'playwright-core/lib/utils';
 
+
```
Comment (mxschmitt) [inline packages/playwright/src/matchers/matcherHint.ts:23]:
```suggestion
```

File: packages/playwright-core/src/server/injected/injectedScript.ts [hunk 4]
```diff
@@ -1166,7 +1166,7 @@ export class InjectedScript {
           throw this.createStacklessError('Element is not a checkbox');
         if (elementState === 'error:notconnected')
           throw this.createStacklessError('Element is not connected');
-        return { received: elementState, matches: elementState };
+        return { matches: elementState };
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/injected/injectedScript.ts:1169]: seems like this was unused or at least not covered with a test?

File: packages/playwright/src/matchers/toMatchText.ts [hunk 5]
```diff
@@ -69,11 +69,11 @@ export async function toMatchText(
       typeof expected === 'string'
         ? matcherHint(this, receiver, matcherName, 'locator', undefined, matcherOptions, timedOut ? timeout : undefined) +
         `Expected ${stringSubstring}: not ${this.utils.printExpected(expected)}\n` +
-        `Received string: ${printReceivedStringContainExpectedSubstring(
+        `Received string: ${receivedString.indexOf(expected) !== -1 ? printReceivedStringContainExpectedSubstring(
```
Comment (mxschmitt) [inline packages/playwright/src/matchers/toMatchText.ts:72]: `printReceivedStringContainExpectedSubstring` behaves weirdly if you pass:

```
 receivedString = something 
receivedString.indexOf(expected) = -1,
expected.length = something long
```

to it. Probably because it was intended only for the matching scenario.

Comment (dgozman) [reply packages/playwright/src/matchers/toMatchText.ts:72]: - Might as well do `Received:` instead of `Received string:`
- We should cover the regex case below as well.

File: packages/playwright-core/src/server/injected/injectedScript.ts (hunk 4 above)
Comment (dgozman) [reply packages/playwright-core/src/server/injected/injectedScript.ts:1169]: This sounds strange. If it's not used in Node.js, it is probably used in other languages.

File: packages/playwright-core/src/server/frames.ts [hunk 6]
```diff
@@ -1382,6 +1382,8 @@ export class Frame extends SdkObject {
     // Library mode special case for the expect errors which are return values, not exceptions.
     if (result.matches === options.isNot)
       metadata.error = { error: { name: 'Expect', message: 'Expect failed' } };
+    if (result.log?.[result.log.length - 1].startsWith('waiting for '))
```
Comment (dgozman) [inline packages/playwright-core/src/server/frames.ts:1385]: Instead of relying on the logs, can we do this at the place where we actually know that element was not found?

File: packages/playwright-core/src/server/injected/injectedScript.ts (hunk 4 above)
Comment (mxschmitt) [reply packages/playwright-core/src/server/injected/injectedScript.ts]: will keep it for now.

File: tests/page/matchers.misc.spec.ts [hunk 7]
```diff
@@ -23,3 +24,41 @@ it('should outlive frame navigation', async ({ page, server }) => {
   }, 1000);
   await expect(page.locator('.box').first()).toBeEmpty();
 });
+
+it('should print no-locator-resolved error when locator matcher did not resolve to any element', async ({ page, server }) => {
+  const myLocator = page.locator('.nonexisting');
+  const expectWithShortLivingTimeout = expect.configure({ timeout: 10 });
+  const locatorMatchers = [
```
Comment (dgozman) [inline tests/page/matchers.misc.spec.ts:31]: This test is not checking `.not.toHaveText()` that has changed extensively in the code. I'd recommend trimming this list to just a few, but add `.not` and any other interesting variants.

File: packages/playwright/src/matchers/toMatchText.ts [hunk 8]
```diff
@@ -64,39 +64,30 @@ export async function toMatchText(
...
+  const notFound = received === kNoElementsFoundError;
+  const message = () => {
+    if (pass) {
+      if (typeof expected === 'string') {
+        if (notFound)
+          return messagePrefix + `Expected ${stringSubstring}: not ${this.utils.printExpected(expected)}\nReceived: ` + received + callLogText(log);
+        const printedReceived = printReceivedStringContainExpectedSubstring(receivedString, receivedString.indexOf(expected), expected.length);
+        return messagePrefix + `Expected ${stringSubstring}: not ${this.utils.printExpected(expected)}\nReceived string: ${printedReceived}` + callLogText(log);
+      } else {
+        if (notFound)
```
Comment (dgozman) [inline packages/playwright/src/matchers/toMatchText.ts:77]: It seems like you can move `notFound` case outside of both branches.

Comment (mxschmitt) [reply packages/playwright/src/matchers/toMatchText.ts:77]: The expected label seems different.

File: tests/page/matchers.misc.spec.ts (hunk 7 above)
Comment (mxschmitt) [reply tests/page/matchers.misc.spec.ts:31]: Would you keep: one boolean matcher and one text matcher for each branch?

Comment (dgozman) [reply tests/page/matchers.misc.spec.ts:31]: Yeah, we should cover every branch, those are easy to mess up.

File: tests/page/matchers.misc.spec.ts [hunk 9]
```diff
@@ -23,3 +24,23 @@ it('should outlive frame navigation', async ({ page, server }) => {
...
+    () => expectWithShortLivingTimeout(myLocator).toBeAttached(),                 // Boolean matcher
+    () => expectWithShortLivingTimeout(myLocator).toHaveJSProperty('abc', 'abc'), // Equal matcher
+    () => expectWithShortLivingTimeout(myLocator).not.toHaveText('abc'),          // Text matcher - pass / string
+    () => expectWithShortLivingTimeout(myLocator).not.toHaveText(/abc/),          // Text matcher - pass / RegExp
+    () => expectWithShortLivingTimeout(myLocator).toContainText('abc'),           // Text matcher - fail
```
Comment (dgozman) [inline tests/page/matchers.misc.spec.ts:36]: Perhaps test both fail/string and fail/RegExp?

File: tests/page/matchers.misc.spec.ts [hunk 10]
```diff
@@ -23,3 +24,23 @@ it('should outlive frame navigation', async ({ page, server }) => {
...
+  ];
+  for (const matcher of locatorMatchers) {
+    await it.step(matcher.toString(), async () => {
+      const error = await matcher().catch(e => e);
+      expect(error).toBeInstanceOf(Error);
+      expect(error.message).toContain(`waiting for locator('.nonexisting')`);
+      expect(stripAnsi(error.message)).toMatch(/Received:  ?"?<element\(s\) not found>/);
```
Comment (dgozman) [inline tests/page/matchers.misc.spec.ts:43]: Now that we only have 6 cases, maybe inlining them with exact expected error message would be easier to understand?

**Review by dgozman — APPROVED** [review]

File: tests/page/matchers.misc.spec.ts (hunk 9 above)
Comment (mxschmitt) [reply tests/page/matchers.misc.spec.ts]: (Same branch, but sure added it)

File: tests/page/matchers.misc.spec.ts (hunk 10 above)
Comment (mxschmitt) [reply tests/page/matchers.misc.spec.ts:44]: Not a huge fan, since it would make the test much larger. This underlines our motivation that the `waiting for locator` and `Received` value should be displayed in all the scenarios.
