### PR TITLE
fix(mcp): make verify tools work in iframes

### LINKED ISSUE #1394: Bug: browser_verify_element_visible and browser_verify_text_visible cannot locate elements within iframe
### Summary
For most playwright tools (click, enter text, etc.) I am able to get these operations to work fine with elements on the page contained within an iframe. However, for the playwright mcp tools browser_verify_element_visible and browser_verify_text_visible, I am not able to get them to locate text or elements within an iframe on the page using latest mcp server version. Example repro is below, is there a way to add support for these tools to locate text or elements within iframes on the page to be inline with other playwright mcp tools along with returning the corresponding code that those actions map to?

#### Html Sample
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example webpage</title>
</head>
<body>
    <h1>Outer frame text</h1>
    <iframe srcdoc="<html><body><h1>Inner iframe</h1></body></html>" width="400" height="200">
    </iframe>
</body>
</html>
```

#### Playwright MCP Snapshot of above page
```yaml
- generic [active] [ref=e1]:
  - heading "Outer frame text" [level=1] [ref=e2]
  - iframe [ref=e3]:
    - heading "Inner iframe" [level=1] [ref=f2e2]
```

Given above, i'd expect the two example tool calls below to work however they fail:

browser_verify_text_visible with input "Inner iframe" as text param gives result error:
Text not found

browser_verify_element_visible with input role 'heading' and accessibleName 'Inner iframe' gives error result:
Element with role "heading" and accessible name "Inner iframe" not found

If i search for the text 'Outer frame text' or the element 'heading' and name 'Outer frame text' those are able to resolve fine within the tools.

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright-mcp/issues/1394

### CODE REVIEW

File: packages/playwright/src/mcp/browser/tools/verify.ts [hunk 1]
```diff
@@ -33,14 +33,16 @@ const verifyElement = defineTabTool({
...
   handle: async (tab, params, response) => {
-    const locator = tab.page.getByRole(params.role as any, { name: params.accessibleName });
-    if (await locator.count() === 0) {
-      response.addError(`Element with role "${params.role}" and accessible name "${params.accessibleName}" not found`);
-      return;
+    for (const frame of tab.page.frames()) {
+      const locator = frame.getByRole(params.role as any, { name: params.accessibleName });
+      if (await locator.count() > 0) {
+        const resolved = await locator._resolveForCode();
+        response.addCode(`await expect(page.${resolved}).toBeVisible();`);
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/tools/verify.ts:40]: should be resolved.first() in case of count > 1, otherwise it will throw

File: packages/playwright/src/mcp/browser/tools/verify.ts [hunk 2]
```diff
@@ -57,14 +59,16 @@ const verifyText = defineTabTool({
...
   handle: async (tab, params, response) => {
-    const locator = tab.page.getByText(params.text).filter({ visible: true });
-    if (await locator.count() === 0) {
-      response.addError('Text not found');
-      return;
+    for (const frame of tab.page.frames()) {
+      const locator = frame.getByText(params.text).filter({ visible: true });
+      if (await locator.count() > 0) {
+        const resolved = await locator._resolveForCode();
+        response.addCode(`await expect(page.${resolved}).toBeVisible();`);
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/tools/verify.ts:66]: ditto

**Review by yury-s — APPROVED** [review]

File: packages/playwright/src/mcp/browser/tools/verify.ts (hunk 1 above)
Comment (pavelfeldman) [reply packages/playwright/src/mcp/browser/tools/verify.ts:40]: Throwing would be intended behavior.
