### PR TITLE
fix(esm): prevent ESM loading deadlock in certain import chains

### LINKED ISSUE #35706: [Bug]: 1.52.0 hangs on "load tests" started or crush with out of memory
### Version

1.52.0

### Description

Playwright version 1.52.0 hangs when running tests or stops with out of memory when using `--ui`, while 1.51.1 works fine.

Logs without ui(hangs):
```
2025-04-23T12:13:13.600Z pw:test:task "apply rebaselines" started
2025-04-23T12:13:13.601Z pw:test:task "apply rebaselines" finished
2025-04-23T12:13:13.601Z pw:test:task "clear output" started
2025-04-23T12:13:13.601Z pw:test:task "clear output" finished
2025-04-23T12:13:13.601Z pw:test:task "plugin setup" started
2025-04-23T12:13:13.601Z pw:test:task "plugin setup" finished
2025-04-23T12:13:13.601Z pw:test:task "plugin setup" started
2025-04-23T12:13:13.601Z pw:webserver HTTP GET: http://localhost:3002/
2025-04-23T12:13:13.629Z pw:webserver HTTP Status: 200
2025-04-23T12:13:13.630Z pw:webserver WebServer is already available
2025-04-23T12:13:13.630Z pw:webserver Waiting for availability...
2025-04-23T12:13:13.630Z pw:webserver HTTP GET: http://localhost:3002/
2025-04-23T12:13:13.652Z pw:webserver HTTP Status: 200
2025-04-23T12:13:13.652Z pw:webserver WebServer available
2025-04-23T12:13:13.652Z pw:test:task "plugin setup" finished
2025-04-23T12:13:13.652Z pw:test:task "load tests" started
```

Logs that I somehow managed to copy before crush with `--ui`
```
2025-04-23T11:57:29.866Z pw:channel <EVENT {"guid":"","method":"__create__","params":{"type":"Playwright","initializer":{"chromium":{"guid":"browser-type@09b49a3e6fdee1d1b6b91216493aa6fe"},"firefox":{"guid":"browser-type@5c9f09c2ab5b071fee0fe20ce2b5e76e"},"webkit":{"guid":"browser-type@22ababf057e53151ad9bd0093c8a83ed"},"bidiChromium":{"guid":"browser-type@d6bccb7e0d8b0886b295b9115783d8a6"},"bidiFirefox":{"guid":"browser-type@d7b7f6786cc08f1de50145dd19526984"},"android":{"guid":"android@a6e55338a41dd14317cc897aa6bb8f8c"},"electron":{"guid":"electron@9c496dce35c3bb9a6e77acbb34071dcc"},"utils":{"guid":"localUtils"},"selectors":{"guid":"selectors@1039ec58f01782872305678583be8367"}},"guid":"Playwright"}}
node:buffer:837
    return this.utf8Slice(0, this.length);
                ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (node:buffer:837:17)
    at PipeTransport._dispatch (/home/xxx/node_modules/.pnpm/playwright-core@1.52.0/node_modules/playwright-core/lib/server/pipeTransport.js:67:57)
    at Socket.<anonymous> (/home/xxx/node_modules/.pnpm/playwright-core@1.52.0/node_modules/playwright-core/lib/server/pipeTransport.js:33:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Socket.Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```

Screenshots(is it supposed to have so many slashes?):

Image
Image

### Expected behavior

Tests should run fine.

### Actual behavior

Tests hang or crush with out of memory when `--ui` used

### Additional context

Let me know if I can debug it more precisely.

### Environment

```shell
System:
    OS: Linux 6.11 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 8845HS w/ Radeon 780M Graphics
    Memory: 5.85 GB / 14.87 GB
    Container: Yes
  Binaries:
    Node: 22.14.0 - /usr/bin/node
    npm: 10.9.2 - /usr/bin/npm
    pnpm: 10.8.0 - ~/snap/code/184/.local/share/pnpm/pnpm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
```

### PR DESCRIPTION
**Pull request by agg23**
Fixes #35706.

After a long investigation I narrowed the error condition to an ESM loading deadlock in certain import chains. When ESM imports a nested CJS package that has another CJS `require` inside, the Playwright loading process would freeze, preventing any further interaction (including `SIGINT`):

```
[ESM]
fail.spec.js
[CJS]
inner_package/require_me.js
inner_package/subdependency.js
```

The Node.js import worker sends events to our ESM loader, which then processes the load asynchronously and returns to the requesting process. Under this scenario, our `esmLoader.ts` attempts to run:

```ts
if (transformed.serializedCache)
  await transport?.send('pushToCompilationCache', { cache: transformed.serializedCache });
```

Which is a `Promise` wrapping the synchronous `MessagePort.postMessage`:

```ts
  async send(method: string, params: any) {
    return await new Promise<any>(f => {
      const id = ++this._lastId;
      this._callbacks.set(id, f);
      this._resetRef();
      this._port.postMessage({ id, method, params });
    });
  }
```

`postMessage()` does not return until the message is accepted by the other port. Since Node.js is already waiting on other work from the ESM loader (the `load` request that is awaiting `transport.send()`) we are in deadlock, and never recover.

----

Issue was bisected to be introduced with #28526 (7670fd21e2efd1118d182b1f0bc396dcbc5c4505), which is the change that introduced the modern ESM loading mechanism.

----

**EDIT:** Looking at this in-depth again after a weekend makes the cause obvious. The following are logs with comments with `NODE_DEBUG=*`:
```
// We finish the load() request for require_me.js, our first CJS package. Notice that it's an "async" response

ESM 31912: got async response from worker {
  method: 'load',
  args: [
    'file:///inner_package/require_me.js',
    {
      format: 'commonjs',
      importAttributes: [Object: null prototype] {}
    }
  ]
}

...

// Node examines the contents of the newly loaded file. It finds a require pointing at fails_require.js
// getModuleJobForRequireInImportedCJS() is called. This calls resolveSync, because we're resolving CJS.
// We ask the custom Playwright loader to resolve this file

ESM 31912: post sync message to worker {
  method: 'resolve',
  args: [
    'file:///inner_package/require_me.js',
    'file:///inner_package/fails_require.js',
    [Object: null prototype] {}
  ],
  transferList: undefined
}

// We begin waiting for the response synchronously, which blocks our runloop

ESM 31912: wait for sync response from worker {
  method: 'resolve',
  args: [
    'file:///inner_package/require_me.js',
    'file:///inner_package/fails_require.js',
    [Object: null prototype] {}
  ]
}
```

Inside of Playwright's `load`, which is called immediately after `resolve`, we call:

```ts
  if (transformed.serializedCache)
    await transport?.send('pushToCompilationCache', { cache: transformed.serializedCache });
```

`postMessage()` does not return until the message is accepted by the other port. Since Node.js is already waiting on other work from the ESM loader, we are in deadlock, and never recover.

---

See https://nodejs.org/api/module.html#caveat-in-the-asynchronous-load-hook for an explanation of:
- why esm loader is engaged for these `require` calls;
- why esm loader is incompatible with namespace imports of cjs.

### CODE REVIEW

File: packages/playwright/src/transform/esmLoader.ts [hunk 1]
```diff
@@ -72,8 +72,14 @@ async function load(moduleUrl: string, context: { format?: string }, defaultLoad
   const transformed = transformHook(code, filename, moduleUrl);
 
   // Flush the source maps to the main thread, so that errors during import() are source-mapped.
-  if (transformed.serializedCache)
-    await transport?.send('pushToCompilationCache', { cache: transformed.serializedCache });
+  // Under certain conditions with ESM -> CJS -> CJS imports, we can enter deadlock awaiting the
+  // MessagePort transfer simultaneously with the Node.js worker thread that is performing the load().
+  // Purposefully do not await
+  if (transformed.serializedCache) {
+    transport?.send('pushToCompilationCache', { cache: transformed.serializedCache })
```
Comment (dgozman) [inline packages/playwright/src/transform/esmLoader.ts:79]: Perhaps we can not await only when `format` is `commonjs` or something like that?

File: packages/playwright/src/transform/esmLoader.ts [hunk 2]
```diff
@@ -84,6 +88,32 @@ async function load(moduleUrl: string, context: { format?: string }, defaultLoad
...
+async function pushToCompilationCache(transport: PortTransport, cache: any) {
+  if (workerShouldFallbackCompilationCache) {
+    transport.send('pushToCompilationCache', { cache })
+        .catch(e => debugTest('Failed to push compilation cache', e));
+    return;
+  }
+
+  let didComplete = false;
+
+  await Promise.race([
```
Comment (dgozman) [inline packages/playwright/src/transform/esmLoader.ts:103]: Let's use `raceAgainstDeadline` here?

File: packages/playwright/src/transform/esmLoader.ts [hunk 3]
```diff
@@ -84,6 +90,23 @@ async function load(moduleUrl: string, context: { format?: string }, defaultLoad
...
+// MessagePort transfer simultaneously with the Node.js worker thread that is performing the load().
+// Attempt to await the IPC transfer, and if it takes too long, fallback to a non-awaiting transfer
+async function pushToCompilationCache(transport: PortTransport, cache: any) {
+  if (workerShouldFallbackCompilationCache) {
+    transport.send('pushToCompilationCache', { cache })
+        .catch(e => debugTest('Failed to push compilation cache', e));
+    return;
+  }
+
+  const { timedOut } = await raceAgainstDeadline(() => transport.send('pushToCompilationCache', { cache }), 1000);
```
Comment (dgozman) [inline packages/playwright/src/transform/esmLoader.ts:103]:
```suggestion
  const { timedOut } = await raceAgainstDeadline(() => transport.send('pushToCompilationCache', { cache }), monotonicTime() + 1000);
```

**Review by dgozman — APPROVED** [review]
