### PR TITLE
fix(ui): bring back the headed param

### LINKED ISSUE #33023: [Bug]: command line flag --headed has no effect in ui mode
### Version

1.48.0

### Steps to reproduce

1. set `headless: true` in playwright.config.ts
2. start playwright using `playwright test --ui --headed`
3. run a test

### Expected behavior

The test is run in headed mode, i.e. a browser window opens.

### Actual behavior

The test is run in the UI, but in headless mode, i.e. without opening a browser and without stopping at `await page.pause`.

### Additional context

In the previous version, 1.47.2 this works as expected.

Also, `playwright test --headed` does work as expected. Only `--headed` together with `--ui` seems to be ignored.

### Environment

  System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 13.63 GB / 31.01 GB
    Container: Yes
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.5.0 - ~/.local/share/pnpm/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: 1 => 1.48.0

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/33023

### CODE REVIEW

**Review by yury-s — APPROVED** [review]

**Review by dgozman — APPROVED** [review]

**Review by yury-s — APPROVED** [review]

File: packages/playwright/src/runner/testServer.ts [hunk 1]
```diff
@@ -302,10 +302,11 @@ export class TestServerDispatcher implements TestServerInterface {
       preserveOutputDir: true,
       reporter: params.reporters ? params.reporters.map(r => [r]) : undefined,
       use: {
-        ...(this._configCLIOverrides.use || {}),
-        trace: params.trace === 'on' ? { mode: 'on', sources: false, _live: true } : (params.trace === 'off' ? 'off' : undefined),
-        video: params.video === 'on' ? 'on' : (params.video === 'off' ? 'off' : undefined),
-        headless: params.headed ? false : undefined,
+        ...this._configCLIOverrides.use,
+        ...(params.trace === 'on' ? { mode: 'on', sources: false, _live: true } : {}),
```
Comment (yury-s) [inline packages/playwright/src/runner/testServer.ts:306]:
```suggestion
        ...(params.trace === 'on' ? { trace: { mode: 'on', sources: false, _live: true }} : {}),
```
