### PR TITLE
fix(mcp): respect fs-based lock file for chromium family

### LINKED ISSUE #1311: browser_navigate retry loop spawns multiple about:blank tabs when profile is locked
## Environment

- OS: macOS 14.x
- Playwright MCP: latest (via `npx @playwright/mcp@latest`)
- Client: Claude Code

## Describe the bug

When the browser profile is already in use (e.g., Chrome wasn't fully killed from a previous session), `browser_navigate` enters a retry loop that spawns 5+ `about:blank` tabs before finally throwing the "Browser is already in use" error.

## To Reproduce

1. Start a Playwright MCP session, navigate to a page
2. Kill the MCP client without calling `browser_close` (simulating a crash or forced quit)
3. Start a new MCP session and call `browser_navigate`
4. Observe: 5-6 `about:blank` tabs open in rapid succession before the error is thrown

## Expected behavior

The MCP should check if the profile is available *before* attempting to launch a browser instance. If locked, fail immediately with a clear error - don't retry in a loop that creates visible side effects.

## Current behavior

The retry loop in `browserContextFactory.ts` catches `ProcessSingleton`/`exitCode=21` errors and retries up to 5 times. Each retry appears to spawn a new tab before failing, resulting in multiple `about:blank` tabs.

## Suggested fix

1. Pre-flight check for Chrome's `SingletonLock` file before launching
2. If lock exists, check if the owning PID is still alive (stale lock detection)
3. Fail fast with actionable error instead of retry loop

## Workaround

Kill all Chrome processes before starting a new session:
```bash
pkill -9 -f "Chromium" 2>/dev/null || true
pkill -9 -f "chrome" 2>/dev/null || true
```

## Related Issues

- #845 - "Opens 10 about:blank tabs"
- #1245 - Browser state not released after browser_close
- #1299 - Agent opens 1000 tabs and keeps failing

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright-mcp/issues/1311

### CODE REVIEW

File: packages/playwright/src/mcp/browser/browserContextFactory.ts [hunk 1]
```diff
@@ -367,6 +358,41 @@ async function browserContextOptionsFromConfig(config: FullConfig, clientInfo: C
...
+  for (let i = 0; i < 5; i++) {
+    if (!isProfileLocked(userDataDir))
+      return false;
+    await new Promise(f => setTimeout(f, 1000));
+  }
+  return true;
+}
+
+export function isProfileLocked(userDataDir: string): boolean {
+  const lockFile = process.platform === 'win32' ? 'lockfile' : 'SingletonLock';
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/browserContextFactory.ts:371]: why is the name different between platforms?

File: packages/playwright/src/mcp/browser/browserContextFactory.ts [hunk 2]
```diff
@@ -367,6 +358,41 @@ async function browserContextOptionsFromConfig(config: FullConfig, clientInfo: C
...
+      return e.code !== 'ENOENT';
+    }
+  }
+
+  try {
+    const target = fs.readlinkSync(lockPath);
+    const pid = parseInt(target.split('-').pop() || '', 10);
+    if (isNaN(pid))
+      return false;
+    process.kill(pid, 0);
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/browserContextFactory.ts:389]: what if it's a legit browser closure, just taking longer than usual?

**Review by yury-s — APPROVED** [review]

File: packages/playwright/src/mcp/browser/browserContextFactory.ts (hunk 2 above)
Comment (pavelfeldman) [reply packages/playwright/src/mcp/browser/browserContextFactory.ts:389]: We kill(0) - probe.

File: packages/playwright/src/mcp/browser/browserContextFactory.ts (hunk 1 above)
Comment (pavelfeldman) [reply packages/playwright/src/mcp/browser/browserContextFactory.ts:371]: I think Chrome folks decided to keep the pipe and the file names separate.
