### PR TITLE
fix(trace): account for last child node removal

### LINKED ISSUE #7304: [BUG] Snapshots are not captured if there is an animation at the beginning
**Context:**
- Playwright Version: 1.12.2
- Operating System: Windows only (works fine on mac)
- Node.js version: 12.14.1
- Browser: Chromium, Webkit

**Describe the bug**
There is an animation at the beginning when the page loads (i.e. when navigating to "XYZ" url). My test scenario involves:
- Click "Forgot Password"
- Navigates to different Page
- Enter email address
- Click Button (Intentionally failing the test on this step)

When capturing the snapshots in trace viewer, it only captures animation loading instead of capturing the actual actions. 
Please see the attached video.

https://user-images.githubusercontent.com/22205721/123350983-06318100-d511-11eb-92c0-465526f2172c.mov

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/7304

### CODE REVIEW

File: src/server/snapshot/snapshotterInjected.ts [hunk 1]
```diff
@@ -355,6 +356,7 @@ export function frameSnapshotStreamer(snapshotStreamer: string) {
           }
           for (let child = node.firstChild; child; child = child.nextSibling)
             visitChild(child);
+          expectValue(kEndOfChildren);
```
Comment (dgozman) [inline src/server/snapshot/snapshotterInjected.ts:359]: Let's do the same at line 414 (new code) for attributes.

**Review by dgozman — APPROVED** [review]

**Review by dgozman — APPROVED** [review]
