### PR TITLE
fix: do not throw on removeListener without listener

### LINKED ISSUE #15219: [REGRESSION]: playwright-core 1.23.0 issue with  'TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument'
**Context:**
- GOOD Playwright Version: 1.22..2
- BAD Playwright Version: 1.23.0
- Operating System: linux (ubuntu 20.04) and windows10 (powershell and bash console)
- Extra: playwright with jest runner

The following error appears after running the tests which were previously worked: 
Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined

      at Page.removeListener (node_modules/playwright-core/lib/client/joiningEventEmitter.js:59:27)
      at Page.removeListener (node_modules/playwright-core/lib/client/page.js:798:11)
      at CustomEnvironment.teardown (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:231:62)
      at PlaywrightRunner.runTests (node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:128:9)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/15219

### CODE REVIEW

File: packages/playwright-core/src/client/joiningEventEmitter.ts [hunk 1]
```diff
@@ -119,7 +119,11 @@ export class JoiningEventEmitter implements EventEmitter {
   }
 
   private _wrapper(listener: (...args: any[]) => void) {
-    return (listener as any)[wrapperListener];
+    const wrapped = (listener as any)[wrapperListener];
```
Comment (aslushnikov) [inline packages/playwright-core/src/client/joiningEventEmitter.ts:122]:
```suggestion
    // Fallback to original listener if not wrapped to ensure backwards compatibility Node.js's event emitter
    return (listener as any)[wrapperListener] ?? listener;
```

**Review by aslushnikov — APPROVED** [review]
