### PR TITLE
chore: fix xpath-in-iframe

### LINKED ISSUE #21364: [BUG] locator picker in trace viewer behaves differently to the one in the playwright inspector
### System info
- Playwright Version: 1.32.0-alpha-mar-3-2023
- Operating System: windows 10
- Browser: chromium
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```ts
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test'
import { devices } from '@playwright/test'

const config: PlaywrightTestConfig = {
    testDir: './tests',
    timeout: 50 * 1000,
    expect: {
        timeout: 50000,
    },
    forbidOnly: !!process.env['CI'],
    retries: process.env['CI'] ? 2 : 0,
    reporter: 'html',
    use: {
        actionTimeout: 0,
        trace: 'on',
    },
    projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
            },
        },
    ],
}

export default config
```

**Test file (self-contained)**

```js
test('asdf', async ({ page }) => {
    await page.goto('https://google.com')
    await page.pause()
})
```

**Steps**
1. run `playwright test`
1. hit run button when the inspector appears
1. when it pauses, input the locator, eg. `//span`
1. hit resume button
1. run `playwright show-report` then click the trace button on the test
1. input the same locator as before, eg. `//span`

**Expected**
the same elements are highlighted in both the inspector and the trace viewer

**Actual**
image
image

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/21364

### CODE REVIEW

File: packages/playwright-core/src/server/injected/xpathSelectorEngine.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const XPathEngine: SelectorEngine = {
     if (selector.startsWith('/'))
       selector = '.' + selector;
     const result: Element[] = [];
-    const document = root instanceof Document ? root : root.ownerDocument;
+    const document = root.ownerDocument || root;
```
Comment (dgozman) [inline packages/playwright-core/src/server/injected/xpathSelectorEngine.ts:24]: Should we add `Document/Node` to the list of prohibited globals?

**Review by dgozman — APPROVED** [review]

**Comment by mxschmitt** [comment]
Test would be nice!

File: packages/playwright-core/src/server/injected/xpathSelectorEngine.ts (hunk 1 above)
Comment (pavelfeldman) [reply packages/playwright-core/src/server/injected/xpathSelectorEngine.ts:24]: I did at first, but I could not find a way to ban it only as a runtime object - it yells at all the type declarations...
