### PR TITLE
fix(chromium): disable use-zoom-for-dsf

### LINKED ISSUE #7362: [Internal] page-drag tests fail on macOS 11.0

### PR DESCRIPTION
**Pull request by JoelEinbinder**
On Mac, use-zoom-for-dsf﻿was enabled by default which caused `Input.dispatchDragEvent` to miss
its target. Disabling the flag while we wait for an upstream fix.

Fixes #7362

### CODE REVIEW

File: src/server/chromium/chromium.ts [hunk 1]
```diff
@@ -221,6 +221,7 @@ const DEFAULT_ARGS = [
   '--use-mock-keychain',
   // See https://chromium-review.googlesource.com/c/chromium/src/+/2436773
   '--no-service-autorun',
+  '--enable-use-zoom-for-dsf=false',
```
Comment (dgozman) [inline src/server/chromium/chromium.ts:224]: Let's only do this on Mac? I am afraid that screenshots on Windows will change if you disable this feature.

Comment (JoelEinbinder) [reply src/server/chromium/chromium.ts:224]: All tests pass? I'm afraid that dragging will break on windows if its enabled!

Comment (JoelEinbinder) [reply src/server/chromium/chromium.ts]: I don't have access to a high dpi windows computer, but I wasn't able to repro this issue on linux. Added the flag for macos only for now.

**Review by dgozman — APPROVED** [review]

**Review by mxschmitt — APPROVED** [review]
