### PR TITLE
fix(test.fail): expect() failure should not skip future tests

### LINKED ISSUE #26435: [BUG] Missing await in test with `test.fail()` causes other tests to be skipped
### System info
- Playwright Version: 1.38.0-alpha-aug-11-2023
- Operating System: Ubuntu 20
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/lukaw3d/playwright-skip-tests-bug

Main parts:
- https://github.com/lukaw3d/playwright-skip-tests-bug/blob/main/tests/test2.spec.ts#L3-L6
  ```ts
  test('test2 (expect fail)', async ({ page }) => {
    test.fail()
    /* await */ expect(Promise.resolve('a')).resolves.toBe('b')
  })
  ```
- run with `--workers 1`

**Expected**

```sh
$ playwright test --workers 1 --reporter list
  ✓  1 tests/test1.spec.ts:3:5 › test1 (145ms)
  ✘  2 tests/test2.spec.ts:3:5 › test2 (expect fail) (59ms)
  ✓  3 tests/test3.spec.ts:3:5 › test3 (60ms)
  ✓  4 tests/test4.spec.ts:3:5 › test4 (74ms)
  ✓  5 tests/test5.spec.ts:3:5 › test5 (65ms)
```

or
any kind of a warning or error that something went wrong

**Actual**

```sh
$ playwright test --workers 1 --reporter list
  ✓  1 tests/test1.spec.ts:3:5 › test1 (145ms)
  ✘  2 tests/test2.spec.ts:3:5 › test2 (expect fail) (59ms)
  -  3 tests/test3.spec.ts:3:5 › test3
  -  4 tests/test4.spec.ts:3:5 › test4
  -  5 tests/test5.spec.ts:3:5 › test5
```

and command exists as success!

### PR DESCRIPTION
**Pull request by dgozman**
We used to stop the worker that would skip future tests. Regressed in https://github.com/microsoft/playwright/pull/11850.

Fixes #26435.

### CODE REVIEW

File: packages/playwright-test/src/worker/workerMain.ts [hunk 1]
```diff
@@ -164,28 +164,41 @@ export class WorkerMain extends ProcessRunner {
...
     // and continuing to run tests in the same worker is problematic. Therefore,
     // we turn this into a fatal error and restart the worker anyway.
+    //
     // The only exception is the expect() error that we still consider ok.
     const isExpectError = (error instanceof Error) && !!(error as any).matcherResult;
-    const isCurrentTestExpectedToFail = this._currentTest?.expectedStatus === 'failed';
-    const shouldConsiderAsTestError = isExpectError || !isCurrentTestExpectedToFail;
-    if (this._currentTest && shouldConsiderAsTestError) {
+    if (isExpectError) {
+      // Note: do not stop the worker, because test.fail() that fails an assertion
```
Comment (yury-s) [inline packages/playwright-test/src/worker/workerMain.ts:196]:
```suggestion
      // Note: do not stop the worker, because test marked with test.fail() that fails an assertion
```

**Review by yury-s — APPROVED** [review]
