### PR TITLE
fix: Service Workers+Interception: missing page-level Network events

### LINKED ISSUE #15474: [BUG] Page Request Served from SW Cache: Missing Page-Request Event
See https://gist.github.com/rwoll/100f361aca78838aad3d138eac30f35a#file-example-spec-ts-L90.

If a page makes a request, even if the SW fetch handler responds from https://developer.mozilla.org/en-US/docs/Web/API/Cache, we should still see the request on the page itself.

### PR DESCRIPTION
**Pull request by rwoll**
Fixes #15474.

Notes:

* page-level requests that are also handled by a SW's fetch handler, should not be interceptable at the page-level
* `Network.requestWillBeSent` does not provide enough metadata for Playwright to fire the `request` event at that time, so it does it as soon as it gets to the end of the request lifecycle

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crNetworkManager.ts [hunk 1]
```diff
@@ -363,7 +363,18 @@ export class CRNetworkManager {
   }
 
   _onResponseReceived(event: Protocol.Network.responseReceivedPayload) {
-    const request = this._requestIdToRequest.get(event.requestId);
+    let request = this._requestIdToRequest.get(event.requestId);
+    // For frame-level Requests that are handled by a Service Worker's fetch handler, we'll never get a requestPaused event, so we need to
+    // manually create the request. In an ideal world, crNetworkManager would be able to know this on Network.requestWillBeSent, but there
+    // is not enough metadata there.
+    if (this._protocolRequestInterceptionEnabled && event.response.fromServiceWorker) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/chromium/crNetworkManager.ts:370]:
```suggestion
    if (!request && event.response.fromServiceWorker) {
```

File: packages/playwright-core/src/server/chromium/crNetworkManager.ts [hunk 2]
```diff
@@ -363,7 +363,18 @@ export class CRNetworkManager {
...
+      const requestWillBeSentEvent = this._requestIdToRequestWillBeSentEvent.get(event.requestId);
+      const frame = requestWillBeSentEvent?.frameId ? this._page?._frameManager.frame(requestWillBeSentEvent.frameId) : null;
+      if (requestWillBeSentEvent && frame) {
+        this._onRequest(frame, requestWillBeSentEvent, null /* requestPausedPayload */);
+        request = this._requestIdToRequest.get(event.requestId);
```
Comment (dgozman) [inline packages/playwright-core/src/server/chromium/crNetworkManager.ts:375]:
```suggestion
        request = this._requestIdToRequest.get(event.requestId);
        this._requestIdToRequestWillBeSentEvent.delete(event.requestId);
```

File: tests/library/chromium/chromium.spec.ts [hunk 3]
```diff
@@ -390,6 +393,7 @@ test('should emit page-level request event for respondWith when interception ena
   expect(pageReq.url()).toMatch(/fetchdummy\/foo$/);
   expect(pageReq.serviceWorker()).toBe(null);
   expect((await pageReq.response()).fromServiceWorker()).toBe(true);
+  expect(markFailureIfPageRoutesARequestAlreadyHandledByServiceWorker).toBe(false);
```
Comment (dgozman) [inline tests/library/chromium/chromium.spec.ts:396]: Let's also test that we get `response` and `requestfinished` events.

Comment (rwoll) [reply tests/library/chromium/chromium.spec.ts:396]: updating. also adding requestfailed case, too.

**Review by dgozman — APPROVED** [review]
