### PR TITLE
fix(route): allow allHeaders call within route

### LINKED ISSUE #9298: [Question]: Should new Headers methods work in RouteAsync ?
### Your question

It seems when I call this new HeadersArrayAsync method like this in RouteAsync
```
await page.RouteAsync("**/*", async (route) =>
{
    var allHeaders= await route.Request.HeadersArrayAsync();
});
```
It throws 
`Microsoft.Playwright.PlaywrightException: 'Unable to fetch raw headers.'`
Are these new methods not supposed to be used in RouteAsync ?

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/9298

### CODE REVIEW

File: src/server/chromium/crNetworkManager.ts [hunk 1]
```diff
@@ -154,6 +154,13 @@ export class CRNetworkManager {
   }
 
   _onRequestPaused(workerFrame: frames.Frame | undefined, event: Protocol.Fetch.requestPausedPayload) {
+    if (!event.responseStatusCode) {
```
Comment (yury-s) [inline src/server/chromium/crNetworkManager.ts:157]: && !event.responseErrorReason ? (in case you pause on failed request)

File: tests/page/page-route.spec.ts [hunk 2]
```diff
@@ -672,3 +672,13 @@ it('should support the times parameter with route matching', async ({ page, serv
   await page.goto(server.EMPTY_PAGE);
   expect(intercepted).toHaveLength(1);
 });
+
+it('should contain raw header', async ({ page, server }) => {
+  let headers: any;
+  await page.route('**/*', async route => {
+    headers = await route.request().allHeaders();
```
Comment (yury-s) [inline tests/page/page-route.spec.ts:679]: Check that it actually returns expected headers?

File: src/server/network.ts [hunk 3]
```diff
@@ -153,8 +154,23 @@ export class Request extends SdkObject {
...
+      this._rawRequestHeadersPromise = new ManualPromise();
+  }
+
+  setRawRequestHeaders(headers: types.HeadersArray) {
+    if (!this._rawRequestHeadersPromise)
+      this._rawRequestHeadersPromise = new ManualPromise();
+    this._rawRequestHeadersPromise!.resolve(headers);
+  }
+
+  async rawRequestHeaders(): Promise<NameValue[]> {
```
Comment (yury-s) [inline src/server/network.ts:168]: Please add a comment explaining 3 ways the raw headers could be received

**Review by yury-s — APPROVED** [review]

File: tests/page/page-route.spec.ts (hunk 2 above)
Comment (pavelfeldman) [reply tests/page/page-route.spec.ts:679]: I don't think we are returning raw headers here, so I only check that it `accept` one exists.

File: src/server/network.ts (hunk 3 above)
Comment (pavelfeldman) [reply src/server/network.ts:168]: Which 3 ways? :)
