### PR TITLE
fix(mcp): do not disable extensions in persistent mode

### LINKED ISSUE #998: [Feature] Allow browser extensions
Allow us to install browser extensions in the Chrome browser or make the default browser one that can.

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes: https://github.com/microsoft/playwright-mcp/issues/998

### CODE REVIEW

File: packages/playwright-client/types/types.d.ts [hunk 1]
```diff
@@ -14918,10 +14918,7 @@ export interface BrowserType<Unused = {}> {
      */
     downloadsPath?: string;
 
-    /**
-     * Specify environment variables that will be visible to the browser. Defaults to `process.env`.
-     */
-    env?: { [key: string]: string|number|boolean; };
+    env?: { [key: string]: string|undefined; };
```
Comment (yury-s) [inline packages/playwright-client/types/types.d.ts:14921]: this is breaking for no reason

File: packages/playwright/src/mcp/browser/browserContextFactory.ts [hunk 2]
```diff
@@ -174,14 +175,19 @@ class PersistentContextFactory implements BrowserContextFactory {
...
     const browserType = playwright[this.config.browser.browserName];
     for (let i = 0; i < 5; i++) {
+      const launchOptions: LaunchOptions = {
+        tracesDir,
+        ...this.config.browser.launchOptions,
+        ...this.config.browser.contextOptions,
+        handleSIGINT: false,
+        handleSIGTERM: false,
+        ignoreDefaultArgs: [
+          '--disable-extensions',
```
Comment (yury-s) [inline packages/playwright/src/mcp/browser/browserContextFactory.ts:185]: I believe we pass it to disable side-effects from preinstalled extensions and now this will enable the extensions for everyone with persistent context, is that what we want? Why not let those that want to use extensions pass `ignoreDefaultArgs` or better yet pass the flags as prescribed in https://playwright.dev/docs/chrome-extensions ?

File: packages/playwright-client/types/types.d.ts (hunk 1 above)
Comment (pavelfeldman) [reply packages/playwright-client/types/types.d.ts:14921]: I'm aligning it with Node.ProcessEnv, looks like a bugfix to me we can afford.

File: packages/playwright/src/mcp/browser/browserContextFactory.ts (hunk 2 above)
Comment (pavelfeldman) [reply packages/playwright/src/mcp/browser/browserContextFactory.ts:185]: `now this will enable the extensions for everyone with persistent context` - this can't re-enable the extensions because these are new profiles created for mcp only, and they did not have extensions.

We want persistent context users to enjoy the experience of a regular browser, so that they could install extensions there.

File: packages/playwright-core/src/browserServerImpl.ts [hunk 3]
```diff
@@ -112,7 +112,7 @@ function toProtocolLogger(logger: Logger | undefined): ProtocolLogger | undefine
   } : undefined;
 }
 
-function envObjectToArray(env: Env): { name: string, value: string }[] {
+function envObjectToArray(env: NodeJS.ProcessEnv): { name: string, value: string }[] {
```
Comment (yury-s) [inline packages/playwright-core/src/browserServerImpl.ts:115]: No need to `String(env[name])` below.

File: packages/playwright-core/src/client/clientHelper.ts [hunk 4]
```diff
@@ -17,10 +17,9 @@
 
 import { isString } from '../utils/isomorphic/rtti';
 
-import type * as types from './types';
 import type { Platform } from './platform';
 
-export function envObjectToArray(env: types.Env): { name: string, value: string }[] {
+export function envObjectToArray(env: NodeJS.ProcessEnv): { name: string, value: string }[] {
```
Comment (yury-s) [inline packages/playwright-core/src/client/clientHelper.ts:22]: No need to String(env[name]) below, the value is always string.

**Review by yury-s — APPROVED** [review]
