### PR TITLE
chore: fix installing of branded browsers under non-root

### LINKED ISSUE #10615: [BUG] Docker image v1.17.0-focal can't install chrome browser
**Context:**
- Playwright Version: 1.17.0
- Operating System: WSL2 Ubuntu 20.04 (Windows)
- Browser: Chrome
- Extra: Docker image mcr.microsoft.com/playwright:v1.17.0-focal

**Code Snippet**

Docker image mcr.microsoft.com/playwright:v1.17.0-focal
```bash
docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.17.0-focal /bin/bash
root@cc72915d2e85:/# npx playwright install chrome
Need to install the following packages:
  playwright
Ok to proceed? (y) y
++ arch
+ [[ x86_64 == \a\a\r\c\h\6\4 ]]
+ is_user_root
+ '[' 0 -eq 0 ']'
+ maybesudo=
+ dpkg --get-selections
+ grep -q '^google-chrome[[:space:]]*install$'
+ command -v wget
+ apt-get install -y wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wget
Failed to install browsers
Error: Failed to install chrome
root@cc72915d2e85:/#
```

Docker image mcr.microsoft.com/playwright:v1.16.3-focal
```
docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.16.3-focal /bin/bash
root@5287653df71a:/# npx playwright install chrome
Need to install the following packages:
  playwright
Ok to proceed? (y) y
++ arch
+ [[ x86_64 == \a\a\r\c\h\6\4 ]]
+ is_user_root
+ '[' 0 -eq 0 ']'
+ maybesudo=
+ dpkg --get-selections
+ grep -q '^google-chrome[[:space:]]*install$'
+ command -v wget
+ apt-get install -y wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  wget
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 349 kB of archives.
After this operation, 1016 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 wget amd64 1.20.3-1ubuntu1 [349 kB]
Fetched 349 kB in 2s (174 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package wget.
(Reading database ... 43891 files and directories currently installed.)
Preparing to unpack .../wget_1.20.3-1ubuntu1_amd64.deb ...
Unpacking wget (1.20.3-1ubuntu1) ...
Setting up wget (1.20.3-1ubuntu1) ...
+ cd /tmp
+ wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
--2021-11-30 17:36:23--  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
Resolving dl.google.com (dl.google.com)... 142.251.129.206, 2800:3f0:4001:82e::200e
Connecting to dl.google.com (dl.google.com)|142.251.129.206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 90769636 (87M) [application/x-debian-package]
Saving to: 'google-chrome-stable_current_amd64.deb'

google-chrome-stable_current_amd64.deb         100%[==================================================================================================>]  86.56M  48.5MB/s    in 1.8s

2021-11-30 17:36:26 (48.5 MB/s) - 'google-chrome-stable_current_amd64.deb' saved [90769636/90769636]

+ apt-get install -y ./google-chrome-stable_current_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'google-chrome-stable' instead of './google-chrome-stable_current_amd64.deb'

########## remove output to reduce log ###################

+ rm -rf ./google-chrome-stable_current_amd64.deb
+ cd -
/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/bin
+ google-chrome --version
Google Chrome 96.0.4664.45
npm notice
npm notice New major version of npm available! 7.24.2 -> 8.1.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.1.4
npm notice Run npm install -g npm@8.1.4 to update!
npm notice
root@5287653df71a:/#
```

**Describe the bug**

Does something changed with the Docker images for version 1.17.0-focal? I can't install Chrome using `npx playwright install chrome`. Running the same commands above but with v1.16.3 works fine.

**Edited**
Just saw that apt-get didn't find the `wget` package.

### PR DESCRIPTION
**Pull request by mxschmitt**
Before the determination, if we should run a certain command under `root` or not was done in multiple places. Inside the channel install scripts, we had a fallback to `sudo` when we were not under root, but there is not always sudo. For example inside our Docker image, we don't have sudo.

This change does centralise this check, so that the actual install.sh script runs already with elevated permissions, since we always modify the system and removes the manual `maybesudo` checks inside the scripts.

Tested under the following scenarios:

1. root user
2. non-root which has sudo available
3. non-root which has no sudo available

Fixes #10615
Should fix the broken CI in https://github.com/microsoft/playwright/pull/10617 as well

### CODE REVIEW

File: packages/playwright-core/bin/reinstall_msedge_beta_linux.sh [hunk 1]
```diff
@@ -8,25 +8,22 @@ if [[ $(arch) == "aarch64" ]]; then
...
+# 1. make sure to remove old beta if any.
 if dpkg --get-selections | grep -q "^microsoft-edge-beta[[:space:]]*install$" >/dev/null; then
-  $maybesudo apt-get remove -y microsoft-edge-beta
+  apt-get remove -y microsoft-edge-beta
 fi
 
+# 2. Install curl to download Microsoft gpg key
 if ! command -v curl >/dev/null; then
-  $maybesudo apt-get install -y curl
+  apt-get update
```
Comment (mxschmitt) [inline packages/playwright-core/bin/reinstall_msedge_beta_linux.sh:18]: note: we have two apt-get updates here.
1. for installing cURL.
2. for updating the local package lists with the newly added msedge source list.

File: packages/playwright-core/bin/reinstall_chrome_beta_linux.sh [hunk 2]
```diff
@@ -7,26 +7,23 @@ if [[ $(arch) == "aarch64" ]]; then
...
-  $maybesudo apt-get remove -y google-chrome-beta
+  apt-get remove -y google-chrome-beta
 fi
 
+# 2. Update apt lists (needed to install curl and chrome dependencies)
+apt-get update
+
+# 3. Install curl to download chrome
 if ! command -v curl >/dev/null; then
-  $maybesudo apt-get install -y curl
```
Comment (mxschmitt) [inline packages/playwright-core/bin/reinstall_chrome_beta_linux.sh:23]: before this ended up in: curl can't be found since its not in apt cache.

File: packages/playwright-core/bin/reinstall_chrome_stable_linux.sh [hunk 3]
```diff
@@ -7,27 +7,23 @@ if [[ $(arch) == "aarch64" ]]; then
...
-  $maybesudo apt-get install -y curl
+  apt-get install -y curl
 fi
 
-# 2. download chrome stable from dl.google.com and install it.
+# 4. download chrome stable from dl.google.com and install it.
 cd /tmp
 curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-$maybesudo apt-get install -y ./google-chrome-stable_current_amd64.deb
+apt-get install -y ./google-chrome-stable_current_amd64.deb
```
Comment (mxschmitt) [inline packages/playwright-core/bin/reinstall_chrome_stable_linux.sh:26]: note: This requires an up-to-date apt cache since its installs chrome dependencies

**Review by aslushnikov — APPROVED** [review]
