### PR TITLE
docs(java): fix pom.xml (and auto-generate)

### LINKED ISSUE #15191: [BUG] Java Docs Contain Wrong Version in pom.xml
[GeMi](https://app.slack.com/team/U03MAKR4S6S)
 [Today at 9:30 AM](https://playwright.slack.com/archives/CSUHZPVLM/p1656433831325129)
Will be nice if in https://playwright.dev/java/docs/intro#usage in pom.xml example will be version of Playwright Artifact corresponding to current version, for now there is <version>1.17.1</version> .

### PR DESCRIPTION
**Pull request by rwoll**
Fixes #15191.

### CODE REVIEW

File: utils/doclint/cli.js [hunk 1]
```diff
@@ -84,6 +85,15 @@ async function run() {
       });
       writeAssumeNoop(filePath, content, dirtyFiles);
     }
+
+    // Patch pom.xml
+    {
+      const introPath = path.join(PROJECT_DIR, 'docs', 'src', 'intro-java.md');
+      const pomVersionRe = new RegExp('^(\\s*<artifactId>playwright<\\/artifactId>\\n\\s*<version>)(.*)(<\\/version>)$', 'gm');
+      let content = fs.readFileSync(introPath).toString();
+      content = content.replace(pomVersionRe, '$1' + playwrightVersion + '$3');
```
Comment (yury-s) [inline utils/doclint/cli.js:94]: Patch version in java may be behind (we don't always roll patch releases into ports) so I'd rather update it to `major.minor.0`

**Review by yury-s — APPROVED** [review]

File: utils/doclint/cli.js (hunk 1 above)
Comment (rwoll) [reply utils/doclint/cli.js]: Updated thanks!
