### PR TITLE
fix: a nicer lockfile message

### LINKED ISSUE #9574: [BUG] Lock file is already being held
```
npm ERR! code 1
npm ERR! path /Users/pfeldman/code/playwright/packages/playwright-webkit
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/pfeldman/code/playwright/node_modules/proper-lockfile/lib/lockfile.js:68
npm ERR!                 return callback(Object.assign(new Error('Lock file is already being held'), { code: 'ELOCKED', file }));
npm ERR!                                               ^
npm ERR! 
npm ERR! Error: Lock file is already being held
npm ERR!     at /Users/pfeldman/code/playwright/node_modules/proper-lockfile/lib/lockfile.js:68:47
npm ERR!     at callback (/Users/pfeldman/code/playwright/node_modules/graceful-fs/polyfills.js:299:20)
npm ERR!     at FSReqCallback.oncomplete (node:fs:199:5) {
npm ERR!   code: 'ELOCKED',
npm ERR!   file: '/Users/pfeldman/Library/Caches/ms-playwright'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pfeldman/.npm/_logs/2021-10-17T18_02_49_591Z-debug.log
```

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #9574

### CODE REVIEW

File: packages/playwright-core/src/utils/registry.ts [hunk 1]
```diff
@@ -524,22 +524,23 @@ export class Registry {
     const executables = this._addRequirementsAndDedupe(executablesToInstall);
     await fs.promises.mkdir(registryDirectory, { recursive: true });
     const lockfilePath = path.join(registryDirectory, '__dirlock');
-    const releaseLock = await lockfile.lock(registryDirectory, {
```
Comment (yury-s) [inline packages/playwright-core/src/utils/registry.ts:527]: Why does it have to move?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/utils/registry.ts (hunk 1 above)
Comment (aslushnikov) [reply packages/playwright-core/src/utils/registry.ts:527]: that's so that it's inside a try-catch and thus catches the lockfile error
