### PR TITLE
fix(har): recalculate receive time after response ended

### LINKED ISSUE #19327: [BUG] receive time recorded in har file is incorrect
**Context:**
- Playwright Version: [1.28.1]
- Operating System: [linux]
- Node.js version: [16]
- Browser: [Chromium]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { test, expect } = require('@playwright/test');
const { chromium, webkit, firefox } = require('playwright');

test.use({ viewport: { width: 600, height: 900 } });

test("test", async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
     recordHar: { path: 'tests/example.har'}
  });
  const page = await context.newPage(); 

  await page.goto('https://www.taobao.com');

  await page.close();
  await context.close();

  await browser.close();
});
```

**Describe the bug**
in the har file, the receive time in timing section is always -1
eg.         "timings": { "dns": 7.623, "connect": 61.947, "ssl": 44.91, "send": 0, "wait": 20.615, "receive": -1 },

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/19327

### CODE REVIEW

File: packages/playwright-core/src/server/har/harTracer.ts [hunk 1]
```diff
@@ -460,6 +465,16 @@ export class HarTracer {
...
   }
 
+  private _computeHarEntryTotalTime(harEntry: har.Entry) {
+    harEntry.time = [
+      harEntry.timings.dns,
+      harEntry.timings.connect,
+      harEntry.timings.ssl,
+      harEntry.timings.wait,
+      harEntry.timings.receive
+    ].reduce((pre, cur) => (cur || -1) > 0 ? cur! + pre! : pre, 0)!;
```
Comment (dgozman) [inline packages/playwright-core/src/server/har/harTracer.ts:475]: Can any of times be zero? Perhaps `??` is better in this case?

```suggestion
    ].reduce((pre, cur) => (cur ?? -1) > 0 ? cur! + pre! : pre, 0)!;
```

**Review by dgozman — APPROVED** [review]
