### PR TITLE
fix(expect): properly handle custom asymmetric matcher regression

### LINKED ISSUE #35138: [Regression]:  TypeError: Cannot read properties of undefined (reading 'expectInfo')
### Last Good Version

1.50

### First Bad Version

1.51

### Steps to reproduce

1. clone my repo https://github.com/Smrtnyk/PW-repros
2. Run the asymmetric matcher test

### Expected behavior

In version 1.50 the error message was clear

### Actual behavior

In version 1.51 a weird exception happens  TypeError: Cannot read properties of undefined (reading 'expectInfo')
I suspect it is related to this commit https://github.com/microsoft/playwright/commit/4b64c47a251e11e6634ef7265ea4d13ebf1f6df6

### Additional context

_No response_

### Environment

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12950HX
    Memory: 35.97 GB / 63.69 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.0 - ~\AppData\Roaming\npm\pnpm.CMD
  IDEs:
    VSCode: 1.96.0 - C:\workspaces\devtools\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: 1.51.0 => 1.51.0
```

### PR DESCRIPTION
**Pull request by agg23**
Fixes #35138. #34620 failed to take into consideration multiple asymmetric matchers running in a given `expect` expression, and was a bit aggressive in cleaning it up.

### CODE REVIEW

File: packages/playwright/src/matchers/expect.ts [hunk 1]
```diff
@@ -333,8 +329,11 @@ class ExpectMetaInfoProxyHandler implements ProxyHandler<any> {
     return (...args: any[]) => {
       const testInfo = currentTestInfo();
       setMatcherCallContext({ expectInfo: this._info, testInfo });
-      if (!testInfo)
-        return matcher.call(target, ...args);
+      if (!testInfo) {
+        const matcherResult = matcher.call(target, ...args);
+        clearMatcherCallContext();
```
Comment (pavelfeldman) [inline packages/playwright/src/matchers/expect.ts:334]: Can there be an async asymmetric matcher? If there can be we are in trouble!

**Review by pavelfeldman — APPROVED** [review]
