### PR TITLE
fix(cli): minimist should not turn strings into numbers

### LINKED ISSUE #235: `playwright-cli fill` command fails when input value is numeric — throws "expected string, received number" error
When using `playwright-cli` to fill a textbox with a numeric username, the command fails with the error:
`error: 'text' argument: expected string, received number.`

The target input is identified as a `textbox` type in the snapshot, and the value to fill is a numeric string (e.g., `"10000001"`). Despite passing the value as a quoted string in the command, the CLI appears to interpret it as a number, causing the operation to fail.

Environment:

OS: Windows Server (64-bit)

Shells tested: PowerShell, Command Prompt (cmd)

Playwright CLI: Latest version installed via npm

Steps to Reproduce:

Open the target page containing a login form.

Identify the textbox for username (ref: `e33`), labeled `"Job number/mobile phone number"`.

Run the following command:

```
bash
npx playwright-cli fill e33 "10000001"
```

Observe the error:

```
text
error: 'text' argument: expected string, received number
```

Expected Behavior:
The command should fill the textbox with the string `"10000001"` without type-related errors.

Actual Behavior:
The CLI rejects the numeric string argument and reports a type mismatch.

Additional Context:

Page snapshot (relevant portion):

```
text
- generic [ref=e30]:
      - generic [ref=e31]:
        - textbox "Job number/mobile phone number" [ref=e33]
        - textbox "Password" [ref=e37]
      - generic [ref=e38]:
        - button "Login" [disabled] [ref=e39]
        - paragraph [ref=e40]:
          - generic [ref=e41]:
            - generic [ref=e42]: Change password
            - generic [ref=e44]: Forgot password
```
The issue occurs regardless of shell environment (PowerShell/cmd).

Question:
Is there a special syntax or workaround in playwright-cli to ensure numeric strings are treated as plain text inputs? Any guidance on resolving this type coercion issue would be appreciated.

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright-cli/issues/235

### CODE REVIEW

File: packages/playwright/src/mcp/terminal/helpGenerator.ts [hunk 1]
```diff
@@ -146,12 +148,35 @@ function generateReadmeEntry(command: AnyCommandSchema): string {
...
+    }
+  }
+
   const help = {
     global: generateHelp(),
     commands: Object.fromEntries(
         Object.entries(commands).map(([name, command]) => [name, generateCommandHelp(command)])
     ),
+    stringOptions: [...stringOptions],
+    booleanOptions: [...booleanOptions],
```
Comment (Skn0tt) [inline packages/playwright/src/mcp/terminal/helpGenerator.ts:179]: this outputs a lot more `booleanOptions` than we currently have:
```js
"stringOptions": [
    "browser",
    "config",
    "profile",
    "modifiers",
    "filename",
    "domain",
    "path",
    "body",
    "content-type",
    "remove-header"
  ],
  "booleanOptions": [
    "extension",
    "headed",
    "persistent",
    "submit",
    "clear",
    "full-page",
    "httpOnly",
    "secure",
    "skills",
    "static"
  ]
```

File: packages/playwright/src/mcp/terminal/program.ts [hunk 2]
```diff
@@ -465,25 +465,17 @@ const globalOptions: (keyof (GlobalOptions & OpenOptions))[] = [
...
-];
-
 export async function program(packageLocation: string) {
   const clientInfo = createClientInfo(packageLocation);
+  const help = require('./help.json');
 
   const argv = process.argv.slice(2);
-  const args: MinimistArgs = require('minimist')(argv, { boolean: booleanOptions });
-  for (const option of booleanOptions) {
+  const args: MinimistArgs = require('minimist')(argv, { boolean: [...help.booleanOptions, 'help', 'version'], string: [...help.stringOptions, '_'] });
```
Comment (dgozman) [inline packages/playwright/src/mcp/terminal/program.ts]: Does this work with `mousemove`? IIRC, it has two number arguments.

Comment (Skn0tt) [reply packages/playwright/src/mcp/terminal/program.ts]: CI says no!

File: packages/playwright/src/mcp/terminal/program.ts [hunk 3]
```diff
@@ -482,21 +482,13 @@ const globalOptions: (keyof (GlobalOptions & OpenOptions))[] = [
...
```
Comment (dgozman) [inline packages/playwright/src/mcp/terminal/program.ts]: I think we should still include `booleanOptions` and `globalOptions` that are cli-only, instead of relying upon them being listed in help.

Alternatively, we can expose those from help, but I'd prefer that to be a separate PR.

File: tests/mcp/cli-parsing.spec.ts [hunk 4]
```diff
@@ -30,9 +30,12 @@ test('too many arguments', async ({ cli, server }) => {
 
 test('wrong option type', async ({ cli, server }) => {
   await cli('open', server.HELLO_WORLD);
-  const { error, exitCode } = await cli('type', 'foo', '--submit=bar');
-  expect(exitCode).toBe(1);
-  expect(error).toContain(`error: '--submit' option: expected boolean, received string`);
+  // boolean options are silently allowed
```
Comment (dgozman) [inline tests/mcp/cli-parsing.spec.ts]: - Why is that? I'd prefer this to throw.
- I also noticed that `type --submit foo` does not work on ToT. I hope it works with this PR, let's add a test for that.

File: tests/mcp/cli-core.spec.ts [hunk 5]
```diff
@@ -86,6 +86,15 @@ test('fill', async ({ cli, server }) => {
   expect(fillSnapshot).toBe(`- textbox [active] [ref=e2]: Hello, world!`);
 });
 
+test('fill numeric', { annotation: { type: 'issue', description: 'https://github.com/microsoft/playwright-cli/issues/235' } }, async ({ cli, server }) => {
+  server.setContent('/', `<input type=text>`, 'text/html');
+  const { snapshot } = await cli('open', server.PREFIX);
+  expect(snapshot).toContain(`- textbox [ref=e2]`);
+
+  const { snapshot: fillSnapshot } = await cli('fill', 'e2', '42', '--submit');
+  expect(fillSnapshot).toBe(`- textbox [active] [ref=e2]: "42"`);
```
Comment (dgozman) [inline tests/mcp/cli-core.spec.ts]: The `[active]` part will fail on some webkit bots.

**Review by dgozman — APPROVED** [review]
