### PR TITLE
fix(adb): minor fixes

### LINKED ISSUE #4674: [BUG] [ANDROID] Does not work with offline emulators
Description: Android version does not work when there is an offline emulator

adb devices output

```
temporaryadmin@C02D91BJML86 playwright % adb devices
List of devices attached
emulator-5554   offline
emulator-5556   device
```

Expected behaviour: works
Actual behaviour: `assert(status.toString() === 'OKAY', status.toString());` gets asserted
Workaround: lib/server/android/backendAdb.js `const lines = result.toString().trim().split('\n').filter(line => !line.includes("offline"));` (needs to be done well oc)

Used the official example.

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes: #4674, #4676, #4677

### CODE REVIEW

File: android-types-internal.d.ts [hunk 1]
```diff
@@ -21,11 +21,12 @@ export interface AndroidDevice<BrowserContextOptions, BrowserContext, Page> exte
 
   setDefaultTimeout(timeout: number): void;
   on(event: 'webview', handler: (webView: AndroidWebView<Page>) => void): this;
-  waitForEvent(event: string, predicate?: (data: any) => boolean): Promise<any>;
+  waitForEvent(event: string, optionsOrPredicate?: (data: any) => boolean | { timeout?: number, predicate?: (data: any) => boolean }): Promise<any>;
 
   serial(): string;
   model(): string;
   webViews(): AndroidWebView<Page>[];
+  webView(selector: { pkg: string }): Promise<AndroidWebView<Page>>;
```
Comment (dgozman) [inline android-types-internal.d.ts:29]: Missing timeout options here.

**Review by dgozman — APPROVED** [review]
