### PR TITLE
fix(screenshot): do not stall on hideHighlight

### LINKED ISSUE #12711: [REGRESSION] Page.screenshot hangs on some sites
**Context:**
- Playwright Version: ToT
- Operating System: Mac
- Node.js version: 16
- Browser: Chromium
- Extra: [any specific details about your environment]

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless:false,
  });
  const page = await browser.newPage()
  await page.goto("https://www.sina.com.cn/", {
    waitUntil: 'networkidle'
  })
  await page.screenshot({
    path: 'foo.png'
  })
  await browser.close();
})();
```

**Describe the bug**

Page.screenshot does not resolved.

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #12711.

### CODE REVIEW

File: packages/playwright-core/src/server/frames.ts [hunk 1]
```diff
@@ -507,46 +507,41 @@ export class Frame extends SdkObject {
       callback(error);
   }
 
-  async nonStallingRawEvaluateInExistingMainContext(expression: string): Promise<any> {
+  async nonStallingEvaluate<T>(cb: () => Promise<T>): Promise<T> {
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/frames.ts:510]: This is no longer a  non-stalling evaluate, it is now `raceAgainstFrameNavigation` ?

File: packages/playwright-core/src/server/screenshotter.ts [hunk 2]
```diff
@@ -261,13 +265,14 @@ export class Screenshotter {
...
-    await this._maskElements(progress, options);
+    const hasHighlight = await this._maskElements(progress, options);
     progress.throwIfAborted(); // Avoid extra work.
 
     const buffer = await this._page._delegate.takeScreenshot(progress, format, documentRect, viewportRect, options.quality, fitsViewport, options.size || 'device');
     progress.throwIfAborted(); // Avoid restoring after failure - should be done by cleanup.
 
-    await this._page.hideHighlight();
+    if (hasHighlight)
+      await this._page.hideHighlight();
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/screenshotter.ts:275]: I was told you were running this before taking screenshot instead.

**Review by pavelfeldman — APPROVED** [review]

**Review by aslushnikov — APPROVED** [review]
