### PR TITLE
fix(fixtures): tear down base fixture after error in derived

### LINKED ISSUE #29325: [Bug]: Automatic screenshot is not taken in case of error in fixture
### Version

1.41.2

### Steps to reproduce

1. clone my repo at https://github.com/vitalets/playwright-issues
2. `npm install`
3. `npm run test`
4. you should see html report opened

### Expected behavior

As test failed, I expect automatic screenshot to appear in the report.

### Actual behavior

There is no screenshot in the report:
image

### Additional context

If error is thrown **before** call of `use()`, screenshot correctly appears in the report:
```ts
import { test as base } from '@playwright/test';

const test = base.extend<{myFixture: void}>({
  myFixture: async ({}, use) => {
    throw new Error('foo'); // <- throw error in fixture, before use()
    await use();
  }
});

test('my test', async ({ page, myFixture }) => {
  await page.goto('https://playwright.dev');
});
```
Report:
image

### Environment

```shell
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 997.16 MB / 16.00 GB
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 7.27.1 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.85.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.41.2 => 1.41.2
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/29325

### CODE REVIEW

File: packages/playwright/src/worker/fixtureRunner.ts [hunk 1]
```diff
@@ -192,6 +185,19 @@ class Fixture {
       this.runner.instanceForId.delete(this.registration.id);
     }
   }
+
+  private _setTeardownDescription(timeoutManager: TimeoutManager) {
+    this._runnableDescription.phase = 'teardown';
+    timeoutManager.setCurrentFixture(this._runnableDescription);
+  }
+
+  takeFixturesInTeardownOrder(scope: FixtureScope, collector: Set<Fixture>) {
```
Comment (dgozman) [inline packages/playwright/src/worker/fixtureRunner.ts:194]: nit: `collectFixturesInTeardownOrder`?

**Review by dgozman — APPROVED** [review]
