### PR TITLE
fix(test runner): regular worker termination finishes long fixtures

### LINKED ISSUE #30504: [Bug]: Worker-scoped fixture execution terminates before timeout
### Version

1.43.1

### Steps to reproduce

1. clone [my repo](https://github.com/NoamGaash/never-ending-fixture) - `git clone git@github.com:NoamGaash/never-ending-fixture.git`
2. npm install
3. npx playwright test -g "my test"

### Expected behavior

1. I expect to see both `"Fixture teardown starts"` and `"Fixture teardown ends"` log messages
2. I expect the string `"will never be thrown"` to be thrown
3. I expect the teardown to take at least 40 seconds

### Actual behavior

1. The "Fixture teardown starts" text appears, but "Fixture teardown ends" is missing
2. The test takes 30.2s
3. No exception is thrown

### Additional context

The documentation states that:

> for slow fixtures, especially [worker-scoped](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) ones, it is convenient to have a separate timeout

That's why I believe timeouts are expected to work for worker-scoped fixtures.

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 14.82 GB / 31.01 GB
    Container: Yes
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
  IDEs:
    VSCode: 1.88.1 - /usr/bin/code
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

### PR DESCRIPTION
**Pull request by dgozman**
Previously, terminating worker always had a 30 seconds force exit.

Now, regular worker termination assumes that process will eventually finish tearing down all the fixtures and exits. However, the self-destruction routine keeps the 30 seconds timeout to avoid zombies.

Fixes #30504.

### CODE REVIEW

File: packages/playwright/src/common/process.ts [hunk 1]
```diff
@@ -92,19 +93,22 @@ process.on('message', async (message: any) => {
...
+  if (forceExit && !forceExitInitiated) {
+    forceExitInitiated = true;
+    // Force exit after 30 seconds.
+    // eslint-disable-next-line no-restricted-properties
+    setTimeout(() => process.exit(0), 30000);
+  }
+  if (!gracefullyCloseCalled) {
+    gracefullyCloseCalled = true;
+    // Meanwhile, try to gracefully shutdown.
+    await processRunner?.gracefullyClose().catch(() => {});
```
Comment (yury-s) [inline packages/playwright/src/common/process.ts:106]: If a fixture hangs while shutting down, it will keep the process running now. Can we avoid that?

**Review by yury-s — APPROVED** [review]

**Review by yury-s — APPROVED** [review]
