### PR TITLE
fix(trace viewer): preserve dialog.showModal() elements

### LINKED ISSUE #35139: [Bug]: Trace viewer live browser snapshot does not show modal
### Version

1.51.0

### Steps to reproduce

1. Clone https://github.com/OliverJAsh/playwright-top-layer-issue
2. Run:
   ```console
   $ pnpm install
   $ pnpm exec playwright test
   $ pnpm exec playwright show-report
   ```

### Expected behavior

The browser screenshots (top) should show the modal.
The live browser snapshot (center) should show the modal.

### Actual behavior

The browser screenshots (top) does show the modal. ✅
The live browser snapshot (center) does _not_ show the modal. ❌

https://github.com/user-attachments/assets/b0127c03-1b86-4806-99b8-b64b4faf12d6

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 15.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 89.30 MB / 16.00 GB
  Binaries:
    Node: 22.14.0 - /nix/store/91y8h7rysgi5cl8hsj2bmjd00dq2l9pk-nodejs-22.14.0/bin/node
    npm: 10.9.2 - /nix/store/91y8h7rysgi5cl8hsj2bmjd00dq2l9pk-nodejs-22.14.0/bin/npm
    pnpm: 10.6.2 - /nix/store/garwslb6cyaj9ma0hsasrx1rd3dsdd12-pnpm-10.6.2/bin/pnpm
  IDEs:
    VSCode: 1.98.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.37 - /nix/store/r6hp1dz7lhg07z4qq9db91xf532f7xk8-bash-5.2p37/bin/bash
  npmPackages:
    @playwright/test: ^1.51.0 => 1.51.0
```

### PR DESCRIPTION
**Pull request by dgozman**
Previously, every `<dialog>` element was opened based on the `open` attribute, automatically by the web platform.

However, the information on `show()` vs `showModal()` was lost, which affected `:modal` selector matching, and did not apply quite a few user agent styles, not to mention web author's styles.

Fixes #35139.

### CODE REVIEW

**Review by mxschmitt — APPROVED** [review]

File: packages/trace-viewer/src/sw/snapshotRenderer.ts [hunk 1]
```diff
@@ -311,7 +311,17 @@ function snapshotScript(viewport: ViewportSize, ...targetIds: (string | undefine
           (element as HTMLElement).showPopover();
         } catch {
         }
-        element.removeAttribute('__playwright_popover_open_');
+        element.removeAttribute('__playwright_dialog_open_');
```
Comment (mxschmitt) [inline packages/trace-viewer/src/sw/snapshotRenderer.ts:314]:
```suggestion
        element.removeAttribute('__playwright_popover_open_');
```
shouldn't it be like that?
