### PR TITLE
fix: reset APIRequestContext network trace between chunks

### LINKED ISSUE #34404: [Bug]:  UI test runner -  multiple api calls are added to the network tab after the test execution by using a new request context on test.beforeAll
### Version

1.49.1 

### Steps to reproduce

1.  clone this repo: https://github.com/dbarrientostk/api-issue
2.  npm install
3. npx playwright test --ui 
4. Run the test
5.  You should see the duplicate calls on the network tab.
Image

https://github.com/user-attachments/assets/663fef1c-7a7e-47b6-a2de-fb5ee4f71f2c

### Expected behavior

I expect so see only one api call to the  specific endpoint.

### Actual behavior

Duplicate api calls appear after the test ran.

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.18 GB / 32.00 GB
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1
```

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/34404

### CODE REVIEW

File: packages/playwright-core/src/server/trace/recorder/tracing.ts [hunk 1]
```diff
@@ -272,9 +272,14 @@ export class Tracing extends SdkObject implements InstrumentationListener, Snaps
...
-    // Network file survives across chunks, so make a copy with the new name.
+    // - Browser context network trace is shared across chunks as it contains resources
+    // used to serve page snapshots, so make a copy with the new name.
+    // - APIRequestContext network traces are chunk-specific, always start from scratch.
     const newNetworkFile = path.join(state.tracesDir, name + '.network');
-    this._fs.copyFile(state.networkFile, newNetworkFile);
+    if (this._context instanceof BrowserContext)
+      this._fs.copyFile(state.networkFile, newNetworkFile);
+    else
+      this._fs.writeFile(state.networkFile, '');
```
Comment (dgozman) [inline packages/playwright-core/src/server/trace/recorder/tracing.ts:282]: You should also update `_allocateNewTraceFile`, because `_changeTraceName` is not called on all code paths.

**Review by dgozman — APPROVED** [review]
