### PR TITLE
fix: require JSX inside PWT with pnpm

### LINKED ISSUE #27285: [BUG] Cannot find module 'playwright/jsx-runtime' when running tests through vscode extension
**Context:**
- Playwright Version: 1.38.
- Operating System: MacOS
- Node.js version:  18
- Visual Studio Code version: 1.82.2
- Playwright for VSCode extension version: v1.0.15
- Browser: All
- Extra:  I am importing some JSX components

**Code Snippet**

```
Error: Cannot find module 'playwright/jsx-runtime'
Require stack:
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/snackBar/billySnackBar.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/SnackbarHandler/SnackbarAlertContainer.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/SnackbarHandler/SnackbarHandler.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/error/BillyErrorSnackbarDisplay.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/ErrorHandler/ErrorHandler.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/data/billyUrql.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/generated/graphql.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/playwright/pageObjectModels/playwright-authApi.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/playwright/fixtures/base.fixture.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/playwright/local/customFields.spec.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/transform/transform.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/common/config.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/reporters/json.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/reporters/html.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/runner/reporters.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/runner/runner.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/cli.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/cli.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/@[playwright+test@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/@playwright/test/cli.js
```

I get a `Error: Cannot find module 'playwright/jsx-runtime'` when importing a `tsx` component  however it's quite far down the stack. However it doesn't show up when I run playwright from the CLI

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/27285

### CODE REVIEW

File: packages/playwright/bundles/babel/src/babelBundleImpl.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ function babelTransformOptions(isTypeScript: boolean, isModule: boolean, plugins
   // Support JSX/TSX at all times, regardless of the file extension.
   plugins.push([require('@babel/plugin-transform-react-jsx'), {
     runtime: 'automatic',
-    importSource: 'playwright'
+    importSource: require('path').dirname(require.resolve('playwright')),
```
Comment (dgozman) [inline packages/playwright/bundles/babel/src/babelBundleImpl.ts:68]: Well, `import path` at the top instead?

File: tests/installation/playwright-component-testing.spec.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+        const component = await mount(
+          <Button title='Submit' onClick={() => { clicked = true }}></Button>
+        );
+        await expect(component).toContainText('Submit');
+        await component.click();
+        expect(clicked).toBeTruthy();
+      });
+    `,
+  });
+  await exec('pnpm exec playwright test -c . --browser=all --reporter=list,json example.spec.tsx', { env: { PLAYWRIGHT_JSON_OUTPUT_NAME: 'report.json' } });
```
Comment (dgozman) [inline tests/installation/playwright-component-testing.spec.ts:49]:
```suggestion
  await exec('pnpm exec playwright test -c . --browser=chromium --reporter=list,json example.spec.tsx', { env: { PLAYWRIGHT_JSON_OUTPUT_NAME: 'report.json' } });
```

**Review by dgozman — APPROVED** [review]
