### PR TITLE
fix(installer): create tmp directory inside `browserPath`

### LINKED ISSUE #2494: [REGRESSION]: Atomic binary install failing in CI
**Context:**
- GOOD Playwright Version: before https://github.com/microsoft/playwright/pull/2489
- BAD Playwright Version: after https://github.com/microsoft/playwright/pull/2489
- Operating System: Linux
- Extra: Jenkins with Docker

**Code Snippet**

```sh
npm i playwright-chromium@1.1.0-next.1591502446737
```

**Describe the bug**

Hey team. The atomic install change is causing some issues for me in Docker on Jenkins. Here's what I get when I try to install.

```sh
(node:63) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/tmp/playwright-extract-chromium-linux-775089-9VigpJ' -> '/var/lib/jenkins/workspace/my-job/test/e2e/node_modules/playwright-chromium/.local-browsers/chromium-775089'
(node:63) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:63) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My understanding is that this means the tmp dir and the NPM install dir are on different partitions. I have no idea if this is an edge case or something that the majority of Jenkins/Docker users will experience, but I wanted to raise it here in case you think it's worth addressing.

### PR DESCRIPTION
**Pull request by aslushnikov**
`fs.rename` doesn't work across partitions, so we have to have
tmp folder next to our final destination.

Fixes #2494

### CODE REVIEW

File: src/install/installer.ts [hunk 1]
```diff
@@ -60,18 +60,25 @@ async function validateCache(packagePath: string, browsersPath: string, linksDir
     }
   }
 
-  // 2. Delete all unused browsers.
+  // 2. Delete all stale browser extract directories and .zip files.
+  // NOTE: this must not run concurrently with other installations.
+  let staleFiles = (await fsReaddirAsync(browsersPath)).map(file => path.join(browsersPath, file));
+  staleFiles = staleFiles.filter(file => browserPaths.isBrowserZipFile(file) || browserPaths.isBrowserExtractDirectory(file));
+  for (const staleFile of staleFiles)
+    await rmAsync(staleFile).catch(e => {});
```
Comment (dgozman) [inline src/install/installer.ts:68]: Let's logPolitely here as well?

File: src/install/installer.ts [hunk 2]
```diff
@@ -28,7 +28,7 @@ const fsReaddirAsync = util.promisify(fs.readdir.bind(fs));
 const fsReadFileAsync = util.promisify(fs.readFile.bind(fs));
 const fsUnlinkAsync = util.promisify(fs.unlink.bind(fs));
 const fsWriteFileAsync = util.promisify(fs.writeFile.bind(fs));
-const removeFolderAsync = util.promisify(removeFolder);
+const rmAsync = util.promisify(removeFolder);
```
Comment (dgozman) [inline src/install/installer.ts:31]: Does this work to remove zip files?

**Review by dgozman — APPROVED** [review]

File: src/install/installer.ts (hunk 2 above)
Comment (aslushnikov) [reply src/install/installer.ts:31]: yep, that's `rm -rf`

File: src/install/installer.ts (hunk 1 above)
Comment (aslushnikov) [reply src/install/installer.ts:68]: done

File: src/install/browserFetcher.ts [hunk 3]
```diff
@@ -109,10 +108,10 @@ export async function downloadBrowserWithProgressBar(browserPath: string, browse
   }
 
   const url = revisionURL(browser);
-  const zipPath = path.join(os.tmpdir(), `playwright-download-${browser.name}-${browserPaths.hostPlatform}-${browser.revision}.zip`);
+  const zipPath = browserPaths.browserZipFile(browserPath, browser);
```
[the remark this answers is not in the document]
Comment (aslushnikov) [reply src/install/browserFetcher.ts:109]: we explicitly do not support concurrent access to this folder - it would require lockdirs with pid files and all the fun. We'd rather stay away from this world for now.

File: src/install/browserPaths.ts [hunk 4]
```diff
@@ -104,7 +104,25 @@ export function browserDirectory(browsersPath: string, browser: BrowserDescripto
...
+  return baseName.startsWith('playwright-extract-');
+}
+
+export function browserExtractDirectory(browserPath: string, browser: BrowserDescriptor): string {
+  return (path.join(path.dirname(browserPath), `playwright-extract-${browser.name}-${hostPlatform}-${browser.revision}`));
+}
+
+export function isBrowserZipFile(aPath: string): boolean {
+  const baseName = path.basename(aPath);
+  return baseName.startsWith('playwright-download-') && baseName.endsWith('.zip');
```
[the remark this answers is not in the document]
Comment (aslushnikov) [reply src/install/browserPaths.ts]: done
