### PR TITLE
fix(codegen): place toolbar on top of top layer

### LINKED ISSUE #39095: [Bug]: Regression ARIA snapshot controls/selection appear behind Angular Material Dialog (cannot see what is snapshotted)
### Version

1.58.1

### Steps to reproduce

When using the Playwright VS Code extension to capture an ARIA snapshot on a page with an Angular Material MatDialog open, the extension’s ARIA snapshot UI (buttons, selection overlay/feedback) appears behind the modal. As a result, it’s not possible to see which element/region is being snapshotted  while the dialog is visible.
This is reproducible on Angular Material’s official dialog examples page.
Navigate to Angular Material dialog examples: https://material.angular.dev/components/dialog/examples.
Click “Open dialog without animation” (or any “Open dialog”) to show a modal dialog.
In the Playwright extension’s Locators/ARIA panel, attempt to pick or preview an ARIA snapshot for the dialog content (or for body).
Actual: the ARIA snapshot UI (buttons/selection highlighting) appears behind the modal dialog, making it unclear what aria tree is being captured, and preventing practical use.

https://github.com/user-attachments/assets/75b12f76-89a1-4646-8d34-311dfd7ef780

### Expected behavior

The Playwright VS Code extension’s ARIA snapshot UI and selection/highlight overlays should remain visible and on top of application UI (including modals), so users can see which node/region is being snapshotted and operate the controls.

### Actual behavior

With MatDialog open, the extension’s ARIA snapshot UI/overlay appears behind the dialog. The snapshot may still be captured, but users cannot see what is selected or interact reliably with the UI.

### Additional context

_No response_

### Environment

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 14.79 GB / 31.73 GB
  Binaries:
    Node: 24.10.0 - C:\nvm4w\nodejs\node.EXE
    npm: 11.7.0 - C:\nvm4w\nodejs\npm.CMD
  IDEs:
    VSCode: 1.108.2 - C:\Progs\Microsoft VS Code\bin\code.CMD
    Claude Code: 2.1.17 - C:\nvm4w\nodejs\claude.CMD
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/39095.

I did some manual testing of the UI and it still looks the same.

### CODE REVIEW

File: packages/injected/src/highlight.ts [hunk 1]
```diff
@@ -80,6 +85,37 @@ export class Highlight {
       this._glassPaneShadow.appendChild(styleElement);
     }
     this._glassPaneShadow.appendChild(this._actionPointElement);
+
+    this._injectedScript.document.addEventListener('toggle', this._onTopLayerChange, true);
+    this._dialogObserver = new injectedScript.window.MutationObserver(this._onOpenMutation);
+    this._dialogObserver.observe(this._injectedScript.document, { subtree: true, attributes: true, attributeFilter: ['open'] });
```
Comment (dgozman) [inline packages/injected/src/highlight.ts]: This needs to be done in `install()`, and all observers/listeners should be reset. See `Recorder.installListeners()` for an example.

File: packages/injected/src/highlight.ts [hunk 2]
```diff
@@ -80,6 +85,37 @@ export class Highlight {
       this._glassPaneShadow.appendChild(styleElement);
     }
     this._glassPaneShadow.appendChild(this._actionPointElement);
+
+    this._injectedScript.document.addEventListener('toggle', this._onTopLayerChange, true);
+    this._dialogObserver = new injectedScript.window.MutationObserver(this._onOpenMutation);
```
Comment (dgozman) [inline packages/injected/src/highlight.ts]: I don't think this works in shadow dom.

File: tests/library/inspector/cli-codegen-3.spec.ts [hunk 3]
```diff
@@ -925,6 +925,27 @@ await page.GetByTestId("testid").HoverAsync();`);
...
+        <button>Close</button>
+      </div>
+      <button popovertarget="mypopover">Show Popover</button>
+    `);
+
+    await page.getByRole('button', { name: 'Show Popover' }).click();
+    await expect(page.getByRole('button', { name: 'Close' })).toBeVisible();
+
+    await page.getByTitle('Assert text').click();
+    await page.getByRole('button', { name: 'Close' }).click();
```
Comment (dgozman) [inline tests/library/inspector/cli-codegen-3.spec.ts]: What does this test? Should we expect something after clicking here?

File: tests/library/inspector/cli-codegen-3.spec.ts [hunk 4]
```diff
@@ -925,6 +925,118 @@ await page.GetByTestId("testid").HoverAsync();`);
...
+        };
+      </script>
+    `);
+
+    await page.getByRole('button', { name: 'Open Dialog' }).click();
+    await expect(page.getByRole('button', { name: 'Close Dialog' })).toBeVisible();
+
+    // 10,10 points to the backdrop. when we replay the click on it backdrop,
+    // playwright doesn't target 10,10, but instead it targets the center of the element at 10,10
+    // this happens to be the 'close dialog' button! what should we do?
```
Comment (dgozman) [inline tests/library/inspector/cli-codegen-3.spec.ts]: I think it's ok that playwright clicks in the center and hits the `close dialog` button. I don't think we should do anything about this. Let's update the test so that's not an issue (e.g. move the button) and not mark it as `.fail`.

**Review by dgozman — APPROVED** [review]

**Comment by Skn0tt** [comment]
As discussed I took another attempt at calling `_bringToFront` in response to DOM events instead of periodically, but couldn't get the `should record when top layer popover inside shadow DOM is open` test to pass. So sticking to the current naīve appraoch.
