### PR TITLE
fix: make sure screenshots work when main page context is tampered

### LINKED ISSUE #20434: [BUG] screenshots broken on Firefox in version 1.30.0
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux; Mac
- Node.js version: 16.15.0
- Browser: Firefox

**Code Snippet**

```
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

  18 |     await page.click('text=Carte');
  19 |     await page.waitForTimeout(3000);
> 20 |     await test.expect(page.locator('dn-map')).toHaveScreenshot('map.png', { maxDiffPixelRatio: 0.05 });
     |     ^
  21 |   });
  22 | });
  23 |

    at /Users/jb/projects/decouvertes-nature/e2e/activities-map.spec.ts:20:5

```
**Describe the bug**

A screenshot test that passed with the previous version of Playwright now fails on Firefox since version 1.30.0. Regenerating the screenshot doesn't even work (see the error message above).
Opening the trace file shows this error:

```json
{
  "type": "action",
  "metadata": {
    "id": "call@17",
    "stack": [],
    "apiName": "page.screenshot",
    "internal": false,
    "objectId": "page@4644ee2e3d87a8fe60f397da9ac044f3",
    "pageId": "page@4644ee2e3d87a8fe60f397da9ac044f3",
    "wallTime": 1674810094035,
    "startTime": 350952.257,
    "endTime": 350959.482,
    "type": "Page",
    "method": "screenshot",
    "params": {
      "timeout": 5000,
      "type": "png",
      "caret": "initial"
    },
    "log": [
      "taking page screenshot"
    ],
    "snapshots": [
      {
        "title": "before",
        "snapshotName": "before@call@17"
      },
      {
        "title": "after",
        "snapshotName": "after@call@17"
      }
    ],
    "afterSnapshot": "after@call@17",
    "error": {
      "error": {
        "message": "Unexpected token u in JSON at position 0",
        "stack": "SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Frame.waitForFunctionValueInUtility (/home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/playwright-core/lib/server/frames.js:1381:17)\n    at FFPage.takeScreenshot (/home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/playwright-core/lib/server/firefox/ffPage.js:402:28)\n    at Screenshotter._screenshot (/home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/playwright-core/lib/server/screenshotter.js:262:20)\n    at /home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/playwright-core/lib/server/screenshotter.js:168:22",
        "name": "SyntaxError"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch has 2 fixes:
- screenshot code was accidentally using main page context to fetch
  page layout metrics instead of a utility context
- Avoid usage of `self.eval` inside utility context since it escapes
  Firefox sandbox. This turns out to be an upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1814898

Fixes #20434

### CODE REVIEW

File: packages/playwright-core/src/server/frames.ts [hunk 1]
```diff
@@ -1474,11 +1474,14 @@ export class Frame extends SdkObject {
...
-        const context = await this._mainContext();
+        const context = world === 'main' ? await this._mainContext() : await this._utilityContext();
         const injectedScript = await context.injectedScript();
         const handle = await injectedScript.evaluateHandle((injected, { expression, isFunction, polling, arg }) => {
           const predicate = (): R => {
-            let result = self.eval(expression);
+            // NOTE: make sure to use `eval` instead of `self.eval` due to a bug with sandbox isolation
+            // in firefox.
+            // See https://bugzilla.mozilla.org/show_bug.cgi?id=1814898
+            let result = eval(expression);
```
Comment (dgozman) [inline packages/playwright-core/src/server/frames.ts:1484]: Perhaps only in Firefox, and only in utility context? `eval` in main context could probably be overridden?

Comment (aslushnikov) [reply packages/playwright-core/src/server/frames.ts]: (replaced with globalThis.eval which works correctly)

**Review by dgozman — APPROVED** [review]
