### PR TITLE
fix:  throw error when workers option is not number or percentage

### LINKED ISSUE #31208: [Bug]: In CLI, workers option make NaN.
### Version

1.44.1

### Steps to reproduce

1. gh repo clone microsoft/playwright-examples
2. npm install
3. npx playwright install
4. `npx playwright test -j --project="chromium"` or `npx playwright test --workers --project="chromium"`

### Expected behavior

```
❯ npx playwright test -j --project="chromium"

Error: Workers undefined must be a number or percentage
```

```
❯  npx playwright test --workers --project="chromium"

Error: Workers undefined must be a number or percentage
```

```
❯ npx playwright test --workers b --project="chromium"

Error: Workers b must be a number or percentage
```

### Actual behavior

```
❯ npx playwright test -j --project="chromium"

Running 36 tests using NaN workers
```

```
❯ npx playwright test --workers --project="chromium"

Running 12 tests using NaN workers
```

```
❯ npx playwright test --workers b --project="chromium"

Running 12 tests using NaN workers
```

### Additional context

When passing the workers(or j as a job) option in CLI, sometimes the workers are set to `NaN`.

It would be helpful to show error or default workers or just give 1 worker.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 139.73 MB / 16.00 GB
  Binaries:
    Node: 18.17.0 - ~/.proto/shims/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.2.3 - /opt/homebrew/bin/npm
    pnpm: 9.2.0 - ~/Library/pnpm/pnpm
    bun: 1.0.11 - /opt/homebrew/bin/bun
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

### PR DESCRIPTION
**Pull request by tolluset**
fix: #31208 

Add checking of the workers option in CLI.

Current validation of the config file shows the error to the user, but the wrong input in CLI shows `NaN` instead of showing the error message. 

So I added the error message for the user to realize the wrong input.

### CODE REVIEW

File: packages/playwright/src/common/config.ts [hunk 1]
```diff
@@ -223,6 +223,14 @@ function resolveReporters(reporters: Config['reporter'], rootDir: string): Repor
   });
 }
 
+function resolveWorkes(workers: string) {
```
Comment (chimurai) [inline packages/playwright/src/common/config.ts:226]: nit: typo in function name

```suggestion
function resolveWorkers(workers: string) {
```

**Review by mxschmitt — COMMENTED** [review]
Looks like we want [this (Custom option processing)](https://www.npmjs.com/package/commander#:~:text=.requiredOption().-,Custom%20option%20processing,-You%20may%20specify) instead, so we can validate all the number CLI options. `--workers` is special, since it accepts a % and a number.

**Comment by tolluset** [comment]
> Looks like we want [this (Custom option processing)](https://www.npmjs.com/package/commander#:~:text=.requiredOption().-,Custom%20option%20processing,-You%20may%20specify) instead, so we can validate all the number CLI options. `--workers` is special, since it accepts a % and a number.

@mxschmitt 
Wow, that `requiredOption()` really great to this pattern!

However, the current structure seems to make it difficult to use that option.

The worker options for the tests are defined here.
https://github.com/microsoft/playwright/blob/afacb84a52cb1428becd071252243fc5c264caca/packages/playwright/src/program.ts#L364


But the problem, It doesn't validate the defined settings by `commander.js`, it just adds them. 
https://github.com/microsoft/playwright/blob/afacb84a52cb1428becd071252243fc5c264caca/packages/playwright/src/program.ts#L39-L61


Should I re-structure for making handle this problem? I really like to that! 

However, it would be nice to follow the existing way of validation like in the current PR, what do you think?

File: packages/playwright/src/common/config.ts (hunk 1 above)
Comment (tolluset) [reply packages/playwright/src/common/config.ts:226]: Thanks! I will replace it!

File: packages/playwright/src/common/config.ts [hunk 2]
```diff
@@ -107,7 +107,7 @@ export class FullConfigInternal {
         const cpus = os.cpus().length;
         this.config.workers = Math.max(1, Math.floor(cpus * (parseInt(workers, 10) / 100)));
       } else {
-        this.config.workers = parseInt(workers, 10);
+        this.config.workers = resolveWorkers(workers);
```
Comment (mxschmitt) [inline packages/playwright/src/common/config.ts:110]:
```suggestion
        this.config.workers = parseWorkers(workers);
```

File: packages/playwright/src/common/config.ts [hunk 3]
```diff
@@ -223,6 +223,14 @@ function resolveReporters(reporters: Config['reporter'], rootDir: string): Repor
   });
 }
 
+function resolveWorkers(workers: string) {
```
Comment (mxschmitt) [inline packages/playwright/src/common/config.ts:226]:
```suggestion
function parseWorkers(workers: string) {
```

**Review by mxschmitt — APPROVED** [review]

**Comment by mxschmitt** [comment]
> Should I re-structure for making handle this problem? I really like to that!

I think we can easily add the validation function to `testOptions` as a third value and pass it along. Something like this, the errors get produced are then much better formatted:

```bash
➜  playwright git:(main) ✗ npm run ctest -- --workers b    

> playwright-internal@1.45.0-next ctest
> playwright test --config=tests/library/playwright.config.ts --project=chromium-* --workers b

error: option '-j, --workers <workers>' argument 'b' is invalid. Not a number.
```

via:

```diff
diff --git a/packages/playwright-core/bundles/utils/src/utilsBundleImpl.ts b/packages/playwright-core/bundles/utils/src/utilsBundleImpl.ts
index 49dc61a05..a5fbb4ec4 100644
--- a/packages/playwright-core/bundles/utils/src/utilsBundleImpl.ts
+++ b/packages/playwright-core/bundles/utils/src/utilsBundleImpl.ts
@@ -41,7 +41,7 @@ export const open = openLibrary;
 
 export { PNG } from 'pngjs';
 
-export { program } from 'commander';
+export { program, InvalidArgumentError } from 'commander';
 
 import progressLibrary from 'progress';
 export const progress = progressLibrary;
diff --git a/packages/playwright-core/src/server/webkit/wkPage.ts b/packages/playwright-core/src/server/webkit/wkPage.ts
index e0326072f..3e960e348 100644
--- a/packages/playwright-core/src/server/webkit/wkPage.ts
+++ b/packages/playwright-core/src/server/webkit/wkPage.ts
@@ -713,7 +713,7 @@ export class WKPage implements PageDelegate {
     ];
     if (options.isMobile) {
       const angle = viewportSize.width > viewportSize.height ? 90 : 0;
-      promises.push(this._session.send('Page.setOrientationOverride', { angle }));
+      promises.push(this._pageProxySession.send('Page.setOrientationOverride', { angle }));
     }
     await Promise.all(promises);
   }
diff --git a/packages/playwright-core/src/utilsBundle.ts b/packages/playwright-core/src/utilsBundle.ts
index bb037a1ca..c1c551aa1 100644
--- a/packages/playwright-core/src/utilsBundle.ts
+++ b/packages/playwright-core/src/utilsBundle.ts
@@ -28,6 +28,7 @@ export const minimatch: typeof import('../bundles/utils/node_modules/@types/mini
 export const open: typeof import('../bundles/utils/node_modules/open') = require('./utilsBundleImpl').open;
 export const PNG: typeof import('../bundles/utils/node_modules/@types/pngjs').PNG = require('./utilsBundleImpl').PNG;
 export const program: typeof import('../bundles/utils/node_modules/commander').program = require('./utilsBundleImpl').program;
+export const InvalidArgumentError: typeof import('../bundles/utils/node_modules/commander').InvalidArgumentError = require('./utilsBundleImpl').InvalidArgumentError;
 export const progress: typeof import('../bundles/utils/node_modules/@types/progress') = require('./utilsBundleImpl').progress;
 export const SocksProxyAgent: typeof import('../bundles/utils/node_modules/socks-proxy-agent').SocksProxyAgent = require('./utilsBundleImpl').SocksProxyAgent;
 export const ws: typeof import('../bundles/utils/node_modules/@types/ws') = require('./utilsBundleImpl').ws;
diff --git a/packages/playwright/src/program.ts b/packages/playwright/src/program.ts
index e85f3c491..b98cfb179 100644
--- a/packages/playwright/src/program.ts
+++ b/packages/playwright/src/program.ts
@@ -29,7 +29,7 @@ import type { ConfigCLIOverrides } from './common/ipc';
 import type { FullResult, TestError } from '../types/testReporter';
 import type { TraceMode } from '../types/test';
 import { builtInReporters, defaultReporter, defaultTimeout } from './common/config';
-import { program } from 'playwright-core/lib/cli/program';
+import { program, InvalidArgumentError } from 'playwright-core/lib/utilsBundle';
 export { program } from 'playwright-core/lib/cli/program';
 import type { ReporterDescription } from '../types/test';
 import { prepareErrorStack } from './reporters/base';
@@ -40,7 +40,7 @@ function addTestCommand(program: Command) {
   const command = program.command('test [test-filter...]');
   command.description('run tests with Playwright Test');
   const options = testOptions.sort((a, b) => a[0].replace(/-/g, '').localeCompare(b[0].replace(/-/g, '')));
-  options.forEach(([name, description]) => command.option(name, description));
+  options.forEach(([name, description, validator]) => command.option(name, description, validator));
   command.action(async (args, opts) => {
     try {
       await runTests(args, opts);
@@ -335,7 +335,7 @@ function resolveReporter(id: string) {
 
 const kTraceModes: TraceMode[] = ['on', 'off', 'on-first-retry', 'on-all-retries', 'retain-on-failure', 'retain-on-first-failure'];
 
-const testOptions: [string, string][] = [
+const testOptions: [string, string, ((value: string, previous: string) => string)?][] = [
   ['--browser <browser>', `Browser to use for tests, one of "all", "chromium", "firefox" or "webkit" (default: "chromium")`],
   ['-c, --config <file>', `Configuration file, or a test directory with optional "playwright.config.{m,c}?{js,ts}"`],
   ['--debug', `Run tests with Playwright Inspector. Shortcut for "PWDEBUG=1" environment variable and "--timeout=0 --max-failures=1 --headed --workers=1" options`],
@@ -366,10 +366,19 @@ const testOptions: [string, string][] = [
   ['--ui-host <host>', 'Host to serve UI on; specifying this option opens UI in a browser tab'],
   ['--ui-port <port>', 'Port to serve UI on, 0 for any free port; specifying this option opens UI in a browser tab'],
   ['-u, --update-snapshots', `Update snapshots with actual results (default: only create missing snapshots)`],
-  ['-j, --workers <workers>', `Number of concurrent workers or percentage of logical CPU cores, use 1 to run in a single worker (default: 50%)`],
+  ['-j, --workers <workers>', `Number of concurrent workers or percentage of logical CPU cores, use 1 to run in a single worker (default: 50%)`, myParseInt],
   ['-x', `Stop after the first failure`],
 ];
 
+function myParseInt(value: string) {
+  if (value.endsWith('%'))
+    return value;
+  const parsedValue = parseInt(value, 10);
+  if (isNaN(parsedValue))
+    throw new InvalidArgumentError('Not a number.');
+  return parsedValue;
+}
+
 addTestCommand(program);
 addShowReportCommand(program);
 addListFilesCommand(program);
```

> However, it would be nice to follow the existing way of validation like in the current PR, what do you think?

Your current validation looks also good. We can follow-up with the other. Since yours is also validating when the config input is incorrectly formatted.

**Comment by tolluset** [comment]
I like how your method is closer to option definitions and validation, and the errors are clearer!
