### PR TITLE
fix(upload): detect mime type from file extension

### LINKED ISSUE #896: [BUG] Filetype is not detected on setInputFiles
**Context:**
- Playwright Version: 0.10.0
- Operating System: Linux

```js
await el.setInputFiles('avatar.jpg')
await page.click('input[type=submit]');
```

Expected: filetype to be `image/jpeg`
Actual file:

```
{
  name: 'avatar.jpg',
  type: 'application/octet-stream',
  tmp_name: '/tmp/phpe1S4NZ',
  error: 0,
  size: 5621
}
```
The file is not empty but the file type is not detected. There is a second parameter of filetype in `setInputFiles` where I can specify a filetype. However, I assume this is a bug because the same test passes for all other engines: WebDriver, Puppeteer, TestCafe

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/896

### CODE REVIEW

File: src/platform.ts [hunk 1]
```diff
@@ -213,9 +213,9 @@ export async function closeFdAsync(fd: number): Promise<void> {
   return await promisify(nodeFS.close)(fd);
 }
 
-export function getMimeType(file: string): string | null {
-  assertFileAccess();
-  return mime.getType(file);
+export function getMimeType(file: string): string {
+  const extension = file.substring(file.lastIndexOf('.') + 1);
+  return extensionToMime[extension] || 'application/octet-stream';
```
Comment (dgozman) [inline src/platform.ts]: Please remove `import * as mime from 'mime'` above, and 'mime' entry from `src/web.webpack.config.js`.

File: test/test.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ require('events').defaultMaxListeners *= parallel;
 
 let timeout = process.env.CI ? 30 * 1000 : 10 * 1000;
 if (!isNaN(process.env.TIMEOUT))
-  timeout = parseInt(process.env.TIMEOUT, 10);
+  timeout = parseInt(process.env.TIMEOUT * 1000, 10);
```
Comment (dgozman) [inline test/test.js]: Please undo this.

**Review by dgozman — APPROVED** [review]

File: test/test.js (hunk 2 above)
Comment (pavelfeldman) [reply test/test.js]: let's keep it!
