### PR TITLE
fix(test-runner): do not start web-server when tests are listed

### LINKED ISSUE #35: Specifying the `webServer` in the config seems to partially initiate it
I have the `webServer` configuration specified in my playwright.config.ts file which is setup to run my local webpack dev server.  I'm noticing that when my webpack dev server has `open: true` set, opening the project or expanding a group of Playwright tests will open the URL in my browser.  This leads me to believe that the extension is partially initiating the web server when listing tests.  This also seems to negatively impact performance of the extension due to it doing something with the server.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright-vscode/issues/35

### CODE REVIEW

File: src/test/runner.ts [hunk 1]
```diff
@@ -167,7 +167,7 @@ export class Runner {
       testFiles.forEach(file => allTestFiles.add(file));
     }
 
-    const webServer = config.webServer && await WebServer.create(config.webServer);
+    const webServer = (!list && config.webServer) && await WebServer.create(config.webServer);
     let globalSetupResult: any;
     if (config.globalSetup)
```
Comment (JoelEinbinder) [inline src/test/runner.ts:172]: We are still running globalSetup when we are in this mode. Is there a reason globalSetup runs before the tests are listed? I would have expected it to run right before we partition tests into work.

@dgozman

Comment (dgozman) [reply src/test/runner.ts:172]: https://github.com/microsoft/playwright/issues/7029
https://github.com/microsoft/folio/pull/222

**Review by JoelEinbinder — APPROVED** [review]
Let's land this for now, but think about some kind of watch mode to avoid re-running the globalSetup a million times.
