### PR TITLE
fix: properly rewrite error message

### LINKED ISSUE #2373: [BUG] Chromium won't show the missing dependency warning
**Context:**
- Playwright Version: Tip of the tree / ^1.0.0-next.1590538859422
- Operating System: Docker image: node to have a system without the deps
- Node version: 14
- Browser: Chromium

**Code Snippet**

```javascript
> playwright.chromium.launch({args:["--no-sandbox"]});
Promise { <pending> }
> (node:105) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setAutoAttach): Target closed.
    at /node_modules/playwright/lib/chromium/crConnection.js:130:63
    at new Promise (<anonymous>)
    at CRSession.send (/node_modules/playwright/lib/chromium/crConnection.js:129:16)
    at CRSession.<anonymous> (/node_modules/playwright/lib/helper.js:65:31)
    at Function.connect (/node_modules/playwright/lib/chromium/crBrowser.js:58:27)
    at Chromium._connectToTransport (/node_modules/playwright/lib/server/chromium.js:44:38)
    at Chromium._innerCreateBrowser (/node_modules/playwright/lib/server/browserType.js:104:36)
    at Chromium._innerLaunch (/node_modules/playwright/lib/server/browserType.js:85:34)
(node:105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

> 
```

**Describe the bug**

The process output during start if an error happens will work for Firefox and WebKit. But not for Chromium, see the attached logs. If I set the `DEBUG` environment variable, then I see that a dependency is missing.

### PR DESCRIPTION
**Pull request by aslushnikov**
Error message is included in error's stack, so we should
re-write stack as well.

Fixes #2373

### CODE REVIEW

File: src/debug/stackTrace.ts [hunk 1]
```diff
@@ -79,3 +79,14 @@ export function getCurrentApiCall(prefix = PLAYWRIGHT_LIB_PATH): string {
   }
   return parts.join('.');
 }
+
+export function rewriteErrorMessage(e: Error, newMessage: string): Error {
```
Comment (dgozman) [inline src/debug/stackTrace.ts:83]: Shouldn't we call this in browserType.ts as well?

**Review by dgozman — APPROVED** [review]
