### PR TITLE
fix(reporters): improve detection of output folder clashes

### LINKED ISSUE #28677: [BUG]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 10]
- Browser: [All]
- Other info:

### Source code

Don't think it's needed for this but I'll gladly work on providing one if you think it is.

**Steps**
1) Setup Playwright and add the [built-in list reporter](https://playwright.dev/docs/test-reporters#list-reporter) as one of the reporters.
2) Set Playwright's `outputDir` to `test-results`
3) Set the list reporter `outputFolder` to `test-results-html-report`
4) Run Playwright tests and you will see a `Configuration Error` message like:
```
Configuration Error: HTML reporter output folder clashes with the tests output folder:

html reporter folder: C:\dev\repos\github-personal\playwright-adventures\demos\code-coverage-with-istanbul-via-webpack-babel-plugin\test-results-html-report

test results folder: C:\dev\repos\github-personal\playwright-adventures\demos\code-coverage-with-istanbul-via-webpack-babel-plugin\test-results
```

**Expected**

No `Configuration Error` message should be displayed.

**Actual**

A `Configuration Error` message is displayed.

### Notes

- I believe that, as per the explanation that @mxschmitt gave in [this comment](https://github.com/microsoft/playwright/issues/28610#issuecomment-1854462505), since the `test-results-html-report` directory is not a child of `test-results` directory then there shouldn't be any `Configuration Error` message.
- I believe the problem is in [this `if` condition](https://github.com/microsoft/playwright/blob/af5a23e55ffcf3385ba1410980ad19d4795c89bd/packages/playwright/src/reporters/html.ts#L89C12-L89C12): 
```
if (outputFolder.startsWith(project.outputDir) || project.outputDir.startsWith(outputFolder)) {
...
}
```
Any folder that `startsWith` the same name as the tests output directory will be flagged, even if it's not a child folder.

### PR DESCRIPTION
**Pull request by georg-unterholzner**
When comparing `outputDir` and html-reporter `outputFolder`, we now make sure that both paths end with a forward-slash.

Fixes #28677

### CODE REVIEW

**Comment by georg-un** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by georg-un** [comment]
> @georg-un please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

File: packages/playwright/src/reporters/html.ts [hunk 1]
```diff
@@ -86,8 +86,11 @@ class HtmlReporter extends EmptyReporter {
     this._open = open;
     this._attachmentsBaseURL = attachmentsBaseURL;
     const reportedWarnings = new Set<string>();
+    const normalizePath = (path: string) => path.replace(/\\/g, '/').replace(/([^/])$/, '$1/');
```
Comment (dgozman) [inline packages/playwright/src/reporters/html.ts:89]: Stack Overflow recommends to use `path.relative()` for this, which sounds more robust than wrangling with the slashes: https://stackoverflow.com/questions/37521893/determine-if-a-path-is-subdirectory-of-another-in-node-js.

**Review by dgozman — COMMENTED** [review]
Thank you for the PR!

**Review by dgozman — APPROVED** [review]
Looks great, merging in. Thank you for the PR!
