### PR TITLE
fix(mouse): set PointerEvent.pressure

### LINKED ISSUE #35844: [Bug]: Mouse clicks incorrectly set PointerEvent pressure to 0 on Chromium
### Version

1.52.0

### Steps to reproduce

1. Clone https://github.com/simenbrekken/playwright-pointer-down-pressure-bug
2. `npx playwright test`

### Expected behavior

I expect Chromium to set pressure to 0.5 like with Safari and WebKit [as per the `PointerEvent` specification](https://w3c.github.io/pointerevents/#dom-pointerevent-pressure)

### Actual behavior

Pressure is 0 on Chromium

### Additional context

I discovered this while researching [this React ARIA issue](https://github.com/adobe/react-spectrum/issues/7306)

### Environment

```shell
System:
    OS: macOS 15.4
    CPU: (8) arm64 Apple M3
    Memory: 99.31 MB / 16.00 GB
  Binaries:
    Node: 22.14.0 - ~/Library/pnpm/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.9.2 - ~/Library/pnpm/npm
    pnpm: 10.6.5 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.99.3 - /opt/homebrew/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.52.0 => 1.52.0
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/35844

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crInput.ts [hunk 1]
```diff
@@ -108,7 +108,8 @@ export class RawMouseImpl implements input.RawMouse {
         buttons: toButtonsMask(buttons),
         x,
         y,
-        modifiers: toModifiersMask(modifiers)
+        modifiers: toModifiersMask(modifiers),
+        force: 0.5,
```
Comment (dgozman) [inline packages/playwright-core/src/server/chromium/crInput.ts:112]: Spec says this is 0.5 when `buttons !== 0`, and zero otherwise.

**Review by dgozman — APPROVED** [review]
