### PR TITLE
fix: validate ffmpeg on context creation

### LINKED ISSUE #33899: [Bug]: Stuck if there is no ffmpeg in launchPersistentContext / electron
When recording a video with launchPersistentContext / electron with enabled video it hangs instead of throws an error that ffmpeg is missing.

Problem is that we wait for the page here: 

https://github.com/microsoft/playwright/blob/b3a82bef46e6f704312c441eea17a6bd737c1302/packages/playwright-core/src/server/browserContext.ts#L365

and receive an error here:

https://github.com/microsoft/playwright/blob/4696dd8682be4f644602a89594945e8b0f8f162c/packages/playwright-core/src/server/chromium/crPage.ts#L124

So we should wire

https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/page.ts#L205

together with when we wait for the error./

### PR DESCRIPTION
**Pull request by mxschmitt**
~~Instead of massaging the signal handling so that the first page creation would notify the context I think it might be better to just validate if ffmpeg is there when we create the context.~~

Resolves https://github.com/microsoft/playwright/issues/33899

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crPage.ts [hunk 1]
```diff
@@ -432,6 +432,8 @@ class FrameSession {
       this._firstNonInitialNavigationCommittedFulfill = f;
       this._firstNonInitialNavigationCommittedReject = r;
     });
+    // We do not always await this promise.
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/chromium/crPage.ts:435]: Without that this Promise ends up in Promise unhandled rejection errors - since we set an error to it (inside FrameSession.dispose) but never read the error.

Comment (yury-s) [reply packages/playwright-core/src/server/chromium/crPage.ts:435]: We wait for it in `FrameSession._initialize` which is called for both main frame and OOPIFs soon after the session is created. I guess there may be an exception before this promise is added to the list of awaited promises, but does it happen in reality? If it does, we probably need to update wkPage too.

File: packages/playwright-core/src/server/browserContext.ts [hunk 2]
```diff
@@ -358,29 +359,30 @@ export abstract class BrowserContext extends SdkObject {
...
+      if (pageOrError instanceof Error)
+        throw pageOrError;
     }
-    const pages = this.pages();
-    if (pages[0]._pageIsError)
-      throw pages[0]._pageIsError;
-    await pages[0].mainFrame()._waitForLoadState(progress, 'load');
-    return pages;
+    const pageOrError = await this.pagesOrErrors()[0];
+    if (pageOrError instanceof Error)
```
Comment (yury-s) [inline packages/playwright-core/src/server/browserContext.ts:372]: Can you restructure the code so that `if (pageOrError instanceof Error)` performed just once?

File: packages/playwright-core/src/server/browserContext.ts [hunk 3]
```diff
@@ -358,29 +359,30 @@ export abstract class BrowserContext extends SdkObject {
     this._timeoutSettings.setDefaultTimeout(timeout);
   }
 
-  async _loadDefaultContextAsIs(progress: Progress): Promise<Page[]> {
-    if (!this.pages().length) {
+  async _loadDefaultContextAsIs(progress: Progress): Promise<Page> {
+    if (!this.pagesOrErrors().length) {
       const waitForEvent = helper.waitForEvent(progress, this, BrowserContext.Events.Page);
       progress.cleanupWhenAborted(() => waitForEvent.dispose);
-      const page = (await waitForEvent.promise) as Page;
```
Comment (yury-s) [inline packages/playwright-core/src/server/browserContext.ts:365]: Was this not working before because the page may have been an error already?

File: packages/playwright-core/src/server/chromium/crPage.ts [hunk 4]
```diff
@@ -432,6 +432,7 @@ class FrameSession {
       this._firstNonInitialNavigationCommittedFulfill = f;
       this._firstNonInitialNavigationCommittedReject = r;
     });
+    this._firstNonInitialNavigationCommittedPromise.catch(() => {});
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/crPage.ts:435]: Maybe do it inside `FrameSession._initialize` and add a comment there that we may get an exception before awaiting the promise?

File: tests/installation/playwright-cli-install-should-work.spec.ts [hunk 5]
```diff
@@ -95,3 +95,27 @@ test('install playwright-chromium should work', async ({ exec, installedSoftware
   await exec('npx playwright install chromium');
   await exec('node sanity.js playwright-chromium chromium');
 });
+
+test('should print error if recording video without ffmpeg', async ({ exec }) => {
```
Comment (yury-s) [inline tests/installation/playwright-cli-install-should-work.spec.ts:99]: Do you want to use custom browser path and delete ffmpeg from that path?  otherwise I don't understand this test.

**Review by yury-s — APPROVED** [review]
lgtm % test

File: tests/installation/playwright-cli-install-should-work.spec.ts (hunk 5 above)
Comment (mxschmitt) [reply tests/installation/playwright-cli-install-should-work.spec.ts:99]: We have isolated browsers in this test so Playwright does not find any browsers including ffmpeg. I need a browser to start with tho - for that I use Google Chrome. We have other tests relying on Google Chrome as well.

File: packages/playwright-core/src/server/chromium/crPage.ts (hunk 4 above)
Comment (mxschmitt) [reply packages/playwright-core/src/server/chromium/crPage.ts:437]: added a comment. I think having it close to where the Promise is created is also reasonable. Similar to what we do with `this._stopVideoRecording().catch(() => {});`.

File: tests/installation/playwright-cli-install-should-work.spec.ts (hunk 5 above)
Comment (mxschmitt) [reply tests/installation/playwright-cli-install-should-work.spec.ts]: done.
