### PR TITLE
fix(trace): do not save trace on failure after success in test+hooks

### LINKED ISSUE #34416: [Bug]: Trace data fetched for passed tests from remote playwright server even when trace is set to "retain-on-failure"
### Version

1.49.1, beta

### Steps to reproduce

1. Test File
```ts
import { test } from '@playwright/test';

test('navigation test', async ({ page }) => {
	await page.goto('https://playwright.dev/');
});
```

2. Playwright Config
```ts
import { defineConfig } from 'playwright/test';

export default defineConfig({
	use: {
		connectOptions: {
			wsEndpoint: 'ws://localhost:8080',
		},
		trace: 'retain-on-failure',
	},
});
```

3. Run a playwright server `npx playwright run-server --port 8080`
4. Set DEBUG="pw:channel"
5. Run the tests `npx playwright test`

### Expected behavior

In the channel logs, there should be no message that states that the trace binary was transferred between the remote server and the client.

### Actual behavior

In the channel logs, we see a message which states that the trace binary was transferred between the server and the client.

### Additional context

We don't observe this behavior when setting video to "retain-on-failure". 

### Environment

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 17.24 GB / 31.71 GB
  Binaries:
    Node: 18.20.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.96.4 - C:\Users\ssingharoy\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.50.0-beta-1737179657000 => 1.50.0-beta-1737179657000
```

### PR DESCRIPTION
**Pull request by dgozman**
Previously, we always saved the trace for each context until the very end of the test, and then either repacked them or abandoned depending on the `trace` mode.

However, this could result in downloading large traces from the remote server when the tests succeeded but trace was set to `retain-on-failure`. This slows down remote operations quite a lot.

The fix is to carefully consider whether the trace should be saved or abandoned, based on whether the test and afterEach hooks have finished successfully.

This could be a minor regression, where the trace will not be saved if one of the fixture teardowns fails after the context has been already closed, and trace mode was `retain-on-failure` or `retain-on-first-failure`.

Fixes #34416.

### CODE REVIEW

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright/src/worker/workerMain.ts [hunk 1]
```diff
@@ -399,6 +399,8 @@ export class WorkerMain extends ProcessRunner {
         firstAfterHooksError = firstAfterHooksError ?? error;
       }
 
+      testInfo._tracing.didFinishTestFunctionAndHooks();
```
Comment (yury-s) [inline packages/playwright/src/worker/workerMain.ts:402]: Maybe add a comment why it is not called after 'afterAll' fixture / fixture teardowns below?

**Review by yury-s — APPROVED** [review]
