### PR TITLE
chore: fix Android 13 compatibility

### LINKED ISSUE #15776: [BUG] Playwright for Android does not work with Android 13
Caused by the "Intent filters block non-matching intents"

See here: https://developer.android.com/about/versions/13/behavior-changes-13

This needs to be adjusted: https://github.com/mxschmitt/playwright/blob/1471c526addb1c66a4ae1a259ce045333940a90a/packages/playwright-core/src/server/android/android.ts#L253

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/15776

Some context: https://issuetracker.google.com/issues/236862869

### CODE REVIEW

File: utils/avd_start.sh [hunk 1]
```diff
@@ -16,7 +16,17 @@ if [[ -n "${GITHUB_ACTIONS}" ]]; then
...
 echo "Starting emulator"
-nohup ${ANDROID_HOME}/emulator/emulator -avd android32 -no-audio -no-window -gpu ${EMULATOR_GPU} -no-boot-anim &
+nohup ${ANDROID_HOME}/emulator/emulator -avd android33 -no-audio -no-window -gpu ${EMULATOR_GPU} -no-boot-anim &
 ${ANDROID_HOME}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
 ${ANDROID_HOME}/platform-tools/adb devices
-echo "Emulator started"
\ No newline at end of file
+echo "Emulator started"
+
+echo "Installing Chromium WebView"
```
Comment (mxschmitt) [inline utils/avd_start.sh:24]: There is no WebViewShell installed anymore inside the Android 13 emulator. So I'm installing it manually.

**Review by dgozman — APPROVED** [review]
