### PR TITLE
fix(ui-mode): disconnected error styling

### LINKED ISSUE #28679: [BUG] UI mode in browser: `Reload the page to reconnect` message not displaying properly
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [All]

### Source code

Clone the [ui-mode-ws-reload-bug branch](https://github.com/edumserrano/playwright-adventures/tree/ui-mode-ws-reload-bug) from the [edumserrano/playwright-adventures repo](edumserrano/playwright-adventures).

**Steps**
- After cloning the repo, go to [/demos/docker/](https://github.com/edumserrano/playwright-adventures/tree/ui-mode-ws-reload-bug/demos/docker/README.md) and run `npm i` to restore the npm packages, followed by `npx playwright install` to install the Playwright browsers.
- Run `npm test:ui` to launch the UI mode in docker.
- Open the UI mode in the browser at `http://localhost:8182`.
- Stop the `npm test:ui` command and the message about the UI mode being disconnected shows on the top left of the page but some of it is hidden, namely the link to reload the page.

This bug can be seen on this video:

https://github.com/microsoft/playwright/assets/15857357/2f219221-e39e-4b9d-9f3f-c94a71be2675

**Expected**

I should be able to see the full message about the UI mode being disconnected and I should be able to click the `Reload the page to reconnect` link.

**Actual**

The message is partially visible and the link to `Reload the page to reconnect` is very hard to select.

### LINKED ISSUE #28680: [BUG] UI mode in browser: `Reload the page to reconnect` link doesn't work
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 10]
- Browser: [All]

### Source code

Clone the [ui-mode-ws-reload-bug branch](https://github.com/edumserrano/playwright-adventures/tree/ui-mode-ws-reload-bug) from the [edumserrano/playwright-adventures repo](edumserrano/playwright-adventures).

**Steps**
- After cloning the repo, go to [/demos/docker/](https://github.com/edumserrano/playwright-adventures/tree/ui-mode-ws-reload-bug/demos/docker/README.md) and run `npm i` to restore the npm packages, followed by `npx playwright install` to install the Playwright browsers.
- Run `npm test:ui` to launch the UI mode in docker.
- Open the UI mode in the browser at `http://localhost:8182`.
- Stop the `npm test:ui` command. 
- Run `npm test:ui` to restart the UI mode.
- Click the `Reload the page to reconnect` link.

This bug can be seen on this video:

> [!NOTE]
> In the video, after I restart the UI mode, I then am clicking on the `Reload the page to reconnect` link that is a bit hidden. I've already reported that in #28679
> 

https://github.com/microsoft/playwright/assets/15857357/b69bc2eb-2231-4698-add1-1ec88fee1188

After I restart the UI mode, the `Reload the page to reconnect` keeps the full URL which contains a query string to a WS which no longer exists and therefor the UI mode displays a `Loading...` message on the tests pane for ever (or at least a long time, perhaps there's some time out and there it will reconnect to with a new websocket?).

As shown in the video, even if I try to refresh the page by removing the `ws` query string from the URL it doesn't work. To force a new web socket to be created I had to refresh the page at the base URL, which for this demo was at `http://localhost:8182`.

**Expected**

The `Reload the page to reconnect` link should refresh the page and the tests pane should update properly. Perhaps, what is expected is that the reload link should trigger the process of creating a new websocket. 

**Actual**

The `Reload the page to reconnect` refrehes the current URL but the tests pane stays with a `Loading...` message for ever.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/28679
Fixes https://github.com/microsoft/playwright/issues/28680

Looks like this:

Screenshot 2023-12-18 at 16 42 34

or

Screenshot 2023-12-18 at 16 42 25

Tested on localhost and on GitHub Codespaces.

### CODE REVIEW

File: packages/trace-viewer/src/ui/workbenchLoader.tsx [hunk 1]
```diff
@@ -19,6 +19,7 @@ import * as React from 'react';
 import type { ContextEntry } from '../entries';
 import { MultiTraceModel } from './modelUtil';
 import './workbenchLoader.css';
+import './shared.css';
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/workbenchLoader.tsx:22]: nit: we usually call this `common.css`

File: packages/trace-viewer/src/ui/shared.css [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+  
+  body .drop-target {
+    background: rgba(255, 255, 255, 0.8);
+  }
+  
+  body.dark-mode .drop-target {
+    background: rgba(0, 0, 0, 0.8);
+  }
+  
+  .drop-target .title {
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/shared.css:41]: I'd rather copy the necessary styles and not abuse `.drop-target` for the disconnected message. There is already `.ui-mode .disconnected` style, but I don't see where it is used.

**Review by dgozman — APPROVED** [review]
