### PR TITLE
fix: filter out comments inside fixture destructuring

### LINKED ISSUE #20944: [BUG] [playwright-test] Comment between fixtures results in `Test has unknown parameter <comment>`
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux
- Node.js version: 16
- Browser: irrelevant

**Code Snippet**

When adding comments between fixtures, I get this error:
```
Error: Test has unknown parameter "// eslint-disable-next-line @typescript-eslint/no-unused-vars
      project".

   at tests/project/support.spec.ts:23

  21 |   test.describe.parallel("business plan", () => {
  22 |     test.use({ projectPlan: "business_yearly" })
> 23 |     test("paid options are shown", async ({
     |         ^
  24 |       sharedAccountPage: page,
  25 |       // eslint-disable-next-line @typescript-eslint/no-unused-vars
  26 |       project,
```

Removing the comment fixes the error.

**Describe the bug**

Apparently the comment is mistaken as a fixture parameter. I read other issues like #15189 which are wont-fixes, but I think this should be fixed as it is relevant for ensuring eslint and similar tools can be sufficiently controlled to prevent real test issues.

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #20944

### CODE REVIEW

File: packages/playwright-test/src/common/fixtures.ts [hunk 1]
```diff
@@ -241,11 +241,33 @@ function innerFixtureParameterNames(fn: Function, location: Location, onError: L
...
+    if (commentState === 'singleline') {
+      if (s[i] === '\n')
+        commentState = 'none';
+    } else if (commentState === 'multiline') {
+      if (s[i - 1] === '*' && s[i] === '/')
+        commentState = 'none';
+    } else if (commentState === 'none') {
+      if (s[i] === '/' && s[i + 1] === '/')
+        commentState = 'singleline';
+      else if (s[i] === '/' && s[i + 1] === '*')
```
Comment (dgozman) [inline packages/playwright-test/src/common/fixtures.ts:262]: Let's test `/*/`.

**Review by dgozman — APPROVED** [review]
