### PR TITLE
fix: per-user cache folders

### LINKED ISSUE #21859: [BUG] permission denied accessing '/tmp/playwright-transform-cache'
### System info
- Playwright Version: 1.28.1
- Operating System: Ubuntu 20
- Browser: All
- Other info:

**Steps**
- Run playwright on a system where multiple users have been using it

**Actual**

```
Running 651 tests using 2 workers

Error: EACCES: permission denied, open '/tmp/playwright-transform-cache/3f/connectionFailurespec_3fcb2d59d7f1ac9abe23f187eeeed5065482bbfa.map'

  651 skipped
  1 error was not a part of any test, see above for details

```

The permissions on /tmp/playwright-transform-cache:

```
drwxrwxrwx 162 BrentBaccala BrentBaccala 4096 Mar 21 23:28 /tmp/playwright-transform-cache/
```

`BrentBaccala` is one of the users on the system.  Permissions on some subdirectories:

```
drwxrwxrwx 2 BrentBaccala    BrentBaccala    4096 Feb 21 12:04 3e
drwxr-xr-x 2 MaximKhlobystov MaximKhlobystov 4096 Mar  1 13:44 3f
drwxrwxrwx 2 BrentBaccala    BrentBaccala    4096 Feb 21 12:04 42
```

`MaximKhlobystov` is also a user on the system, and I'm running this test (that's trying to access `3f`) as user `baccala`, so obviously there's a problem.

It looks like Maxim is also running Playwright 1.28.1.

What explanation is there for how this directory `3f` was created with these restrictive permissions?  It surely happened on a previous playwright run, and I really don't know what the exact test configuration was that caused this.  The directory is dated March 1, and today is March 21, so reproducing exactly what caused this might be problematic (if it isn't obvious to somebody).

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes https://github.com/microsoft/playwright/issues/21859

### CODE REVIEW

File: packages/playwright-test/src/common/compilationCache.ts [hunk 1]
```diff
@@ -27,7 +27,11 @@ export type MemoryCache = {
 };
 
 const version = 13;
-const cacheDir = process.env.PWTEST_CACHE_DIR || path.join(os.tmpdir(), 'playwright-transform-cache');
+
+const DEFAULT_CACHE_DIR_WIN32 = path.join(os.tmpdir(), `playwright-transform-cache`);
+const DEFAULT_CACHE_DIR_POSIX = path.join(os.tmpdir(), `playwright-transform-cache-` + os.userInfo().username);
```
Comment (dgozman) [inline packages/playwright-test/src/common/compilationCache.ts:32]: Are we sure `username` is safe to use in file paths?

**Review by dgozman — APPROVED** [review]

File: packages/playwright-test/src/common/compilationCache.ts (hunk 1 above)
Comment (aslushnikov) [reply packages/playwright-test/src/common/compilationCache.ts]: According to https://unix.stackexchange.com/a/157431/323684 - seems to be safe on Debian. However, I added sanitization - just in case.

**Comment by daydayhappychao** [comment]
Same issue as https://github.com/microsoft/playwright/issues/21859.
I really want to use this update, when will it be merged into the online version ?

File: packages/playwright-test/src/common/compilationCache.ts [hunk 2]
```diff
@@ -27,7 +28,11 @@ export type MemoryCache = {
 };
 
 const version = 13;
-const cacheDir = process.env.PWTEST_CACHE_DIR || path.join(os.tmpdir(), 'playwright-transform-cache');
+
+const DEFAULT_CACHE_DIR_WIN32 = path.join(os.tmpdir(), `playwright-transform-cache`);
+const DEFAULT_CACHE_DIR_POSIX = path.join(os.tmpdir(), `playwright-transform-cache-` + sanitizeForFilePath(os.userInfo().username));
```
Comment (pei-wang) [inline packages/playwright-test/src/common/compilationCache.ts:33]: Hi @aslushnikov 
I encountered some issue which caused by `os.userInfo()`. u may want to use the alternative what Cypress use.
https://github.com/cypress-io/cypress/pull/17488

Comment (mxschmitt) [reply packages/playwright-test/src/common/compilationCache.ts:33]: Please file an GitHub issue, thanks!
