### PR TITLE
Revert "fix(codegen): fix unselect issue (#32127)"

### LINKED ISSUE #33064: [Bug] concurrent selectOption infers which each-other on WebKit + Linux
See a test here: https://github.com/microsoft/playwright/pull/33060

### PR DESCRIPTION
**Pull request by mxschmitt**
This reverts commit 5121b19ac618432c9203282c07d8448b4889869d.

the tree is red and fixing seems non-trivial.

closes https://github.com/microsoft/playwright/issues/33064
Closes https://github.com/microsoft/playwright/pull/33060

### CODE REVIEW

File: packages/playwright-core/src/server/codegen/javascript.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ export class JavaScriptLanguageGenerator implements LanguageGenerator {
       case 'navigate':
         return `await ${subject}.goto(${quote(action.url)});`;
       case 'select':
-        return `await ${subject}.${this._asLocator(action.selector)}.selectOption(${formatObject(action.options.length === 1 ? action.options[0] : action.options)});`;
+        return `await ${subject}.${this._asLocator(action.selector)}.selectOption(${formatObject(action.options.length > 1 ? action.options : action.options[0])});`;
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/codegen/javascript.ts:109]: maybe just remove the test since to fix seems fine to land without a test?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/server/codegen/javascript.ts (hunk 1 above)
Comment (mtsmfm) [reply packages/playwright-core/src/server/codegen/javascript.ts:109]: @mxschmitt Shall I just submit a PR without test then?

Comment (mxschmitt) [reply packages/playwright-core/src/server/codegen/javascript.ts:109]: That should work, fix seems non confrontational to land without a test.
