### PR TITLE
fix(trace): operate trace uri, not path

### LINKED ISSUE #38551: [Regression]: UI does not update actions (and more) for a re-run
### Last Good Version

1.56

### First Bad Version

1.57

### Steps to reproduce

1. Open UI mode
2. Run a test that passes
3. Change the test such that test now fails,  e.g. comment out `page.goto` call
4. Rerun test

### Expected behavior

To see the actions, network calls etc. for the latest run

### Actual behavior

Seeing actions of previous (successful) run

### Additional context

Succesful run VS run after which fails. Note that the status is changed correctly, but actions and network tab not.

ImageImage

### Environment

```shell
System:
    OS: Linux 6.6 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
    CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
    Memory: 5.41 GB / 19.53 GB
    Container: Yes
  Binaries:
    Node: 22.15.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.2 - /usr/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/38551

### CODE REVIEW

File: utils/limits.sh [hunk 1]
```diff
@@ -0,0 +1,2 @@
+#!/bin/sh
+sudo sysctl -w fs.inotify.max_user_instances=1024
```
Comment (yury-s) [inline utils/limits.sh:2]: revert?

File: packages/playwright-core/src/server/trace/viewer/traceViewer.ts [hunk 2]
```diff
@@ -55,25 +55,26 @@ export type TraceViewerAppOptions = {
...
 
   try {
-    const stat = fs.statSync(traceUrl);
+    const stat = fs.statSync(traceFile);
     // If the path is a directory, add 'trace.dir' which has a special handler.
     if (stat.isDirectory())
-      return path.join(traceUrl, tracesDirMarker);
-    return traceUrl;
+      traceFile = path.join(traceFile, tracesDirMarker);
+    return `file?path=${encodeURIComponent(traceFile)}`;
```
Comment (yury-s) [inline packages/playwright-core/src/server/trace/viewer/traceViewer.ts]: traceFileURL ?

**Review by yury-s — APPROVED** [review]

**Comment by pavelfeldman** [comment]
@cpAdm do you want to review this one? We used to pass absolute file path into traceURL and I replaced it with the uri that contains path + timestamp.

File: packages/trace-viewer/src/ui/sourceTab.tsx [hunk 3]
```diff
@@ -59,7 +59,7 @@ function useSources(stack: StackFrame[] | undefined, selectedFrame: number, sour
         if (!response || response.status === 404)
```
Comment (cpAdm) [inline packages/trace-viewer/src/ui/sourceTab.tsx:59]: Sidenote, related to #38364

This response currently always fails once per test run, since `TraceModel` is initiated with empty `traceUri`, due to the `loadSingleTraceFile` call failing inside the polling of `TraceView` (uiModeTraceView.tsx:75).

We could do a check if `model?.traceUri` is truthy instead of just the `model`

File: packages/trace-viewer/src/ui/uiModeTraceView.tsx [hunk 4]
```diff
@@ -65,14 +65,14 @@ export const TraceView: React.FC<{
 
     const traceLocation = [
```
Comment (cpAdm) [inline packages/trace-viewer/src/ui/uiModeTraceView.tsx:66]: Fetching this resource always fails

File: packages/trace-viewer/src/sw/main.ts [hunk 5]
```diff
@@ -88,40 +88,39 @@ async function loadTraceOrError(clientId: string, url: URL, isContextRequest: bo
   }
 }
 
-function loadTrace(clientId: string, url: URL, isContextRequest: boolean, progress: Progress): Promise<LoadedTrace> {
-  const traceUrl = url.searchParams.get('trace')!;
-  if (!traceUrl)
+function loadTrace(clientId: string, url: URL, progress: Progress): Promise<LoadedTrace> {
+  const traceUri = url.searchParams.get('trace')!;
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:92]: nit: Bang is not needed here

**Review by cpAdm — COMMENTED** [review]
Can confirm that these changes fixes the related issue. But whilst add it, I think we should try to solve #38364 as well

File: packages/trace-viewer/src/ui/sourceTab.tsx (hunk 3 above)
Comment (pavelfeldman) [reply packages/trace-viewer/src/ui/sourceTab.tsx:59]: we need to sort it out separately, i'm just removing annoying message as a drive-by

File: packages/trace-viewer/src/ui/uiModeTraceView.tsx (hunk 4 above)
Comment (pavelfeldman) [reply packages/trace-viewer/src/ui/uiModeTraceView.tsx:66]: What do you mean? No live traces tests would pass if this failed.
