### PR TITLE
fix(webkit): use new protocol methods for bindings

### LINKED ISSUE #14745: [BUG] exposeBinding() breaks in Webkit on a certain page
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: v17.8.0
- Browser: WebKit
- Extra: nothing special

**Code Snippet**

```typescript
import { test, expect, Page, Frame } from "@playwright/test";

test.describe('xxx', async () => {
  test(`test exposeBinding`, async ({ page }) => {
    const url = "https://www.dastelefonbuch.de/"; // fails with this url
    // const url = "https://example.com/"; // works with this url
    await page.exposeBinding("exposedFn", messageCallback);
    await page.goto(url, { waitUntil: "commit" });

    let received = null;

    async function messageCallback({ frame }: { frame: Frame }, msg: any) {
      console.log("RECEIVED MESSAGE", msg);
      received = msg;
    }

    await page.waitForTimeout(1000); // seems to be important. I suspect the page is messing up the global context upon initialization

    console.log('trying to call the exposed function...');
    await page.evaluate(
      'exposedFn({ hello: "there" })'
    ); // hangs here
    console.log('...done');

    expect(received).toEqual({ hello: "there" });
  });
});

```

**Describe the bug**

The callback exposed with `Page.exposeBinding()` stops working on a specific page: https://www.dastelefonbuch.de/. It does seem to exist in page context, but the payload is never delivered to playwright scope.
It works when I change the URL or the browser, so it's really specific to WebKit and this particular website.

I run the above code with `npx playwright test doit.spec.ts --browser webkit`, so there's no extra config.

### PR DESCRIPTION
**Pull request by yury-s**
Fixes #14745

### CODE REVIEW

File: packages/playwright-core/src/server/webkit/wkPage.ts [hunk 1]
```diff
@@ -522,6 +524,15 @@ export class WKPage implements PageDelegate {
     this._contextIdToContext.set(contextPayload.id, context);
   }
 
+  private async _onBindingCalled(contextId: any, name: any, argument: any) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkPage.ts:527]: Change `any` to actual types?

File: tests/page/page-expose-function.spec.ts [hunk 2]
```diff
@@ -300,3 +300,13 @@ it('should serialize cycles', async ({ page }) => {
...
   expect(object).toEqual(a);
 });
+
+it('should work with overridden console object', async ({ page }) => {
+  await page.evaluate(() => window.console = null);
+  expect(page.evaluate(() => window.console === null)).toBeTruthy();
+  await page.exposeFunction('__pw_add', function(a, b) {
+    return Promise.resolve(a + b);
+  });
+  await (page as any)._removeExposedBindings();
```
Comment (dgozman) [inline tests/page/page-expose-function.spec.ts:310]: Let's drop this line.

**Review by dgozman — APPROVED** [review]
