### PR TITLE
fix(trace): make locator picker work for iframes

### LINKED ISSUE #26878: [BUG]: locator picker not working in iframe in UI mode
### System info
- Playwright Version: [^1.38.0-alpha-sep-4-2023]
- Operating System: [Mac]
- Browser: [Chromium]
- Other info:

### Source code

- [yes ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.goto('https://stackblitz.com/');
  await page.getByRole('button', { name: 'Vite' }).click();
  await page.getByRole('link', { name: 'vanilla Vite' }).click();
  const iframe = page.frameLocator('iframe[title="Preview page"]')
  await iframe.getByRole('button', { name: 'count is 0' }).click();
  await expect(iframe.getByRole('button', { name: 'count is 1' })).toBeVisible();
});
```

**Steps**
- [Run the test]
- [Open UI mode]
- [try to use locator picker to get the button with count is 1]

**Expected**
It should give me the locator when I use the pick locator option

**Actual**

it just acts like a webpage rather than giving me a locator

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/26878

### CODE REVIEW

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/injected/recorder.ts [hunk 1]
```diff
@@ -82,13 +80,20 @@ export class Recorder {
...
   }
 
-  setUIState(state: UIState) {
+  setUIState(state: UIState, delegate: RecorderDelegate) {
+    this._delegate = delegate;
+
+    if (state.mode !== 'none' || state.actionSelector)
+      this.refreshListenersIfNeeded();
+    else
+      removeEventListeners(this._listeners);
```
Comment (dgozman) [inline packages/playwright-core/src/server/injected/recorder.ts:89]: This must uninstall the highlight, otherwise line 58 will prevent the listeners from being added next time we change `state.mode`.

File: packages/trace-viewer/src/ui/snapshotTab.tsx [hunk 2]
```diff
@@ -227,37 +227,54 @@ export const InspectModeController: React.FunctionComponent<{
...
     }
-    if (!recorder) {
-      const injectedScript = new InjectedScript(win, false, sdkLanguage, testIdAttributeName, 1, 'chromium', []);
-      recorder = new Recorder(injectedScript, {
+
+    for (const { recorder, frameSelector } of recorders) {
+      const actionSelector = locatorOrSelectorAsSelector(sdkLanguage, highlightedLocator, testIdAttributeName);
+      recorder.setUIState({
+        mode: isInspecting ? 'inspecting' : 'none',
+        actionSelector,
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/snapshotTab.tsx:241]: I wonder what happens when `actionSelector` has a `.frameLocator()` inside? For example, what if user edits iframe's locator inside the codemirror?
