### PR TITLE
fix: swallow expect.soft errors inside successful toPass matcher

### LINKED ISSUE #20437: [Feature] Expect.toPass to work with soft asserts
After some test actions, I load a complex object via API and check its structure by multiple soft asserts.
This structure doesn't update fast so the API call might return the object with obsolete data.
I tried wrapping these soft asserts like

```typescript
await expect(async () => {
   const myObject = await getObjectViaApi();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   expect.soft(myObject).toHaveSomething();
   console.log(test.info().errors.count);
}).toPass();
```

But the test fails and the console output looks like
7
14
21
28
35
35
35
35
35

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #20437

### CODE REVIEW

File: packages/playwright-test/src/common/testInfo.ts [hunk 1]
```diff
@@ -246,6 +252,20 @@ export class TestInfoImpl implements TestInfo {
     this.errors.push(error);
   }
 
+  _saveTestState(): TestInfoState {
```
Comment (dgozman) [inline packages/playwright-test/src/common/testInfo.ts:255]:
```suggestion
  _saveErrorState(): TestInfoErrorState {
```

File: packages/playwright-test/src/matchers/matchers.ts [hunk 2]
```diff
@@ -317,11 +319,24 @@ export async function toPass(
     timeout?: number,
   } = {},
 ) {
+  const testInfo = currentTestInfo();
+  if (!testInfo)
+    throw new Error(`toPass() must be called during the test`);
```
Comment (dgozman) [inline packages/playwright-test/src/matchers/matchers.ts:324]: Let's avoid this hard dependency and do things conditionally.

File: packages/playwright-test/src/matchers/matchers.ts [hunk 3]
```diff
@@ -317,11 +319,24 @@ export async function toPass(
...
+  // We want to revert this later if the matcher is actually passing.
+  // See https://github.com/microsoft/playwright/issues/20437
+  let testStateBeforeToPassMatcher: undefined|TestInfoState;
   const result = await pollAgainstTimeout<Error|undefined>(async () => {
     try {
+      if (testStateBeforeToPassMatcher)
+        testInfo._restoreTestState(testStateBeforeToPassMatcher);
+      testStateBeforeToPassMatcher = testInfo._saveTestState();
       await callback();
+      if (testInfo.errors.length !== testStateBeforeToPassMatcher.errors.length)
```
Comment (dgozman) [inline packages/playwright-test/src/matchers/matchers.ts:338]:
```suggestion
      if (testInfo.errors.length > testStateBeforeToPassMatcher.errors.length)
```

File: packages/playwright-test/src/matchers/matchers.ts [hunk 4]
```diff
@@ -339,5 +354,6 @@ export async function toPass(
 
     return { message, pass: this.isNot };
   }
-  return { pass: !this.isNot, message: () => '' };
+  const pass = !this.isNot;
+  return { pass, message: () => '' };
```
Comment (dgozman) [inline packages/playwright-test/src/matchers/matchers.ts:358]: nit: might as well undo this

**Review by dgozman — APPROVED** [review]
