### PR TITLE
fix(html): put HTML report next to `package.json` by default

### LINKED ISSUE #12970: output throwaway artifacts relative to package.json
See https://docs.google.com/spreadsheets/d/1y_F6eNNiClyY-Eg1hFQZGH7v6-dobxyouFlgUBLNwSg/edit?usp=sharing

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #12970

### CODE REVIEW

File: packages/playwright-test/src/loader.ts [hunk 1]
```diff
@@ -99,6 +99,7 @@ export class Loader {
     const configUse = mergeObjects(this._defaultConfig.use, config.use);
     config = mergeObjects(mergeObjects(this._defaultConfig, config), { use: configUse });
 
+    (this._fullConfig as any).__configDir = configDir;
```
Comment (dgozman) [inline packages/playwright-test/src/loader.ts:102]: You should rebase on top of FullConfigInternal by Ross.

File: packages/playwright-test/src/reporters/html.ts [hunk 2]
```diff
@@ -174,7 +174,12 @@ export function htmlReportFolder(outputFolder?: string): string {
 }
 
 function defaultReportFolder(): string {
-  return path.resolve(process.cwd(), 'playwright-report');
+  let basePath = getPackageJsonPath(process.cwd());
```
Comment (dgozman) [inline packages/playwright-test/src/reporters/html.ts:177]: Why not `getPackageJsonPath(configDir)`?

**Review by dgozman — APPROVED** [review]
