### PR TITLE
fix(ct): resolve paths before detecting JS

### LINKED ISSUE #29302: [REGRESSION]: Wrong enum value when imported from another file
I am doing react component testing

**Context:**
- GOOD Playwright Version: 1.41.0
- BAD Playwright Version: 1.41.2
- Operating System: [e.g. Windows, Linux or Mac]: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

```js
// CreateSignature.types.ts

 export enum ALLOWED_TABS {
  DRAW = "DRAW",
  TYPE = "TYPE",
  IMAGE = "IMAGE",
}
```

```js
// x.spec.tsx
import { ALLOWED_TABS } from "../CreateSignature.types";

console.log(ALLOWED_TABS);

// This gives
// {
//  __pw_type: 'importRef',
//  id: 'recipes_src_components_CreateSignature_CreateSignature_types_ts_ALLOWED_TABS'
// }
```

When we define `ALLOWED_TABS` in other file and import it,

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/29302

### CODE REVIEW

File: packages/playwright-ct-core/src/tsxTransform.ts [hunk 1]
```diff
@@ -142,27 +142,32 @@ function collectJsxComponentUsages(node: T.Node): Set<string> {
   return names;
 }
 
-export type ImportInfo = {
-  id: string;
+export type ResolvedImportSource = {
```
Comment (dgozman) [inline packages/playwright-ct-core/src/tsxTransform.ts:145]: No need for export, I think.

**Review by dgozman — APPROVED** [review]

**Review by dgozman — APPROVED** [review]
