### PR TITLE
fix(client-certificates): auto detect proxy in the browser

### LINKED ISSUE #36775: [Docs]: ? Skip TLS Client Certificates request
Hi Playwright team,

I'm currently facing an issue with handling a TLS client certification popup when using Playwright.
Specifically, I'm trying to skip this popup so that I can proceed with the two-factor authentication process on my website.
I've attempted to set up the context with client certificates using the following Python code:

```
context = await browser.new_context(
    client_certificates=[
        {
            "origin": "https://website.net",
            "pfxPath": "",
            "passphrase": "",
        }
    ],
)
```
However, this approach results in an error, and I'm unable to bypass the popup.
My goal is to programmatically press "Cancel" in the TLS client certificate popup and continue with the authentication flow.

Could you please provide guidance on how to handle this scenario effectively?
Is there a recommended way to interact with such popups using Playwright, or any workaround to achieve this?

Thank you for your assistance!

### PR DESCRIPTION
**Pull request by mxschmitt**
**Background**

Client certificates affect two components in Playwright:
1. Fetch API
2. Browser

This patch addresses (2). In the Fetch API (1), we don’t auto-detect the HTTP_PROXY/HTTPS_PROXY environment variables by design, so no changes are needed there.

However, in the browser, proxy auto-detection typically works—unless the user sets client certificates. In that case, Playwright uses a SOCKS proxy to intercept TLS traffic. When this happens, the browser is unaware of any system-wide proxy configuration, because the user (i.e. Playwright) has explicitly set up a proxy already.

To fix this, we now auto-detect the HTTP_PROXY/HTTPS_PROXY environment variables inside our internal SOCKS proxy. This enables Playwright to keep working in enterprise environments without requiring users to manually re-specify the proxy.

---

Fixes
- Enables auto-detection of system proxies when using client certificates in the browser.
- Resolves: https://github.com/microsoft/playwright/issues/36775
- Fixes finding (1) from https://github.com/microsoft/playwright/issues/36775#issuecomment-3113136338

### CODE REVIEW

File: packages/playwright-core/src/server/socksClientCertificatesInterceptor.ts [hunk 1]
```diff
@@ -274,6 +276,13 @@ export class ClientCertificatesProxy {
     loadDummyServerCertsIfNeeded();
   }
 
+  getProxyAgent(host: string, port: number) {
+    const proxyFromEnv = getProxyForUrl(`https://${host}:${port}`);
+    if (proxyFromEnv)
```
Comment (yury-s) [inline packages/playwright-core/src/server/socksClientCertificatesInterceptor.ts:284]: Why can't the user do it in their configuration?

File: packages/playwright-core/src/server/socksClientCertificatesInterceptor.ts [hunk 2]
```diff
@@ -274,6 +276,13 @@ export class ClientCertificatesProxy {
...
+      return createProxyAgent({ server: proxyFromEnv });
+    return createProxyAgent(this._proxy);
```
Comment (yury-s) [inline packages/playwright-core/src/server/socksClientCertificatesInterceptor.ts]: If the user config specifies a proxy explicitly, we should prioritize that, similar to how the browser would use it instead of the env var.

File: packages/playwright-core/src/server/socksClientCertificatesInterceptor.ts (hunk 1 above)
Comment (mxschmitt) [reply packages/playwright-core/src/server/socksClientCertificatesInterceptor.ts:284]: Browsers make it work out of the box, would be great if we can make it work out of the box as well to match browser behaviour.

File: tests/library/client-certificates.spec.ts [hunk 3]
```diff
@@ -371,6 +371,49 @@ test.describe('browser', () => {
...
+    await page.goto(serverURL);
+    const host = browserName === 'webkit' && isMac ? 'localhost' : '127.0.0.1';
+    expect([...new Set(proxyServer.connectHosts)]).toEqual([`${host}:${new URL(serverURL).port}`]);
+    await expect(page.getByTestId('message')).toHaveText('Hello Alice, your certificate was issued by localhost!');
+    await page.close();
+    delete process.env.HTTPS_PROXY;
+  });
+
+  test('should pass with matching certificates and when a http proxy is used from config but env is there', async ({ browser, startCCServer, asset, browserName, proxyServer, isMac }) => {
+    process.env.HTTPS_PROXY = `http://this-should-not-taken-into-account:424242`;
```
Comment (yury-s) [inline tests/library/client-certificates.spec.ts]: Use a valid port number (< 65,535) ?

**Review by yury-s — APPROVED** [review]
