### PR TITLE
fix: update performance.now() when calling in a busy loop

### LINKED ISSUE #35362: [Bug]: Unexpected timeout when .clock() is used
### Version

1.51.0

### Steps to reproduce

1. Clone the repository https://github.com/tetiana-kolos/pw-repro
2. Open the file ClockBug.spec.ts

**I. _For Test ONE:_**
1. Run the Test ONE in the debug mode (--debug)
2. Try to inspect elements during page.pause()

**II. _For Test TWO:_**
1. Run Test TWO in the ui mode

### Expected behavior

**I. _For Test ONE:_**
The test is PASSED without hanging

**II. _For Test TWO:_**
The test is FAILED on the test timeout, not the global 10 min timeout

### Actual behavior

Both tests demonstrate unexpected behavior when `.clock()` is used. See below:

**I. _For Test ONE:_**
1. Browser is stuck and is not interactable (e.g. it's not possible to inspect elements)
2. The test does NOT fail, but hangs until the global timeout
Repro video recording: https://github.com/user-attachments/assets/5290d10e-a4be-4020-b031-a5ec6fe01513

**II. _For Test TWO:_**
The test does NOT fail on the test timeout, but is finished on the global timeout
Repro video recording: https://github.com/user-attachments/assets/26c7fcb4-efef-4404-9f3a-3091cb6954eb

### Additional context

Run tests during UTC working hours - from 7:00 UTC till 19:00 UTC, as the test environment sleeps during the night

### Environment

```shell
System:
    OS: macOS 12.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.13 GB / 16.00 GB
  Binaries:
    Node: 22.13.1 - ~/.nvm/versions/node/v22.13.1/bin/node
    npm: 10.9.2 - ~/.nvm/versions/node/v22.13.1/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.51.0 => 1.51.0 
    playwright: 1.51.0 => 1.51.0
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/35362

### CODE REVIEW

File: packages/playwright-core/src/server/injected/clock.ts [hunk 1]
```diff
@@ -119,9 +119,21 @@ export class ClockController {
 
   performanceNow(): DOMHighResTimeStamp {
     this._replayLogOnce();
+    this._syncRealTimeBusyLoop();
```
Comment (dgozman) [inline packages/playwright-core/src/server/injected/clock.ts:122]: Shouldn't we do the same for `Date.now()` and `new Date()` then?

File: tests/library/page-clock.spec.ts [hunk 2]
```diff
@@ -533,3 +533,30 @@ it.describe('Date.now', () => {
...
+  await page.clock.setSystemTime(new Date('2026-01-01'));
+  server.setRoute('/repro.html', (req, res) => {
+    res.writeHead(200, { 'Content-Type': 'text/html' });
+    res.end(`
+      <html>
+        <body>
+          <script>
+          // call performance.now() until 5s has passed
+          const start = performance.now();
+          while (performance.now() - start < 5000) { }
```
Comment (dgozman) [inline tests/library/page-clock.spec.ts:552]: Can we make this `100` to not waste cpu on the bots?

**Review by dgozman — COMMENTED** [review]
I'd like Pavel to review this one, since he is more familiar with internal details of the clock.

File: packages/playwright-core/src/server/injected/clock.ts (hunk 1 above)
Comment (mxschmitt) [reply packages/playwright-core/src/server/injected/clock.ts:122]: I personally would start minimal for now and add it to more stuff if it bubbles up. If you think the likelihood of a user doing this vs. doing the same with `Date.now()` or `new Date()` we should do it for them as well.

Comment (pavelfeldman) [reply packages/playwright-core/src/server/injected/clock.ts:122]: i saw more busy loops on Date.now than performance.now

File: packages/playwright-core/src/server/injected/clock.ts [hunk 3]
```diff
@@ -119,9 +119,21 @@ export class ClockController {
...
     return this._now.ticks;
   }
 
+  private _syncRealTimeBusyLoop() {
+    if (this._realTime) {
+      const now = this._embedder.performanceNow();
+      const sinceLastSync = now - this._realTime.lastSyncTicks;
+      if (sinceLastSync > 0) {
+        this._advanceNow(shiftTicks(this._now.ticks, sinceLastSync));
+        this._realTime.lastSyncTicks = now;
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/injected/clock.ts:132]: We can't have more than one place in code that does this assignment. Addressing it is likely to surface bugs.

File: tests/library/page-clock.spec.ts [hunk 4]
```diff
@@ -437,8 +437,7 @@ it.describe('while running', () => {
     await page.clock.install({ time: 0 });
     await page.goto('data:text/html,');
     await page.clock.pauseAt(1000);
-    await page.waitForTimeout(1000);
-    await page.clock.resume();
+    await page.waitForTimeout(2000); // Should not progress time.
```
Comment (pavelfeldman) [inline tests/library/page-clock.spec.ts:440]: why did this change?

Comment (mxschmitt) [reply tests/library/page-clock.spec.ts:440]: The test looked wrong to me, it was testing that the paused time at 1000 corresponds to the `Date.now()` call. For some unknown reason it resumed the clock afterwards. Was this intentional?

**Review by pavelfeldman — DISMISSED** [review]

File: tests/library/page-clock.spec.ts (hunk 4 above)
Comment (mxschmitt) [reply tests/library/page-clock.spec.ts:440]: Extracted into https://github.com/microsoft/playwright/pull/35522.

**Review by pavelfeldman — APPROVED** [review]
