### PR TITLE
fix: cross-origin Page.goto referer

### LINKED ISSUE #27765: [BUG] referer not set to full url in Firefox
### System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11]
- Browser: [Firefox]

### Source code

**Config file**

```js
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
	trace: 'on',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] }
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] }
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] }
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('referer test', async ({ page }) => {
	await page.goto('https://whatsmyreferer.com/', {referer: 'https://whatsmyreferer.com/test/page/'});
	await page.pause();
})
```

**Steps**
- npx playwright test --browser=chromium --headed refererTest.spec.js
- npx playwright test --browser=webkit --headed refererTest.spec.js
- npx playwright test --browser=firefox --headed refererTest.spec.js

**Expected**

I have tests that are only failing on firefox and its due to the Referer value not being set to the the full url given. I've put together a basic test above to show the issue when using UI mode (npx playwright test --ui and running against each of the browsers) or using via CLI.

The referrer in each case should be "https://whatsmyreferer.com/test/page/" however its just "https://whatsmyreferer.com/" when running in Firefox.

**Actual**
```
npx playwright test --browser=chromium --headed refererTest.spec.js		Your HTTP Referer is : https://whatsmyreferer.com/test/page/

npx playwright test --browser=webkit --headed refererTest.spec.js		Your HTTP Referer is : https://whatsmyreferer.com/test/page/

npx playwright test --browser=firefox --headed refererTest.spec.js		Your HTTP Referer is : https://whatsmyreferer.com/

```

### PR DESCRIPTION
**Pull request by mxschmitt**
- WebKit was working
- Firefox did not pass a refererPolicy before.
- Chromium requires a new parameter as per [here](https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-ReferrerPolicy).

Draft: Waiting for Firefox roll to land.

Fixes https://github.com/microsoft/playwright/issues/27765

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/crPage.ts [hunk 1]
```diff
@@ -587,7 +587,7 @@ class FrameSession {
   }
 
   async _navigate(frame: frames.Frame, url: string, referrer: string | undefined): Promise<frames.GotoResult> {
-    const response = await this._client.send('Page.navigate', { url, referrer, frameId: frame._id });
+    const response = await this._client.send('Page.navigate', { url, referrer, frameId: frame._id, referrerPolicy: 'unsafeUrl' });
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/crPage.ts:590]: Why was it not required before and now we have to add it?

Comment (mxschmitt) [reply packages/playwright-core/src/server/chromium/crPage.ts:590]: By default it has [network::mojom::ReferrerPolicy::kDefault](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/page_handler.cc;l=462;drc=2d0a33ccdfa8ac1a9bdf1d86d3b9138f99484bdf), and if the referer was cross-origin, it did not pass it over. Only the same origin was working. After the change it works cross-origin and align it with the other browsers.

**Review by yury-s — APPROVED** [review]
