### PR TITLE
fix(network): make allHeaders wait until all headers are available

### LINKED ISSUE #14944: [Question]: How can I re-arrange this code to get the comprehensive headers when I visit this page
### Your question

I have the below code and when executed gives a comprehensive response:

```
from playwright.sync_api  import sync_playwright
with sync_playwright() as p:
    test_l = []
    browser = p.chromium.launch_persistent_context(
        channel="chrome",
        user_data_dir = r'path/to/directory',
        headless=False,
        user_agent =  user_agent
        slow_mo = 100        
        )
    page = browser.new_page()

    res = page.goto("https://www.reed.co.uk/candidate-profile")
  
    time.sleep(50)
    page.on("request", lambda request: print(">>", request.method, request.url, request.headers))
```

output:

```
>> GET https://secure.reed.co.uk/authorize?client_id=fhhoJPVALbexeKgJJcaAlpC2iZA4wllb&redirect_uri=https%3A%2F%2Fwww.reed.co.uk%2Fauthentication%2Flogin%2Fcallback&audience=https%3A%2F%2Fwww.reed.co.uk%2F&scope=openid%20profile%20email%20offline_access&response_type=code&response_mode=web_message&state=ZmlRS2FDVldiZUFaQ0VVRXlLUzJycnAzV3VtblZmazIzOFNKUXdSQ1B1cg%3D%3D&nonce=bEh5V2Jab0llMEpNZVVLM3VtQ1NuSHFrbHBlMkpzLlhhQWdWbGpILmFoaQ%3D%3D&code_challenge=KV0AUuplExjF0eV3dc5aoL82BB6R8kmY2r3t1Ud3DqY&code_challenge_method=S256&prompt=none&auth0Client=eyJuYW1lIjoiYXV0aDAtc3BhLWpzIiwidmVyc2lvbiI6IjEuMjIuMCJ9 {'referer': 'https://www.reed.co.uk/', 'upgrade-insecure-requests': '1', 'user-agent': ““}
>> POST https://secure.reed.co.uk/oauth/token {'auth0-client':’’, 'referer': '', 'user-agent': ““, 'content-type': 'application/json'}
>> GET https://api.reed.co.uk/api-bff-candidate-profile/profile/ {'user-agent': ““, 'x-correlation-id': ‘‘, 'referer': 'https://www.reed.co.uk/', 'authorization':’’, 'content-type': 'application/json'}
>> GET https://api.reed.co.uk/api-bff-candidate-profile/lookup/languages/ {'user-agent': ““, 'x-correlation-id': ‘', 'referer': 'https://www.reed.co.uk/', 'authorization': ‘', 'content-type': 'application/json'}
>> GET https://api.reed.co.uk/api-bff-candidate-profile/lookup/countries/ {'user-agent': ““, 'x-correlation-id': '', 'referer': 'https://www.reed.co.uk/', 'authorization': ‘', 'content-type': 'application/json'}
>> GET https://www.reed.co.uk/api/search/GetRecentSearchesOnlyAutocomplete? {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ““}
>> GET https://api.reed.co.uk/api-bff-candidate-profile/lookup/sectors/ {'user-agent': ““, 'x-correlation-id':’’, 'referer': 'https://www.reed.co.uk/', 'authorization':’’, 'content-type': 'application/json'}
>> GET https://api.reed.co.uk/api-bff-candidate-profile/cv/current {'user-agent': ““, 'x-correlation-id':’’, 'referer': 'https://www.reed.co.uk/', 'authorization':’’, 'content-type': 'application/json'}
>> GET https://www.googletagmanager.com/gtag/js?id=GTM-228P {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://cdn-ukwest.onetrust.com/scripttemplates/otSDKStub.js {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://www.googletagmanager.com/gtm.js?id=GTM-228P {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://fonts.gstatic.com/s/redhattext/v3/RrQIbohi_ic6B3yVSzGBrMxYm4Q4HO2E.woff2 {'origin': 'https://www.reed.co.uk', 'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://fonts.gstatic.com/s/redhattext/v3/RrQIbohi_ic6B3yVSzGBrMxY04I4HO2E.woff2 {'origin': 'https://www.reed.co.uk', 'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://cdn-ukwest.onetrust.com/consent/188cee29-2336-4bd7-8d57-25bcd588dc31/188cee29-2336-4bd7-8d57-25bcd588dc31.json {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://www.googletagmanager.com/gtag/js?id=G-R5V3Y98M6D&l=dataLayer&cx=c {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://www.google-analytics.com/analytics.js {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}  
>> GET https://cdn-ukwest.onetrust.com/scripttemplates/6.6.0/otBannerSdk.js {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://www.google-analytics.com/plugins/ua/linkid.js {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> POST https://region1.analytics.google.com/g/collect?v=2&tid=G-R5V3Y98M6D&gtm=2oe6f0&_p=1443069860&_z=ccd.v9B&_gaz=1&cid=989775403.1655359096&ul=en-gb&sr=1280x720&ir=1&_eu=Q&_s=1&dt=Profile%20-%20reed.co.uk&sid=1655437259&sct=5&seg=1&dl=https%3A%2F%2Fwww.reed.co.uk%2Fcandidate-profile&uid=33783569&en=page_view&ep.page_path_clean=%2Fcandidate-profile&upn.candidate_id=33783569&up.candidate_login_state=loggedin {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://www.google.co.uk/ads/ga-audiences?v=1&t=sr&slf_rd=1&_r=4&tid=G-R5V3Y98M6D&cid=989775403.1655359096&gtm=2oe6f0&aip=1&uid=33783569&z=1533702458 {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://cdn-ukwest.onetrust.com/consent/188cee29-2336-4bd7-8d57-25bcd588dc31/44eddb34-a4fd-480e-9410-905a190a60e9/en.json {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://cdn-ukwest.onetrust.com/vendorlist/iab2Data.json {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> GET https://cdn-ukwest.onetrust.com/scripttemplates/6.6.0/otTCF.js {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
>> POST https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j96&tid=UA-41105424-4&cid=989775403.1655359096&jid=2084347585&uid=33783569&gjid=1213508573&_gid=388029566.1655359096&_u=SCCAiEIhBAAAAE~&z=220808306 {'referer': 'https://www.reed.co.uk/', 'user-agent': ““, 'content-type': 'text/plain'}
>> GET https://www.google-analytics.com/collect?v=1&_v=j96&a=1443069860&t=pageview&_s=1&dl=https%3A%2F%2Fwww.reed.co.uk%2Fcandidate-profile&dp=%2Fcandidate-profile&ul=en-gb&de=UTF-8&dt=Profile%20-%20reed.co.uk&sd=24-bit&sr=1280x720&vp=1263x720&je=0&_u=SCCAiEIhB~&jid=2084347585&gjid=1213508573&cid=989775403.1655359096&uid=33783569&tid=UA-41105424-4&_gid=388029566.1655359096&cd2=profile_and_cv&cd1=Profile%20-%20reed.co.uk&cd4=%2Fcandidate-profile&cd5=33783569&cd6=loggedin&cd15=not%20set&cd16=not%20set&cd28=not%20set&cd30=not%20set&cd31=not%20set&cd49=&cd54=https%3A%2F%2Fwww.reed.co.uk%2Fcandidate-profile&cd61=n%2Fa&cd65=n%2Fa&cd66=n%2Fa&cd67=n%2Fa&cd68=n%2Fa&cd71=1655440135890&cd95=n%2Fa&cd96=n%2Fa&cd97=n%2Fa&cd103=&cd105=(not%20set)&cd106=(not%20set)&z=1463767016 {'referer': 'https://www.reed.co.uk/', 'user-agent': ““}
```
I omitted some sensitive information from the output.

However, following doing the same but storing the req.headers in a list falls short. When I followed the advice of [this query](https://github.com/microsoft/playwright-python/issues/1305#issuecomment-1127857580), it worked but did not get the comprehensive headers. 

```
from playwright.sync_api  import sync_playwright
with sync_playwright() as p:
    
    browser = p.chromium.launch_persistent_context(
        channel="chrome",
        user_data_dir = r'path/to/directory',
        headless=False,
        user_agent =  user_agent
        slow_mo = 100        
        )
    page = browser.new_page()


    requests=[]
    def get_req(r):
        
          requests.append((r.method, r.url, r.headers))
          return requests
    
    page.on("request", get_req) 
        
    res = page.goto("https://www.reed.co.uk/candidate-profile")
```
Output from printing list:

`
[('GET', 'https://www.reed.co.uk/candidate-profile', {'upgrade-insecure-requests': '1', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/css/41de46c16c9b5189.css', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/css/acf65625ee00838a.css', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/webpack-a2214e41a7981072.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/framework-5f4595e5518b5600.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/main-06ec44127a586d9c.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/pages/_app-b1f36270450cbf8d.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/8c5eaf36-c1cf244a879ab2c0.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/34-1a7dd2fb78e4e6f2.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/867-548040b84e134355.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/16-b1ce3ba4d7776264.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/chunks/pages/candidate-profile-e3b6d04571f16163.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/XnU7UzVPGZ8j1M746PgdG/_buildManifest.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/XnU7UzVPGZ8j1M746PgdG/_ssgManifest.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://www.reed.co.uk/cdn/web-jobseeker-candidate-profile/_next/static/XnU7UzVPGZ8j1M746PgdG/_middlewareManifest.js', {'referer': 'https://www.reed.co.uk/candidate-profile', 'user-agent': ‘‘}), ('GET', 'https://fonts.gstatic.com/s/redhattext/v3/RrQXbohi_ic6B3yVSzGBrMxQaKct.woff2', {'origin': 'https://www.reed.co.uk', 'referer': 'https://www.reed.co.uk/', 'user-agent': ‘‘}), ('GET', 'blob:https://www.reed.co.uk/ae2d464c-3cc7-4c54-b95a-6f478543eb0a', {'referer': '', 'user-agent': ‘‘})]
`

I did try positioning it like the first example but it returned an empty list.

How would I go about getting the comprehensive req headers like the first example?

### PR DESCRIPTION
**Pull request by dgozman**
Before, calling `allHeaders()` from `page.on('request')` would yield provisional headers instead.

With these changes:
- In Firefox, all headers are available immediately.
- In Chromium, all headers are available upon requestWillBeSentExtraInfo.
- In WebKit, all headers are available upon responseReceived.
- In all browsers, intercepted requests use "provisional" headers
  as all headers, since there is no network stack to change the headers.

Drive-by: migrated Chromium to `hasExtraInfo` flags that simplifies the logic quite a bit.

Fixes #14944.

### CODE REVIEW

**Comment by pavelfeldman** [comment]
This looks backwards to me, I think we recently stumbled upon why existing behavior actually makes sense.

File: packages/playwright-core/src/server/chromium/crNetworkManager.ts [hunk 1]
```diff
@@ -573,92 +553,63 @@ const errorReasons: { [reason: string]: Protocol.Network.ErrorReason } = {
...
   }
 
   requestPaused(request: network.Request, event: Protocol.Fetch.requestPausedPayload) {
-    // requestWillBeSentExtraInfo is not being called when interception
-    // is enabled. But interception is mutually exclusive with the redirects.
-    // So we can use the headers from the Fetch.requestPausedPayload immediately.
+    // We will not receive extra info when intercepting the request.
+    // Use the headers from the Fetch.requestPausedPayload and release the allHeaders()
+    // right away, so that client can call it from the route handler.
     request.setRawRequestHeaders(headersObjectToArray(event.request.headers, '\n'));
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/chromium/crNetworkManager.ts:595]: nit: does not touch `this`.

File: packages/playwright-core/src/server/chromium/crNetworkManager.ts [hunk 2]
```diff
@@ -573,92 +553,63 @@ const errorReasons: { [reason: string]: Protocol.Network.ErrorReason } = {
...
   }
 
-  processResponse(requestId: string, response: network.Response, wasFulfilled: boolean) {
-    // We are not interested in ExtraInfo tracking for fulfilled requests, our Blink
-    // headers are the ones that contain fulfilled headers.
-    if (wasFulfilled) {
-      this._stopTracking(requestId);
+  processResponse(requestId: string, response: network.Response, hasExtraInfo: boolean) {
+    if (!hasExtraInfo) {
+      // Use "provisional" headers as "raw" ones.
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/chromium/crNetworkManager.ts:607]: nit: does not touch `this`.

**Review by pavelfeldman — APPROVED** [review]
