### PR TITLE
fix(websocket): pass through underlying WebSocket protocol

### LINKED ISSUE #33425: [Bug]: routeWebSocket fails
### Version

1.48.2

### Steps to reproduce

- Clone https://github.com/frattaro/playwright-ws-repro
- follow README.md

### Expected behavior

The `routeWebSocket` should succeed

### Actual behavior

`routeWebSocket` fails to connect

### Additional context

The repro sets up a local `ws` server, and tests succeed when using that.

There is a (commented out) call to `routeWebSocket` in the test. The local `ws` server code is the same code as the `routeWebSocket` handler.

When the `routeWebSocket` call is uncommented, the test fails.

As far as I can tell, the (native) `WebSocket` never leaves the `CONNECTING` state.

### Environment

  System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 93.94 MB / 32.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.48.2 => 1.48.2

### PR DESCRIPTION
**Pull request by mxschmitt**
3 modes:

- **pass-through:** We call `ensureOpened` after the server negotiated and set the actual underlying `ws.protocol` setting.
- **mock via protocol as a string:**: There we select the given one.
- **mock via protocol as a string array:**: There we select the first one and pretend this one was negotiated.

Its getting set right before we emit the `open` event. Before its an empty string as per [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/protocol).

Fixes https://github.com/microsoft/playwright/issues/33425.

### CODE REVIEW

File: packages/playwright-core/src/server/injected/webSocketMock.ts [hunk 1]
```diff
@@ -332,6 +332,13 @@ export function inject(globalThis: GlobalThis) {
       if (this.readyState !== WebSocketMock.CONNECTING)
         return;
       this.readyState = WebSocketMock.OPEN;
+      this.protocol = (() => {
```
Comment (dgozman) [inline packages/playwright-core/src/server/injected/webSocketMock.ts:335]: - I don't quite like IIFE when we don't really need it. Can we do if/else chain instead?
- What about `WebSocket.extensions`? Perhaps we should do the same.

Comment (mxschmitt) [reply packages/playwright-core/src/server/injected/webSocketMock.ts]: 1. Done.
2. `WebSocket.extensions` are getting handled by the browser, hence it looks simpler there. should I add a test for it? It would require to enable deflate conditionally in the WS server in `tests/config/testserver/index.ts:81`. Maybe create a WS server inline?

**Review by dgozman — APPROVED** [review]
No need for `extensions` test.
