### PR TITLE
test: ensure tests do not run after globalSetup fail

### LINKED ISSUE #13244: [BUG] When GlobalSetup fails the tests still continue
**Context:**
- Playwright Version: 1.20
- Operating System: Mac
- Node.js version: v16.14.2
- Browser: Chromium

**Describe the bug**

Throwing an error in the globalsetup does not work as expected and prevent the tests from continuing.

Adding the below image from a thread in the Playwright Slack:
image
 

Add any other details about the problem here.

### PR DESCRIPTION
**Pull request by rwoll**
Resolves #13244

### CODE REVIEW

File: packages/playwright-test/types/testReporter.d.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@
 
 import type { FullConfig, FullProject, TestStatus, TestError } from './test';
 export type { FullConfig, TestStatus, TestError } from './test';
+export type {}
```
Comment (rwoll) [inline packages/playwright-test/types/testReporter.d.ts:20]:
```suggestion
```

File: utils/generate_types/overrides-testReporter.d.ts [hunk 2]
```diff
@@ -16,6 +16,7 @@
 
 import type { FullConfig, FullProject, TestStatus, TestError } from './test';
 export type { FullConfig, TestStatus, TestError } from './test';
+export type {}
```
Comment (rwoll) [inline utils/generate_types/overrides-testReporter.d.ts:19]:
```suggestion
```

**Review by pavelfeldman — APPROVED** [review]
