### PR TITLE
fix(click): wait for button, input and select to be enabled before clicking

### LINKED ISSUE #2401: [BUG] Actionability: Playwright does not wait for button to be enabled
Clicking `<button disabled>` or `<span>` inside `<button disabled>`is silently going through. Should be waiting for `disabled` to be dropped.

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #2401.

### CODE REVIEW

File: src/injected/injectedScript.ts [hunk 1]
```diff
@@ -360,15 +360,20 @@ export default class InjectedScript {
...
       const style = element.ownerDocument && element.ownerDocument.defaultView ? element.ownerDocument.defaultView.getComputedStyle(element) : undefined;
-      isDisplayedAndStable = isDisplayedAndStable && (!!style && style.visibility !== 'hidden');
-      lastRect = rect;
-      return !!isDisplayedAndStable;
+      const isVisible = !!style && style.visibility !== 'hidden';
+
+      const elementOrButton = element.closest('button, [role=button]') || element;
+      const isDisabled = ['BUTTON', 'INPUT', 'SELECT'].includes(elementOrButton.nodeName) && elementOrButton.hasAttribute('disabled');
+
+      return isDisplayedAndStable && isVisible && !isDisabled;
```
Comment (pavelfeldman) [inline src/injected/injectedScript.ts:376]: Should we check for disabled before stability because it is cheaper?

**Review by pavelfeldman — APPROVED** [review]

File: src/injected/injectedScript.ts (hunk 1 above)
Comment (dgozman) [reply src/injected/injectedScript.ts:376]: I think we still have to save `lastRect`, so the difference would be negligible.
