### PR TITLE
fix(leak): do not retain test fixtures in worker fixtures

### LINKED ISSUE #14336: pageshot case memory leak
context: 
- playwright version: 1.19.2
- operation System: Linux
- node.js version:  14 & 16
- browser: chromium

I am using pageshot to save images, but the memory increased obvious~
when check code line by line, I find this: It seems pageshot method case a memory leak?

1. **the heap keeps even I didn't use the Buffer**
image
image

2. **and when delete this code, the Retained Size clear**:
image
image

_Originally posted by @roy-k in https://github.com/microsoft/playwright/issues/6319#issuecomment-1133694599_

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes: https://github.com/microsoft/playwright/issues/14336
Affects: https://github.com/microsoft/playwright/issues/6319

### CODE REVIEW

File: packages/playwright-test/src/fixtures.ts [hunk 1]
```diff
@@ -125,9 +130,13 @@ class Fixture {
     if (typeof this.registration.fn !== 'function')
       return;
     try {
-      for (const fixture of this.usages)
+      for (const fixture of this._usages)
         await fixture.teardown(timeoutManager);
-      this.usages.clear();
+      if (this._usages.size !== 0) {
+        // TODO: replace with assert.
```
Comment (yury-s) [inline packages/playwright-test/src/fixtures.ts:136]: Why not do it right away?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-test/src/fixtures.ts (hunk 1 above)
Comment (pavelfeldman) [reply packages/playwright-test/src/fixtures.ts:136]: I was thinking we merge it into 1.22
