### PR TITLE
fix: override cookie even if new is expired

### LINKED ISSUE #17997: [BUG] Set-Cookie is discarded if the expiry is in the past
**Context:**
- Playwright Version: 1.23.0
- Operating System: Windows
- Node.js version: 16.15.1
- Browser: Chromium

**Code Snippet**

```javascript
import { test, APIRequestContext, expect } from "@playwright/test";

let authCookieName = "authCookieName";
let baseUrl = "";

test(`Logout test`, async ({ playwright }) => {
    let apiContext = <APIRequestContext>await playwright.request.newContext({
        baseURL: baseUrl,
    });

    await apiContext.post(`/login`, { data: {/* Login data */ } });     // Sets the authCookie - Set-Cookie: token=tokenvalue ...

    await apiContext.post(`/logout`);                                   // Should remove the authCookie - Set-Cookie: token=; expires=Thu, 01 Jan 1970 00:00:00 GMT

    let storageState = await apiContext.storageState();
    let authCookie = storageState.cookies.filter(cookie => cookie.name == authCookieName);

    expect(authCookie).toHaveLength(0);                                 // Error: Expected length: 0, Received length: 1
});
```

**Describe the bug**

Our backend sets the cookie when the user logs in. When the user logs out we would like to delete that cookie and to do this the backend sends a response with a header like this:

`Set-Cookie: token=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`

In browsers the cookie is properly cleared by this. But with playwright the cookie doesn’t get updated / removed, it stays as it was before.
I think that the correct behavior would be to remove the cookie.
See this example in RFC 6265:

- https://datatracker.ietf.org/doc/html/rfc6265#section-3.1

> Finally, to remove a cookie, the server returns a Set-Cookie header with an expiration date in the past.`

### PR DESCRIPTION
**Pull request by barbaralocsi**
This fixes #17997

### CODE REVIEW

**Comment by barbaralocsi** [comment]
@microsoft-github-policy-service agree [company="{GenTwo}"]

File: packages/playwright-core/src/server/cookieStore.ts [hunk 1]
```diff
@@ -93,12 +91,11 @@ export class CookieStore {
     CookieStore.pruneExpired(set);
```
Comment (yury-s) [inline packages/playwright-core/src/server/cookieStore.ts:91]: Remove this line, it's now done in line 98.

File: tests/library/global-fetch-cookie.spec.ts [hunk 2]
```diff
@@ -206,6 +206,28 @@ it('should store cookie from Set-Cookie header even if it contains equal signs',
   });
 });
 
+it('should override cookie from Set-Cookie header even if it expired', async ({ request, server }) => {
+  server.setRoute('/setcookie.html', (req, res) => {
+    res.setHeader('Set-Cookie', [`a=ok`]);
```
Comment (yury-s) [inline tests/library/global-fetch-cookie.spec.ts:211]: Please also add a test where the cookie is persistent, i.e. has explicit `Max-Age` or `Expires` attribute in the future.

Comment (barbaralocsi) [reply tests/library/global-fetch-cookie.spec.ts:239]: I added a test with expiries in the future. This would also fail before the changes, because `cookieStore` used to keep the old  cookie's expiry.

Comment (yury-s) [reply tests/library/global-fetch-cookie.spec.ts:239]: Nice! This does cover the change in the behavior with the expiry time.

What I meant though is to add another test where the original cookie had an explicit expiry time and then new cookie is received with expiry time in the past which should delete the cookie from the storage. Maybe you can just extend the newly added test to cover that?

**Review by yury-s — APPROVED** [review]

File: tests/library/global-fetch-cookie.spec.ts (hunk 2 above)
Comment (barbaralocsi) [reply tests/library/global-fetch-cookie.spec.ts]: Okay, I extended this test with another cookie that initally has an explicit expiry in the future and later the expiry is set to the past.

**Review by yury-s — APPROVED** [review]

File: tests/library/global-fetch-cookie.spec.ts (hunk 2 above)
Comment (yury-s) [reply tests/library/global-fetch-cookie.spec.ts]: Thanks!
