### PR TITLE
fix(junit reporter): embedding attachments on report didnt work for tests outside root folder

### LINKED ISSUE #15360: [BUG] junit_reporter: embed attachments only works for tests in project root folder
**Context:**
- Playwright Version: 1.23.1
- Operating System: Mac
- Node.js version: v12.18.2
- Browser: All
- Extra: 

## System:
 - OS: macOS 12.4
 - Memory: 1.26 GB / 16.00 GB
## Binaries:
 - Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 8.3.0 - ~/.nvm/versions/node/v12.18.2/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

playwright.config.js
```

```

sample test:

```javascript
    test('Login with valid credentials', async({ page }, testInfo) => {
       await page.goto('https://example.com/');

        // Capture a screenshot and attach it.
        const path = testInfo.outputPath('tmp_screenshot.png');
        await page.screenshot({ path });
        testInfo.attachments.push({ name: 'screenshot.png', path, contentType: 'image/png' });
    });

```

Expected Junit XML report (after running `npx playwright test`):
```xml
<testcase name="Login validations Login with valid credentials" classname="login.spec.js:13:5 › Login validations › Login with valid credentials" time="2.226">
<properties>
<property name="testrun_evidence">
<item name="screenshot.png">
<![CDATA[iVBORw0KGgoAAAANSUhEUgAABQAAAALQCAYAAADPfd1WAAAAAXNSR0IArs4c6QAAIABJREFUeJzs3Xv81/PdP/BHB+TwdbhQDjW09FVR5ComYiGHhGrNYWziYphTOeW6nMIcZpfDLlNsl5nM2ZrFZcmQQ5pDKkSlDNloLHwlJfX7o9/3s759Pt/65rB4736/3brt83m9X+/3+/V+vz9u6/bo9Xo/G02fPn1RAAAAAIBCaryyBwAAAAAAfHkEgAAAAABQYAJAAAAAACgwASAAAAAAFJgAEAAAAAAKTAAIAAAAAAUmAAQAAACAAhMAAgAAAECBCQABAAAAoMAEgAAAAABQYAJAAAAAACgwASAAAAAAFJgAEAAAAAAKTAAIAAAAAAUm....
....
```
**Describe the bug**

The junit reporter has the possibility of embedding attachments as base64. However, the previous code checked for the existence of the attachment based on a wrong check and was not reading it also from the correct path.
The previous code worked fine, if the test was in the project's root folder. If the test was somewhere else, like in ".tests/", then it wouldn't work as expected.

### PR DESCRIPTION
**Pull request by bitcoder**
There was a relative path for attachments that could be embed on the junit XML report; it was obtained for logging purposes; however, the actual attachment path is the one to consider (and it's independent from the relative location of the tests).

fixes #15360 by properly checking the attachment path and reading from the correct path

### CODE REVIEW

File: packages/playwright-test/src/reporters/junit.ts [hunk 1]
```diff
@@ -192,8 +192,8 @@ class JUnitReporter implements Reporter {
               continue;
             try {
               const attachmentPath = path.relative(this.config.rootDir, attachment.path);
```
Comment (aslushnikov) [inline packages/playwright-test/src/reporters/junit.ts:194]: I wonder if this was supposed to be `path.resolve` instead. cc @dgozman

File: packages/playwright-test/src/reporters/junit.ts [hunk 2]
```diff
@@ -192,8 +192,8 @@ class JUnitReporter implements Reporter {
...
-              if (fs.existsSync(attachmentPath))
-                contents = fs.readFileSync(attachmentPath, { encoding: 'base64' });
+              if (fs.existsSync(attachment.path))
+                contents = fs.readFileSync(attachment.path, { encoding: 'base64' });
               else
                 systemErr.push(`\nWarning: attachment ${attachmentPath} is missing`);
```
Comment (dgozman) [inline packages/playwright-test/src/reporters/junit.ts:198]: Let's print `attachment.path` here and drop `attachmentPath` variable altogether?

**Review by dgozman — COMMENTED** [review]
Thank you for the fix, this is indeed an issue.

File: packages/playwright-test/src/reporters/junit.ts (hunk 2 above)
Comment (bitcoder) [reply packages/playwright-test/src/reporters/junit.ts]: done

**Review by dgozman — APPROVED** [review]
