### PR TITLE
fix(test runner): serial suites inside parallel suite should run in parallel

### LINKED ISSUE #15741: [Question] Running parallelly two or more test.describe.serial suites that are located in the single file
**Context:**
- Playwright Version: 1.23.3
- Operating System: macOS Monterey
- Node.js version: 16.15.0
- Browser: any
- Extra: M1 chip

**Code Snippet**

```typescript
//fixture
import { test as base } from '@playwright/test';
import { SearchPage } from '../pages/Search&Apply';
import { SearchFilters } from '../pages/components/SearchFilters';

type SearchFixtures = {
  filters: SearchFilters
}

export const test = base.extend<SearchFixtures>({
  filters: async ({browser, isMobile}, use) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    const search = new SearchPage(page)
    await search.open()
    isMobile ?
      await search.cookiesPopup.closeBtn.tap() :
      await search.cookiesPopup.closeBtn.click()
    await use(search.filters)
  }
})

export const expect = test.expect;
```

```typescript
//test
import { expect } from '@playwright/test';
import { test } from '../../framework/fixtures'
import { SearchFilters } from '../../framework/pages/components/SearchFilters';

test.describe.parallel('Search filters overlay', () => {
  
  test.describe.serial('Area of work', () => {
    let searchFilters: SearchFilters
    
    test.beforeAll(async ({filters}) => {
      searchFilters = filters;
    })

    test.afterAll(async () => {
      searchFilters.page.close()
    })

    test('@smoke: Filters overlay can be opened', async ({isMobile}) => {
      await test.step('Open Area of Work filters', async () => {
        isMobile ?
          await searchFilters.areaOfWorkFilterBtn.tap() :
          await searchFilters.areaOfWorkFilterBtn.click() 
      });
      await test.step('Verify filters overlay and its elements are shown',async () => {
        await expect(searchFilters.filtersHeaderText).toHaveText('Filter by Area of Work')
        await expect(searchFilters.clearAllfiltersBtn).toBeVisible()
        await expect(searchFilters.applyFiltersBtn).toBeVisible()
        await expect(searchFilters.closeFiltersOverlayBtn).toBeVisible()
        expect(await searchFilters.filterCheckboxes.count(), 'expect there are some filters').toBeGreaterThan(0)
      })
    })

    test('@smoke: Filters overlay can be closed', async ({isMobile}) => {
      await test.step('Close Area of Work filters', async () => {
        isMobile ?
          await searchFilters.closeFiltersOverlayBtn.tap() :
          await searchFilters.closeFiltersOverlayBtn.click() 
      })
      await test.step('Verify filters overlay and its elements are shown',async () => {
        await expect(searchFilters.filtersHeaderText).not.toBeVisible()
        await expect(searchFilters.clearAllfiltersBtn).not.toBeVisible()
        await expect(searchFilters.applyFiltersBtn).not.toBeVisible()
        await expect(searchFilters.closeFiltersOverlayBtn).not.toBeVisible()
        expect(await searchFilters.filterCheckboxes.count(), 'expect there are some filters').toBeFalsy()
      })
    })
  })

  test.describe.serial('Location', () => {
    let searchFilters: SearchFilters
    
    test.beforeAll(async ({filters}) => {
      searchFilters = filters;
    })

    test.afterAll(async () => {
      searchFilters.page.close()
    })

    test('@smoke: Filters overlay can be opened', async ({isMobile}) => {
      await test.step('Open Location filters', async () => {
        isMobile ?
          await searchFilters.locationFilterBtn.tap() :
          await searchFilters.locationFilterBtn.click() 
      });
      await test.step('Verify filters overlay and its elements are shown', async () => {
        await expect(searchFilters.filtersHeaderText).toHaveText('Filter by Location')
        await expect(searchFilters.clearAllfiltersBtn).toBeVisible()
        await expect(searchFilters.applyFiltersBtn).toBeVisible()
        await expect(searchFilters.closeFiltersOverlayBtn).toBeVisible()
        expect(await searchFilters.filterCheckboxes.count(), 'expect there are some filters').toBeGreaterThan(0)
      })
    })

    test('@smoke: Filters overlay can be closed', async ({isMobile}) => {
      await test.step('Close Location filters', async () => {
        isMobile ?
          await searchFilters.closeFiltersOverlayBtn.tap() :
          await searchFilters.closeFiltersOverlayBtn.click() 
      })
      await test.step('Verify filters overlay and its elements are shown', async () => {
        await expect(searchFilters.filtersHeaderText).not.toBeVisible()
        await expect(searchFilters.clearAllfiltersBtn).not.toBeVisible()
        await expect(searchFilters.applyFiltersBtn).not.toBeVisible()
        await expect(searchFilters.closeFiltersOverlayBtn).not.toBeVisible()
        expect(await searchFilters.filterCheckboxes.count(), 'expect there are some filters').toBeFalsy()
      })
    })
  })

})
```

**Description**
With the recent change in 1.23 (https://github.com/microsoft/playwright/pull/14530) I tried a parallel run of two `test.describe.serial()`'s  that are located in the single file. The test didn't errored out like in the previous versions, but it didn't utilise two workers. Instead, the test suites ran sequentially.

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #15741.

### CODE REVIEW

File: packages/playwright-test/src/runner.ts [hunk 1]
```diff
@@ -675,29 +681,33 @@ function createTestGroups(rootSuite: Suite, workers: number): TestGroup[] {
...
-          parallel: [],
+          parallel: new Map(),
           parallelWithHooks: createGroup(test),
         };
         withWorkerHash.set(test._requireFile, withRequireFile);
       }
 
       let insideParallel = false;
-      let insideSerial = false;
+      let outermostMostSerialSuite: Suite | undefined;
```
Comment (aslushnikov) [inline packages/playwright-test/src/runner.ts:691]:
```suggestion
      let outerMostSerialSuite: Suite | undefined;
```

File: packages/playwright-test/src/runner.ts [hunk 2]
```diff
@@ -675,29 +681,33 @@ function createTestGroups(rootSuite: Suite, workers: number): TestGroup[] {
...
       let hasAllHooks = false;
       for (let parent: Suite | undefined = test.parent; parent; parent = parent.parent) {
-        insideSerial = insideSerial || parent._parallelMode === 'serial';
-        // Serial cancels out any enclosing parallel.
-        insideParallel = insideParallel || (!insideSerial && parent._parallelMode === 'parallel');
+        if (parent._parallelMode === 'serial')
+          outermostMostSerialSuite = parent;
+        insideParallel = insideParallel || parent._parallelMode === 'parallel';
```
Comment (aslushnikov) [inline packages/playwright-test/src/runner.ts:696]: let's comment that `describe.parallel` is never inside `describe.serial` - this is forced somewhere else

**Review by aslushnikov — APPROVED** [review]
