### PR TITLE
fix(webkit): handle will/didCheckPolicyForNavigation

### LINKED ISSUE #11595: Open new tab in same window for Webkit
**Context:**
- Playwright Version: 1.18.0
- Operating System: Windows
- Node.js version: 16.13.1
- Browser: WebKit

**Describe the bug**
When a user tries to perform a "ctrl + click" on a link or open a link/URL in a new tab, playwright WebKit opens that link in the same tab instead of opening a new tab. It creates a problem for crossbrowser testing.

It is also visible in attached screenshot that there is no option for new tab.
Playwright

### PR DESCRIPTION
**Pull request by yury-s**
The PR includes webkit roll to 1604.

Fixes #11595

### CODE REVIEW

File: packages/playwright-core/src/server/webkit/wkPage.ts [hunk 1]
```diff
@@ -404,6 +406,22 @@ export class WKPage implements PageDelegate {
     await Promise.all(sessions.map(session => callback(session).catch(e => {})));
   }
 
+  private _onWillCheckNavigationPolicy(frameId: string) {
+    if (this._provisionalPage)
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkPage.ts:410]: Let's add a comment summarizing our offline discussion?

File: tests/page/page-goto.spec.ts [hunk 2]
```diff
@@ -405,7 +405,7 @@ it('should fail when replaced by another navigation', async ({ page, server, bro
   if (browserName === 'chromium')
     expect(error.message).toContain('net::ERR_ABORTED');
   else if (browserName === 'webkit')
-    expect(error.message).toContain('cancelled');
+    expect(error.message).toContain('Navigation interrupted by another one');
```
Comment (dgozman) [inline tests/page/page-goto.spec.ts:408]: Shouldn't this PR include removing ctrl+click fixme?

**Review by dgozman — APPROVED** [review]
