### PR TITLE
fix: only convert input files for browser collocated with server

### LINKED ISSUE #27792: [internal] file upload Android tests are failing
Since: https://github.com/microsoft/playwright/pull/27671

https://github.com/microsoft/playwright-browsers/actions/workflows/tests-android.yml

### PR DESCRIPTION
**Pull request by yury-s**
Reference #27452
Fixes #27792

### CODE REVIEW

File: packages/playwright-core/src/server/dispatchers/browserContextDispatcher.ts [hunk 1]
```diff
@@ -46,13 +46,14 @@ export class BrowserContextDispatcher extends Dispatcher<BrowserContext, channel
   private _context: BrowserContext;
   private _subscriptions = new Set<channels.BrowserContextUpdateSubscriptionParams['event']>();
 
-  constructor(parentScope: DispatcherScope, context: BrowserContext) {
+  constructor(parentScope: DispatcherScope, context: BrowserContext, isLocalBrowser: boolean) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/dispatchers/browserContextDispatcher.ts:49]: Can we make this a property of `BrowserContext` itself?

File: packages/playwright-core/src/client/elementHandle.ts [hunk 2]
```diff
@@ -270,6 +270,8 @@ export async function convertInputFiles(files: string | FilePayload | string[] |
     if (!items.every(item => typeof item === 'string'))
       throw new Error('File paths cannot be mixed with buffers');
     if (context._connection.isRemote()) {
+      if (!context._isLocalBrowser())
```
Comment (dgozman) [inline packages/playwright-core/src/client/elementHandle.ts:273]: I think server should also throw in this case, to avoid relying on clients 100%.

File: packages/protocol/src/protocol.yml [hunk 3]
```diff
@@ -1012,6 +1012,7 @@ BrowserContext:
 
   initializer:
     isChromium: boolean
+    isLocalBrowser: boolean
```
Comment (dgozman) [inline packages/protocol/src/protocol.yml:1015]: `isLocalOnServer`/`isLocalBrowserOnServer`?

File: packages/playwright-core/src/client/elementHandle.ts [hunk 4]
```diff
@@ -279,14 +281,26 @@ export async function convertInputFiles(files: string | FilePayload | string[] |
...
       return { streams };
     }
-    return { localPaths: items.map(f => path.resolve(f as string)) as string[] };
+    if (context._isLocalBrowser())
+      return { localPaths: items.map(f => path.resolve(f as string)) as string[] };
+    const filePayloads: SetInputFilesFiles = await Promise.all((items as string[]).map(async item => {
+      return {
+        name: path.basename(item),
+        buffer: await fs.promises.readFile(item)
+      };
```
Comment (mxschmitt) [inline packages/playwright-core/src/client/elementHandle.ts:290]: nit: ideally we pass lastModifiedMs over here to the server an use it like [here](https://github.com/microsoft/playwright/pull/27798/files#diff-06edc6b9e1c43786236ac754ec9a7ed6a4470c550a657aa6d38c2afc5dbdd850).

File: packages/playwright-core/src/server/dispatchers/browserContextDispatcher.ts [hunk 5]
```diff
@@ -177,6 +178,8 @@ export class BrowserContextDispatcher extends Dispatcher<BrowserContext, channel
   }
 
   async createTempFile(params: channels.BrowserContextCreateTempFileParams): Promise<channels.BrowserContextCreateTempFileResult> {
+    if (!this._context._browser._isCollocatedWithServer)
+      throw new Error('Cannot create temp file: browser is not collocated with server');
```
Comment (dgozman) [inline packages/playwright-core/src/server/dispatchers/browserContextDispatcher.ts:182]:
```suggestion
      throw new Error('Cannot create temp file: the browser is not co-located with the server');
```

File: packages/playwright-core/src/server/browserContext.ts [hunk 6]
```diff
@@ -109,6 +109,10 @@ export abstract class BrowserContext extends SdkObject {
     return this._isPersistentContext;
   }
 
+  isLocalBrowserOnServer(): boolean {
```
Comment (dgozman) [inline packages/playwright-core/src/server/browserContext.ts:112]: This one seems unused.

File: packages/playwright-core/src/client/elementHandle.ts [hunk 7]
```diff
@@ -270,6 +270,8 @@ export async function convertInputFiles(files: string | FilePayload | string[] |
     if (!items.every(item => typeof item === 'string'))
       throw new Error('File paths cannot be mixed with buffers');
     if (context._connection.isRemote()) {
+      if (!context._isLocalBrowserOnServer())
+        throw new Error('File paths are not supported in this type of browser, please set buffers instead');
```
Comment (dgozman) [inline packages/playwright-core/src/client/elementHandle.ts:274]: I thought we can read small files and transport them as buffers here? Same as line 286.

**Review by mxschmitt — APPROVED** [review]
