### PR TITLE
fix(webkit): reenable CrossOriginOpenerPolicy

### LINKED ISSUE #14043: [BUG] SharedArrayBuffer should work in WebKit
This popped up in https://github.com/microsoft/playwright/pull/13976, SharedArrayBuffer was reenabled in Safari https://webkit.org/blog/12140/new-webkit-features-in-safari-15-2/ but we disabled COOP handling in https://github.com/microsoft/playwright/pull/9185 as it broke some other functionality in WebKit. We should reenable COOP to match Safari and make SharedArrayBuffer work.

### PR DESCRIPTION
**Pull request by yury-s**
Depends on https://github.com/microsoft/playwright-browsers/pull/1160
Fixes: https://github.com/microsoft/playwright/issues/14043

### CODE REVIEW

File: packages/playwright-core/src/server/webkit/wkProvisionalPage.ts [hunk 1]
```diff
@@ -43,16 +53,20 @@ export class WKProvisionalPage {
...
-      eventsHelper.addEventListener(session, 'Network.loadingFinished', overrideFrameId(e => wkPage._onLoadingFinished(e))),
-      eventsHelper.addEventListener(session, 'Network.loadingFailed', overrideFrameId(e => wkPage._onLoadingFailed(session, e))),
+      eventsHelper.addEventListener(session, 'Network.loadingFinished', overrideFrameId(e => this._onLoadingFinished(e))),
+      eventsHelper.addEventListener(session, 'Network.loadingFailed', overrideFrameId(e => this._onLoadingFailed(e))),
     ];
 
     this.initializationPromise = this._wkPage._initializeSession(session, true, ({ frameTree }) => this._handleFrameTree(frameTree));
   }
 
+  pendingNavigationRequest(): network.Request | undefined {
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkProvisionalPage.ts:66]: I'd call these `coopNavigationRequest()` or similar.

File: packages/playwright-core/src/server/webkit/wkPage.ts [hunk 2]
```diff
@@ -1157,6 +1190,12 @@ export class WKPage implements PageDelegate {
     if (!request)
       return;
 
+    // If a provisional page was created after Cross-Origin-Opener-Policy headers were received, it
+    // will take over the request (with a new id). We'll only fail it if the provisional navigation
+    // fails/get canceled.
+    if (this._provisionalPage?.pendingNavigationRequest() === request.request)
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkPage.ts:1196]: It would be ideal to get rid of the extra `loadingFailed` from the original page.

File: packages/playwright-core/src/server/webkit/wkPage.ts [hunk 3]
```diff
@@ -1015,10 +1017,41 @@ export class WKPage implements PageDelegate {
...
+    }
+  }
+
+  _changeRequestId(navigationRequest: network.Request, newRequestId: string) {
+    for (const [requestId, request] of this._requestIdToRequest) {
+      if (request.request === navigationRequest) {
+        this._requestIdToRequest.delete(requestId);
+        request.changeRequestId(newRequestId);
+        this._requestIdToRequest.set(newRequestId, request);
+        // Simply ignore this event as it has already been dispatched from the original process
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkPage.ts:1042]: This comment is not needed here.

File: packages/playwright-core/src/server/webkit/wkProvisionalPage.ts [hunk 4]
```diff
@@ -62,6 +78,29 @@ export class WKProvisionalPage {
     this._wkPage._onFrameAttached(this._mainFrameId, null);
   }
 
+  private _onRequestWillBeSent(event: Protocol.Network.requestWillBeSentPayload) {
+    if (this._coopNavigationRequest && this._coopNavigationRequest.url() === event.request.url) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkProvisionalPage.ts:82]: IIUC, the first request must be the `coopNavigationRequest`? Perhaps we should assert that urls are equal instead of comparing?

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/webkit/wkProvisionalPage.ts (hunk 4 above)
Comment (yury-s) [reply packages/playwright-core/src/server/webkit/wkProvisionalPage.ts:82]: That is correct. I'm not sure about turning this into an assert, in case something changes and the page starts cancelling the cross process provisional load a bit later or something like that it could start firing.
