### PR TITLE
fix(ui): added test in watched file should be run

### LINKED ISSUE #22211: [BUG] Watch mode in UI Mode does not handle adding new test
### System info
- Playwright Version: [v1.32.1]
- Operating System: [macOS 13.2.1]
- Other info: UI Mode

**Steps**
- Open UI mode
- Turn on Watch mode for one of the files.
- Add a new test in that file.
- Save the file

**Expected**

Watch mode should run the newly added test as well.

**Actual**

Watch mode runs only previously existing tests. The new test just appears in the list.

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/22211

Currently, when the server notifies the UI about changed files, the UI determines what files to re-run based on an old test list. By listing tests before that, we make sure that the test list is up-to-date, and that added tests are included in the next run.

I've also removed the `listChanged` event as discussed in the team sync. The event isn't used anywhere and fires in exactly the same cases where `testFilesChanged` fired, so i've folded them into one another.

### CODE REVIEW

**Comment by Skn0tt** [comment]
Dima and me had a look at this synchronously, and decided to try removing one of the callbacks so we spare a roundtrip.

**Comment by Skn0tt** [comment]
Dima and me discussed that we should combine the two `Watcher` instances into one to prevent duplicate events, and remove the concept of a watcher mode at the same time. We don't remember why it exists.

**Comment by Skn0tt** [comment]
I've successfully dropped the `listChanged` event in favor of `testFilesChanged`, and simplified the `Watcher` implementation.

There's two new tests in `test-server-connection.spec.ts` that assert on the interface we have to VS Code, so we can be a little more sure about changes in that area in the future. We can extend that with more test cases as we introduce new functionality to the test server.

File: packages/trace-viewer/src/ui/uiModeView.tsx [hunk 1]
```diff
@@ -336,9 +323,26 @@ export const UIModeView: React.FC<{}> = ({
 
   // Watch implementation.
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/uiModeView.tsx:324]: Let's update the comment, this is list update + watch now. Or just remove it.

File: packages/trace-viewer/src/ui/uiModeView.tsx [hunk 2]
```diff
@@ -336,9 +323,26 @@ export const UIModeView: React.FC<{}> = ({
...
   React.useEffect(() => {
-    if (!testServerConnection)
+    if (!testServerConnection || !teleSuiteUpdater)
       return;
-    const disposable = testServerConnection.onTestFilesChanged(params => {
+    const disposable = testServerConnection.onTestFilesChanged(async params => {
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/uiModeView.tsx:328]: Let's comment that we first update the list to get the up-to-date list of tests, and then run the watched ones.

File: packages/trace-viewer/src/ui/uiModeView.tsx [hunk 3]
```diff
@@ -336,9 +323,26 @@ export const UIModeView: React.FC<{}> = ({
...
+        } catch (e) {
+          // eslint-disable-next-line no-console
+          console.log(e);
+        } finally {
+          setIsLoading(false);
+        }
+      });
+      await commandQueue.current;
+
+      const testModel = teleSuiteUpdater.asModel();
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/uiModeView.tsx:343]: Perhaps return if `params.testFiles` is empty?

File: packages/trace-viewer/src/ui/uiModeView.tsx [hunk 4]
```diff
@@ -336,9 +323,26 @@ export const UIModeView: React.FC<{}> = ({
...
+      const testTree = new TestTree('', testModel.rootSuite, testModel.loadErrors, projectFilters, pathSeparator);
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/uiModeView.tsx:344]: It is unfortunate that we have to create a new `TestTree` here, even though one would be created naturally through `useMemo()`. I wonder whether there is a better pattern to handle such a thing in React?

File: packages/playwright/src/runner/testServer.ts [hunk 5]
```diff
@@ -86,8 +90,7 @@ class TestServerDispatcher implements TestServerInterface {
           gracefullyProcessExitDoNotHang(0);
       },
     };
-    this._globalWatcher = new Watcher('deep', () => this._dispatchEvent('listChanged', {}));
```
Comment (dgozman) [inline packages/playwright/src/runner/testServer.ts:89]: We should double check that emitting `testFilesChanged` event with an empty list of test files is properly ignored in the VSCode extension.

File: tests/playwright-test/test-server-connection.spec.ts [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+import { test as baseTest, expect } from './ui-mode-fixtures';
+
+import { TestServerConnection } from '../../packages/playwright/src/isomorphic/testServerConnection';
```
Comment (dgozman) [inline tests/playwright-test/test-server-connection.spec.ts:18]: You probably want to import from `lib`, not `src`, otherwise path mapping goes crazy.

File: tests/playwright-test/test-server-connection.spec.ts [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+
+  await writeFiles({
+    'utils.ts': `
+      export const expected = 123;
+      `,
+  });
+
+  await expect.poll(() => testServerConnection.events).toHaveLength(1);
+  expect(testServerConnection.events).toEqual([
+    ['testFilesChanged', { testFiles: [testInfo.outputPath('a.test.ts')] }]
```
Comment (dgozman) [inline tests/playwright-test/test-server-connection.spec.ts:73]: Are we trying to test that there is a single event here? Seems kinds of redundant, because we rely on chokidar to make it so.

File: tests/playwright-test/test-server-connection.spec.ts [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+  ]);
+});
+
+test('test run events', async ({ testServerConnection, writeFiles }) => {
```
Comment (dgozman) [inline tests/playwright-test/test-server-connection.spec.ts:77]: Perhaps it would make more sense to test the end-user behavior? While I do think such a test makes sense for a public API that should preserve backwards compatibility, test server interface is not public yet. WDYT?

**Review by dgozman — COMMENTED** [review]
This looks good, just a few comments.

File: packages/trace-viewer/src/ui/uiModeView.tsx (hunk 4 above)
Comment (Skn0tt) [reply packages/trace-viewer/src/ui/uiModeView.tsx:344]: I agree. The big problem with `useMemo` is that it only updates on the next render, which is too late for this. I feel like this component could benefit from separating some of the underlying state from the presentation. I'd like to do that in a separate PR, though.

Comment (Skn0tt) [reply packages/trace-viewer/src/ui/uiModeView.tsx:348]: I agree. The big problem with useMemo is that it only updates on the next render, which is too late for this. I feel like this component could benefit from separating some of the underlying state from the presentation. I'd like to do that in a separate PR, though.

File: tests/playwright-test/test-server-connection.spec.ts (hunk 7 above)
Comment (Skn0tt) [reply tests/playwright-test/test-server-connection.spec.ts:73]: We're trying to test that there are no other events. Prior to this PR, there would've also been a `listChanged` event.

Also, prior to this PR, we would've seen two `testFilesChanged` events because we had two chokidar instances emitting the same file changes. So there's some value in this test :D If it had existed before, we would've spotted earlier that the two `Watcher` instances are a redundant.

File: tests/playwright-test/test-server-connection.spec.ts (hunk 8 above)
Comment (Skn0tt) [reply tests/playwright-test/test-server-connection.spec.ts:77]: This API might not be public, but we still need to preserve backwards compatibility so we don't break the VS Code extension. That's the main value in this test suite I think.

File: tests/playwright-test/test-server-connection.spec.ts (hunk 6 above)
Comment (Skn0tt) [reply tests/playwright-test/test-server-connection.spec.ts]: good idea! that's probably what tripped up the linter.

File: packages/playwright/src/runner/testServer.ts (hunk 5 above)
Comment (Skn0tt) [reply packages/playwright/src/runner/testServer.ts:89]: will do!

**Review by Skn0tt — COMMENTED** [review]
Thanks for the feedback! I've left comment and addressed the actionable feedback in c24be29a86187d513c2faa9835014b6f951e2ee9.

File: tests/playwright-test/test-server-connection.spec.ts (hunk 8 above)
Comment (Skn0tt) [reply tests/playwright-test/test-server-connection.spec.ts]: `report` also is one of the events of `TestServerInterface`, but I agree that if its contents exclusively contain reporter output, then it doesn't make sense to test it.

In https://github.com/microsoft/playwright/pull/31842/commits/9ee6994979b3332bba881f265c70131e1e158491, i've removed the `report` event and rewrote this test to cover STDIO interception instead.

File: tests/playwright-test/test-server-connection.spec.ts [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+        console.log("this goes to stdout");
+        console.error("this goes to stderr");
+        expect(true).toBe(true);
+      });
+      `,
+  });
+
+  const tests = await testServerConnection.runTests({ trace: 'on' });
+  expect(tests).toEqual({ status: 'passed' });
+  await expect.poll(() => testServerConnection.events).toHaveLength(8);
```
Comment (dgozman) [inline tests/playwright-test/test-server-connection.spec.ts:91]: nit: I'd recommend to not hard-code the length (for an easier-to-maintain test), and just expect some entries, something along these lines:

```ts
await expect.poll(() => testServerConnection.events).toEqual(expect.arrayContaining([
  ['stdio', { type: 'stderr', text: 'this goes to stderr\n' }],
  ['stdio', { type: 'stdout', text: 'this goes to stdout\n' }],
]));
```

**Review by dgozman — APPROVED** [review]
Looks good!
