### PR TITLE
fix(tracing): bump trace version to V5, migrate V4 traces to consoleMessage.args

### LINKED ISSUE #27144: [BUG]can not display trace
When I open trace, the page is blank
image

### PR DESCRIPTION
**Pull request by dgozman**
This moves the fix in #27095 from `modernize` to `appendEvent`. The reason is that `trace V4` is used both for older traces that do not have `consoleMessage.args` and the new ones with `args`. Since we do not call `modernize` for traces of the same version, the original fix does not help in this case.

Fixes #27144.

### CODE REVIEW

**Review by pavelfeldman — APPROVED** [review]

File: packages/trace-viewer/src/traceModel.ts [hunk 1]
```diff
@@ -348,6 +343,48 @@ export class TraceModel {
...
+        return {
+          type: 'console',
+          time: event.time,
+          pageId: event.pageId,
+          messageType: consoleMessage.type,
+          text: consoleMessage.text,
+          args: consoleMessage.args,
+          location: consoleMessage.location,
+        };
+      }
```
Comment (yury-s) [inline packages/trace-viewer/src/traceModel.ts:384]: else return null

**Review by yury-s — APPROVED** [review]
