### PR TITLE
fix(test runner): fixture teardown double error, testInfo.attach()

### LINKED ISSUE #11341: [BUG] testInfo.attach(…) hangs with paths in fixtures
**Context:**
- Playwright Version: `@playwright/test@1.18.0-alpha-jan-12-2022`
- Operating System: macOS
- Node.js version: v14.17.6

**Code Snippet**

```ts
export const exampleTest = _test.extend<{ aNumber: number }>({
  aNumber: async ({}, use, testInfo) => {
    await use(10);
    console.log("use completed");
    await testInfo.attach("example.txt", {
      contentType: "text/plain",
      path: "/path/to/nowhere",
    });
    console.log("attach completed");
  },
});

exampleTest("foo", ({ aNumber }) => {
  expect(aNumber).toBe(10);
  console.log("done");
});
```

**Describe the bug**

The above code hangs when you run `npx playwright --reporter line`.  I expect it to error immediately. If there is an attachment that exists, I'd expect it to be included, but this case should at least error.

---

The above repro is a simplified example. I hit it when trying to add a per-test logger fixture which I want to add since we have too many `console.log`s spamming our test output (but who's output I don't want to lose).

Here's the fixture I was writing:

```ts
export const test = _test.extend<{
  logger: Logger;
  pollAPI: (id: string) => Promise<string>;
}>({
  logger: async ({}, use, testInfo) => {
    const outFile = testInfo.outputPath("test-logs.log");
    const transports: winston.transport[] = [
      new winston.transports.File({
        filename: outFile,
      }),
    ];

    // Force console output. This is sometimes nice to have locally.
    if (process.env["PLAYWRIGHT_TEST_FORCE_CONSOLE_LOGS"]) {
      transports.push(new winston.transports.Console());
    }

    const logger = winston.createLogger({
      level: "debug",
      transports,
    });

    const finished = new Promise((res, rej) => {
      logger.on("finish", res);
      logger.on("error", rej);
    });

    await use(logger);
    logger.end();
    await finished;
    await testInfo.attach("debug.log", {
      path: outFile,
      contentType: "text/plain",
    });
  },
  pollAPI: async ({ logger }, use) => {
    const pollAPI = async (id: string) => {
      logger.debug(`Polling for ${id}`);
      const cycles = Math.random() * 100;
      for (let i = 0; i < cycles; i++) {
        logger.debug(`still polling`);
      }
      logger.debug("finished polling");
      return "example";
    };
    await use(pollAPI);
  },
});

test("spam example", async () => {
  console.log("spams the console…");
});

test("per-test logging, without the spam!", async ({ pollAPI }) => {
  const result = await pollAPI("foo");
  expect(result).toBe("example");
});

```

I'll open an PR with a test case in a few.

### PR DESCRIPTION
**Pull request by dgozman**
- Use file path, not content to calculate the attachment hash.
- Always cleanup fixture from the list on teardown, to avoid reporting
  teardown error multiple times: from the test, and from the cleanup.

Fixes #11341.

### CODE REVIEW

File: packages/playwright-core/src/utils/utils.ts [hunk 1]
```diff
@@ -402,17 +389,6 @@ export function arrayToObject(array?: NameValue[]): { [key: string]: string } |
   return result;
 }
 
-export async function calculateFileSha1(filename: string): Promise<string> {
```
Comment (rwoll) [inline packages/playwright-core/src/utils/utils.ts:405]: Can't have a bug in it if the code no longer exists! 😃

File: tests/playwright-test/fixture-errors.spec.ts [hunk 2]
```diff
@@ -435,3 +435,23 @@ test('should not teardown when setup times out', async ({ runInlineTest }) => {
   expect(result.output.split('\n').filter(line => line.startsWith('%%'))).toEqual([
   ]);
 });
+
+test('should not report fixture teardown error twice', async ({ runInlineTest }) => {
```
Comment (rwoll) [inline tests/playwright-test/fixture-errors.spec.ts:439]: Can you bring over the other test, too? 

https://github.com/microsoft/playwright/pull/11342/files#diff-7baf8520adc91e87042c746455f6e8a73b78771e9ca03095c9b15437894a6b4aR107

I intentionally had two tests so I ensured the positive test case actually does work alongside the negative test case. (Afterall, the positive case is what lead us here 😀 so I'd want to know if we broke that in the future, and it feels different enough from the other attachment cases since it happens in fixture teardown as opposed to during the test.)

File: packages/playwright-test/src/workerRunner.ts [hunk 3]
```diff
@@ -268,7 +268,7 @@ export class WorkerRunner extends EventEmitter {
         if ((options.path !== undefined ? 1 : 0) + (options.body !== undefined ? 1 : 0) !== 1)
           throw new Error(`Exactly one of "path" and "body" must be specified`);
         if (options.path) {
-          const hash = await calculateFileSha1(options.path);
+          const hash = calculateSha1(options.path);
```
Comment (rwoll) [inline packages/playwright-test/src/workerRunner.ts:271]: What's the reason for the switch to filename instead of contents? Regardless, filename hash seems much simpler (and I suppose negligibly faster depending on what was in the files).

**Review by rwoll — CHANGES_REQUESTED** [review]
Left some questions for my own education/curiosity/understanding, and a request to bring over one more of the test cases.

Thanks!

File: packages/playwright-test/src/workerRunner.ts (hunk 3 above)
Comment (dgozman) [reply packages/playwright-test/src/workerRunner.ts:271]: You got it right 😄

File: tests/playwright-test/fixture-errors.spec.ts (hunk 2 above)
Comment (dgozman) [reply tests/playwright-test/fixture-errors.spec.ts:439]: Sure, why not.

**Review by pavelfeldman — APPROVED** [review]
