### PR TITLE
fix: do not throw from fetch when response has invalid cookie

### LINKED ISSUE #27165: [BUG] goto() never returns
### System info
- Playwright Version: [v1.37.0]
- Operating System: [amazonlinux2:2022, macOS 13.5, etc.]
- Browser: [Chromium]
- Other info:

The below stack trace is displayed in our logs and the Thread that is running this never returns from 
        response = self.page.goto(link.url, timeout=NAVIGATE_TIMEOUT_SECS*1000, wait_until=WAIT_UNTIL)

After crawling approximately 300 pages we receive this error.  It will always happen on the same site, but on random pages (around the 300th page). We believe that the site owner is intentionally returning bad info which causes this stack trace.  

Since the code gets stuck, we cannot see what "cookies" are causing it or prevent it from getting stuck.

**************************************************************
Problematic Code 
**************************************************************
```python
NAVIGATE_TIMEOUT_SECS = 120
WAIT_UNTIL = 'load'
response = self.page.goto(link.url, timeout=NAVIGATE_TIMEOUT_SECS*1000, wait_until=WAIT_UNTIL)
```

**************************************************************
Log snippet
**************************************************************

[DEBUG]|2023-09-06 11:49:00,416|common.playutil|64f8c59688daff0a9d514f9f|filter_response: fetching http://redactedsitedyavc6szj6ppbplfqoz3pgrk3zw57my4vybgblpfeayd.onion/Thread-Equifax-data-breach
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ProtocolError: Protocol error (Storage.setCookies): Invalid cookie fields
    at /Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/driver/package/lib/server/chromium/crConnection.js:169:16
    at new Promise (<anonymous>)
    at CRSession.send (/Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/driver/package/lib/server/chromium/crConnection.js:165:12)
    at CRBrowserContext.addCookies (/Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/driver/package/lib/server/chromium/crBrowser.js:367:34)
    at BrowserContextAPIRequestContext._addCookies (/Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/driver/package/lib/server/fetch.js:400:25)
    at ClientRequest.<anonymous> (/Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/driver/package/lib/server/fetch.js:213:40)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  sessionClosed: false
}

Node.js v18.17.0

**************************************************************
Thread Dump
**************************************************************

Thread 0x0000000174617000 (most recent call first):
  File "/Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 107 in _sync
  File "/Users/me/projects/proj/venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 9303 in goto
  File "/Users/me/projects/proj/src/crawling.py", line 400 in _goto
  File "/Users/me/projects/proj/src/crawling.py", line 377 in goto_with_retry
  File "/Users/me/projects/proj/src/crawling.py", line 327 in start_crawl_loop
  File "/Users/me/projects/proj/src/crawling.py", line 142 in _run
  File "/Users/me/projects/proj/src/crawling.py", line 119 in run
  File "/Users/me/.pyenv/versions/3.8.10/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/Users/me/.pyenv/versions/3.8.10/lib/python3.8/threading.py", line 890 in _bootstrap

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
```
We cannot write a code example because we don't know what actually causes this to occur and the real site takes 300ish pages to trigger it.
```

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```

**Steps**
- No test (explained above)

**Expected**

1) Make sure that if this happens the error percolates out. AND/OR
2) Make sure this problem correctly returns or raises a catchable error. OR
3) Honors the timeout.

**Actual**

Nothing. The code never returns.

### PR DESCRIPTION
**Pull request by yury-s**
Cookie value is limited by 4096 characters in the browsers. If setCookies failed we try setting each cookie individually just in case only some of them are bad.

Fixes https://github.com/microsoft/playwright/issues/27165

### CODE REVIEW

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/fetch.ts [hunk 1]
```diff
@@ -282,8 +282,15 @@ export abstract class APIRequestContext extends SdkObject {
           progress.log(`  ${name}: ${value}`);
 
         const cookies = this._parseSetCookieHeader(response.url || url.toString(), response.headers['set-cookie']) ;
-        if (cookies.length)
-          await this._addCookies(cookies);
+        if (cookies.length) {
+          try {
+            await this._addCookies(cookies);
+          } catch (e) {
+            // Cookie value is limited by 4096 characters in the browsers. If setCookies failed,
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/fetch.ts:289]: What are browsers doing in terms of: 2 good cookies get returned and one bad cookie. Do they then drop the whole set of cookies or only ignore the one bad cookie?

Comment (mxschmitt) [reply packages/playwright-core/src/server/fetch.ts:289]: oh I see your change below, great!

**Review by mxschmitt — APPROVED** [review]

File: packages/playwright-core/src/server/fetch.ts (hunk 1 above)
Comment (yury-s) [reply packages/playwright-core/src/server/fetch.ts:289]: They ignore invalid cookies and accept others.
