### PR TITLE
fix: parent step for API calls inside waitForEvent callback

### LINKED ISSUE #33186: [Bug]: Playwright report showing waitForResponse logs outside test step
### Version

v1.48.1

### Steps to reproduce

Example Steps
1. Clone repo at https://github.com/anandtiwari1/playwright-issue.git
2. npm install
3. npx playwright test
4. verify the playwright report

### Expected behavior

waitForResponse logs `response.text` should display instead test.step
working on playwright version: [v1.46.1](https://github.com/microsoft/playwright/releases/tag/v1.46.1)
Image

### Actual behavior

`response.text` showing outside test.step:
Image

### Additional context

_No response_

### Environment

System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.69 GB / 32.00 GB
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/33186

### CODE REVIEW

File: packages/playwright-core/src/utils/zones.ts [hunk 1]
```diff
@@ -39,6 +39,17 @@ class ZoneManager {
     return this._asyncLocalStorage.run(undefined, func);
   }
 
+  currentZoneBefore(type: ZoneType): ZoneReference {
+    let zone = this._asyncLocalStorage.getStore();
+    while (zone && zone.type === type)
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/zones.ts:44]: I'm not sure I understand the logic here.

File: packages/playwright-core/src/client/waiter.ts [hunk 2]
```diff
@@ -29,10 +29,14 @@ export class Waiter {
...
   private _waitId: string;
   private _error: string | undefined;
+  private _savedZone: ZoneReference;
 
   constructor(channelOwner: ChannelOwner<channels.EventTargetChannel>, event: string) {
     this._waitId = createGuid();
     this._channelOwner = channelOwner;
+    // Save current chain before the wait for event API call (we don't nest API calls)
+    // and restore it later to find proper parent for the event listener.
+    this._savedZone = zones.currentZoneBefore('apiZone');
```
Comment (pavelfeldman) [inline packages/playwright-core/src/client/waiter.ts:39]: What does it mean zone before zone? Do you mean simply current zone?

File: packages/playwright-core/src/utils/zones.ts [hunk 3]
```diff
@@ -53,6 +64,20 @@ class ZoneManager {
   }
 }
 
+export class ZoneReference {
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/zones.ts:67]: What's is zone reference? I thought zone was a zone reference already. Real zone is the async context. I don't think we need 3 types, should be just async context and a logical apiCall zone with a parent.

File: packages/playwright-core/src/utils/zones.ts [hunk 4]
```diff
@@ -19,49 +19,52 @@ import { AsyncLocalStorage } from 'async_hooks';
...
+  private constructor(store: Map<ZoneType, unknown>) {
+    this.store = store;
   }
-}
 
-class Zone<T> {
-  readonly type: ZoneType;
-  readonly data: T;
-  readonly previous: Zone<unknown> | undefined;
+  copyWithoutTypes(types: ZoneType[]): Zone {
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/zones.ts:61]: I think I understand the refactoring, but it does not help me understand the physical model of what is going on.

**Review by pavelfeldman — APPROVED** [review]
