### PR TITLE
fix: do not collide with other tests when test names have special chars

### LINKED ISSUE #23386: [Feature] Automatically transform special characters in test name to avoid file overwrite in results folder (e.g. video recording)
Consider the following test

```ts
test.describe('this is a test suite', () => {
  // these are all `**-a-b-**` ❌
  test('a > b', async () => { expect(1).toBe(1); });
  test('a = b', async () => { expect(1).toBe(1); });
  test('a < b', async () => { expect(1).toBe(1); });
  test('a + b', async () => { expect(1).toBe(1); });
  test('a # b', async () => { expect(1).toBe(1); });

  // this will result in `**-a---b-**` ✅
  test('a - b', async () => { expect(1).toBe(1); });

  // this will result in `**-a-test-b-**` ✅
  test('a test b', async () => { expect(1).toBe(1); });
)}
```

For the first 5 tests, the video recorded for earlier ones will be overwritten by the latest one, since the folder name all resolves to `**-a-b-**` that those special characters got ignored. I don't think it's developer's responsibility to make test name `fs.safe`, since it makes sense to use special characters like `>` or `<` to replace `greater than` or `smaller than`, etc.

image

image

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/23386

### CODE REVIEW

File: packages/playwright-test/src/util.ts [hunk 1]
```diff
@@ -195,8 +195,19 @@ export function expectTypes(receiver: any, types: string[], matcherName: string)
...
+export function sanitizeForFilePath(input: string) {
+  let removedNonWhiteSpaceChars = false;
+  let sanitized = input.replace(/[\x00-\x2C\x2E-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\x2A]+/g, substring => {
+    if (substring.trim())
+      removedNonWhiteSpaceChars = true;
+    return '-';
+  });
+  // For cosmetic reasons we only suffix with a hash if we removed non-whitespace characters.
+  if (!removedNonWhiteSpaceChars)
+    return sanitized;
```
Comment (aslushnikov) [inline packages/playwright-test/src/util.ts:207]: IIUC the following will clash:

`should<1 space>work`
`should<2 spaces>work`

File: tests/playwright-test/golden.spec.ts [hunk 2]
```diff
@@ -696,12 +696,16 @@ test('should respect comparator in config', async ({ runInlineTest }) => {
   expect(result.report.suites[0].specs[0].tests[1].status).toBe('unexpected');
 });
 
+// ../../snapshot!.txt as a snapshot name.
+// Its different per platform because we normalize the slashes.
+const kSnapshotNameWithSpecialCharactersOnDisk = process.platform === 'win32' ? 'snapshot-e636e8.txt' : 'napshot-6320a2.txt';
```
Comment (mxschmitt) [inline tests/playwright-test/golden.spec.ts:701]: needed for https://github.com/microsoft/playwright/blob/5821c547aacfd542259c8a9707b1eee119f0b692/packages/playwright-test/src/util.ts#L212-L218 which normalises the slashes for Windows.

File: packages/playwright-test/src/util.ts [hunk 3]
```diff
@@ -195,8 +195,18 @@ export function expectTypes(receiver: any, types: string[], matcherName: string)
...
+  let nonTrivialSubstitute = false;
+  let sanitized = input.replace(/[\x00-\x2C\x2E-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\x2A]+/g, substring => {
+    if (substring !== ' ')
+      nonTrivialSubstitute = true;
+    return '-';
+  });
+  if (!nonTrivialSubstitute)
+    return sanitized;
+  // If we sanitized the last or first character, remove it for cosmetic reasons.
+  sanitized = sanitized.replace(/^-/, '').replace(/-$/, '');
```
Comment (dgozman) [inline packages/playwright-test/src/util.ts:208]:
```suggestion
  sanitized = sanitized.replace(/^-+/, '').replace(/-+$/, '');
```

File: packages/playwright-test/src/util.ts [hunk 4]
```diff
@@ -195,8 +195,18 @@ export function expectTypes(receiver: any, types: string[], matcherName: string)
   }
 }
 
-export function sanitizeForFilePath(s: string) {
-  return s.replace(/[\x00-\x2C\x2E-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F]+/g, '-');
+export function sanitizeForFilePath(input: string) {
+  let nonTrivialSubstitute = false;
+  let sanitized = input.replace(/[\x00-\x2C\x2E-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\x2A]+/g, substring => {
```
Comment (dgozman) [inline packages/playwright-test/src/util.ts:200]: I hope this list includes dashes? We want `nonTrivialSubstitute` to be true in this case.

File: packages/trace-viewer/src/traceModelBackends.ts [hunk 5]
```diff
@@ -133,7 +133,7 @@ export class FetchTraceModelBackend implements TraceModelBackend {
 }
 
 function formatUrl(trace: string) {
-  let url = trace.startsWith('http') || trace.startsWith('blob') ? trace : `file?path=${trace}`;
+  let url = trace.startsWith('http') || trace.startsWith('blob') ? trace : `file?path=${encodeURIComponent(trace)}`;
```
Comment (dgozman) [inline packages/trace-viewer/src/traceModelBackends.ts:136]: Do we `decodeURIComponent` on the http server side?

File: packages/trace-viewer/src/ui/attachmentsTab.tsx [hunk 6]
```diff
@@ -66,6 +66,6 @@ function attachmentURL(traceUrl: string, attachment: {
   body?: string;
 }) {
   if (attachment.sha1)
-    return 'sha1/' + attachment.sha1 + '?trace=' + traceUrl;
+    return 'sha1/' + attachment.sha1 + '?trace=' + encodeURIComponent(traceUrl);
```
Comment (dgozman) [inline packages/trace-viewer/src/ui/attachmentsTab.tsx:69]: I feel like all the trace viewer changes are unrelated, let's move them to a separate PR?

File: tests/playwright-test/golden.spec.ts [hunk 7]
```diff
@@ -696,12 +696,16 @@ test('should respect comparator in config', async ({ runInlineTest }) => {
   expect(result.report.suites[0].specs[0].tests[1].status).toBe('unexpected');
 });
 
+// ../../snapshot!.txt as a snapshot name.
+// Its different per platform because we normalize the slashes.
```
Comment (dgozman) [inline tests/playwright-test/golden.spec.ts:700]: This is problematic - we want the same file names on different OSes, because they are committed to a repo.

File: tests/playwright-test/reporter-attachment.spec.ts [hunk 8]
```diff
@@ -235,7 +235,7 @@ test(`testInfo.attach name should be sanitized`, async ({ runInlineTest }) => {
   expect(result.failed).toBe(1);
 
   expect(result.output).toContain('attachment #1: ../../../test (text/plain)');
-  expect(result.output).toContain(`attachments${path.sep}-test`);
+  expect(result.output).toContain(`attachments${path.sep}test-`);
```
Comment (dgozman) [inline tests/playwright-test/reporter-attachment.spec.ts:238]: Where is the sha1?

File: tests/playwright-test/golden.spec.ts [hunk 9]
```diff
@@ -696,12 +696,16 @@ test('should respect comparator in config', async ({ runInlineTest }) => {
...
+const kSnapshotNameWithSpecialCharactersOnDisk = process.platform === 'win32' ? 'snapshot-e636e8.txt' : 'snapshot-6320a2.txt';
+
 test('should sanitize snapshot name when passed as string', async ({ runInlineTest }) => {
   const result = await runInlineTest({
     ...files,
-    'a.spec.js-snapshots/-snapshot-.txt': `Hello world`,
+    [`a.spec.js-snapshots/${kSnapshotNameWithSpecialCharactersOnDisk}`]: `Hello world`,
```
Comment (dgozman) [inline tests/playwright-test/golden.spec.ts:706]: This is a breaking change, I don't think we can afford it right now.

File: tests/playwright-test/reporter-attachment.spec.ts (hunk 8 above)
Comment (mxschmitt) [reply tests/playwright-test/reporter-attachment.spec.ts:238]: updated the test

File: tests/playwright-test/golden.spec.ts (hunk 7 above)
Comment (mxschmitt) [reply tests/playwright-test/golden.spec.ts:700]: clarified offline, don't touching vrt snapshot filenames.

File: packages/trace-viewer/src/ui/attachmentsTab.tsx (hunk 6 above)
Comment (mxschmitt) [reply packages/trace-viewer/src/ui/attachmentsTab.tsx:69]: yup https://github.com/microsoft/playwright/pull/23893.

File: packages/trace-viewer/src/traceModelBackends.ts (hunk 5 above)
Comment (mxschmitt) [reply packages/trace-viewer/src/traceModelBackends.ts:136]: We do, but extracted into https://github.com/microsoft/playwright/pull/23893.

File: packages/playwright-test/src/util.ts (hunk 4 above)
Comment (mxschmitt) [reply packages/playwright-test/src/util.ts:200]: added a test for it.

**Review by dgozman — APPROVED** [review]

File: tests/playwright-test/reporter-attachment.spec.ts [hunk 10]
```diff
@@ -235,7 +235,7 @@ test(`testInfo.attach name should be sanitized`, async ({ runInlineTest }) => {
   expect(result.failed).toBe(1);
 
   expect(result.output).toContain('attachment #1: ../../../test (text/plain)');
-  expect(result.output).toContain(`attachments${path.sep}-test`);
+  expect(result.output).toContain(`attachments${path.sep}test-8d909b-`);
```
[the remark this answers is not in the document]
Comment (mxschmitt) [reply tests/playwright-test/reporter-attachment.spec.ts:238]: https://github.com/microsoft/playwright/blob/e966b82cd01273c5ca1a68e7d4bb131f7faf9e64/packages/playwright-test/src/util.ts#L269-L281
