### PR TITLE
fix(html): don't conflate file names

### LINKED ISSUE #33554: [Bug]: HTML report confuses files from different projects
### Version

1.48.2

### Steps to reproduce

`playwright.config.ts`:
```typescript
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: [['html', { open: 'always' }]],
  projects: [
    { name: 'a', testDir: './tests/a' },
    { name: 'b', testDir: './tests/b' },
  ],
});
```
Two identical files `tests/a/test.spec.ts` and `tests/b/test.spec.ts`:
```typescript
import { test, expect } from '@playwright/test';

test('nothing', async () => {
  expect(true).toBe(true)
});
```

Run the tests...

### Expected behavior

Two passing tests under two separate file headers.

### Actual behavior

Running those tests results in an HTML report that looks like this:

Image

Both tests are listed under the same file header, even though they're from different files in different projects.

### Additional context

I believe the problem is caused here: https://github.com/microsoft/playwright/blob/33f9c8279c4375d2324957e00688bf750f90e43d/packages/playwright/src/reporters/html.ts#L246-L249

The `fileId` is calculated based only on the file path relative to its project's `testDir`. But projects can have different `testDir`s. This gives the same `fileId` to all files in all projects with the same path relative to their project "root".

It seems to me like using `fileName` instead of `relativeFile` as the argument to `calculateSha1()` would fix it. But I'm not sure what the significance is of the comment on line 247.

---

It's also possible to get the opposite problem if I add a third project in the above config like this:

```typescript
{ name: 'c', testDir: './', testMatch: '**/tests/a/**/*.spec.ts' }
```

Running tests for projects *a* and *c* causes the tests for project `a` and `c` to be listed under different file headers even though they're from the same file. I think this is less problematic.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    Container: Yes
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

(Some info omitted because I don't think it's relevant.)
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/33554

This change breaks how we generate `fileId`, but from what I can tell it's an implementation detail of ours so we don't need to care.

### CODE REVIEW

**Comment by Skn0tt** [comment]
This broke in https://github.com/microsoft/playwright/pull/29752/files#diff-d41bd2dd4bfbb96b59bcf2722ae6efb2076fe0869fed2f6425afa1e8e7498abeR232-R234, and it doesn't seem like that was intended.

File: packages/playwright/src/reporters/html.ts [hunk 1]
```diff
@@ -238,14 +238,12 @@ class HtmlBuilder {
...
+  async build(metadata: Metadata, rootDir: string, projectSuites: Suite[], result: FullResult, topLevelErrors: TestError[]): Promise<{ ok: boolean, singleTestId: string | undefined }> {
     const data = new Map<string, { testFile: TestFile, testFileSummary: TestFileSummary }>();
     for (const projectSuite of projectSuites) {
-      const testDir = projectSuite.project()!.testDir;
       for (const fileSuite of projectSuite.suites) {
         const fileName = this._relativeLocation(fileSuite.location)!.file;
-        // Preserve file ids computed off the testDir.
-        const relativeFile = path.relative(testDir, fileSuite.location!.file);
+        const relativeFile = path.relative(rootDir, fileSuite.location!.file);
         const fileId = calculateSha1(toPosixPath(relativeFile)).slice(0, 20);
```
Comment (pavelfeldman) [inline packages/playwright/src/reporters/html.ts:247]: I would pass fileName here.

**Review by pavelfeldman — APPROVED** [review]
