### PR TITLE
fix(tracing): allow disabling tracing through env

### LINKED ISSUE #21993: [BUG] Browser chrash when using Playwright VSC extension and trace-viewer enabled in config
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info: 
  - Base on default code after running 'npx init playwright@latest'
  - VSC extension: Playwright Test for VSCode v1.0.9
  - VSC: 1.76.2

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Config file**
Change made: 
```ts
    trace: 'retain-on-failure',
```

**Steps**
Prerequisites:
- Create project using 'npx init playwright@latest' (valid for Playwright v1.32.1)
- Open it in VSC
- Add extension: Playwright Test for VSCode 
- Change config to option `trace: 'retain-on-failure',`

- Enable `Show browser` in Playwright tab in Testing view
- Run first test using Test Explorer
- Browser should be preserved
- Try run another test, Record at cursor etc

**Expected**
Browser preserved for next actions

**Actual**
Browser exits or crashes with error: `Error: browser._newContextForReuse: Browser has been closed`
Hitting button: `Close all browsers` trigger information: Can't close browsers while running tests

### PR DESCRIPTION
**Pull request by dgozman**
We point `tracesDir` inside `test-results`, so it is removed between test runs, while reused context is still writing there.
    To fix the issue, we can now pass `env.PW_TEST_REUSE_CONTEXT`.

References #21993.

### CODE REVIEW

File: packages/playwright-test/src/index.ts [hunk 1]
```diff
@@ -251,7 +251,11 @@ const playwrightFixtures: Fixtures<TestFixtures, WorkerFixtures> = ({
     const traceMode = normalizeTraceMode(trace);
     const defaultTraceOptions = { screenshots: true, snapshots: true, sources: true };
     const traceOptions = typeof trace === 'string' ? defaultTraceOptions : { ...defaultTraceOptions, ...trace, mode: undefined };
-    const captureTrace = shouldCaptureTrace(traceMode, testInfo);
+    // "Show browser" mode forces context reuse that lives over multiple test runs.
+    // In this case, tracesDir will be removed between runs,
+    // and ongoing tracing on the same reused context will fail with ENOENT because trace files
+    // were suddenly removed.
+    const captureTrace = shouldCaptureTrace(traceMode, testInfo) && _contextReuseMode !== 'force';
```
Comment (pavelfeldman) [inline packages/playwright-test/src/index.ts:258]: I think this is misleading, we can force context reuse in the component testing and it should not affect the trace capturing, right?

**Review by pavelfeldman — APPROVED** [review]
