### PR TITLE
fix(codegen): trim alt selectors to 80 chars

### LINKED ISSUE #31254: [Bug]: Codegen freezes
### Version

1.44.1

### Steps to reproduce

Start codegen from the vs code extension or via a terminal window and browser freezes in under a min and unable to complete recording.  Tried on two different machine, one machine had a complete fresh install of NPM, VScode and playwright (Only has the playwright extension on this machine) and same issue as my normal work laptop codegen browser freezes.

When the codegen browser freezes the laptop fan is working overtime even though the cpu is under 50% and memory usage holding steady at around 60%.

### Expected behavior

Used codegen tool in the past no issue. really useful tool that now is unusable as unable to finish recording a test

### Actual behavior

Start codegen from the vs code extension or via a terminal window and browser freezes and unable to complete recording.  Tried on two different machine, one machine had a complete fresh install of NPM, VScode and playwright (Only has the playwright extension on this machine) and same issue as my normal work laptop codegen browser freezes.

When the codegen browser freezes the laptop fan is working overtime even though the cpu is under 50% and memory usage holding steady at around 60%.

### Additional context

Start codegen from the vs code extension or via a terminal window and browsers freezes and unable to complete recording.  Tried on two different machine, one machine had a complete fresh install of NPM, VScode and playwright (Only has the playwright extension on this machine) and same issue as my normal work laptop codegen browser freezes.

When the codegen browser freezes the laptop fan is working overtime even though the cpu is under 50% and memory usage holding steady at around 60%.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 5.79 GB / 15.61 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.0 - C:\Users\shaun.regan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1

PS C:\Dev\Access Applause\Automation> npx envinfo --preset playwright
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
   
  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 5.79 GB / 15.61 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.0 - C:\Users\shaun.regan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/31254

### CODE REVIEW

File: packages/playwright-core/src/server/injected/selectorGenerator.ts [hunk 1]
```diff
@@ -551,7 +551,7 @@ function suitableTextAlternatives(text: string) {
 
   result = result.filter(r => r.text);
   if (!result.length)
-    result.push({ text: text.substring(0, 80), scoreBouns: 0 });
+    result.push({ text: trimWordBoundary(text, 80), scoreBouns: 0 });
```
Comment (dgozman) [inline packages/playwright-core/src/server/injected/selectorGenerator.ts:554]: This was `substring()` on purpose, just in case line 548 did not yield anything.

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/injected/selectorGenerator.ts (hunk 1 above)
Comment (yury-s) [reply packages/playwright-core/src/server/injected/selectorGenerator.ts:554]: ok, reverted
