### PR TITLE
fix(clock): do not advance into the past

### LINKED ISSUE #37700: [Bug]: clock moves backward
### Version

1.55.1

### Steps to reproduce

When using `page.clock.runFor`, observed clock (via `Date.now()`) may go backwards.

### Expected behavior

Observed clock should never go backwards when using `runFor`.

### Actual behavior

Because fake clock `_runTo()` will advance the clock after running all timers and emptying event loop (through original `setTimeout(0)`.
If a timer (or any async code executed) calls `Date.now()`, it'll sync the fake clock with the native clock, potentially ahead of what will be set at the end of `_runTo()`.

Image

### Additional context

Confirmed it's fixed by preventing `_advanceNow()` to go backwards:

Image

### Environment

```shell
System:
    OS: macOS 15.6.1
    CPU: (8) arm64 Apple M3
    Memory: 81.66 MB / 24.00 GB
  Binaries:
    Node: 20.19.1 - ~/.nvm/versions/node/v20.19.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.19.1/bin/npm
    pnpm: 9.15.9 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.84.2 - /Users/gluck/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #37700.

### CODE REVIEW

File: packages/injected/src/clock.ts [hunk 1]
```diff
@@ -139,6 +151,13 @@ export class ClockController {
   }
 
   private _advanceNow(to: Ticks) {
+    if (this._now.ticks > to) {
```
Comment (pavelfeldman) [inline packages/injected/src/clock.ts:144]: It fees like all the non-replay advances can end up in this situation, just check and return instead of the strict mode?

**Review by pavelfeldman — APPROVED** [review]
