### PR TITLE
fix(mcp): pick a writable output directory when cwd is unsuitable

### LINKED ISSUE #1582: EPERM error: Playwright MCP ignores --user-data-dir and PLAYWRIGHT_MCP_STATE_DIR, defaults to C:\Windows\System32\.playwright-mcp\ on Windows"
My  OS: Windows

I was launching Playwright MCP using Claude Desktop

when i use navigate to a website : The webiste opens in chrome browser however claude desktop gives the below error.
The exact error: EPERM: operation not permitted, open 'C:\Windows\System32\.playwright-mcp\...'
Playwright MCP ignores --user-data-dir and PLAYWRIGHT_MCP_STATE_DIR, defaults to C:\Windows\System32\.playwright-mcp\ on Windows"

My config see bleow:
```json
{
  "preferences": {
    "coworkWebSearchEnabled": true,
    "coworkScheduledTasksEnabled": false,
    "ccdScheduledTasksEnabled": false
  },
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": [
        "@playwright/mcp@latest",
        "--user-data-dir",
        "C:\\Users\\<USERNAME>\\AppData\\Roaming\\npm\\PlaywrightMCP"
      ],
      "cwd": "C:\\Users\\<USERNAME>\\AppData\\Roaming\\npm\\PlaywrightMCP",
      "env": {
        "PLAYWRIGHT_MCP_STATE_DIR": "C:\\Users\\<USERNAME>\\AppData\\Roaming\\npm\\PlaywrightMCP"
      }
    }
  }
}
```

Any help or support is appreciated

Thanks 
Janaki

### PR DESCRIPTION
**Pull request by yury-s**
## Summary
- MCP hosts (e.g. Claude Desktop) launch the server with `cwd=/` on macOS/Linux or under `%SystemRoot%` on Windows, so the default `<cwd>/.playwright-mcp` output dir hits `EPERM` on the first tool call.
- Fall back to `os.tmpdir()/.playwright-mcp` when `cwd` is unsuitable or not writable. Throw at config resolution if `--output-dir` is explicitly set to such a location.

Fixes microsoft/playwright-mcp#1582

### CODE REVIEW

File: packages/playwright-core/src/tools/backend/context.ts [hunk 1]
```diff
@@ -384,10 +385,32 @@ export async function workspaceFile(options: ContextOptions, fileName: string, p
...
+    return false;
+  }
+}
+
 export function outputDir(options: ContextOptions): string {
   if (options.config.outputDir)
     return path.resolve(options.config.outputDir);
-  return path.resolve(options.cwd, options.config.skillMode ? '.playwright-cli' : '.playwright-mcp');
+  const baseName = options.config.skillMode ? '.playwright-cli' : '.playwright-mcp';
+  const cwd = path.resolve(options.cwd);
```
Comment (pavelfeldman) [inline packages/playwright-core/src/tools/backend/context.ts]: That's weird

**Review by pavelfeldman — APPROVED** [review]
