### PR TITLE
fix(tracing): do not capture iframes in head

### LINKED ISSUE #12005: [BUG] trace.playwright.dev showing grid above screens
**Context:**

- Playwright Version: @playwright/test 1.18.1
- Browser: Chromium
- Extra: https://trace.playwright.dev/
- OS: Linux 4.4 Ubuntu 20.04.3 LTS (Focal Fossa)
- Memory: [26](https://gitlab.com/zapier/team-zap-creation-infinity/editor/-/jobs/2078935792#L26)5.08 MB / 7.59 GB
- Container: Yes
- Node: 16.13.2 - /usr/bin/node
- Yarn: 1.22.17 - /usr/bin/yarn
- npm: 8.1.2 - /usr/bin/npm
- Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

Irrelevant.

**Describe the bug**

When we open a `trace.zip` on https://trace.playwright.dev, the previews show a 4 column grid above the actual screen (which is shown scrambled here for confidentiality):

As you can see they are iframes that look like:

```
<iframe __playwright_src__="/snapshot/frame@2e53f9f8d147652347672e36989e770d" src="https://trace.playwright.dev/snapshot/frame@2e53f9f8d147652347672e36989e770d?trace=blob%3Ahttps%3A%2F%2Ftrace.playwright.dev%2F53f04cf0-9afd-4ccb-b7cd-94602678cb68&amp;name=action%40call%4070" style="
"></iframe>
```

I also see this locally with `npx playwright show-trace` (1.18.1), but no in the recorded movies and screenshots. They are also not visible when I run headed locally, but then do show up in the trace when I open it.

### PR DESCRIPTION
**Pull request by yury-s**
Fixes #12005

### CODE REVIEW

File: packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts [hunk 1]
```diff
@@ -414,6 +414,10 @@ export function frameSnapshotStreamer(snapshotStreamer: string) {
         // Process iframe src attribute before bailing out since it depends on a symbol, not the DOM.
         if (nodeName === 'IFRAME' || nodeName === 'FRAME') {
           const element = node as Element;
+          // Skip iframes which are not inside document's body as they are not visisble.
+          // See https://github.com/microsoft/playwright/issues/12005.
+          if (!element.closest('body'))
```
Comment (dgozman) [inline packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts:419]: This does not work in shadow dom.

Comment (yury-s) [reply packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts]: Fixed.

File: packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts [hunk 2]
```diff
@@ -414,6 +423,10 @@ export function frameSnapshotStreamer(snapshotStreamer: string) {
         // Process iframe src attribute before bailing out since it depends on a symbol, not the DOM.
         if (nodeName === 'IFRAME' || nodeName === 'FRAME') {
           const element = node as Element;
+          // Skip iframes which are inside document's head as they are not visisble.
+          // See https://github.com/microsoft/playwright/issues/12005.
+          if (this._isInsideHeadTag(element))
```
Comment (dgozman) [inline packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts:428]: Let's move this check to the top, next to NOSCRIPT and others.

File: packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts [hunk 3]
```diff
@@ -264,6 +264,15 @@ export function frameSnapshotStreamer(snapshotStreamer: string) {
       }
     }
 
+    private _isInsideHeadTag(e: Element): boolean {
```
Comment (dgozman) [inline packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts:267]: I wonder if you'd like an approach like we take with `shadowDomNesting` better, since we are already traversing the whole DOM.

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts (hunk 3 above)
Comment (yury-s) [reply packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts]: Done. Not sure if I like it better.

**Review by FokkeZB — APPROVED** [review]
Thanks for fixing this @yury-s !
