### PR TITLE
fix(tracing): do not serialize buffers into the trace file

### LINKED ISSUE #18126: [BUG] "Tracing stop" is taking a very long time (Longer than 5 minutes)
**Context:**
- Playwright Version: 1.27.0
- Operating System: Windows
- Node.js version: 16.13.0
- Browser: Edge
- Extra: [any specific details about your environment]

**Code Snippet**

We are calling the `tracing.stop()` method at the end of our test and it is hanging in `await tracingContext.stop({
          path: `${this.baseLogDirectory}/playwright`,
        });`

```typescript
      this.log("🛑 Stopping Playwright UI Driver");
      const tracingContext = this.playwrightContext?.tracing;
      if (tracingContext) {
        await tracingContext.stop({
          path: `${this.baseLogDirectory}/playwright`,
        });
      }
      await this.browser.close();
      await this.playwrightContext?.close();

      this.log("🛑 Stopped Playwright UI Driver");
```

**Describe the bug**
I ran this with a debugger and see the "hanging" is happening in the `visitSha1s` function in tracing.js of Playwright Core
image

For some reason there is a huge object its trying to iterate over -> 

image

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #18126.

### CODE REVIEW

File: packages/playwright-core/src/server/trace/recorder/tracing.ts [hunk 1]
```diff
@@ -452,22 +452,24 @@ export class Tracing extends SdkObject implements InstrumentationListener, Snaps
...
 
-function visitSha1s(object: any, sha1s: Set<string>) {
-  if (Array.isArray(object)) {
-    object.forEach(o => visitSha1s(o, sha1s));
-    return;
-  }
+function visitTraceEvent(object: any, sha1s: Set<string>): any {
+  if (Array.isArray(object))
+    return object.map(o => visitTraceEvent(o, sha1s));
+  if (object instanceof Buffer)
```
Comment (yury-s) [inline packages/playwright-core/src/server/trace/recorder/tracing.ts:458]: Should we also skip it in the parent instead of inserting undefined?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/server/trace/recorder/tracing.ts (hunk 1 above)
Comment (dgozman) [reply packages/playwright-core/src/server/trace/recorder/tracing.ts:458]: Luckily, `JSON.stringify()` does it for us.
