### PR TITLE
fix(cli): show full tab list when opening with --extension

### LINKED ISSUE #254: Extension seems broken again
ok this worked just a couple versions before. before the switch to ephemeral sessions was done.

now.. running playwright-cli 0.1.0 (latest in npm), have an extension installed in a custom profile

> playwright-cli --profile=C:\Users\me\Downloads\q --extension open

the extension page does pop up, so the --profile=C:\Users\me\Downloads\q argument works, but that page is actually asking about token authorization, and it will *NOT list any open pages to connect to*

separately, I discovered having a ./playwright-cli,json file no longer works (I used to specify the profile there), like this:

> {
  "browser": {
    "userDataDir": "C:\\Users\\me\\Downloads\\q"
  }
}

so now need to use --profile= only.

Image

Image

> playwright-cli --version
0.1.0
> node --version
v24.13.0

### PR DESCRIPTION
**Pull request by yury-s**
Fixes: https://github.com/microsoft/playwright-cli/issues/254

### CODE REVIEW

File: packages/playwright/src/mcp/browser/tools/navigate.ts [hunk 1]
```diff
@@ -32,6 +32,12 @@ const navigate = defineTool({
 
   handle: async (context, params, response) => {
     const tab = await context.ensureTab();
+
+    if (!params.url) {
```
Comment (pavelfeldman) [inline packages/playwright/src/mcp/browser/tools/navigate.ts]: Navigate w/o url does not sound right, also including the snapshot seems weird.

**Review by pavelfeldman — APPROVED** [review]
