### PR TITLE
fix(har): account for reused sockets

### LINKED ISSUE #32960: [internal] Investigate fetch timings when Socket is reused
I wonder what does this mean for the timings? If the socket is reused, will it get zero `connect` timings? What if sending does not start right away - should that count as `blocked` or `queued`?

_Originally posted by @dgozman in https://github.com/microsoft/playwright/issues/32956#issuecomment-2393704472_

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/32960

If the socket is reused, the connect and DNS timings are set to -1, because that timing doesn't apply to the current request. The time between request start and the socket being free is counted as `blocked`.

### CODE REVIEW

File: packages/playwright-core/src/server/fetch.ts [hunk 1]
```diff
@@ -491,8 +498,14 @@ export abstract class APIRequestContext extends SdkObject {
       request.on('socket', socket => {
         // happy eyeballs don't emit lookup and connect events, so we use our custom ones
         const happyEyeBallsTimings = timingForSocket(socket);
-        dnsLookupAt = happyEyeBallsTimings.dnsLookupAt;
-        tcpConnectionAt ??= happyEyeBallsTimings.tcpConnectionAt;
+        if (request.reusedSocket) {
+          reusedSocketAt = monotonicTime();
+          dnsLookupAt = startAt;
```
Comment (dgozman) [inline packages/playwright-core/src/server/fetch.ts:503]: Perhaps set both `dnsLookupAt` and `tcpConnectionAt` to `undefined`? Would that make the code cleaner?

**Review by dgozman — APPROVED** [review]

File: packages/playwright-core/src/server/fetch.ts (hunk 1 above)
Comment (Skn0tt) [reply packages/playwright-core/src/server/fetch.ts]: Good idea. I've refactored it a little more, how do you like that?

**Review by dgozman — APPROVED** [review]
