### PR TITLE
fix(inspector): fall back to custom executable path for UI

### LINKED ISSUE #6158: [Question] How to run chrome in debug mode from executable path?
In my organization i can't download executable files from internet. Chrome version managed by oraganizationsecurity department.
Playwright works fine on chrome which i passed to executablePath: but in debug mode playwright tries to find executable in path where it should be downloaded by playwright. How can i change executablePath for debug mode? (PWDEBUG=1)

### PR DESCRIPTION
**Pull request by yury-s**
Fixes #6158

### CODE REVIEW

File: packages/installation-tests/installation-tests.sh [hunk 1]
```diff
@@ -194,6 +196,32 @@ function test_skip_browser_download {
...
+  fi
+
+  if [[ "$(uname)" != "Linux" ]]; then
+    echo
+    echo "Skipping test on non-Linux platform"
+    echo
+    return
+  fi
+
+  OUTPUT=$(PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 PWDEBUG=1 node inspector-custom-executable.js)
```
Comment (dgozman) [inline packages/installation-tests/installation-tests.sh:216]: Just do double-check: `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` is not required here, right?

**Review by dgozman — APPROVED** [review]

File: packages/installation-tests/installation-tests.sh (hunk 1 above)
Comment (yury-s) [reply packages/installation-tests/installation-tests.sh:216]: Yes, you are right

Comment (yury-s) [reply packages/installation-tests/installation-tests.sh]: Removed.
