### PR TITLE
fix: ensure ElementHandlerDispatcher has FrameDispatcher parent

### LINKED ISSUE #524: MCP Server crashes when a simple button is clicked
elementHandlerDispatcher.js:49
      throw new Error("ElementHandle can only be created from FrameDispatcher");
            ^

Error: ElementHandle can only be created from FrameDispatcher
    at ElementHandleDispatcher.fromJSHandle (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/dispatchers/elementHandlerDispatcher.js:49:13)
    at /Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/dispatchers/browserContextDispatcher.js:101:99
    at Array.map (<anonymous>)
    at WKBrowserContext.<anonymous> (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/dispatchers/browserContextDispatcher.js:101:32)
    at WKBrowserContext.emit (node:events:519:28)
    at Page.emitOnContextOnceInitialized (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/page.js:151:27)
    at Page.addConsoleMessage (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/page.js:253:10)
    at WKPage._onConsoleRepeatCountUpdated (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/webkit/wkPage.js:526:20)
    at WKPage._onConsoleMessage (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/webkit/wkPage.js:514:10)
    at WKSession.<anonymous> (/Users/amigoldenberg/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/server/webkit/wkPage.js:350:112)

Node.js v21.7.3
2025-06-05T07:53:54.137Z [playwright] [info] Server transport closed
2025-06-05T07:53:54.137Z [playwright] [info] Client transport closed
2025-06-05T07:53:54.137Z [playwright] [info] Server transport closed unexpectedly, this is likely due to the process exiting early. If you are developing this MCP server you can add output to stderr (i.e. `console.error('...')` in JavaScript, `print('...', file=sys.stderr)` in python) and it will appear in this log.
2025-06-05T07:53:54.137Z [playwright] [error] Server disconnected. For troubleshooting guidance, please visit our [debugging documentation](https://modelcontextprotocol.io/docs/tools/debugging) {"context":"connection"}
2025-06-05T07:53:54.137Z [playwright] [info] Client transport closed

### PR DESCRIPTION
**Pull request by dgozman**
This was not the case for console message arguments.

Fixes https://github.com/microsoft/playwright-mcp/issues/524.

### CODE REVIEW

File: packages/playwright-core/src/server/dispatchers/elementHandlerDispatcher.ts [hunk 1]
```diff
@@ -48,6 +49,8 @@ export class ElementHandleDispatcher extends JSHandleDispatcher<FrameDispatcher>
     const elementHandle = handle.asElement();
     if (!elementHandle)
       return new JSHandleDispatcher(scope, handle);
+    if (scope instanceof PageDispatcher)
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/dispatchers/elementHandlerDispatcher.ts]: I think line 45 has a bug - we can't allow creating ElementHandleDispatcher with the JSHandleDispatcherParentScope, it should be ElementHandledispatcherParentScope, which strictly is FrameDispatcher, but you could probably allow PageDispatcher for convenience. That way you can remove this exception and also remove wrong code from electronDispatcher.

**Review by pavelfeldman — APPROVED** [review]

**Comment by Manouchehri** [comment]
Running into this a lot with the Playwright MCP (noting this down so I can find the solution later).
