### PR TITLE
fix(ui): print the web server output in the ui mode

### LINKED ISSUE #31300: [Bug]: UI Mode doesn't show stderr or stdout of webServers
### Version

1.44.1

### Steps to reproduce

1. Configure `webServer[0].stdout` to be `'pipe'`
2. Use either `throw new Error('abc')` and `console.log('def')` in server files ran by `webServer` in `playwright.config.ts`
3. Observe that there is no feedback in either the UI or in the terminal that anything has gone wrong, but all tests are missing ("No tests", see screenshot below)

Screenshot 2024-06-13 at 20 18 00

Terminal:

```bash
➜  repro-playwright-ui-mode-missing-stderr-stdout git:(main) ✗ pnpm playwright test --ui
(nothing shown here, no stderr or stdout)
```

### Reproduction Repo

Reproduction: https://github.com/karlhorky/repro-playwright-ui-mode-missing-stderr-stdout

Run `pnpm install` and `pnpm test` to see the behavior.

### Expected behavior

1. `stderr` and `stdout` are shown in the terminal
2. An error message (maybe a modal overlay?) is displayed in the UI

### Actual behavior

No observable errors anywhere (unless you start non-UI mode)

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 92.28 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - /opt/homebrew/bin/node
    npm: 10.5.2 - /opt/homebrew/bin/npm
    pnpm: 9.3.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.4 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.90.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/31300

### CODE REVIEW

File: packages/playwright/src/runner/taskRunner.ts [hunk 1]
```diff
@@ -20,20 +20,26 @@ import type { FullResult, TestError } from '../../types/testReporter';
 import { SigIntWatcher } from './sigIntWatcher';
 import { serializeError } from '../util';
 import type { ReporterV2 } from '../reporters/reporterV2';
+import { InternalReporter } from '../reporters/internalReporter';
+import { Multiplexer } from '../reporters/multiplexer';
 
-type TaskPhase<Context> = (context: Context, errors: TestError[], softErrors: TestError[]) => Promise<void> | void;
+type TaskPhase<Context> = (reporter: ReporterV2, context: Context, errors: TestError[], softErrors: TestError[]) => Promise<void> | void;
```
Comment (yury-s) [inline packages/playwright/src/runner/taskRunner.ts:26]:
```suggestion
type TaskPhase<Context> = (reporter: InternalReporter, context: Context, errors: TestError[], softErrors: TestError[]) => Promise<void> | void;
```

?

**Review by yury-s — APPROVED** [review]
