### PR TITLE
fix(only-changed): show nice error message about shallow clones

### LINKED ISSUE #32188: [Bug]: --only-changed with shallow clone throws "unknown revision" error
We're seeing some reports on Discord about users trying out `--only-changed` in CI, and being surprised about the "unknown revision" error thrown by Git. This occurs on shallow clones, which is the default for GH Actions. We should detect this and show a nice error message.

Example report from Discord:

> Hi! I have a problem with new feature only-changed. I’m using gitlab and I want to use this option when I create new MR. 
But I get a error like this:
>
> npx playwright test --grep-invert '@fetch|@no-ci' --project=chromium --only-changed=main --reporter=line
Error: Cannot detect changed files for --only-changed mode:
git diff origin/main --name-only
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> 
> Any idea what i’m doing wrong?

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/32188

### CODE REVIEW

**Comment by Skn0tt** [comment]
I didn't want to add a test because shallow-cloning a repo in tests is quite a hassle. Works locally for me:
Screenshot 2024-08-16 at 09 58 10

File: packages/playwright/src/runner/vcs.ts [hunk 1]
```diff
@@ -27,6 +27,20 @@ export async function detectChangedTestFiles(baseCommit: string, configDir: stri
...
+
+      const unknownRevision = error.output.some(line => line?.includes('unknown revision'));
+      if (unknownRevision) {
+        const isShallowClone = childProcess.execSync('git rev-parse --is-shallow-repository', { encoding: 'utf-8',  stdio: 'pipe' }).trim() === 'true';
+        if (isShallowClone) {
+          throw new Error([
+            `Revision '${baseCommit}' is not available in the local repository.`,
+            `On CI, this is likely caused by a shallow clone.`,
+            `To fix, clone the full repository history:`,
+            '   https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches'
```
Comment (mxschmitt) [inline packages/playwright/src/runner/vcs.ts:39]:
```suggestion
            'e.g. for GitHub Actions: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches'
```

maybe something like that. Let's also get a stamp from Dima for this.

**Review by dgozman — APPROVED** [review]
