### PR TITLE
fix(test runner): expect.poll error reporting should handle non-expect errors

### LINKED ISSUE #32256: [Bug]: Test report says "undefined" when a promise is rejected inside expect.poll
### Version

1.46.1

### Steps to reproduce

1. Clone this sample repo https://github.com/bdcarr/playwright-poll-covers-error
2. `npm install && npm run test`

You can remove axios and just `return Promise.reject({ some: 'object', or: 'other' })` inside expect.poll, but I included the request & interceptor to explain our use case.

### Expected behavior

The test report prints the whole error object, same as happens when the error occurs outside of `expect.poll`.

### Actual behavior

The error printed in the report just says "undefined":
```
  1) test.spec.ts:19:5 › issue happens when request is inside expect.poll ──────────────────────────

    undefined

      20 |     await expect.poll(async () => {
      21 |         return request.get('https://www.fwoeifhwefwf.com/efhjio2wfhejilfuhwf');
    > 22 |     }).toMatchObject({ something: 'idk' });
         |        ^
      23 | });
      24 |
      25 | test('issue does not happen when request is outside expect.poll', async () => {

        at /Users/brycecarr/dev/src/my/playwright-poll-covers-error/test.spec.ts:22:8
```

### Additional context

In our actual repo, the report says "undefined: undefined". Not sure why it just says "undefined" once in the repro. Our real repo's on 1.40.1, maybe that's why.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 78.86 MB / 32.00 GB
  Binaries:
    Node: 20.15.1 - ~/.local/state/fnm_multishells/77311_1724290084305/bin/node
    npm: 10.7.0 - ~/.local/state/fnm_multishells/77311_1724290084305/bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.32 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/32256

We were expecting all errors to be of type `ExpectError`, but apparently `expect` propagates rejections in the polling functions right through. So we also need to handle that case.

I wonder if we have more cases of this. Would it make sense to enable `useUnknownInCatchVariables` in TypeScript?

### CODE REVIEW

File: packages/playwright/src/matchers/expect.ts [hunk 1]
```diff
@@ -289,8 +289,9 @@ class ExpectMetaInfoProxyHandler implements ProxyHandler<any> {
 
       const step = testInfo._addStep(stepInfo);
 
-      const reportStepError = (jestError: ExpectError) => {
-        const error = new ExpectError(jestError, customMessage, stackFrames);
+      const reportStepError = (_error: unknown) => {
+        const jestError = _error instanceof Error ? _error : new Error(String(_error));
```
Comment (dgozman) [inline packages/playwright/src/matchers/expect.ts:293]: Why wrapping into `Error(...)`? I'd think the next line is sufficient.

File: packages/playwright/src/matchers/expect.ts [hunk 2]
```diff
@@ -289,8 +289,9 @@ class ExpectMetaInfoProxyHandler implements ProxyHandler<any> {
 
       const step = testInfo._addStep(stepInfo);
 
-      const reportStepError = (jestError: ExpectError) => {
-        const error = new ExpectError(jestError, customMessage, stackFrames);
+      const reportStepError = (_error: unknown) => {
```
Comment (dgozman) [inline packages/playwright/src/matchers/expect.ts:292]: style: we only use `_leadingUnderscore` for private fields, not for local variable.

Comment (Skn0tt) [reply packages/playwright/src/matchers/expect.ts]: done in e4b1dc95dc5155dfbad915358cda5b09f89d4c7d

File: packages/playwright/src/matchers/expect.ts (hunk 1 above)
Comment (Skn0tt) [reply packages/playwright/src/matchers/expect.ts]: Because both `step.complete()` and `testInfo._failWithError` require the `Error` type and don't take `unknown`.

Comment (dgozman) [reply packages/playwright/src/matchers/expect.ts]: Actually, both of these are ready for non-`Error` errors, but the types are incorrect. I think we should add a test for this just in case, similar to the one in this PR.

Comment (Skn0tt) [reply packages/playwright/src/matchers/expect.ts]: Done in https://github.com/microsoft/playwright/pull/32257/commits/e4b1dc95dc5155dfbad915358cda5b09f89d4c7d. The test in this PR already has the non-`Error` case.

File: tests/playwright-test/expect-poll.spec.ts [hunk 3]
```diff
@@ -232,3 +232,16 @@ test('should show intermediate result for poll that spills over test time', asyn
   expect(result.output).toContain('Expected: 2');
   expect(result.output).toContain('Received: 3');
 });
+
+test('should propagate promise rejections', { annotation: { type: 'issue', description: 'https://github.com/microsoft/playwright/issues/32256' } }, async ({ runInlineTest }) => {
```
Comment (dgozman) [inline tests/playwright-test/expect-poll.spec.ts:236]: Let's add a second test that would have the predicate `async () => { throw 'String value'; }`.

**Review by dgozman — APPROVED** [review]

File: tests/playwright-test/expect-poll.spec.ts (hunk 3 above)
Comment (Skn0tt) [reply tests/playwright-test/expect-poll.spec.ts:236]: done in 6b07b2287b2bea98fbfdba1a0611952183393827
