### PR TITLE
fix(html): encode all stdio attachments

### LINKED ISSUE #33886: [Bug]: Calling execSync() in test produces extra attachment
### Version

1.49.0

### Steps to reproduce

Follow the steps in README: https://github.com/vitalets/playwright-issues/tree/exec-sync-output

The key point is calling `execSync()` in the test:
```ts
test('my test', async ({}) => {
  console.log('foo');
  execSync('echo bar', { stdio: 'inherit' });
  console.log('baz');
});
``` 

### Expected behavior

Single `stdout` attachment containing all outputs:
```
foo
bar
baz
```

### Actual behavior

There are two `stdout` attachments:
1. normal expandable `stdout` attachment: 
   ```
   foo
   baz
   ```
2. binary `stdout` attachment

Report:

### Additional context

Also tried to call `execSync()` without `stdout: 'inherit'`, result is the same.

### Environment

```shell
System:
    OS: macOS 13.6.9
    CPU: (8) arm64 Apple M1
    Memory: 56.22 MB / 16.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.14.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 7.27.1 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.95.3 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.49.0 => 1.49.0
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/33886. We're concatenating all stdio chunks that are `string`, but we don't concatenate `Buffer` chunks. The addition of `Buffer` attachments seems to go back to https://github.com/microsoft/playwright/pull/26391, but it's not sure if that was a necessary thing.

This PR fixes the issue by encoding all `Buffer` chunks, so they're concatenated together with the rest.

### CODE REVIEW

**Comment by Skn0tt** [comment]
@yury-s you authored the addition of the code i'm removing here. Do we know if folks rely on having binary stdout chunks available as attachments? It's not obvious to me if this is a bug or a feature.

File: packages/playwright/src/reporters/html.ts [hunk 1]
```diff
@@ -602,17 +602,10 @@ type JsonAttachment = {
...
 
 function stdioAttachment(chunk: Buffer | string, type: 'stdout' | 'stderr'): JsonAttachment {
-  if (typeof chunk === 'string') {
-    return {
-      name: type,
-      contentType: 'text/plain',
-      body: chunk
-    };
-  }
   return {
```
Comment (yury-s) [inline packages/playwright/src/reporters/html.ts:605]: The only case that I can think of where it may be useful to see original binary output is a tool that produces e.g. an image and prints the bytes to stdout. And even in that case the users should store the output to an attachment manually rather than piping it to playwright's.

**Review by yury-s — APPROVED** [review]

File: packages/playwright/src/reporters/html.ts (hunk 1 above)
Comment (Skn0tt) [reply packages/playwright/src/reporters/html.ts:605]: Thanks, that makes sense!
