### PR TITLE
fix(expect): adjust normalization for regex values in toHaveText matcher

### LINKED ISSUE #29382: [Bug]: Diff message of `expect().toHaveText()` is hard to read when there are matching and non-matching regex in expected texts
### Version

1.41.2

### Steps to reproduce

When there are both matching regex and non-matching regex in expected texts, the diff message is hard to read
```ts
import { expect, test } from "@playwright/test";

test("toHaveText()", async ({ page }) => {
  page.setContent(`
    <ul>
      <li>Coffee</li>
      <li>Tea</li>
      <li>Milk</li>
    </ul>
  `);
  const item = page.getByRole("listitem");
  await expect(item).toHaveText(["Coffee", /\d+/, /Milk/]);
});
```

### Expected behavior

The diff message should not highlight the matched regex. It should only highlight the non-matched regex.

### Actual behavior

The diff message also highlights the matched regex.
```shell
Running 1 test using 1 worker
  1) tohavetext.spec.ts:3:5 › toHaveText() ─────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveText(expected)

    Locator: getByRole('listitem')
    - Expected  - 2
    + Received  + 2

      Array [
        "Coffee",
    -   /\d+/,
    -   /Milk/,
    +   "Tea",
    +   "Milk",
      ]
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for getByRole('listitem')
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements
      -   locator resolved to 3 elements


      10 |   `);
      11 |   const item = page.getByRole("listitem");
    > 12 |   await expect(item).toHaveText(["Coffee", /\d+/, /Milk/]);
         |                      ^
      13 | });
      14 |

        at /private/tmp/playwright-to-have-text/tests/tohavetext.spec.ts:12:22

  1 failed
    tohavetext.spec.ts:3:5 › toHaveText() ──────────────────────────────────────────────────────────
```

### Additional context

_No response_

### Environment

```
System:
  OS: macOS 12.7.3
  CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Memory: 121.03 MB / 8.00 GB
Binaries:
  Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
  npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  pnpm: 8.15.1 - ~/.nvm/versions/node/v16.18.0/bin/pnpm
IDEs:
  VSCode: 1.86.0 - /usr/local/bin/code
Languages:
  Bash: 3.2.57 - /bin/bash
npmPackages:
  @playwright/test: ^1.41.2 => 1.41.2
```

### PR DESCRIPTION
**Pull request by pengooseDev**
Fixes #29382

1. The current issue occurs in the `toEqual` call when the `expected` type in `toHaveText` is `(string | RegExp)[]`. Since we cannot modify the external dependency `this.utils.printDiffOrStringify`, normalization is performed before invoking it.
2. As a precaution, I checked the `toMatchText` method, which handles cases where the type is `string | RegExp`, to ensure that regex values are processed correctly. Regression tests confirmed that no issues are present.

### CODE REVIEW

File: packages/playwright/src/matchers/toEqual.ts [hunk 1]
```diff
@@ -59,6 +59,21 @@ export async function toEqual<T>(
   if (pass) {
     printedExpected = `Expected: not ${this.utils.printExpected(expected)}`;
     printedReceived = `Received: ${this.utils.printReceived(received)}`;
+  } else if (Array.isArray(expected) && Array.isArray(received)) {
+    const normalizedExpected = expected.map((exp, index) => {
+      const rec = received[index];
+      if (exp instanceof RegExp)
```
Comment (yury-s) [inline packages/playwright/src/matchers/toEqual.ts:65]: nit: please use `isRexExp` from 'playwright-core/lib/utils'.

**Review by yury-s — APPROVED** [review]

File: packages/playwright/src/matchers/toEqual.ts (hunk 1 above)
Comment (pengooseDev) [reply packages/playwright/src/matchers/toEqual.ts]: @yury-s 
I've applied the suggested change. Thanks for the helpful feedback! :)

**Review by yury-s — APPROVED** [review]
