### PR TITLE
fix(line reporter): wrap chinese characters correctly

### LINKED ISSUE #33315: [Bug]: Incorrect length calculation with Chinese symbols in Line Reporter
### Version

1.46.0

### Steps to reproduce

Create a test step with Chinese symbols, like this "诶开伊艾西吉艾艾伊娜伊"

### Expected behavior

The line reporter must work in a line.

### Actual behavior

The line reporter incorrect work because if we use the 10 Chinese symbols it`s not equal length 10, it prints text to second line after this delete line and write new and the first line remain displayed.

### Additional context

Image

### Environment

System:
  OS: Windows 11 23H2 22631.4037
  CPU: (16) x64
Binaries:
  Node: 22.1.0
  npm: 10.8.3
npmPackages:
  @playwright/test: 1.46.0

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/33315.

### CODE REVIEW

File: packages/playwright/src/reporters/base.ts [hunk 1]
```diff
@@ -489,11 +489,34 @@ export function stripAnsiEscapes(str: string): string {
...
 }
 
+function characterWidth(c: string) {
+  return /[\u4e00-\u9fff]/.test(c) ? 2 : 1;
+}
+
+function stringWidth(v: string) {
+  let width = 0;
+  for (let i = 0; i < v.length; ++i)
+    width += characterWidth(v[i]);
```
Comment (pavelfeldman) [inline packages/playwright/src/reporters/base.ts:499]: v[i] accesses a single 16-bit code unit, which may not represent a full character if it's part of a surrogate pair.

File: packages/playwright/src/reporters/base.ts [hunk 2]
```diff
@@ -489,11 +489,34 @@ export function stripAnsiEscapes(str: string): string {
...
+  return width;
+}
+
+function suffixOfWidth(v: string, width: number) {
+  let i = v.length - 1;
+  for (; i > 0; --i) {
+    const c = v[i];
```
Comment (pavelfeldman) [inline packages/playwright/src/reporters/base.ts:506]: Same, this code can split surrogate pairs because it decrements the index i without considering whether v[i] is a full character or part of a surrogate pair

File: packages/playwright/src/reporters/base.ts [hunk 3]
```diff
@@ -489,11 +489,34 @@ export function stripAnsiEscapes(str: string): string {
   return str.replace(ansiRegex, '');
 }
 
+function characterWidth(c: string) {
+  return /[\u4e00-\u9fff]/.test(c) ? 2 : 1;
```
Comment (pavelfeldman) [inline packages/playwright/src/reporters/base.ts:493]: This range only covers the CJK, but there are more double-width characters, but there is more. https://www.npmjs.com/package/east-asian-width would be a proper way of handling this.

Comment (Skn0tt) [reply packages/playwright/src/reporters/base.ts]: was hesitant to introduce a dependency so I proposed this shortcut. agree that a dependency is good. I added `get-east-asian-width` in https://github.com/microsoft/playwright/pull/33322/commits/3d713aaf536d9a5ad3dd625db606b7525ace7342, it has ~7 million monthly downloads.

File: packages/playwright/src/reporters/base.ts (hunk 1 above)
Comment (Skn0tt) [reply packages/playwright/src/reporters/base.ts]: good point. I updated it to segment with `Intl.Segmenter` in https://github.com/microsoft/playwright/pull/33322/commits/f778ddb6c50bb0ec32cfe7bef59c2f98fd9f12e5, that's working well with surrogate emoji in my testing.

File: packages/playwright/src/reporters/base.ts [hunk 4]
```diff
@@ -489,11 +490,35 @@ export function stripAnsiEscapes(str: string): string {
   return str.replace(ansiRegex, '');
 }
 
+function characterWidth(c: string) {
+  return getEastAsianWidth.eastAsianWidth(c.codePointAt(0)!);
+}
+
+function stringWidth(v: string) {
+  let width = 0;
+  for (const { segment } of new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment(v))
```
Comment (pavelfeldman) [inline packages/playwright/src/reporters/base.ts:499]: Sounds like this is no better than `for (const segment of v)` in your use case.

File: packages/playwright/src/reporters/base.ts [hunk 5]
```diff
@@ -489,11 +490,35 @@ export function stripAnsiEscapes(str: string): string {
...
+    width += characterWidth(segment);
+  return width;
+}
+
+function suffixOfWidth(v: string, width: number) {
+  const segments = [...new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment(v)];
```
Comment (pavelfeldman) [inline packages/playwright/src/reporters/base.ts:505]: ditto

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright/src/reporters/base.ts (hunk 4 above)
Comment (Skn0tt) [reply packages/playwright/src/reporters/base.ts:499]: I think it is:

```js
> [...new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment("👟")]
[ { segment: '👟', index: 0, input: '👟' } ]
> "👟".split("")
[ '\ud83d', '\udc5f' ]
```

Comment (Skn0tt) [reply packages/playwright/src/reporters/base.ts:499]: It makes a difference for grapheme clusters, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Symbol.iterator#description
