### PR TITLE
fix(pwtest): fix focused line with dirname specified

### LINKED ISSUE #18155: [BUG]
**Context:**
- Playwright Version: 1.27
- Operating System: Windows 10
- Node.js version: 18.11.0
- Browser:  All

**Code Snippet**
I am using playwright example from here https://github.com/microsoft/playwright/tree/main/examples/todomvc
**Executing with line number**
```
>npx playwright test tests/integration.spec.ts:18

Running 0 tests using 0 workers
=================
 no tests found.
=================


To open last HTML report run:

  npx playwright show-report
```
**Executing without line number:**
```
npx playwright test tests/integration.spec.ts

Running 75 tests using 4 workers
```
**Describe the bug**
I was trying to execute only one test from a spec file by mentioning the line number like this

 "npx playwright test tests/integration.spec.ts:18" 

O/P:
no tests found.

but when I try to execute same spec file without line number ex: 

"npx playwright test tests/integration.spec.ts" 

all the tests in the file getting executed.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/18155

### CODE REVIEW

File: packages/playwright-test/src/runner.ts [hunk 1]
```diff
@@ -898,10 +894,14 @@ class ListModeReporter implements Reporter {
 
 function fileMatcherFrom(testFileFilters?: TestFileFilter[]): Matcher {
   if (testFileFilters?.length)
-    return createFileMatcher(testFileFilters.map(e => e.re || e.exact || ''));
+    return createFileMatcher(testFileFilters.map(filter => normalizeFilter(filter)));
   return () => true;
 }
 
+function normalizeFilter(filter: TestFileFilter): string | RegExp {
```
Comment (yury-s) [inline packages/playwright-test/src/runner.ts:901]: nit: flattenFilter?

**Review by yury-s — APPROVED** [review]

**Review by yury-s — APPROVED** [review]
