### PR TITLE
fix: should be able to upload multiple large files

### LINKED ISSUE #23258: [BUG] Several files of 50 megabytes are not added to the input
### System info
- Playwright Version: [v1.33.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[/pull/23158]

**Expected**
10 files of 50MB or 30MB should be added to input

**Actual**

files are not added to input

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/23258

### CODE REVIEW

File: packages/playwright-core/src/client/elementHandle.ts [hunk 1]
```diff
@@ -271,8 +271,9 @@ export async function convertInputFiles(files: string | FilePayload | string[] |
     throw new Error('Cannot set buffer larger than 50Mb, please write it to a file and pass its path instead.');
 
   const stats = await Promise.all(items.filter(isString).map(item => fs.promises.stat(item as string)));
+  const totalExceedsMaxSize = stats.reduce((acc, stat) => acc + stat.size, 0) > sizeLimit;
```
Comment (mxschmitt) [inline packages/playwright-core/src/client/elementHandle.ts:274]: note: if the size is too big, over multiple files, we fail to convert it to JSON (when it gets stringified, and are not able to send it to the Chromium CDP transport)

File: packages/playwright-core/src/client/elementHandle.ts [hunk 2]
```diff
@@ -271,8 +271,9 @@ export async function convertInputFiles(files: string | FilePayload | string[] |
...
   const hasLargeFile = !!stats.find(s => s.size > sizeLimit);
-  if (hasLargeFile) {
+  if (hasLargeFile || totalExceedsMaxSize) {
```
Comment (dgozman) [inline packages/playwright-core/src/client/elementHandle.ts:276]: It looks like `hasLargeFile` is redundant now.

**Review by dgozman — APPROVED** [review]
