### PR TITLE
fix(test runner): better error message when importing typescript from esmodule

### LINKED ISSUE #9344: [BUG] fixed but it's not - Unknown file extension ".ts"
**Context:**
- Playwright Version: 1.15.2
- Operating System: Win 10 x64
- Node.js version: 14.17.6
- Browser: -
- Extra: part of my angular project

**Describe the bug**

I've had Playwright tests for a while in my project. And they used to work. I repaved my machine, everything works, angular project builds and runs. But when I try to run my tests with `npx playwright test` I get this error:

>Using config at [project_path]\playwright.config.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION] [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for [project_path]\e2e\src\sign-up.spec.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)
    at Loader._requireOrImport ([project_path]\node_modules\@playwright\test\lib\test\loader.js:214:52)
    at Loader.loadTestFile ([project_path]\node_modules\@playwright\test\lib\test\loader.js:130:7)
    at Runner._run ([project_path]\node_modules\@playwright\test\lib\test\runner.js:219:40) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

I understand I may miss something but this really gives me any clue. I saw there are some closed related issues but they seemed to be resolved. So what's wrong here?

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Fixes #9344﻿

### CODE REVIEW

File: packages/playwright-test/src/loader.ts [hunk 1]
```diff
@@ -204,6 +204,14 @@ export class Loader {
         }
       }
     } catch (error) {
+      if (error.code === 'ERR_MODULE_NOT_FOUND' && error.message.includes('Did you mean to import')) {
+        const didYouMean = /Did you mean to import (.*)\?/.exec(error.message)?.[1];
+        if (didYouMean?.endsWith('.ts'))
+          throw errorWithFile(file, 'Cannot import a typescript file from an esmodule. https://github.com/microsoft/playwright/issues/9344');
```
Comment (aslushnikov) [inline packages/playwright-test/src/loader.ts:210]: why do we refer to this issue? it's pretty obscure

**Review by aslushnikov — APPROVED** [review]
lgtm % remove issue reference since it's confusing
