### PR TITLE
fix(watch): cancel waitForCommand when files change

### LINKED ISSUE #32758: [internal] Watch mode ends up in 'MaxListenersExceededWarning: Possible EventEmitter memory leak detected'
```
(node:19233) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [ReadStream]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at _addListener (node:events:593:17)
    at ReadStream.addListener (node:events:611:10)
    at ReadStream.Readable.on (node:internal/streams/readable:1128:35)
    at InterfaceConstructor (node:internal/readline/interface:288:11)
    at new Interface (node:readline:115:3)
    at Object.createInterface (node:readline:212:10)
    at readCommand (/Users/maxschmitt/Developer/playwright/packages/playwright/src/runner/watchMode.ts:287:23)
    at runWatchModeLoop (/Users/maxschmitt/Developer/playwright/packages/playwright/src/runner/watchMode.ts:149:7)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at runTests (/Users/maxschmitt/Developer/playwright/packages/playwright/src/program.ts:190:20)
    at _Command.<anonymous> (/Users/maxschmitt/Developer/playwright/packages/playwright/src/program.ts:46:7)
```

repro: `PWTEST_WATCH=1 npm run ctest -- page-fill:23` and make a few changes to the file, like 15, so it does rerun it.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/32758

### CODE REVIEW

File: packages/playwright/src/runner/watchMode.ts [hunk 1]
```diff
@@ -144,11 +144,13 @@ export async function runWatchModeLoop(configLocation: ConfigLocation, initialOp
...
       printPrompt();
 
+    const waitForCommand = readCommand();
     const command = await Promise.race([
       onDirtyTests,
-      readCommand(),
+      waitForCommand.result,
     ]);
-
+    if (command === 'changed')
```
Comment (mxschmitt) [inline packages/playwright/src/runner/watchMode.ts:152]: Note: `onDirtyTests` can only resolve to `changed`.

**Review by dgozman — APPROVED** [review]
