### PR TITLE
fix(video): do not produce frames much faster than desired fps

### LINKED ISSUE #18198: [waitForTimeout] Slower than actual
```ts
test("rotatestart", async ({ page }) => {
  await page.goto("http://localhost:5173/#/rotatestart");
  await page.waitForTimeout(5000);
});

```
I visited a `<canvas ></canvas >`page and asked him to wait for 5000ms to generate a video. The action of the video **is slower than that on the actual web** (twice slower)

### PR DESCRIPTION
**Pull request by dgozman**
Otherwise, we get very long but slow videos.

Fixes #18198.

### CODE REVIEW

File: packages/playwright-core/src/server/chromium/videoRecorder.ts [hunk 1]
```diff
@@ -135,6 +135,7 @@ export class VideoRecorder {
     if (this._lastFrameBuffer) {
       const durationSec = timestamp - this._lastFrameTimestamp;
       const repeatCount = Math.max(1, Math.round(fps * durationSec));
+      this._progress.log(`pushing frame with duration ${durationSec} => repeating ${repeatCount} times`);
```
Comment (yury-s) [inline packages/playwright-core/src/server/chromium/videoRecorder.ts:138]: logging frame proved to be too verbose and just cluttering the output, let's remove this?

File: packages/playwright-core/src/server/page.ts [hunk 2]
```diff
@@ -846,54 +849,66 @@ function addPageBinding(bindingName: string, needsHandle: boolean, utilityScript
...
+      --this._budget;
+      ack();
+    }
+
+    if (this._throttlingEnabled && this._budget <= 0) {
+      // Non-throttled frame budget is exceeded. Next ack will be throttled.
+      this._timeoutId = setTimeout(() => this._tick(), this._throttlingInterval);
+    } else {
+      // Either not throttling, or still under budget. Next ack will be after the default timeout.
+      this._timeoutId = setTimeout(() => this._tick(), this._defaultInterval);
```
Comment (yury-s) [inline packages/playwright-core/src/server/page.ts:911]: should it be something like Math.max(0, this._defaultTimeout - this._timeSinceLastAck) ?

**Review by yury-s — APPROVED** [review]

File: packages/playwright-core/src/server/chromium/videoRecorder.ts (hunk 1 above)
Comment (dgozman) [reply packages/playwright-core/src/server/chromium/videoRecorder.ts:138]: Oh, sure!
