### PR TITLE
fix(fetch): cookie with domain=localhost

### LINKED ISSUE #18362: [BUG] `Invalid cookie fields` with `page.request.post(...)`
**Context:**
- Playwright Version: [what Playwright version do you use?] `@playwright/test 1.27.1`
- Operating System: [e.g. Windows, Linux or Mac] Linux
- Node.js version: [e.g. 12.22, 14.6] 16.14.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] All

## System:
 - OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
 - Memory: 26.90 GB / 38.89 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.0 - /usr/bin/node
 - Yarn: 1.22.19 - ~/.npm-global/bin/yarn
 - npm: 8.3.1 - /usr/bin/npm
## Languages:
 - Bash: 5.2.2 - /usr/bin/bash

**Code Snippet**

Playwright code
```ts
  test("foo test", async ({
    page,
  }) => {
    await page.request.post("/foobar", {
      form: {
        url: "https://example.com/",
      },
    });
  });
```

Request cookies:
```
cookie: readstufflater-session-id=0VENEQPYQYZZXRZWPBJC3GCD4C; readstufflater-client-visible-session=%7B%22access_expires%22%3A%222022-11-10T01%3A49%3A26.288Z%22%2C%22user_id%22%3A%2299C46PW4NPZT5SBPX2W7RR2T4M%22%7D
```

Response cookies: 
```
set-cookie: readstufflater-session-id=0VENEQPYQYZZXRZWPBJC3GCD4C; Domain=localhost; Path=/; Expires=Thu, 10 Nov 2022 00:49:26 GMT; HttpOnly; SameSite=Lax
set-cookie: readstufflater-client-visible-session=%7B%22access_expires%22%3A%222022-11-10T01%3A49%3A26.288Z%22%2C%22user_id%22%3A%2299C46PW4NPZT5SBPX2W7RR2T4M%22%7D; Domain=localhost; Path=/; Expires=Thu, 10 Nov 2022 00:49:26 GMT; SameSite=Lax
```

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

The cookies get set fine when updated through UI actions (clicking buttons, submitting forms).

It's only when I do `page.request.post(...)` or `page.request.get(...)` that I have a problem.


Chromium output:
```
Error: Protocol error (Storage.setCookies): Invalid cookie fields                                                                                                                    
                                                                                                                                                                                         
       at node_modules/playwright-core/lib/server/chromium/crConnection.js:206                                                                                                           
                                                                                                                                                                                         
      204 |         resolve,                                                                                                                                                             
      205 |         reject,                                                                                                                                                              
    > 206 |         error: new _protocolError.ProtocolError(false),                         
          |                ^                                                                
      207 |         method                                                                                                                                                               
      208 |       });                                                                       
      209 |     });                                                                         
                                                                                                                                                                                         
        at /home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/chromium/crConnection.js:206:16                                                      
        at new Promise (<anonymous>)                                                                                                                                                     
        at CRSession.send (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/chromium/crConnection.js:202:12)                                     
        at CRBrowserContext.addCookies (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/chromium/crBrowser.js:436:34)                           
        at BrowserContextAPIRequestContext._addCookies (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/fetch.js:453:25)                        
        at ClientRequest.<anonymous> (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/fetch.js:251:40)                                          
        at Object.onceWrapper (node:events:640:26)                                                                                                                                       
        at ClientRequest.emit (node:events:520:28)                                                                                                                                       
        at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)                                                                                                                  
        at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)                                                                                                                 
        at Socket.socketOnData (node:_http_client:482:22)
        at Socket.emit (node:events:520:28)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Socket.Readable.push (node:internal/streams/readable:228:10)
```

Firefox output:
```
Error: Protocol error (Browser.setCookies): Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICookieManager.add] setCookies@chrome://juggler/content/TargetReg
istry.js:959:24                                                                             
    Browser.setCookies@chrome://juggler/content/protocol/BrowserHandler.js:249:64
    dispatch@chrome://juggler/content/protocol/Dispatcher.js:129:39
    _dispatch@chrome://juggler/content/protocol/Dispatcher.js:69:36
    receiveMessage@chrome://juggler/content/components/Juggler.js:116:20


       at node_modules/playwright-core/lib/server/firefox/ffConnection.js:93

      91 |         resolve,
      92 |         reject,
    > 93 |         error: new _protocolError.ProtocolError(false),
         |                ^
      94 |         method
      95 |       });
      96 |     });

        at /home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/firefox/ffConnection.js:93:16
        at new Promise (<anonymous>)
        at FFConnection.send (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/firefox/ffConnection.js:89:12)
        at FFBrowserContext.addCookies (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/firefox/ffBrowser.js:334:37)
        at BrowserContextAPIRequestContext._addCookies (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/fetch.js:453:25)
        at ClientRequest.<anonymous> (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/playwright-core/lib/server/fetch.js:251:40)
        at Object.onceWrapper (node:events:640:26)
        at ClientRequest.emit (node:events:520:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
        at Socket.socketOnData (node:_http_client:482:22)
        at Socket.emit (node:events:520:28)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Socket.Readable.push (node:internal/streams/readable:228:10)
```

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/18362

### CODE REVIEW

File: packages/playwright-core/src/server/fetch.ts [hunk 1]
```diff
@@ -207,7 +207,7 @@ export abstract class APIRequestContext extends SdkObject {
       if (!cookie.domain)
         cookie.domain = url.hostname;
       else
-        assert(cookie.domain.startsWith('.'));
+        assert(cookie.domain.startsWith('.') || !cookie.domain.includes('.'));
```
Comment (dgozman) [inline packages/playwright-core/src/server/fetch.ts:210]: Is this a user-facing error? Let's do a throw with a meaningful message instead?

**Review by dgozman — APPROVED** [review]

**Review by mxschmitt — APPROVED** [review]

File: packages/playwright-core/src/server/fetch.ts (hunk 1 above)
Comment (yury-s) [reply packages/playwright-core/src/server/fetch.ts:210]: No, it's not user facing, it's a CHECK.
