### PR TITLE
fix(codegen): do not codegen non-existing fixtures

### LINKED ISSUE #32981: [Bug]: recordHar not exist when recording using codegen with HAR
### Version

1.42.0, but reproducible on latest

### Steps to reproduce

run in CLI npx playwright codegen "https://www.google.com" --save-har=testing.har

record some step

### Expected behavior

we can run the test using step from codegen

### Actual behavior

image

### Additional context

error code : 
Object literal may only specify known properties, and 'recordHar' does not exist in type 'Fixtures<{}, {}, PlaywrightTestArgs & PlaywrightTestOptions, PlaywrightWorkerArgs & PlaywrightWorkerOptions>'.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.28 MB / 16.00 GB
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.42.0 => 1.47.2
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Closes https://github.com/microsoft/playwright/issues/32981

### CODE REVIEW

File: packages/playwright-core/src/server/codegen/javascript.ts [hunk 1]
```diff
@@ -199,8 +199,12 @@ function formatObjectOrVoid(value: any, indent = '  '): string {
   return result === '{}' ? '' : result;
 }
 
-function formatContextOptions(options: BrowserContextOptions, deviceName: string | undefined): string {
+function formatContextOptions(options: BrowserContextOptions, deviceName: string | undefined, isTest: boolean): string {
   const device = deviceName && deviceDescriptors[deviceName];
+  if (isTest) {
+    // No recordHAR fixture in test.
+    options = { ...options, recordHar: undefined };
```
Comment (yury-s) [inline packages/playwright-core/src/server/codegen/javascript.ts:206]: add a test?

**Review by yury-s — APPROVED** [review]
