### PR TITLE
fix(canvas snapshots): position mismatch in headless mode

### LINKED ISSUE #33562: [Bug]: Trace screenshots of canvas elements look incorrect
### Version

1.49.0-alpha-2024-11-12

### Steps to reproduce

Filing this at the request of @Skn0tt per our conversation in [feat(trace viewer): show Screenshot instead of Snapshot](https://github.com/microsoft/playwright/pull/32248#issuecomment-2465461548)

Clone the repo at [https://github.com/craigglennie/playwright-canvas-bug-repro](https://github.com/craigglennie/playwright-canvas-bug-repro) and follow the instructions to run the test.

### Expected behavior

Trace screenshots should look like the webpage

Expected the following

Image

### Actual behavior

The trace image is stretched and kinda smeared. Also the `<canvas>` border appears doubled, there's a blue background where none is specified, and theres a horizontal line below the canvas that isn't in the HTML.

Get the following

Image

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 15.0.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 59.52 MB / 36.00 GB
  Binaries:
    Node: 20.18.0 - ~/.local/state/fnm_multishells/86698_1724810507933/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.local/state/fnm_multishells/86698_1724810507933/bin/npm
    pnpm: 8.15.9 - /opt/homebrew/opt/pnpm@8/bin/pnpm
  IDEs:
    VSCode: 1.95.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.32 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.49.0-alpha-2024-11-12 => 1.49.0-alpha-2024-11-12
```

### PR DESCRIPTION
**Pull request by Skn0tt**
The code for canvas rendering currently assumes that the screenshot it crops from has the same aspect ratio as the frame it's displaying in. That assumption is wrong. The fix is record the canvas position at snapshot time, so that it's relative to the screnshot aspect ratio.
Closes https://github.com/microsoft/playwright/issues/33562.

### CODE REVIEW

**Comment by dgozman** [comment]
> The code for canvas rendering currently assumes that the screenshot it crops from has the same aspect ratio as the frame it's displaying in. That assumption is wrong. The fix is to only use the image and frame width when cropping, not the height.

Why width and not height? If anything, I'd assume that width might differ due to different scrollbars, but height would likely be correct. Do you have a real repro that shows the discrepancy in width and/or height?

> To test this, I first tried comparing a screenshot of the snapshotted page with a screenshot of the rendered snapshot, but that didn't work because those screenshots had different dimensions. So I had to fall back to a visual regression test. Let me know if you have a better idea, or if it'd be better to not test it at all.

I'd skip the test in this case.

**Comment by Skn0tt** [comment]
> Why width and not height? If anything, I'd assume that width might differ due to different scrollbars, but height would likely be correct. Do you have a real repro that shows the discrepancy in width and/or height?

I was wondering the same. In the repro the customer shared, the height differed between headed and headless, but the width did not. If we know that the width will also differ because of scrollbars, then maybe this whole approach doesn't work.

**Comment by Skn0tt** [comment]
I've updated with the approach discussed yesterday, where we record the bounding rect at snapshot time and use that to identify the right img crop.

File: packages/trace-viewer/src/sw/snapshotRenderer.ts [hunk 1]
```diff
@@ -427,25 +427,26 @@ function snapshotScript(...targetIds: (string | undefined)[]) {
...
-            const partiallyUncaptured = xEnd > 1 || yEnd > 1;
-            const fullyUncaptured = xStart > 1 || yStart > 1;
+            drawCheckerboard(context, canvas);
+
+            const boundingRectAttribute = canvas.getAttribute('__playwright_bounding_rect__');
+            canvas.removeAttribute('__playwright_bounding_rect__');
+            if (!boundingRectAttribute)
+              continue;
+
+            const boundingRect = JSON.parse(boundingRectAttribute) as { left: number, top: number, right: number, bottom: number };
```
Comment (dgozman) [inline packages/trace-viewer/src/sw/snapshotRenderer.ts:437]: Let's try/catch parsing just in case.

File: packages/trace-viewer/src/sw/snapshotRenderer.ts [hunk 2]
```diff
@@ -427,25 +427,26 @@ function snapshotScript(...targetIds: (string | undefined)[]) {
...
 
-            const boundingRect = canvas.getBoundingClientRect();
-            const xStart = boundingRect.left / window.innerWidth;
-            const yStart = boundingRect.top / window.innerHeight;
-            const xEnd = boundingRect.right / window.innerWidth;
-            const yEnd = boundingRect.bottom / window.innerHeight;
-
-            const partiallyUncaptured = xEnd > 1 || yEnd > 1;
-            const fullyUncaptured = xStart > 1 || yStart > 1;
+            drawCheckerboard(context, canvas);
```
Comment (dgozman) [inline packages/trace-viewer/src/sw/snapshotRenderer.ts:430]: Let's keep not drawing the checkerboard for `fullyUncaptured` canvases, to avoid any performance penalties.

**Review by dgozman — APPROVED** [review]
Note that PR description is now wrong.
