### PR TITLE
fix: throw error if setInputFile does not exist

### LINKED ISSUE #29941: [Bug]: Locator.setInputFiles() does not throw error on invalid path passed in
### Version

1.41.2

### Steps to reproduce

Repro code is in this pull request- https://github.com/angelo-loria/playwright-boilerplate/pull/22
Actions code showing successful test execution here (first shard)- https://github.com/angelo-loria/playwright-boilerplate/actions/runs/8283196577/job/22665798875?pr=22

```
import {test} from '@playwright/test';
import path from 'path';

test.only('should set input files', async ({ page }) => {
    await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp');
    await page.getByTestId('myFile').setInputFiles(path.join(__dirname,'bogusFilePath.txt'));
});
```

image

### Expected behavior

I would expect `setInputFiles()` to throw an error if the path in the `files` argument passed in does not exist.

### Actual behavior

`setInputFiles()` does not throw error.

### Additional context

_No response_

### Environment

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 72.20 MB / 16.00 GB
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2 
    playwright-tesults-reporter: ^1.0.1 => 1.1.0
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/29941

### CODE REVIEW

File: packages/playwright-core/src/server/dom.ts [hunk 1]
```diff
@@ -642,10 +643,14 @@ export class ElementHandle<T extends Node = Node> extends js.JSHandle<T> {
     await progress.beforeInputAction(this);
     await this._page._frameManager.waitForSignalsCreatedBy(progress, options.noWaitAfter, async () => {
       progress.throwIfAborted();  // Avoid action that has side-effects.
-      if (localPaths)
+      if (localPaths) {
+        await Promise.all(localPaths.map(async localPath => (
```
Comment (mxschmitt) [inline packages/playwright-core/src/server/dom.ts:647]:
```suggestion
        await Promise.all(localPaths.map(localPath => (
```

**Review by pavelfeldman — APPROVED** [review]
