### PR TITLE
fix: do not change glob pattern when converting to url

### LINKED ISSUE #34915: [Bug]: Incorrect behavior of '?' in the url glob pattern
### Version

1.50.1

### Steps to reproduce

Per [documentation](https://playwright.dev/docs/network#glob-url-patterns), `?` in the url glob pattern matches any character except `/`. But the following code does not work as expected:
```ts
await page.goto('https://playwright.dev');
// notice '?' in the url pattern
await page.route('https://playwright.?ev', async route => {
  console.log('captured!');
  await route.continue();
});
await page.evaluate(() => fetch('https://playwright.dev'));
```

### Expected behavior

Request to `https://playwright.dev` will be captured.

### Actual behavior

Request to `https://playwright.dev` is not captured.

### Additional context

Outside the hostname, `?` also behaves in the confusing way. For example:
```ts
await page.goto('https://playwright.dev');
// notice '?' in the url pattern
await page.route('https://jsonplaceholder.typicode.com/comments?postId=1', async route => {
  console.log('captured!');
  await route.continue();
});
await page.evaluate(() => fetch('https://jsonplaceholder.typicode.com/comments?postId=1'));
```
Here, the request to `https://jsonplaceholder.typicode.com/comments?postId=1` is matched. But it occurs because `?` serves as any symbol, not as a query params separator. 
So any of the following requests are matched: 
```
https://jsonplaceholder.typicode.com/comments-postId=1
https://jsonplaceholder.typicode.com/comments_postId=1
https://jsonplaceholder.typicode.com/commentsXpostId=1
```
I've recently [submitted](https://github.com/microsoft/playwright/pull/34899) a documentation pr, that highlights that we should escape `?` to distinguish query separator from pattern symbol. But with the above example it does not help:
```ts
await page.goto('https://playwright.dev');
// notice '?' in the url pattern
await page.route('https://jsonplaceholder.typicode.com/comments\\?postId=1', async route => {
  console.log('captured!');
  await route.continue();
});
await page.evaluate(() => fetch('https://jsonplaceholder.typicode.com/comments?postId=1'));
```
Request to `https://jsonplaceholder.typicode.com/comments?postId=1` is not captured. 
The reason: url pattern is [passed through](https://github.com/microsoft/playwright/blob/release-1.50/packages/playwright-core/src/utils/isomorphic/urlMatch.ts#L128) `new URL()` constructor, that is not aware of special meaning for `?`. And given url is transformed as follows:
```
$ node -p 'new URL("https://jsonplaceholder.typicode.com/comments\\?postId=1").toString()'
https://jsonplaceholder.typicode.com/comments/?postId=1
```
Although it's a valid url, an extra `/` after `comments` breaks the comparison, because in the actual request url there is no such normalization:
```
final pattern: https://jsonplaceholder.typicode.com/comments/?postId=1
real req url:  https://jsonplaceholder.typicode.com/comments?postId=1
```
The same thing happens with the original example for this bug:
```
$ node -p 'new URL("https://playwright.?ev").toString()'
https://playwright./?ev
```

### Environment

```shell
System:
    OS: macOS 14.7.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 52.31 MB / 16.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.15.4 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.50.1 => 1.50.1
```

### PR DESCRIPTION
**Pull request by yury-s**
* Always treat `?` as escaped `?`. Suggest `*` to match any character.
* Dropped support for char sets `[...]`. `[` and `]` are treated same as escaped `\[` and `\]`. We didn't find any use of it on GitHub and it just complicates the code.

Fixes https://github.com/microsoft/playwright/issues/34915

### CODE REVIEW

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts [hunk 1]
```diff
@@ -101,10 +101,18 @@ export function urlMatches(baseURL: string | undefined, urlString: string, match
...
-    match = constructURLBasedOnBaseURL(baseURL, match);
+    // Resolve match relative to baseURL only if baseURL is set and match is not an absolute URL.
+    // Otherwise, leave it unchanged to prevent the URL constructor from interpreting glob symbols
+    // like ?, {, and }, which could alter the pattern.
+    if (baseURL && !parseURL(match))
+      match = constructURLBasedOnBaseURL(baseURL, match);
   }
-  if (isString(match))
+  if (isString(match)) {
+    const tryWithoutTrailingSlash = urlString.endsWith('/') && !match.endsWith('/');
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/isomorphic/urlMatch.ts:111]: ?

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts [hunk 2]
```diff
@@ -101,7 +101,35 @@ export function urlMatches(baseURL: string | undefined, urlString: string, match
...
+    }
+    // Glob symbols may be escaped in the URL and some of them such as ? affect resolution,
+    // so we replace them with safe components first.
+    const relativePath = match.split('/').map((token, index) => {
+      if (token === '.' || token === '..' || token === '')
+        return token;
+      // Handle special case of http*://
+      if (index === 0 && token.endsWith(':')) {
+        return mapToken(token, 'http:');
+      } else {
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/isomorphic/urlMatch.ts:118]: you don't need this else

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts [hunk 3]
```diff
@@ -101,7 +102,33 @@ export function urlMatches(baseURL: string | undefined, urlString: string, match
...
+      return replacement;
+    }
+    // Glob symbols may be escaped in the URL and some of them such as ? affect resolution,
+    // so we replace them with safe components first.
+    const relativePath = match.split('/').map((token, index) => {
+      if (token === '.' || token === '..' || token === '')
+        return token;
+      // Handle special case of http*://
+      if (index === 0 && token.endsWith(':'))
+        return mapToken(token, 'http:');
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/isomorphic/urlMatch.ts:118]:
```suggestion
        return mapToken(token, 'pw-matcher-schema:');
```

File: tests/page/interception.spec.ts [hunk 4]
```diff
@@ -90,21 +89,50 @@ it('should work with glob', async () => {
...
 
   expect(globToRegex('\\?')).toEqual(/^\?$/);
   expect(globToRegex('\\')).toEqual(/^\\$/);
   expect(globToRegex('\\\\')).toEqual(/^\\$/);
   expect(globToRegex('\\[')).toEqual(/^\[$/);
-  expect(globToRegex('[a-z]')).toEqual(/^[a-z]$/);
+  expect(globToRegex('[a-z]')).toEqual(/^\[a-z\]$/);
   expect(globToRegex('$^+.\\*()|\\?\\{\\}\\[\\]')).toEqual(/^\$\^\+\.\*\(\)\|\?\{\}\[\]$/);
+
+  expect(urlMatches(undefined, 'http://playwright.dev/', 'http://playwright.dev')).toBeTruthy();
```
Comment (pavelfeldman) [inline tests/page/interception.spec.ts:108]: I don't see a test for escaped ? (we've seen a bunch in the wild). Also not seeing where you support it.

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts [hunk 5]
```diff
@@ -51,13 +51,14 @@ export function globToRegex(glob: string): RegExp {
...
+        // Unescaped ? is treated same as escaped.
+        tokens.push('\\?');
         break;
       case '[':
-        tokens.push('[');
+        tokens.push('\\[');
         break;
       case ']':
-        tokens.push(']');
+        tokens.push('\\]');
```
Comment (vitalets) [inline packages/playwright-core/src/utils/isomorphic/urlMatch.ts:61]: Looks like `?`,`[`,`]` can be passed through to the `default:` case.

File: tests/page/interception.spec.ts (hunk 4 above)
Comment (yury-s) [reply tests/page/interception.spec.ts:108]: > I don't see a test for escaped ? (we've seen a bunch in the wild).

There is a few tests in `interception.spec.ts` and also in `tests/page/page-route.spec.ts`. Escaped behavior didn't change.

> Also not seeing where you support it.

See changes in `urlMatcher.ts`

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts (hunk 3 above)
Comment (yury-s) [reply packages/playwright-core/src/utils/isomorphic/urlMatch.ts:109]: Unfortunately, it didn't work. The slashes are properly inserted after domain only for known schemas (http:, ws:).

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts (hunk 5 above)
Comment (yury-s) [reply packages/playwright-core/src/utils/isomorphic/urlMatch.ts]: You are right, updated.

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts (hunk 3 above)
Comment (yury-s) [reply packages/playwright-core/src/utils/isomorphic/urlMatch.ts:109]: It has to be a "special scheme", defined here: https://url.spec.whatwg.org/#special-scheme

File: packages/playwright-core/src/utils/isomorphic/urlMatch.ts [hunk 6]
```diff
@@ -101,7 +92,34 @@ export function urlMatches(baseURL: string | undefined, urlString: string, match
...
+        return mapToken(token, `$_${index}_$`);
+      if (questionIndex === 0)
+        return mapToken(token, `?$_${index}_$`);
+      const newPrefix = mapToken(token.substring(0, questionIndex), `$_${index}_$`);
+      const newSuffix = mapToken(token.substring(questionIndex), `?$_${index}_$`);
+      return newPrefix + newSuffix;
+    }).join('/');
+    let resolved = constructURLBasedOnBaseURL(baseURL, relativePath);
+    for (const [token, original] of tokenMap)
+      resolved = resolved.replace(token, original);
```
Comment (pavelfeldman) [inline packages/playwright-core/src/utils/isomorphic/urlMatch.ts:121]: you take semantics here

File: tests/page/interception.spec.ts (hunk 4 above)
Comment (pavelfeldman) [reply tests/page/interception.spec.ts:108]: I can't see it there!

**Review by pavelfeldman — APPROVED** [review]
