### PR TITLE
fix(trace viewer): encode some urls inside style tags

### LINKED ISSUE #35681: [Bug]: CSS rendered as text in playwright test runner
### Version

1.52.0

### Steps to reproduce

1. Clone repo at https://github.com/BrightNight-Energy/debug-css-playwright.git
2. Install deps: `npm install`
3. Run dev server: `npm run dev`
4. Open test runner: `npx playwright test --ui`
5. You should see the issue:

Image

### Expected behavior

I expect the CSS to get inject, not rendered as text.

Image

### Actual behavior

Rendered as text, rather than injected as CSS.

Image

### Additional context

This issue does not exist when viewing in the browser normally. Nor have I seen this issue when using cypress. Therefore I'm thinking this is a playwright issue but do let me know if anything else comes to mind.

### Environment

```shell
System:
    OS: macOS 15.3.2
    CPU: (16) arm64 Apple M4 Max
    Memory: 654.33 MB / 64.00 GB
  Binaries:
    Node: 20.18.1 - ~/.local/share/nvm/v20.18.1/bin/node
    npm: 11.0.0 - ~/.local/share/nvm/v20.18.1/bin/npm
    bun: 1.1.45 - ~/.bun/bin/bun
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.52.0 => 1.52.0
```

### PR DESCRIPTION
**Pull request by dgozman**
When url inside a style tag contains `</style>`, it messes up with html parsing.

Fixes #35681.

### CODE REVIEW

File: packages/trace-viewer/src/sw/snapshotRenderer.ts [hunk 1]
```diff
@@ -618,6 +618,21 @@ function rewriteURLsInStyleSheetForCustomProtocol(text: string): string {
...
 }
 
+// url() inside a <style> tag can mess up with html parsing, so we encode some of them.
+// As an example, the following url will close the </style> tag:
+// url('data:image/svg+xml,<svg><defs><style>.a{fill:none}</style></defs><g class="a"></g></svg>')
+const urlToEscapeRegex1 = /url\(\s*'([^']*)'\s*\)/ig;
+const urlToEscapeRegex2 = /url\(\s*"([^"]*)"\s*\)/ig;
+function escapeURLsInStyleSheet(text: string): string {
+  const replacer = (match: string, url: string) => {
+    // Conservatively encode only urls with a closing tag.
```
Comment (agg23) [inline packages/trace-viewer/src/sw/snapshotRenderer.ts:628]: Why conservatively? Either the encoding works inside of `<style>` or it doesn't.

File: tests/library/trace-viewer.spec.ts [hunk 2]
```diff
@@ -1840,3 +1840,40 @@ test("shouldn't render not-blob trace received from message", async ({ showTrace
...
+      div {
+        background-image: url(   'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.cls-1{fill:none}</style></defs><title>Custom Title</title><polyline class="cls-1" points="1 2 3 4"/></svg>');
+        color: rgb(1, 2, 3);
+      }
+      span {
+        color: rgb(4, 5, 6);
+        background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><defs><style>.cls-1{fill:none}</style></defs><title>Custom Title</title><polyline class='cls-1' points='1 2 3 4'/></svg>" );
+      }
+    `;
+    await page.evaluate(css => document.querySelector('style').textContent = css, css);
```
Comment (agg23) [inline tests/library/trace-viewer.spec.ts:1870]: Is there significance to applying the style through JS instead of inline in the HTML?

File: packages/trace-viewer/src/sw/snapshotRenderer.ts (hunk 1 above)
Comment (dgozman) [reply packages/trace-viewer/src/sw/snapshotRenderer.ts:628]: I'd like to be on the safe side and alter the actual content as less a possible. We know that `</` urls are broken anyway, so fixing them is definitely a win.

**Review by pavelfeldman — APPROVED** [review]

**Review by mxschmitt — APPROVED** [review]
