### PR TITLE
fix: resolve WebServer cwd dir wrt configDir

### LINKED ISSUE #13115: [BUG] webServer command is relative to cwd, not config
- All paths in config should be relative to config
- Default cwd should match the config directory

### PR DESCRIPTION
**Pull request by aslushnikov**
Drive-by: speed-up webserver tests by not waiting 750ms to start it.

Fixes #13115

### CODE REVIEW

File: tests/playwright-test/assets/simple-server.js [hunk 1]
```diff
@@ -11,4 +11,4 @@ setTimeout(() => {
       response.end(process.env.FOO);
     });
   });
-}, 750);
+}, +(process.argv[3] ?? '0'));
```
Comment (mxschmitt) [inline tests/playwright-test/assets/simple-server.js:14]:
```suggestion
}, process.argv[3] ? +process.argv[3] : 0);
```
this does not get transpiled so we have to use default Node.js syntax.

**Review by mxschmitt — APPROVED** [review]
does this require docs changes/additions?
https://playwright.dev/docs/api/class-testconfig#test-config-web-server

**Review by dgozman — APPROVED** [review]
