### PR TITLE
chore: fix selector engines in electron and android

### LINKED ISSUE #36072: [internal] Failing selector tests in Electron
Failing since 92d4ce30c6efd251f5c353e8eda3f493d27fa4f2 

Image

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #36072.
Closes https://github.com/microsoft/playwright/pull/36075

### CODE REVIEW

File: packages/playwright-core/src/client/selectors.ts [hunk 1]
```diff
@@ -20,30 +20,35 @@ import { setTestIdAttribute } from './locator';
...
     setTestIdAttribute(attributeName);
-    for (const playwright of this._playwrights) {
-      for (const context of playwright._allContexts())
-        context._channel.setTestIdAttributeName({ testIdAttributeName: attributeName }).catch(() => {});
-    }
+    for (const context of this._contextsForSelectors)
+      context._channel.setTestIdAttributeName({ testIdAttributeName: attributeName }).catch(() => {});
+  }
+
+  _addSelectorOptions<T>(options: T) {
```
Comment (mxschmitt) [inline packages/playwright-core/src/client/selectors.ts:51]: nit: not 100% happy with the wording of 'add' since it would mean it would change the object which gets passed in.

**Review by mxschmitt — APPROVED** [review]
