### PR TITLE
fix: accomodate to changed MSEdge download format

### LINKED ISSUE #15932: [BUG] - Install MS Edge on CI Fails
On CI machines (MacOS and Windows) running:
`yarn dlx playwright@1.23.2 install chrome webkit msedge --with-deps`

Fails with an error installing Edge. We see linux passing this step just fine.

MacOS Error:
image

Windows Error:
image

I believe the script is failing here: https://github.com/microsoft/playwright/blob/c11f594c2921f98c4e72e47f9e819d2a40787b5e/packages/playwright-core/src/server/registry/index.ts#L760

Not sure why this is happening all of a sudden but we started seeing it in our CI ~5 hours ago and it is still happening.

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #15932

### CODE REVIEW

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright-core/src/server/registry/index.ts [hunk 1]
```diff
@@ -908,4 +909,20 @@ export function findChromiumChannel(sdkLanguage: string): string | undefined {
   return channel;
 }
 
+function lowercaseAllKeys(json: any): any {
+  if (typeof json !== 'object')
```
Comment (dgozman) [inline packages/playwright-core/src/server/registry/index.ts:913]: To accomodate null:

```suggestion
  if (typeof json !== 'object' || !json)
```

File: packages/playwright-core/src/server/registry/index.ts [hunk 2]
```diff
@@ -908,4 +909,20 @@ export function findChromiumChannel(sdkLanguage: string): string | undefined {
...
+    return json;
+
+  if (Array.isArray(json)) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/registry/index.ts:916]:
```suggestion
  if (Array.isArray(json))
    return json.map(lowercaseAllKeys);
```

**Review by dgozman — APPROVED** [review]

**Comment by charlesanim** [comment]
When can we expect a package update? @aslushnikov
