### PR TITLE
test: setContent with disabled javascript

### LINKED ISSUE #21379: [BUG] Page.setContent() not working in WebKit when JavaScript is disabled
### System info
- Playwright Version: v1.31.2
- Operating System: mcr.microsoft.com/playwright:v1.31.2-focal image
- Browser: WebKit
- Other info: JavaScript disabled

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'Chromium without JS',
      use: { ...devices['Desktop Chrome'], javaScriptEnabled: false },
    },
    {
      name: 'WebKit with JS',
      use: { ...devices['Desktop Safari'], javaScriptEnabled: true },
    },
    {
      name: 'WebKit without JS',
      use: { ...devices['Desktop Safari'], javaScriptEnabled: false },
    },
  ]
});
```
**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('Page.setContent', async ({ page }) => {
  await page.setContent('<h1>Hello</h1>')

  await expect(page.locator('h1')).toHaveText('Hello')
})

```

**Expected**

Tests pass.

**Actual**

The test fails when JavaScript is not available in WebKit:

```
Running 3 tests using 2 workers

  ✓  1 [Chromium without JS] › publishing-a-prereview.spec.ts:690:6 › Page.setContent (1.3s)
  ✓  2 [WebKit with JS] › publishing-a-prereview.spec.ts:690:6 › Page.setContent (1.3s)
  ✘  3 [WebKit without JS] › publishing-a-prereview.spec.ts:690:6 › Page.setContent (30.0s)


  1) [WebKit without JS] › publishing-a-prereview.spec.ts:690:6 › Page.setContent ──────────────────

    Test timeout of 30000ms exceeded.

    page.setContent: Navigation failed because page was closed!
    =========================== logs ===========================
    setting frame content, waiting until "load"
    ============================================================

      689 |
      690 | test.only('Page.setContent', async ({ page }) => {
    > 691 |   await page.setContent('<h1>Hello</h1>')
          |              ^
      692 |
      693 |   await expect(page.locator('h1')).toHaveText('Hello')
      694 | })

        at /app/integration/publishing-a-prereview.spec.ts:691:14

    Pending operations:
      - page.setContent at integration/publishing-a-prereview.spec.ts:691:14

  1 failed
    [WebKit without JS] › publishing-a-prereview.spec.ts:690:6 › Page.setContent ───────────────────
  2 passed (44.0s)
```

The failure screenshot shows that it was able to set the content:

test-failed-1

I've tried all the `waitUntil` options, and none work.

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/21379

### CODE REVIEW

File: packages/playwright-core/src/server/webkit/wkPage.ts [hunk 1]
```diff
@@ -571,6 +571,16 @@ export class WKPage implements PageDelegate {
         context = this._contextIdToContext.get(objectId.injectedScriptId);
       } else {
         context = this._contextIdToContext.get(this._mainFrameContextId!);
+        if (!this._page._browserContext._options.javaScriptEnabled) {
```
Comment (dgozman) [inline packages/playwright-core/src/server/webkit/wkPage.ts:574]: I think we just want to grab any context in the frame, not necessary main context or when javascript is disabled.

```ts
} else {
  context = [...this._contextIdToContext.values()].find(c => c.frame === this._page.mainFrame());
}
```

**Review by dgozman — APPROVED** [review]
