### PR TITLE
fix(chromium): drag and drop works in chromium

### LINKED ISSUE #1094: [Feature] drag and drop
Drag and drop should work with playwright. Using the existing mouse apis should generate working `dragstart`, `drag`, and `drop` events. There should also be new APIs to simulate dropping in external content, and to inspect content dragged from the web page.

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Waiting for #6203 to percolate to the cdn. But this all works locally.

Fixes #1094

### CODE REVIEW

File: src/server/chromium/crDragDrop.ts [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+    const dragSignalPromises: Promise<boolean>[] = [];
+    for (const frame of this._page._page.frames()) {
+      const promise = frame.evaluateExpression((function(){
+        return new Promise<boolean>(callback => {
+          document.addEventListener('mousemove', () => setTimeout(() => callback(false), 0), {once: true});
+          document.addEventListener('dragstart', () => callback(true), {once: true});
+        });
+      }).toString(), true, undefined, 'utility');
+      // don't resolve on errors. This could be replaced by Promise.any after Node v15
+      dragSignalPromises.push(promise.catch(e => new Promise(() => {})));
```
Comment (dgozman) [inline src/server/chromium/crDragDrop.ts:72]: Why not resolve on errors? What if we have just a single frame and is has just navigated under our feet? We'll stall forever.

File: src/server/chromium/crDragDrop.ts [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+    const client = this._page._mainFrameSession._client;
+    let onDragIntercepted: (payload: Protocol.Input.dragInterceptedPayload) => void;
+    const dragInterceptedPromise = new Promise<Protocol.Input.dragInterceptedPayload>(x => onDragIntercepted = x);
+
+    const dragSignalPromises: Promise<boolean>[] = [];
+    for (const frame of this._page._page.frames()) {
+      const promise = frame.evaluateExpression((function(){
+        return new Promise<boolean>(callback => {
+          document.addEventListener('mousemove', () => setTimeout(() => callback(false), 0), {once: true});
+          document.addEventListener('dragstart', () => callback(true), {once: true});
```
Comment (dgozman) [inline src/server/chromium/crDragDrop.ts:68]: Check defaultPrevented?

File: src/server/chromium/crDragDrop.ts [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+  constructor(page: CRPage) {
+    this._page = page;
+  }
+
+  async cancelDrag() {
+    if (!this._dragState)
+      return false;
+    await this._page._mainFrameSession._client.send('Input.dispatchDragEvent', {
+      type: 'dragCancel',
+      x: 0,
```
[the remark this answers is not in the document]
Comment (JoelEinbinder) [reply src/server/chromium/crDragDrop.ts:34]: Reasonable! I was going based off of Firefox, which has (0,0) for the position on all `dragend` events. But Chromium does report the position of `dragend`.

File: src/server/chromium/crDragDrop.ts (hunk 1 above)
Comment (JoelEinbinder) [reply src/server/chromium/crDragDrop.ts:73]: It doesn't stall because these are used with `Promise.race`

**Comment by JoelEinbinder** [comment]
Ready for review!

File: tests/page/page-drag.spec.ts [hunk 4]
```diff
@@ -19,8 +19,8 @@ import { test as it, expect } from './pageTest';
 import { attachFrame } from '../config/utils';
 
 it.describe('Drag and drop', () => {
-  it.skip(({ isAndroid }) => isAndroid);
-  it.fixme(({ browserName }) => browserName === 'chromium');
+  it.skip(({isAndroid}) => isAndroid);
+  it.skip(({isChromium, browserMajorVersion}) => isChromium && browserMajorVersion < 91);
```
Comment (dgozman) [inline tests/page/page-drag.spec.ts:23]: I was under impression that we are waiting for the stable to pick up the protocol changes.

File: tests/page/page-drag.spec.ts [hunk 5]
```diff
@@ -174,6 +173,40 @@ it.describe('Drag and drop', () => {
...
+    await page.hover('#target');
+    await page.mouse.up();
+    expect(await page.$eval('#target', target => target.contains(document.querySelector('#source')))).toBe(true);
+  });
+
+  it('should be able to drag the mouse in a frame', async ({page, server}) => {
+    await page.goto(server.PREFIX + '/frames/one-frame.html');
+    await page.mouse.move(30, 30);
+    await page.mouse.down();
+    await page.mouse.move(60, 60);
```
Comment (dgozman) [inline tests/page/page-drag.spec.ts:208]: Let's do a mouseup just in case.

File: src/server/chromium/crDragDrop.ts [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+            delete (window as any).dontWaitForMouseMove;
+            setTimeout(() => callback(dragEvent ? !dragEvent.defaultPrevented : false), 0);
+          }, {once: true, capture: true});
+          window.addEventListener('dragstart', event => dragEvent = event, {once: true, capture: true});
+        });
+      }).toString(), true, undefined, 'utility');
+      dragSignalPromises.push(promise.catch(() => false));
+    }
+    // make sure that all previous evaluate expressions hit the renderer
+    await this._crPage._page.mainFrame().evaluateExpression('1', false, undefined, 'utility').catch(() => {});
```
Comment (dgozman) [inline src/server/chromium/crDragDrop.ts:81]: You have to do this for all oopifs, I guess.

File: src/server/chromium/crDragDrop.ts [hunk 7]
```diff
@@ -0,0 +1,134 @@
...
+    if (button !== 'left')
+      return moveCallback();
+
+    const client = this._crPage._mainFrameSession._client;
+    let onDragIntercepted: (payload: Protocol.Input.dragInterceptedPayload) => void;
+    const dragInterceptedPromise = new Promise<Protocol.Input.dragInterceptedPayload>(x => onDragIntercepted = x);
+
+    const dragSignalPromises: Promise<boolean>[] = [];
+    for (const frame of this._crPage._page.frames()) {
+      const promise = frame.evaluateExpression((function() {
```
Comment (dgozman) [inline src/server/chromium/crDragDrop.ts:67]: I think you need something like `nonStallingRawEvaluateInExistingMainContext` her (there is such a function) to avoid stalling mouse move because some frame is perpetually navigating.

File: tests/page/page-drag.spec.ts (hunk 4 above)
Comment (JoelEinbinder) [reply tests/page/page-drag.spec.ts:23]: There is a try-catch in the code.

File: tests/page/page-drag.spec.ts (hunk 5 above)
Comment (JoelEinbinder) [reply tests/page/page-drag.spec.ts:209]: Done. Added an event tracker as well.

File: src/server/chromium/crDragDrop.ts [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+      client.off('Input.dragIntercepted', onDragIntercepted!);
+      return moveCallback();
+    }
+    await moveCallback();
+
+    const expectingDrag = (await Promise.all(this._crPage._page.frames().map(async frame => {
+      return frame.evaluateExpression((() => window.__didStartDrag).toString(), true, undefined, 'utility').catch(() => false);
+    }))).some(x => x);
+    this._dragState = expectingDrag ? (await dragInterceptedPromise).data : null;
+    client.off('Input.dragIntercepted', onDragIntercepted!);
```
Comment (yury-s) [inline src/server/chromium/crDragDrop.ts:99]: Consider removing 'mousemove' listeners too

File: src/server/chromium/crDragDrop.ts [hunk 9]
```diff
@@ -0,0 +1,129 @@
...
+        }, {once: true, capture: true});
+      }).toString(), true, undefined, 'utility').catch(() => {});
+    }));
+
+    client.on('Input.dragIntercepted', onDragIntercepted!);
+    try {
+      await client.send('Input.setInterceptDrags', {enabled: true});
+    } catch {
+      // If Input.setInterceptDrags is not supported, just do a regular move.
+      // This can be removed once Input.setInterceptDrags lands into Chromium Stable.
```
Comment (dgozman) [inline src/server/chromium/crDragDrop.ts:89]: This will be needed for quite a while for Electron, right? Let's update the comment.

File: src/server/chromium/crDragDrop.ts [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+    }
+    if (button !== 'left')
+      return moveCallback();
+
+    const client = this._crPage._mainFrameSession._client;
+    let onDragIntercepted: (payload: Protocol.Input.dragInterceptedPayload) => void;
+    const dragInterceptedPromise = new Promise<Protocol.Input.dragInterceptedPayload>(x => onDragIntercepted = x);
+
+    await Promise.all(this._crPage._page.frames().map(async frame => {
+      await frame.evaluateExpression((function() {
```
Comment (dgozman) [inline src/server/chromium/crDragDrop.ts:72]: I still think that awaiting all frames when some oopif could be perpetually navigating is going to stall. Did we figure out the solution?

Comment (JoelEinbinder) [reply src/server/chromium/crDragDrop.ts:72]: I'll go add a test

File: src/server/chromium/crDragDrop.ts (hunk 8 above)
Comment (JoelEinbinder) [reply src/server/chromium/crDragDrop.ts:99]: They have `{once: true}` and have no side effects, so I am not worried about them.

**Comment by bsteffensTempus** [comment]
What is the correct way to implement this functionality from within a playwright test?

**Comment by Dospios** [comment]
How use that from tests?

**Comment by JoelEinbinder** [comment]
Today you can just do `page.mouse.down`, `page.mouse.move`, and `page.mouse.up`. Follow #7562 for the high level api.
