### PR TITLE
fix(merge): preserve original "rootDir" by default

### LINKED ISSUE #27877: [BUG] TestCase.location incorrect/different when merging reports
### System info
- Playwright Version: 1.39.0
- Operating System: macOS 14.1
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './specs',
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('Run test', async ({ page }) => {
  // Do nothing
});
```

**Test reporter**
```ts
class CustomReporter implements Reporter {
	onTestEnd( test: TestCase, result: TestResult ) {
		console.log( 'onTestEnd', test.location.file);
	}
}
```

**Steps**

My project is in `/full/path/to/my/project` and specs are in `/full/path/to/my/project/specs`

- Run tests with `--reporter path/to/custom-reporter.ts`
- Get console output such as `onTestEnd /full/path/to/my/project/specs/frontend.spec.ts`
- Run tests with `--shard=1/2 --reporter=blob` followed by `npx playwright merge-reports --reporter path/to/custom-reporter.ts ./blob-report`
- Get console output such as `onTestEnd /full/path/to/my/project/frontend.spec.ts`

**Expected**

I'd expect `test.location.file` to be the same when running tests normally and when merging reports.

**Actual**

The `/specs` path segment is missing when merging reports

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/27877

### CODE REVIEW

File: packages/playwright/src/reporters/html.ts [hunk 1]
```diff
@@ -596,6 +596,7 @@ function createSnippets(stepsInFile: MultiMap<string, TestStep>) {
   for (const file of stepsInFile.keys()) {
     let source: string;
     try {
+      console.log('file = ' + file);
```
Comment (dgozman) [inline packages/playwright/src/reporters/html.ts:599]: undo?

File: packages/playwright/src/reporters/merge.ts [hunk 2]
```diff
@@ -235,6 +235,15 @@ function mergeConfigureEvents(configureEvents: JsonEvent[]): JsonEvent {
   };
   for (const event of configureEvents)
     config = mergeConfigs(config, event.params.config);
+
+  if (rootDirOverride) {
+    config.rootDir = rootDirOverride;
+  } else {
+    const rootDirs = new Set(configureEvents.map(e => e.params.config.rootDir));
+    if (rootDirs.size > 1)
+      throw new Error(`Multiple test root directories found in the blob reports. Please specify merge config with desired 'testDir'.\nFound directories:\n${[...rootDirs].join('\n')}`);
```
Comment (dgozman) [inline packages/playwright/src/reporters/merge.ts:244]: Let's be more descriptive here, something like:

```
Blob reports being merged were recorded with different test directories, and merging cannot proceed. This usually happens if you are merging reports from machines with different environment, like different operating system.

You can force merge by specifying a merge config file with "-c" option. If you'd like all test paths to be correct, make sure `testDir` in the merge config file points to the actual tests location.
```

File: packages/playwright/src/cli.ts [hunk 3]
```diff
@@ -199,7 +199,8 @@ async function mergeReports(reportDir: string | undefined, opts: { [key: string]
     reporterDescriptions = config.config.reporter;
   if (!reporterDescriptions)
     reporterDescriptions = [[defaultReporter]];
-  await createMergedReport(config, dir, reporterDescriptions!);
+  const rootDirOverride = configFile ? config.config.rootDir : undefined;
```
Comment (dgozman) [inline packages/playwright/src/cli.ts:202]: Should we update our docs to suggest a config when merging between OSes?

**Review by dgozman — APPROVED** [review]
