### PR TITLE
fix(connect): report all frames in existing page to the client

### LINKED ISSUE #8868: [BUG] Java, null pointer exception on first navigate call when using connectOverCDP()
**Context:**
- Playwright Version: 1.14.1
- Operating System: Winsows 10
- Browser: Chrome 93
- Extra: Started chrome from custom link like this "C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\chrome_instance" --restore-last-session --remote-debugging-port=9999

**Code Snippet**
```
    // This is kotlin code, but you can turn it into Java rather easily
    private var page: Page? = null
    private fun initBrowser() {
        val playwright = Playwright.create()
        val context = playwright.chromium().connectOverCDP("http://127.0.0.1:9999").contexts().first()
        context.onClose {
            page = null
        }
        context.setDefaultNavigationTimeout(10000.0)
        page = context.pages().first()
        page!!.setViewportSize(1014, 1039)
    }

// then somewhere else simply nagivate to any url
page!!.navigate("any url")
```

**Describe the bug**

I open a browser instance from command line with the parameters specified above, then i take control of the page by connecting to it.
I get a null pointer exception upon first navigation, but the page is successfully navigated with no issues, except for the exception trace. It seems to be an issue in your code. Subsequent nagivations work well without exceptions so it could be something related to the first call to navigate().
```
Exception of type class java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.microsoft.playwright.impl.PageImpl.handleEvent(PageImpl.java:183)
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:258)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:212)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:109)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
        at com.microsoft.playwright.impl.FrameImpl.navigateImpl(FrameImpl.java:395)
        at com.microsoft.playwright.impl.PageImpl.lambda$navigate$32(PageImpl.java:791)
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
        at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:790)
        at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:41)
        at com.microsoft.playwright.Page.navigate(Page.java:3145)
```

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/8868

### CODE REVIEW

File: src/dispatchers/frameDispatcher.ts [hunk 1]
```diff
@@ -44,6 +44,9 @@ export class FrameDispatcher extends Dispatcher<Frame, channels.FrameInitializer
       loadStates: Array.from(frame._subtreeLifecycleEvents),
     });
     this._frame = frame;
+    // Ensure client knows about all frames, otherwise it will not get events for those (such as FrameDetached)
+    for (const child of frame.childFrames())
```
Comment (dgozman) [inline src/dispatchers/frameDispatcher.ts:48]: I think we should instead emit frameAttached for all frames in PageDispatcher constructor.

Comment (yury-s) [reply src/dispatchers/frameDispatcher.ts:48]: Can you explain? I don't quite like the idea of firing 'model' events from a dispatcher.

**Review by dgozman — APPROVED** [review]
