### PR TITLE
test: fix WebKit socks proxy tests

### LINKED ISSUE #18301: [internal] failing tests on macOS Ventura
Summary:

- Chromium: all passing
- Firefox: 'should scope context handles' is failing
- WebKit: Socks seems not working, tests end up in a timeout, list of tests see below.

```
npm run ftest -- library/channels.spec.ts:39:1

library/channels.spec.ts:39:1 › should scope context handles

npm run wtest -- --workers 1 library/browsercontext-proxy.spec.ts:346:1 library/browsercontext-proxy.spec.ts:356:1 library/proxy.spec.ts:221:1

    [webkit] › library/browsercontext-proxy.spec.ts:346:1 › should use socks proxy =================
    [webkit] › library/browsercontext-proxy.spec.ts:356:1 › should use socks proxy in second page ==
    [webkit] › library/proxy.spec.ts:221:1 › should use socks proxy ================================
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/18301

### CODE REVIEW

File: tests/config/serverFixtures.ts [hunk 1]
```diff
@@ -49,9 +49,11 @@ export const serverFixtures: Fixtures<ServerFixtures, ServerWorkerOptions> = {
 
     const socksServer = socks.createServer((info, accept, deny) => {
       const socket = accept(true);
-      if (socket) {
-        // Catch and ignore ECONNRESET errors.
-        socket.on('error', () => {});
+      if (!socket)
+        return;
+      socket.on('data', data => {
+        if (!data.toString().startsWith('GET /'))
```
Comment (yury-s) [inline tests/config/serverFixtures.ts:55]: Does it have to be 'GET' ? Can we wait for complete http request header instead?

**Review by yury-s — APPROVED** [review]
