### PR TITLE
fix(trace): survive sw restart

### LINKED ISSUE #37421: [Bug]: Response body in trace viewer shows empty after some idle time
### Version

1.55.0

### Steps to reproduce

1. Given you start a test in UI mode (or load trace in trace viewer)
2. And you go to the network tabs
3. And you open the body subtab for some response (this loads fine)
4. And you now switch browser tab
5. And wait some minutes
6. And you go back to the Playwright browser tab
7. Then opening any response body shows `<Empty>`

### Expected behavior

While expected to see the response body.

### Actual behavior

Seeing `<Empty>` (which is really annoying, especially if the test has a large duration, which now has to be started again, just to see some network response)   

Image

And console (network) errors for the sha1 network requests: 
`Failed to load resource: the server responded with a status of 404 ()`

### Additional context

_No response_

### Environment

```shell
System:
  OS: Linux 6.6 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
  CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
  Memory: 10.39 GB / 23.47 GB
  Container: Yes
Binaries:
  Node: 22.15.1 - /usr/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.9.2 - /usr/bin/npm
  pnpm: 10.15.0 - /usr/bin/pnpm
npmPackages:
  @playwright/test: ^1.55.0 => 1.55.0
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/37421

### CODE REVIEW

File: packages/trace-viewer/src/sw/main.ts [hunk 1]
```diff
@@ -122,6 +132,16 @@ async function doFetch(event: FetchEvent): Promise<Response> {
       }
     }
 
+    if (!clientIdToTraceUrls.has(event.clientId)) {
+      // Service worker was restarted upon subresource fetch.
+      // It was stopped because ping did not keep in alive since the tab itself was throttled.
```
Comment (yury-s) [inline packages/trace-viewer/src/sw/main.ts]:
```suggestion
      // It was stopped because ping did not keep it alive since the tab itself was throttled.
```

File: packages/trace-viewer/package.json [hunk 2]
```diff
@@ -4,6 +4,7 @@
   "version": "0.0.0",
   "type": "module",
   "dependencies": {
+    "idb-keyval": "^6.2.2",
```
Comment (yury-s) [inline packages/trace-viewer/package.json:7]: Unpacked Size
928 kB

**Review by yury-s — APPROVED** [review]

File: packages/trace-viewer/package.json (hunk 2 above)
Comment (pavelfeldman) [reply packages/trace-viewer/package.json:7]: sw.bundle.js

before
220990
after
223446

File: packages/trace-viewer/src/sw/main.ts [hunk 3]
```diff
@@ -221,6 +241,36 @@ async function gc() {
...
+      limit: data.limit,
+      traceUrls: [...data.traceUrls]
+    };
+  }
+
+  const newValue = JSON.stringify(serialized);
+  const oldValue = await idbKeyval.get('clientIdToTraceUrls');
+  if (newValue === oldValue)
+    return;
+  idbKeyval.set('clientIdToTraceUrls', newValue);
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:265]: I think we want to `await` this

File: packages/trace-viewer/src/sw/main.ts [hunk 4]
```diff
@@ -221,6 +241,36 @@ async function gc() {
     if (!usedTraces.has(traceUrl))
       loadedTraces.delete(traceUrl);
   }
+
+  await saveClientIdParams();
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:245]: Saving here is troublesome:

When we re-open the browser tab, the service worker starts again, and the `/ping`s requests come in, which will call `gc`.
At this point `clientIdToTraceUrls` is empty and thus we clear the database, even tough this client has traces.

So, I suggest to either only call `saveClientIdParams` if we call `clientIdToTraceUrls.delete` 
and/or  move the `if (!clientIdToTraceUrls.has(event.clientId)) {` check before the `/ping` handling.

File: packages/trace-viewer/src/sw/main.ts [hunk 5]
```diff
@@ -122,6 +132,16 @@ async function doFetch(event: FetchEvent): Promise<Response> {
       }
     }
 
+    if (!clientIdToTraceUrls.has(event.clientId)) {
+      // Service worker was restarted upon subresource fetch.
+      // It was stopped because ping did not keep it alive since the tab itself was throttled.
+      const params = await loadClientIdParams(event.clientId);
+      if (params) {
+        for (const traceUrl of params.traceUrls)
+          await loadTrace(traceUrl, null, client, params.limit, () => {});
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:141]: `loadTrace` also calls `gc`. Not really what we need here, but not sure if that can cause (concurrency) issues?

Maybe move `gc` out of `loadTrace` and just call it in the  `relativePath === '/contexts'` branch?

File: packages/trace-viewer/src/sw/main.ts [hunk 6]
```diff
@@ -122,6 +132,16 @@ async function doFetch(event: FetchEvent): Promise<Response> {
       }
     }
 
+    if (!clientIdToTraceUrls.has(event.clientId)) {
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:135]: For the 'trace/snapshot/' client this will always be true.

File: packages/trace-viewer/src/sw/main.ts [hunk 7]
```diff
@@ -14,6 +14,8 @@
  * limitations under the License.
  */
 
+import * as idbKeyval from 'idb-keyval';
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:17]: I believe importing it like this will generally prevent tree-shaking?

This does allow tree-shaking:
`import { get, set } from 'idb-keyval';`

File: packages/trace-viewer/src/sw/main.ts [hunk 8]
```diff
@@ -221,6 +241,36 @@ async function gc() {
     if (!usedTraces.has(traceUrl))
       loadedTraces.delete(traceUrl);
   }
+
+  await saveClientIdParams();
+}
+
+// Persist clientIdToTraceUrls to localStorage to avoid losing it when the service worker is restarted.
```
Comment (cpAdm) [inline packages/trace-viewer/src/sw/main.ts:248]: Technically IndexDB !== localStorage

**Review by cpAdm — COMMENTED** [review]
@pavelfeldman Thanks for the effort! Unfortunately, it is not quite fixed, due to the `/ping` calling `gc` before we reload the traces, see PR comment.

File: packages/trace-viewer/src/sw/main.ts (hunk 7 above)
Comment (cpAdm) [reply packages/trace-viewer/src/sw/main.ts:17]: Nvm. This does seem to work
