### PR TITLE
fix(chromium): do not bring page to front before screenshot

### LINKED ISSUE #2576: [BUG] Screenshot: Reduce flicker in headful mode.
**Context:**
- Playwright Version: 1.1.1
- Operating System: MacOS Catalina
- Node version: 12.16
- Browser: Chromium

**Code Snippet**

```javascript
const playwright = require('playwright');

async function init (){
  const browser = await playwright['chromium'].launch({headless: false});
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://example.com');
  screenshot(page)
};

async function screenshot(page){
  let buffer = await page.screenshot();
  let imageBuffer = buffer.toString('base64');
  // save imageBuffer to database
  setTimeout(screenshot, 3000, page)
}

init();
```

**Describe the bug**

Bringing this here from [this question on StackOverflow](https://stackoverflow.com/questions/62373387/puppeteer-and-playwright-chrome-headful-bugs-when-making-a-screenshot).

Do you think we can/want to remove [this flicker](https://youtu.be/Tl2w-qKckkc)?

### PR DESCRIPTION
**Pull request by dgozman**
Fixes #2576.

### CODE REVIEW

File: src/screenshotter.ts [hunk 1]
```diff
@@ -30,13 +30,7 @@ export class Screenshotter {
...
   constructor(page: Page) {
     this._page = page;
-
-    const browserContext = page.context();
-    this._queue = (browserContext as any)[taskQueueSymbol];
-    if (!this._queue) {
-      this._queue = new TaskQueue();
-      (browserContext as any)[taskQueueSymbol] = this._queue;
-    }
+    this._queue = new TaskQueue();
```
Comment (pavelfeldman) [inline src/screenshotter.ts:33]: I'd actually understand if the queue went to the higher (browser) level, but it instead went to a page. Why?

**Review by pavelfeldman — APPROVED** [review]

**Review by aslushnikov — APPROVED** [review]
