### PR TITLE
chore: fix ui mode w/ multiple contexts

### LINKED ISSUE #21895: [BUG] UI mode doesn't show live trace when beforeEach is used to make an API call
### System info
- Playwright Version: 1.32
- Operating System: macOS
- Browser: Chromium
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ request }) => {
  const test = await request.get(`https://catfact.ninja/fact`);
  expect(test.ok()).toBeTruthy();
});

test('some steps', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.waitForTimeout(5000)
  await expect(page).toHaveTitle(/Playwright/);
});
```

**Steps**
- Run the test using UI watch mode and observe the live trace

**Expected**
The live trace is rendered as the test runs

**Actual**
The live trace is not rendered as the test runs.

In our framework implementation, we make api call to create a new workspace (in beforeEach block) in every test

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes: https://github.com/microsoft/playwright/issues/21895

### CODE REVIEW

File: packages/playwright-test/src/index.ts [hunk 1]
```diff
@@ -397,7 +397,8 @@ const playwrightFixtures: Fixtures<TestFixtures, WorkerFixtures> = ({
     {
       (playwright.request as any)._onDidCreateContext = onDidCreateRequestContext;
       (playwright.request as any)._onWillCloseContext = onWillCloseRequestContext;
-      (playwright.request as any)._defaultContextOptions = _combinedContextOptions;
+      (playwright.request as any)._defaultContextOptions = { ..._combinedContextOptions };
+      (playwright.request as any)._defaultContextOptions.tracesDir = path.join(_artifactsDir(), 'traces');
```
Comment (dgozman) [inline packages/playwright-test/src/index.ts:401]: Is this for persistent contexts only? Let's add a comment.

**Review by dgozman — APPROVED** [review]
