### PR TITLE
chore: miscellaneous trace viewer fixes

### LINKED ISSUE #23693: [BUG] attachment steps are not hidden inside `expect.toHaveScreenshot()`
1. The following test snippet:

```ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.goto('https://playwright.dev');
  await expect(page).toHaveScreenshot();
});
```

2. Execute with `--trace on`:

```
npx playwright test --trace on
```

3. Open trace with `npx playwright show-trace`:

image

---

### Actual / Expected

The "attach" step (focused on the screenshot) is a top-level step. I'd expect it to be hidden inside the `expect.toHaveScreenshot` step.

### PR DESCRIPTION
**Pull request by aslushnikov**
- properly annotate continued requests
- nest `attach` steps inside the related `expect` step
- fix primary-id-to-non-primary-id mapping
- make sure images in trace are not draggable

Fixes #23693

### CODE REVIEW

**Review by dgozman — APPROVED** [review]

File: packages/trace-viewer/src/ui/attachmentsTab.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ export const AttachmentsTab: React.FunctionComponent<{
     {screenshots.size ? <div className='attachments-section'>Screenshots</div> : undefined}
     {[...screenshots].map((a, i) => {
       return <div className='attachment-item' key={`screenshot-${i}`}>
-        <div><img src={attachmentURL(traceUrl, a)} /></div>
+        <div><img draggable="false" src={attachmentURL(traceUrl, a)} /></div>
```
Comment (mxschmitt) [inline packages/trace-viewer/src/ui/attachmentsTab.tsx:48]:
```suggestion
        <div><img draggable='false' src={attachmentURL(traceUrl, a)} /></div>
```

File: packages/web/src/components/imageDiffView.tsx [hunk 2]
```diff
@@ -161,7 +161,7 @@ const ImageWithSize: React.FunctionComponent<{
       <span style={{ flex: 'none', margin: '0 5px' }}>x</span>
       <span style={{ flex: '1 1 0', textAlign: 'start' }}>{ size ? size.height : ''}</span>
     </div>
-    <img src={src} onLoad={() => {
+    <img draggable="false" src={src} onLoad={() => {
```
Comment (mxschmitt) [inline packages/web/src/components/imageDiffView.tsx:164]:
```suggestion
    <img draggable='false' src={src} onLoad={() => {
```

File: packages/trace-viewer/src/ui/networkResourceDetails.tsx [hunk 3]
```diff
@@ -103,7 +103,7 @@ export const NetworkResourceDetails: React.FunctionComponent<{
         {resource.request.postData ? <div className='network-request-body'>{formatBody(requestBody, requestContentType)}</div> : ''}
         <div className='network-request-details-header'>Response Body</div>
         {!resource.response.content._sha1 ? <div className='network-request-response-body'>Response body is not available for this request.</div> : ''}
-        {responseBody !== null && responseBody.dataUrl ? <img src={responseBody.dataUrl} /> : ''}
+        {responseBody !== null && responseBody.dataUrl ? <img draggable="false" src={responseBody.dataUrl} /> : ''}
```
Comment (aslushnikov) [inline packages/trace-viewer/src/ui/networkResourceDetails.tsx:106]:
```suggestion
        {responseBody !== null && responseBody.dataUrl ? <img draggable='false' src={responseBody.dataUrl} /> : ''}
```
