### PR TITLE
fix: encode launch options correctly when reusing browser

### LINKED ISSUE #24157: [BUG] TypeError: browserType.connect: Invalid character in header content ["x-playwright-launch-options"]
**Steps**
- Install playwright
- Open the Testing tab in the VSCode
- Open the Playwright menu
- Chose "Show browser" item
- Run the "example" spec

**Expected**
The browser is open and the tests are green

**Actual**

TypeError: browserType.connect: Invalid character in header content ["x-playwright-launch-options"]

example spec ts - Untitled (Workspace) - Visual St

If I run tests in the 'Show trace viewer' mode - the tests are green:
example spec ts - Untitled (Workspace) - Visual St1

If I run tests in the 'headless' mode - the tests are green:
example spec ts - Untitled (Workspace) - Visual St2

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright/issues/24157

### CODE REVIEW

File: packages/playwright-core/src/client/browserType.ts [hunk 1]
```diff
@@ -93,7 +93,7 @@ export class BrowserType extends ChannelOwner<channels.BrowserTypeChannel> imple
     return this._connect({
       wsEndpoint: connectOptions.wsEndpoint,
       headers: {
-        'x-playwright-launch-options': JSON.stringify({ ...this._defaultLaunchOptions, ...launchOptions }),
+        'x-playwright-launch-options': jsonStringifyEncodeUnicode({ ...this._defaultLaunchOptions, ...launchOptions }),
```
Comment (dgozman) [inline packages/playwright-core/src/client/browserType.ts:96]: Let's comment that HTTP headers are ASCII-only, not UTF-8.

File: packages/playwright-core/src/utils/ascii.ts [hunk 2]
```diff
@@ -23,3 +23,10 @@ export function wrapInASCIIBox(text: string, padding = 0): string {
     '╚' + '═'.repeat(maxLength + padding * 2) + '╝',
   ].join('\n');
 }
+
+export function jsonStringifyEncodeUnicode(object: any): string {
```
Comment (dgozman) [inline packages/playwright-core/src/utils/ascii.ts:27]:
```suggestion
export function jsonStringifyForceASCII(object: any): string {
```

File: packages/playwright-test/src/index.ts [hunk 3]
```diff
@@ -125,7 +125,7 @@ const playwrightFixtures: Fixtures<TestFixtures, WorkerFixtures> = ({
         ...connectOptions,
         headers: {
           'x-playwright-reuse-context': '1',
-          'x-playwright-launch-options': JSON.stringify(_browserOptions),
+          'x-playwright-launch-options': jsonStringifyEncodeUnicode(_browserOptions),
```
Comment (dgozman) [inline packages/playwright-test/src/index.ts:128]: Same comment here please.

**Review by dgozman — APPROVED** [review]
