### PR TITLE
fix(connect): disable context takeover in websocket transport

### LINKED ISSUE #33810: [Bug]: WebSocket RPC transport is slow: per-message compression threshold ignored
### Version

1.49.0

### Steps to reproduce

1. Run Playwright tests.
2. For comparison, run Playwright tests with context takeover disabled in WebSocket RPC transport's `perMessageDeflate`[^1][^2] configuration (patch in additional context).

[^1]: https://github.com/microsoft/playwright/blob/b5bd543cc6935f62732da3b6183bd319eb2bdc2a/packages/playwright-core/src/server/transport.ts#L26-L34
[^2]: https://github.com/microsoft/playwright/blob/b5bd543cc6935f62732da3b6183bd319eb2bdc2a/packages/playwright-core/src/utils/wsServer.ts#L27-L35

### Expected behavior

- Vanilla Playwright is as fast as the modified Playwright.
- Under tcpdump, vanilla Playwright transmits small RPC channel messages (size under threshold) uncompressed.

### Actual behavior

- Vanilla Playwright is much slower than the modified Playwright.
- Under tcpdump, vanilla Playwright compresses even small RPC channel messages (size under threshold), unlike the modified Playwright.

### Additional context

Per-message compression was introduced in PR #26720.

From [`ws` documentation][wsdoc] (emphasis mine):

> `perMessageDeflate` can be used to control the behavior of [permessage-deflate
> extension][permessage-deflate]. The extension is disabled when `false` (default
> value). If an object is provided then that is extension parameters:
> 
> - `serverNoContextTakeover` {Boolean} Whether to use context takeover or not.
> - `clientNoContextTakeover` {Boolean} Acknowledge disabling of client context
>   takeover.
> 
> (snip)
> 
> - `threshold` {Number} Payloads smaller than this will not be compressed **if
>   context takeover is disabled**. Defaults to 1024 bytes.

Experiment shows that `threshold` is currently being ignored due to missing `serverNoContextTakeover` and `clientNoContextTakeover` options.

For testing, Playwright has been modified as follows and compared with original playwright:

```diff
diff --git a/packages/playwright-core/src/server/transport.ts b/packages/playwright-core/src/server/transport.ts
index e213e030e..d1567aa22 100644
--- a/packages/playwright-core/src/server/transport.ts
+++ b/packages/playwright-core/src/server/transport.ts
@@ -26,9 +26,11 @@ import type { HeadersArray } from './types';
 export const perMessageDeflate = {
+  serverNoContextTakeover: true,
+  clientNoContextTakeover: true,
   zlibDeflateOptions: {
     level: 3,
   },
   zlibInflateOptions: {
     chunkSize: 10 * 1024
   },
   threshold: 10 * 1024,
 };
diff --git a/packages/playwright-core/src/utils/wsServer.ts b/packages/playwright-core/src/utils/wsServer.ts
index 63c0ed1fe..e8d12ad93 100644
--- a/packages/playwright-core/src/utils/wsServer.ts
+++ b/packages/playwright-core/src/utils/wsServer.ts
@@ -27,9 +27,11 @@ const kConnectionSymbol = Symbol('kConnection');
 export const perMessageDeflate = {
+  serverNoContextTakeover: true,
+  clientNoContextTakeover: true,
   zlibDeflateOptions: {
     level: 3,
   },
   zlibInflateOptions: {
     chunkSize: 10 * 1024
   },
   threshold: 10 * 1024,
 };
```

Assuming a properly controlled experiment, this shows that WebSocket RPC messages are being unconditionally compressed, with a measurable negative performance impact.

[wsdoc]: https://github.com/websockets/ws/blob/c9d5436500fad16493a2cc62a0ce6daed83c9129/doc/ws.md#new-websocketserveroptions-callback
[permessage-deflate]: https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-19

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (64) x64 AMD EPYC 9654 96-Core Processor
    Memory: 54.79 GB / 62.73 GB
    Container: Yes
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    playwright: ^1.49.0 => 1.49.0
```

### PR DESCRIPTION
**Pull request by jinohkang-theori**
The `threshold` option in `perMessageDeflate` is ignored due to context takeover being enabled. This leads to WebSocket RPC messages being unconditionally compressed.

Most RPC channel messages are small, and unconditionally performing message compression has measurable performance impact.

Disable context takeover (for both server and client) to let compression threshold option to take effect.

Fixes #33810

### CODE REVIEW

**Comment by jinohkang-theori** [comment]
@microsoft-github-policy-service agree company="Theori"

File: packages/playwright-core/src/server/transport.ts [hunk 1]
```diff
@@ -24,6 +24,8 @@ import { httpHappyEyeballsAgent, httpsHappyEyeballsAgent } from '../utils/happy-
 import type { HeadersArray } from './types';
 
 export const perMessageDeflate = {
+  serverNoContextTakeover: true,
```
Comment (yury-s) [inline packages/playwright-core/src/server/transport.ts:27]: I believe (based on [this part](https://github.com/websockets/ws/blob/68614728c164eb55462ff12ba24cb30451d28ec6/lib/sender.js#L372-L375) of the implementation) that `serverNoContextTakeover` doesn't have any effect on the client web socket. If so let's not set it in the options here.

File: packages/playwright-core/src/utils/wsServer.ts [hunk 2]
```diff
@@ -25,6 +25,8 @@ let lastConnectionId = 0;
 const kConnectionSymbol = Symbol('kConnection');
 
 export const perMessageDeflate = {
+  serverNoContextTakeover: true,
+  clientNoContextTakeover: true,
```
Comment (yury-s) [inline packages/playwright-core/src/utils/wsServer.ts:29]: Ditto. Let's not set `clientNoContextTakeover` here if it's a noop anyway.

**Review by yury-s — APPROVED** [review]
The change looks good to me. Is there an easy way to test that it does improve the performance and not regress it?

**Review by yury-s — APPROVED** [review]

**Comment by jinohkang-theori** [comment]
> The change looks good to me. Is there an easy way to test that it does improve the performance and not regress it?

Would this work?

1. Run two inline tests, once with launch() and once with connect(), that calls a certain lightweight API 10,000 times.
2. Measure the execution time of both.
3. Assert that the ratio of launch() test time to connect() test time is below certain threshold.

Also, should this go into `tests/stress/`?

(I looked into the test suite, and couldn't find anything related to performance regression test other than timeouts here and there.)

File: packages/playwright-core/src/server/transport.ts (hunk 1 above)
Comment (jinohkang-theori) [reply packages/playwright-core/src/server/transport.ts]: Good catch, thanks.

**Comment by jinohkang-theori** [comment]
FWIW, here's a simple test you can run against https://github.com/microsoft/playwright/tree/main and https://github.com/jinohkang-theori/playwright/tree/fix/connect/no-context-takeover:

```javascript
const playwright = require("playwright");

async function main() {
    const n = 10000;
    const server = await playwright.chromium.launchServer({channel: "chromium", headless: true});
    const browser = await playwright.chromium.connect(server.wsEndpoint());
    const page = await browser.newPage();
    const startTs = performance.now();
    for (let i = 0; i < n; i++) {
        await page.title();
    }
    const endTs = performance.now();
    console.log(`mean call time: ${(endTs - startTs) / n}ms`);
    await page.close();
    await browser.close();
    await server.close();
}

main().catch(console.error);
```

**Comment by yury-s** [comment]
I've added the following test next to https://github.com/microsoft/playwright/blob/d029b03d9fc7d65329b47e08b9690b237bee30b7/tests/library/browsertype-connect.spec.ts#L161 and I see very little improvement and if I added heavier calls to the loop such as page.goto() it becomes indistinguishable.

```ts
    test('short message compression', async ({ connect, startRemoteServer }) => {
      const remoteServer = await startRemoteServer(kind);
      const browser = await connect(remoteServer.wsEndpoint());

      const n = 1000;
      const page = await browser.newPage();
      await page.goto('https://playwright.dev/');
      const startTs = performance.now();
      for (let i = 0; i < n; i++) {
        await page.title();
      }
      const endTs = performance.now();
      console.log(`mean call time: ${(endTs - startTs)}ms`);
      await page.close();
      await browser.close();
    });

```

**Comment by jinohkang-theori** [comment]
> and I see very little improvement

Thanks for sharing! I find it interesting since this PR resulted in 2x-3x perf improvement for me. Maybe something to do with DEFLATE implementation on my platform?

> and if I added heavier calls to the loop such as page.goto() it becomes indistinguishable.

Right, this is expected.
