### PR TITLE
fix: collect stdio from forked processes

### LINKED ISSUE #24591: [BUG] Forked process output won't get shown inside tests
```ts
test('should collect stdio', async ({ runInlineTest }) => {
  const { exitCode, report } = await runInlineTest({
    'stdio.spec.js': `
      import { test } from '@playwright/test';
      import { fork } from 'child_process';
      test('stdio', async () => {
        const child = fork('fork.js');
        await new Promise((resolve) => child.on('exit', (code) => resolve(code)));
      });
    `,
    'fork.js': `
      process.stdout.write('stdout text');
      process.stdout.write(Buffer.from('stdout buffer'));
      process.stderr.write('stderr text');
      process.stderr.write(Buffer.from('stderr buffer'));
    `
  });
  expect(exitCode).toBe(0);
  const testResult = report.suites[0].specs[0].tests[0].results[0];
  const { stdout, stderr } = testResult;
  expect(stdout).toEqual([{ text: 'stdout text' }, { buffer: Buffer.from('stdout buffer').toString('base64') }]);
  expect(stderr).toEqual([{ text: 'stderr text' }, { buffer: Buffer.from('stderr buffer').toString('base64') }]);
});
```

this won't work, since we only listen for `process.stdout.write = ...` and not listen to the actual FD. We should change it to listen on the parent process instead.

### LINKED ISSUE #26859: [BUG] No console output in Rust native module
### System info
- Playwright Version:1.37.1
- Operating System: Windows 11
- Browser: None
- Other info:
May have an effect on all operating systems.
The Rust toolchain is required.

### Source code

**Link to the GitHub repository with the repro**

https://github.com/samrg472/playwright-bug-26859

**Steps**

See the GitHub repository for reproducing.

**Expected**

I expect the the `no console output` test to have output. The provided `has console output` test is an example workaround by executing JS from Rust.

**Actual**

The `no console output` test has no console output.

### PR DESCRIPTION
**Pull request by mxschmitt**
A summary about the attempts we tried in https://github.com/microsoft/playwright/pull/26931 for https://github.com/microsoft/playwright/issues/26859 and https://github.com/microsoft/playwright/issues/24591.

1. attempt: collect all the stdio from the worker host.
    - this made it hard to capture the live console logs for the live trace
2. attempt: collect all the stdio from the worker host, but keep proxying `process.{stdout,stderr}.write`.
    - this solved the live console logs problem, since we could still listen on them
    - we found out about a race that the stdout/stderr streams can still buffer data while the test already had finished
    - we created a best effort flush implementation but didn't like the complexity it introduced to the project
 3. attempt: keep things like they are but also listen to stdio from the worker host
    - this solves the race of console.log in the test (things stay like they are)
    - this keeps live trace working (things stay like they are)
    - a known pitfall is that it could result in logs which don't end up in the reporter onStdOut/onStdErr, but it is already a significant improvement over how it was before.
      - before: they were not getting displayed
      - after: they are getting displayed and there is a low likelihood that they don't end up in the reporter API if the write happens slightly before a test finished.

Closes #26931
Fixes #26859
Fixes #24591

### CODE REVIEW

File: packages/playwright/src/common/ipc.ts [hunk 1]
```diff
@@ -141,3 +142,11 @@ export function serializeConfig(config: FullConfigInternal): SerializedConfig {
   };
   return result;
 }
+
+export function chunkToParams(chunk: Uint8Array | string): TestOutputPayload {
```
Comment (dgozman) [inline packages/playwright/src/common/ipc.ts:146]:
```suggestion
export function stdioChunkToParams(chunk: Uint8Array | string): TestOutputPayload {
```

**Review by dgozman — APPROVED** [review]
