### PR TITLE
fix(snapshotter): support constructed CSSStyleSheet

### LINKED ISSUE #7085: [BUG] Traceviewer screens are not recorded well when using constructable stylesheets
**Context:**
- Playwright Version: 12.1.1
- Operating System: mac
- Node.js version: 16
- Browser: Chromium
- Extra: [any specific details about your environment]

when running trace viewer on a site built with stencil-js, the html snapshots are displayed incorrectly. 
This is due to the use of constructable stylesheet.

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Fixes #7085

### CODE REVIEW

**Comment by pavelfeldman** [comment]
I am reading about constructable ss [here](https://developers.google.com/web/updates/2019/02/constructable-stylesheets) and it feels like you should dedupe them. It will actually make the code simpler to follow.

The doc is saying that you are supposed to create a bunch of constructable stylesheets and then add them into the adopted collections left and right. I would mimic this spirit in the serialization process:
- dedupe constructables by reference, serialize them once
- use your array of stylesheets only on the snapshot itself, not on shadow attrs
- put the index in that table in the template attributes for hydration

That way you are as scaleable as the web itself.

**Review by pavelfeldman — APPROVED** [review]

File: src/server/snapshot/snapshotterInjected.ts [hunk 1]
```diff
@@ -345,6 +355,15 @@ export function frameSnapshotStreamer(snapshotStreamer: string) {
           }
           for (let child = node.firstChild; child; child = child.nextSibling)
             visitChild(child);
+          let ownedDocument = null;
```
Comment (dgozman) [inline src/server/snapshot/snapshotterInjected.ts:358]: Let's call this `documentOrShadowRoot`

File: src/server/snapshot/snapshotterInjected.ts [hunk 2]
```diff
@@ -397,6 +416,23 @@ export function frameSnapshotStreamer(snapshotStreamer: string) {
         return checkAndReturn(result);
       };
 
+      const visitStyleSheet = (sheet: CSSStyleSheet) => {
+        const data = ensureCachedData(sheet);
+        const oldCSSText = data.cssText;
+        const cssText = this._updateStyleElementStyleSheetTextIfNeeded(sheet) || '';
+        const equals = cssText === oldCSSText;
+        const checkAndReturn = (n: NodeSnapshot): { equals: boolean, n: NodeSnapshot } => {
```
Comment (dgozman) [inline src/server/snapshot/snapshotterInjected.ts:424]: Let's inline this method.

**Review by dgozman — APPROVED** [review]
