### PR TITLE
fix(codegen): generate routeFromHAR for --save-har option

### LINKED ISSUE #33465: [Bug]: playwright codegen use --save-har generate error code
### Version

1.48.2

### Steps to reproduce

run cli `npx playwright codegen --save-har=example.har  https://www.npmjs.com/package/@playwright/test`

inspector gen 
Image

i copy to vscode, it's show  error tip
Image

i look the document. `recordHar` not support test.use. its only support `browser.newContext({recordHar:...})` 

https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-har

### Expected behavior

import { test, expect } from "@playwright/test";

test.use({
  // recordHar: {
  //   mode: "minimal",
  //   path: "/Users/landon/Documents/moego/qa-test/example.har",
  // },
  serviceWorkers: "block",
});

test("test", async ({ browser }) => {
  const context = await browser.newContext({
    recordHar: {
      mode: "minimal",
      path: "/Users/landon/Documents/moego/qa-test/example.har",
    },
  });
  const page = await context.newPage();
  await page.goto("https://www.npmjs.com/package/@playwright/test");
});

### Actual behavior

test.use({
  recordHar: { // error this line
    mode: 'minimal',
    path: '/Users/landon/Documents/moego/qa-test/example.har'
  },
  serviceWorkers: 'block'
});

test('test', async ({ page }) => {
  await page.goto('https://www.npmjs.com/package/@playwright/test');
});

### Additional context

_No response_

### Environment

 System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M2
    Memory: 157.78 MB / 16.00 GB
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  IDEs:
    VSCode: 1.95.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

### PR DESCRIPTION
**Pull request by yury-s**
Fixes https://github.com/microsoft/playwright/issues/33465

### CODE REVIEW

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright/src/matchers/matchers.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export function toBeVisible(
   const expected = visible ? 'visible' : 'hidden';
   const unexpected = visible ? 'hidden' : 'visible';
   const arg = visible ? '' : '{ visible: false }';
-  return toBeTruthy.call(this, 'toBeVisible', locator, 'Locator', expected, unexpected, arg, async (isNot, timeout) => {
+  return toBeTruthy.call(this, 'toBeVisibleFoo', locator, 'Locator', expected, unexpected, arg, async (isNot, timeout) => {
```
Comment (pavelfeldman) [inline packages/playwright/src/matchers/matchers.ts:143]: I don't think this is great.

File: packages/playwright-core/src/server/codegen/javascript.ts [hunk 2]
```diff
@@ -145,6 +145,8 @@ export class JavaScriptLanguageGenerator implements LanguageGenerator {
       import { test, expect${options.deviceName ? ', devices' : ''} } from '@playwright/test';
 ${useText ? '\ntest.use(' + useText + ');\n' : ''}
       test('test', async ({ page }) => {`);
+    if (options.contextOptions.recordHar)
+      formatter.add(`  await page.routeFromHAR('${options.contextOptions.recordHar.path}');`);
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/codegen/javascript.ts:149]: This might be not great on Windows

File: packages/playwright-core/src/server/codegen/javascript.ts [hunk 3]
```diff
@@ -160,6 +162,8 @@ ${useText ? '\ntest.use(' + useText + ');\n' : ''}
       (async () => {
         const browser = await ${options.browserName}.launch(${formatObjectOrVoid(options.launchOptions)});
         const context = await browser.newContext(${formatContextOptions(options.contextOptions, options.deviceName, false)});`);
+    if (options.contextOptions.recordHar)
+      formatter.add(`        await context.routeFromHAR('${options.contextOptions.recordHar.path}');`);
```
Comment (pavelfeldman) [inline packages/playwright-core/src/server/codegen/javascript.ts:166]: ditto
