### PR TITLE
fix(fixtures): make undefined option mean "default value"

### LINKED ISSUE #14989: [BUG] Setting the use.trace option to `undefined` causes TypeError: Cannot read property 'mode' of undefined
## Context:
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 14.18
- Browser: All

### Test file
```ts
// tests/example.test.ts
import { test } from '@playwright/test'


test('test', async () => {})
```

### Playwright Config

```ts
// playwright.config.ts
import { PlaywrightTestConfig } from "@playwright/test";

const playwrightTestConfig: PlaywrightTestConfig = {
  use: {
    trace: undefined,
  },
};

export default playwrightTestConfig;
```

**Describe the bug**

Running the above throws this error:

```
Running 1 test using 1 worker

  ✘  test/example.test.ts:4:1 › test (4ms)


  1) test/example.test.ts:4:1 › test ==================================================================

    TypeError: Cannot read property 'mode' of undefined




  1 failed
    test/example.test.ts:4:1 › test ===================================================================
```

This is caused by having `use,trace` as undefined in the playwright config.

This used to work with Playwright `v1.19`, and given the types of the option (`trace?: ...`), it should be allowed.

_After_ you figure out what the problem actually is, it is not a big deal as you can simply set the option to `off` instead of `undefined`. But it did take me a while to find that the trace option was causing it, as there is no stack trace in the error.

I got this right after upgrading to `v1.21`, and the reason the option is undefined is that I was setting it conditionally.

### PR DESCRIPTION
**Pull request by dgozman**
In the following example, `locale` inside the `describe` would be reverted to the default value:

```js
test.use({ locale: 'en-GB' });

test.decsribe(() => {
  test.use({ locale: undefined });
});
```

Fixes #14989.

### CODE REVIEW

File: packages/playwright-test/src/fixtures.ts [hunk 1]
```diff
@@ -222,6 +222,15 @@ export class FixturePool {
         if (options.scope === 'worker' && disallowWorkerFixtures)
           throw errorWithLocations(`Cannot use({ ${name} }) in a describe group, because it forces a new worker.\nMake it top-level in the test file or put in the configuration file.`, { location, name });
 
+        // Overriding option with "undefined" value means setting it to the default value
+        // from the original declaration of the option.
+        if (fn === undefined && options.option && previous) {
```
Comment (yury-s) [inline packages/playwright-test/src/fixtures.ts:227]: `fn` is a bit weird in this context, consider a more descriptive name `valueOrFn` maybe?

**Review by yury-s — APPROVED** [review]
