### PR TITLE
fix: support hasColors and getColorDepth in worker

### LINKED ISSUE #15584: [BUG] TypeError: process.stderr.hasColors is not a function
Calling assert from 'assert' crashes.

### PR DESCRIPTION
**Pull request by yury-s**
Fixes #15584

### CODE REVIEW

**Review by pavelfeldman — APPROVED** [review]

File: packages/playwright-test/src/worker.ts [hunk 1]
```diff
@@ -126,12 +127,24 @@ function initConsoleParameters(initParams: WorkerInitParams) {
...
+    process.stdout.columns = initParams.stdoutParams.columns;
+  setColorDepthMethods(process.stdout, initParams.stdoutParams.colorDepth);
+  if (initParams.stderrParams.rows)
+    process.stderr.rows = initParams.stderrParams.rows;
+  if (initParams.stderrParams.columns)
+    process.stderr.columns = initParams.stderrParams.columns;
+  setColorDepthMethods(process.stderr, initParams.stderrParams.colorDepth);
+}
+
+function setColorDepthMethods(stream: WriteStream, depth: number) {
```
Comment (dgozman) [inline packages/playwright-test/src/worker.ts:142]: Let's reduce duplication by generalizing this method to `setTTYParams(stream, params)`

**Review by dgozman — APPROVED** [review]
