### PR TITLE
fix(test): do not allow mixing tests from different types

### LINKED ISSUE #29282: [BUG] fixutre with worker scope will mess execution test executions in serial mode
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

```
// testFixture.ts

import test, { Page } from "@playwright/test";

export const scopedWorkerTests = test.extend<
  { scopedWorkerPage: Page },
  { scopedWorkerTest: string }
>({
  scopedWorkerTest: [
    async ({}, use) => {
      await use("test");
    },
    { scope: "worker" },
  ],
  scopedWorkerPage: async ({ page }, use) => {
    await use(page);
  },
});
```
```
// test.spec.ts

import test from "@playwright/test";
import { scopedWorkerTests } from "./testFixture";

test.describe("test serial test", () => {
  test.describe.configure({ mode: "serial" });
  test("test 1", async ({ page }) => {
    await page.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
  test("test 2", async ({ page }) => {
    await page.goto("https://playwright.dev");
  });
  scopedWorkerTests("test 3", async ({ scopedWorkerPage}) => {
    await scopedWorkerPage.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
});

```

**Steps**
- Run the group test in test.describe in serial mode

**Expected**

Test 1 failed, test 2 and test 3 should be skipped

**Actual**

image
Test 1 and Test 3 failled, Test 2 was skipped first then passed in the retry (I didn't set any retries)
And the html report shows blank in the first run and pass in retry for test 2
image

Now make test 3 pass: 
```
// test.spec.ts

import test from "@playwright/test";
import { scopedWorkerTests } from "./testFixture";

test.describe("test serial test", () => {
  test.describe.configure({ mode: "serial" });
  test("test 1", async ({ page }) => {
    await page.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
  test("test 2", async ({ page }) => {
    await page.goto("https://playwright.dev");
  });
  scopedWorkerTests("test 3", async ({ scopedWorkerPage}) => {
    await scopedWorkerPage.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
});

```
**Expected**

Test 1 failed, test 2 and test 3 should be skipped

**Actual**
image
Test 1 failed, test 2 skipped, test 3 passed

This should have something to do with the fixture with the property with worker scope, although the property with worker scope is not used in the test. When I remove the property with worker scope, everything is back to normal.

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/29282

### CODE REVIEW

File: packages/playwright/src/common/testType.ts [hunk 1]
```diff
@@ -78,12 +80,17 @@ export class TestTypeImpl {
         `  when one of the dependencies in your package.json depends on @playwright/test.`,
       ].join('\n'));
     }
+    if (suite._testTypeHash && suite._testTypeHash !== this._testTypeHash) {
+      throw new Error([
+        `Can't add tests created with another test type (test.extend) into the suite.`,
```
Comment (dgozman) [inline packages/playwright/src/common/testType.ts:85]: To properly handle use(), configure() and hooks:

```suggestion
        `Can't call ${title} inside a describe() suite of a different test type.\nMake sure to use the same "test" function (created by the test.extend() call) for all declarations inside a suite.`,
```

File: packages/playwright/src/common/test.ts [hunk 2]
```diff
@@ -54,9 +54,11 @@ export class Suite extends Base implements SuitePrivate {
   _fullProject: FullProjectInternal | undefined;
   _fileId: string | undefined;
   readonly _type: 'root' | 'project' | 'file' | 'describe';
+  readonly _testTypeHash: string;
```
Comment (dgozman) [inline packages/playwright/src/common/test.ts:57]: In `TestCase` we have `_testType: TestTypeImpl`. Perhaps we can do the same here and compare instances instead?

**Review by dgozman — APPROVED** [review]
