### PR TITLE
fix(esm): fix source maps in esm loader

### LINKED ISSUE #38578: [Bug]: Wrong line numbers in reports with type: module in package.json and Node.js 24.12.0
### Version

1.57.0

### Steps to reproduce

1. Clone https://github.com/dword-design/demo-playwright-tests-wrong-line-numbers
2. Have Node.js `24.12.0` installed and active
3. `npm ci`
4. `npx playwright test`
```ts
import { test } from '@playwright/test';

test('test', () => {});
```

### Expected behavior

```bash
Running 1 test using 1 worker

  ✓  1 tests/example.spec.ts:3:1 › test (1ms)

  1 passed (396ms)
```

### Actual behavior

```bash
Running 1 test using 1 worker

  ✓  1 tests/example.spec.ts:2:1 › test (1ms)

  1 passed (396ms)
```

### Additional context

- I think it's related to https://github.com/microsoft/playwright/pull/36187 where the source map loading was unblocked, but I guess the source maps are not there when the tests are loaded
- It works when `type: module` is removed from `package.json`
- It works in other Node.js versions, it only doesn't work with 24.12.0
- I also somehow got it to work with `PLAYWRIGHT_WAIT_FOR_SOURCE_MAPS` but it also lead to infinite loading issues (which probably is why the behavior has been changed)

### Environment

```shell
System:
    OS: macOS 15.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 129.92 MB / 16.00 GB
  Binaries:
    Node: 24.12.0 - /Users/sebastianlandwehr/.nvm/versions/node/v24.12.0/bin/node
    Yarn: 1.22.22 - /Users/sebastianlandwehr/.nvm/versions/node/v24.12.0/bin/yarn
    npm: 11.6.2 - /Users/sebastianlandwehr/.nvm/versions/node/v24.12.0/bin/npm
    pnpm: 10.26.0 - /Users/sebastianlandwehr/.nvm/versions/node/v24.12.0/bin/pnpm
  IDEs:
    VSCode: 1.106.3 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.57.0 => 1.57.0
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/38578

### CODE REVIEW

File: packages/playwright/src/transform/transform.ts [hunk 1]
```diff
@@ -260,16 +260,21 @@ function calculateHash(content: string, filePath: string, isModule: boolean, plu
...
-      // Compilation cache, which includes source maps, is populated in a post task.
-      // When importing a module results in an error, the very next access to `error.stack`
-      // will need source maps. To make sure source maps have arrived, we insert a task
-      // that will be processed after compilation cache and guarantee that
-      // source maps are available, before `error.stack` is accessed.
-      await new Promise(resolve => setTimeout(resolve, 0));
-    });
+    const fileName = url.pathToFileURL(file);
+    const esmImport = () => eval(`import(${JSON.stringify(fileName)})`);
+    await nextTask();
```
Comment (yury-s) [inline packages/playwright/src/transform/transform.ts]: revert?

File: packages/playwright/src/transform/esmLoader.ts [hunk 2]
```diff
@@ -71,29 +79,23 @@ async function load(moduleUrl: string, context: { format?: string }, defaultLoad
...
+  // Flush the source maps to the main thread, so that errors after import() are source-mapped.
+  if (transformed.serializedCache)
+    transport?.post('pushToCompilationCache', { cache: transformed.serializedCache });
 
   // Output format is required, so we determine it manually when unknown.
   // shortCircuit is required by Node >= 18.6 to designate no more loaders should be called.
   return {
     format: kSupportedFormats.get(context.format) || (fileIsModule(filename) ? 'module' : 'commonjs'),
-    source: transformed.code,
+    source: originalModuleUrl.endsWith(esmPreflightExtension) ? `void 0;` : transformed.code,
```
Comment (yury-s) [inline packages/playwright/src/transform/esmLoader.ts:90]:
```suggestion
    source: originalModuleUrl.endsWith(esmPreflightExtension) ? `` : transformed.code,
```

**Review by yury-s — APPROVED** [review]
